### ISSUE TITLE
DNSMasq fails to start on Odroid XU4

### ISSUE THREAD

**Issue by Technetium1** [pi-hole/pi-hole#2018] opened 2018-03-03 04:57 UTC
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

`A clean install of DietPi with pihole should work immediately after reboot on an Odroid XU4.`

**Actual behaviour:**

```
dnsmasq fails to start with the following systemctl status message:
-----
Mar 02 23:22:22 DietPiHole systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Mar 02 23:22:22 DietPiHole dnsmasq[587]: extraneous parameter at line 37 of /etc/dnsmasq.d/01-pihole.conf
Mar 02 23:22:22 DietPiHole dnsmasq[587]: dnsmasq: extraneous parameter at line 37 of /etc/dnsmasq.d/01-pihole.conf
Mar 02 23:22:22 DietPiHole systemd[1]: dnsmasq.service: control process exited, code=exited status=1
Mar 02 23:22:22 DietPiHole systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Mar 02 23:22:22 DietPiHole systemd[1]: Unit dnsmasq.service entered failed state.
-----
the line referenced (37) is:

log-queries=extra
```

**Steps to reproduce:**

`Install DietPi on an Odroid XU4 (no extra packages), and install pihole via curl.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`uglmgrjkdh`

**Troubleshooting undertaken, and/or other relevant information:**

+ `Reimage of DietPi and another pihole install as well as reconfiguring, uninstalling and reinstalling pihole (as that has helped for some others in the past).`

+ `I assumed it was uploading from the teleporter that broke something; so I formatted the card and reinstalled with all defaults to achieve the same result/error.`

+ `I also noticed that there is not a newline at the end of the pihole install script, so the prompt starts on the end of the install line.`

**Comment by dschaper** [comment] 2018-03-03 05:00
Duplicate of #1977

**Closed** 2018-03-03 05:02 UTC
