### ISSUE TITLE
Updating only FTL does not update the binary variable and thus fails

### ISSUE THREAD

**Issue by RlndVt** [pi-hole/pi-hole#2986] opened 2019-10-31 16:13 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

7

---
**Expected behaviour:**

Succesful update

**Actual behaviour:**

```
pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] FTL:              update available

  [i] FTL out of date

  [i] FTL Checks...

  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/FTL/releases/download/v4.3.1/tbd not found
```

**Steps to reproduce:**

`pihole -up` without up to date FTL

**Troubleshooting undertaken, and/or other relevant information:**

Added `get_binary_name` to line 2193 of 'automated install/basic-install.sh'.

**Comment by dschaper** [comment] 2019-10-31 16:35
@DL6ER This may be the source of things we've been looking for.

**Comment by dschaper** [comment] 2019-11-13 22:07
@RlndVt Is this reproducible or was this just a one time situation? If we can duplicate the error it would help us a lot on the fix.

**Comment by RlndVt** [comment] 2019-11-14 08:18
I repeatedly tried updating and the issue was then reproducible. I manually added the `get_binary_name` so the update would run, which alleviated the error. I imagine it's still perfectly reproducible on a system where only FTL needs to be updated, but mine is up to date at the moment...

**Comment by dschaper** [comment] 2020-02-24 20:24
Resolved in v4.3.5

**Closed by dschaper** 2020-02-24 20:24 UTC
Labels: Investigating, triage: Issue

**Comment by meow81** [comment] 2020-06-21 02:42
I'm on FTL v5.0 and having this issue.  Came home after a few weeks of being away and I couldn't get internet access on any of my devices.  Switched DNS back to my ISP defaults, resolved the issue and narrowed it down to the pihole.  Thought maybe an update was needed, so ran pihole -up and only a FTL update is available 
![IMG_20200620_223941](https://user-images.githubusercontent.com/22875048/85215480-5ea2d100-b347-11ea-8f64-dcf1773f537e.jpg)
![IMG_20200620_223923](https://user-images.githubusercontent.com/22875048/85215481-619dc180-b347-11ea-92cf-9c3fa5c6ce0c.jpg)

**Comment by dschaper** [comment] 2020-06-21 03:31
What does `dig github.com` return as the IP address? It looks like you are blocking it?

**Comment by meow81** [comment] 2020-06-21 04:23
I'll take a look tomorrow.  It was strange, I was away for 3 weeks, prior to, never had any issues.  Come home and no devices can connect to internet while pi hole is active.  I didn't change anything since it was last working.  switching to default isp dns resolved everything.  just not sure what changed that caused this?  I haven't updated anything on my end since everything was working.  Is it caused by the newer FTL version?  I don't have any custom blocking set up.  Just the pihole defaults.

**Comment by dschaper** [comment] 2020-06-21 04:25
What are you using for your upstream? Are you using anything like `cloudflared`?

**Comment by meow81** [comment] 2020-06-21 04:54
yes, cloudflare

**Comment by dschaper** [comment] 2020-06-21 05:09
The `cloudflared` daemon seems to be crashing a lot lately. Try using a different upstream and not using If you really need DoH

**Comment by dschaper** [comment] 2020-06-21 05:10
https://github.com/pi-hole/pi-hole/issues?q=is%3Aissue+cloudflared

**Comment by meow81** [comment] 2020-06-21 05:46
Wait, now I'm not sure. I know cloudflare is my upstream, but I'm pretty sure I'm not using DoH. will check later today.  thanks for your help

**Comment by meow81** [comment] 2020-06-21 18:59
it definitely was cloudflare. I just turned pihole back on with nextdns custom addresses and I'm back up and running.
