### ISSUE TITLE
Changes to php-fpm in version 7.4.0 breaks pi-hole compatibility 

### ISSUE THREAD

**Issue by graysky2** [pi-hole/pi-hole#3039] opened 2019-12-13 18:51 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`4`

---
**Expected behaviour:**

Pi-hole webUI should allow for blocking of domains when using nginx and the php dependencies

**Actual behaviour:**

The latest upstream version of php-fpm has a systemd service file that adds restrictions in order to sandbox processes better (no elevated permissions with sudo, read-only file system, etc). These restrictions interfere due to the way that pi-hole files need access to sudo and a writable /etc to run the pihole executable to get status and enable/disable from the web (which is also broken now).

There is a work-around, see [this](https://aur.archlinux.org/packages/pi-hole-ftl/#comment-720623) post.

Any changes to be applied upstream to insure both security and compatibility?

**Comment by dschaper** [comment] 2019-12-13 19:01
Is this Arch specific or does it affect other distributions as well?

**Comment by graysky2** [comment] 2019-12-13 20:30
@dschaper - Based on the description I linked, it should affect anyone using nginx/php-fpm but I have not verified on another distro.  One would need a distro with php-fpm 4.7.0 to replicate.

**Comment by graysky2** [comment] 2019-12-13 20:37
The issue only affects nginx with php-fpm >=4.7.0.  When I use lighttpd 1.4.54, php 7.4.0, php-cgi 7.4.0, and php-sqlite 7.4.0, pi-hole behaves as it should.

**Comment by DL6ER** [comment] 2019-12-14 13:13
@graysky2 We are slowly phasing out the current web interface including its dependence on PHP, etc. The next generation of Pi-hole will use a completely [static web interface](https://github.com/pi-hole/web) not needing any interpreter. FTL will, by default, offer these files with an inbuilt HTTP server but you can obviously host them with any web browser.

All endpoints will be similarly offered directly by FTL through a JSON-based API. There is no calling to the `pihole` script.

**Comment by balticer** [comment] 2019-12-21 23:08
Hey, i runned into the same issue and took some time to analyze the root cause. Surprise, surprise...as @graysky2 wrote it is not PHP 7.4 for this kind of setup. The real problem is that the php-fpm process is running as http:http by default. Also it has some systemd protections. Both lead into the process is not able to write /etc/pihole/setupVars.conf.

regards
Kai

**Comment by yubiuser** [comment] 2021-08-12 20:21
Closing as OP uses an unsupported web server

**Closed by yubiuser** 2021-08-12 20:21 UTC
