### ISSUE TITLE
DNS local entry overriden if domain is IPv6 enabled

### ISSUE THREAD

**Issue by Yqnn** [pi-hole/pi-hole#4023] opened 2021-01-28 10:00 UTC
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  -1
- FTL:   v5.5.1

### Platform

- OS and version:  Ubuntu 20.04.1

- Platform:  x86_64 desktop PC

### Expected behavior

If I add a domain in local DNS domains, I expect the DNS server to return only the IPv4 address that's defined there.

### Actual behavior / bug

DNS server actually return the both the IP defined IP address, and the real IPv6 address of the domain.

### Steps to reproduce

1. Activate IPv6 in upstream DNS Servers 
2. Add the following entry in local DNS domains:   IP=192.168.1.1  Domain=facebook.com
3. Run a DNS lookup on facebook.com:
```
$host facebook.com
facebook.com has address 192.168.1.1
facebook.com has IPv6 address 2a03:2880:f142:182:face:b00c:0:25de
```
=> I would expect the IPv6 not to be returned.

## Debug Token

- URL:   https://tricorder.pi-hole.net/efs3b2p3a8

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment] 2021-01-28 10:45
Thanks for the report. Closing as duplicate of
https://github.com/pi-hole/pi-hole/issues/3433

**Closed by yubiuser** 2021-01-28 10:45 UTC
