### ISSUE TITLE
Work with DHCP address instead of static IP address configuration.

### ISSUE THREAD

**Issue by jpluimers** [pi-hole/pi-hole#629] opened 2016-08-21 15:26 UTC
This is more of a feature request.

A lot of networks prefer DHCP addresses that are fixed by MAC over individual hard-coded static IP addresses. This can make central maintenance of IP addresses a lot easier. Another benefit is that it would allow to configure a machine in one network, then move it over to another network and it would "just work".

The feature request is for pi-hole to be able to work with DHCP provided IP-addresses. Upon boot/dhcp-change any configuration file that now has the fixed IP address would then need to be changed.
##

**Comment by dschaper** [comment] 2016-08-21 16:52
Would a Yes/No dialog screen for Static IP address assignment be something that you see as a working solution?

**Comment by jpluimers** [comment] 2016-08-21 17:07
It would, but I think there will be more work needed: each time an IP address is assigned by DHCP any configuration file (including `/etc/pihole/gravity.list`) depending on the IP address needs to change.

It might be that following http://roy.marples.name/man/html8/dhcpcd-run-hooks.html is enough.

**Comment by dschaper** [comment] 2016-08-21 19:37
Very interesting link, didn't know about the hooks, but that would work great for `dhcpcd` configuration. This is definitely something to look at implementing. Would you be willing to start work on some code to PR, or is this more of a feature request for us to code and implement?

**Comment by jpluimers** [comment] 2016-08-22 08:46
I'm a relative n00b on debian and certainly not proficient at bash programming. But with some assistance, I could give it a head-start as I do have Red Hat (5-6) and SuSE/opensuse (7 and up) user experience and am not afraid of touching new grounds. To get an impression of what I can do, browse a bit of my blog http://wiert.me or G+ stream https://plus.google.com/+JeroenPluimers (yes, both are high volume as this relatively old fart is trying to keep up with tech)

**Comment by dschaper** [comment] 2016-08-22 10:00
`gravity.list` basically is the resultant host file of the entire script, so is the question about how that file is created in its entirety, or just how the individual lists are amalgamated into the final monolithic file?

The changes that involve calls to the hooks would probably be best in the https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L333 section, this is where the static / DHCP choice is actually made.

**Comment by jacobsalmela** [comment] 2016-11-12 19:19
Made this votable in Discourse.  @dschaper are you still working on this or has it fallen out of scope?

@jpluimers any further input?

**Comment by dschaper** [comment] 2016-11-13 00:46
Definately not out of scope and self-assigned. Goes with the DHCPCD5 issue. #830

**Comment by jacobsalmela** [comment] 2016-11-13 01:09
OK thanks!

**Comment by jpluimers** [comment] 2016-11-17 10:53
No real input. I could help testing, but helping with development will be tough as my schedule is tight until the end of January.

**Comment by dschaper** [comment] 2017-07-09 16:21
Bumping myself @dschaper to come back to this issue.

**Comment by WaLLy3K** [comment] 2017-10-09 07:02
Thoughts on this:

The issue is that `/etc/pihole/gravity.list` and `/etc/dnsmasq.d/03-pihole-wildcard.conf` both rely on `IPV4_ADDRESS` and `IPV6_ADDRESS` from `/etc/pihole/setupVars.conf`, as AFAIK they're the only places the current IP address is "hardcoded".

If we can detect an IP change, we can then run `change_setting()` (from `/opt/pihole/webpage.sh`) to update the IP addresses, and then run `pihole -g -sd` to recompile `gravity.list`. We'd also need to fix the IP addresses within `03-pihole-wildcard.conf`,  (preferably?) via `gravity.sh` too.

That'd make it nice and easy to have a simple command that when called, grabs the latest IP address, changes `setupVars.conf` and regenerates the blocklists.

**Comment by jacobsalmela** [comment] 2018-04-10 00:51
This feature request is already on Discourse so it's votable: https://discourse.pi-hole.net/t/work-with-dhcp-address-instead-of-static-ip-address-configuration/561

**Closed by jacobsalmela** 2018-04-10 00:51 UTC
Labels: Discussion, Enhancement, Feature Request, Help Wanted

**Comment by HarvsG** [comment] 2018-05-22 19:09
So this issue moved onto the forums and is marked as solved. However I cannot get it to work. I am trying to create a PiHole on a digital ocean server which can be dropped around the globe. The solution to the broken networking is to use pihole -r to reset the static IP to the new DHCP configuration. However since networking is broken by this pihole -r hangs, and even if it didn't I think it would just retrieve the incorrect, old, configuration.

Also, since the networking is broken, you can't do any of this over SSH

**Comment by pralor** [comment] 2020-05-25 14:33
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/hardware-software-requirements/273/1
