### ISSUE TITLE
PHP error (2): fsockopen(): unable to connect to 127.0.0.1:4711 (Connection refused) in /var/www/html/admin/scripts/pi-hole/php/FTL.php:47

### ISSUE THREAD

**Issue by Asteliks** [pi-hole/pi-hole#4961] opened 2022-10-07 11:13 UTC
### Versions

- Pi-hole:  5.12.2
- Web interface: 5.15.1 
- FTL:  5.18.1
- Docker tag: 2022.09.04

### Platform

- OS and version:  Ubuntu 20.04.5 LTS

- Platform:  Docker

### Expected behavior

Pi-hole DNS service works

### Actual behavior / bug

At random times the Pi-hole DNS service stops working. At such times I'm getting errors such errors in the browser:
`DNS_PROBE_FINISHED_BAD_CONFIG`
`DNS_PROBE_FINISHED_NXDOMAIN`
and such errors in Pi-Hole:
`There was a problem applying your settings.
Debugging information:
PHP error (2): fsockopen(): unable to connect to 127.0.0.1:4711 (Connection refused) in /var/www/html/admin/scripts/pi-hole/php/FTL.php:47`

The errors accrue randomly but quite often and result with lack of DNS service however after a while everything starts working again on its own. That is without the need of an external action. 

These errors started appearing after the latest update.

## Debug Token

- URL:  https://tricorder.pi-hole.net/RivcE4KN/

**Comment by jfb-pihole** [comment] 2022-10-07 16:02
Your debug log shows a number of problems:

```
*** [ DIAGNOSING ]: Pi-hole FTL Query Database
-rw-rw-r-- 1 pihole pihole 616M Oct  7 13:10 /etc/pihole/pihole-FTL.db
[i] Checking integrity of /etc/pihole/pihole-FTL.db ... (this can take several minutes)
[✗] Integrity errors in /etc/pihole/pihole-FTL.db found.
```

```
-----tail of FTL.log------
   [2022-10-07 13:10:13.262 153328M] Error while trying to close database: database is locked
   [2022-10-07 13:10:13.288 153328M] Resizing "FTL-queries" from 62160896 to (1114112 * 56) == 62390272 (/dev/shm: 62.8MB used, 67.1MB total, FTL uses 62.8MB)
   [2022-10-07 13:10:13.288 153328M] WARNING: RAM shortage (/dev/shm) ahead: 93% is used (/dev/shm: 62.8MB used, 67.1MB total, FTL uses 62.8MB)
   [2022-10-07 13:10:14.289 153328M] add_message(type=7, message=/dev/shm) - SQL error step DELETE: database is locked
   [2022-10-07 13:10:14.289 153328M] Error while trying to close database: database is locked
```
```

*** [ DIAGNOSING ]: Pi-hole log
-rw-r--r-- 1 pihole pihole 114M Oct  7 13:10 /var/log/pihole/pihole.log
   -----head of pihole.log------
   Oct  7 00:00:12 dnsmasq[128977]: query[A] ix-truenas from 192.168.1.1
   Oct  7 00:00:12 dnsmasq[128977]: config error is REFUSED (EDE: blocked)
   Oct  7 00:00:12 dnsmasq[128977]: Rate-limiting ix-truenas is REFUSED (EDE: blocked)
```

It looks like conditional forwarding has created and endless loop:

```
-----tail of pihole.log------
   Oct  7 13:10:00 dnsmasq[153269]: forwarded 146.1.168.192.in-addr.arpa to 192.168.1.1
   Oct  7 13:10:00 dnsmasq[153269]: query[PTR] 146.1.168.192.in-addr.arpa from 192.168.1.1
   Oct  7 13:10:00 dnsmasq[153269]: forwarded 146.1.168.192.in-addr.arpa to 192.168.1.1
   Oct  7 13:10:00 dnsmasq[153269]: query[PTR] 146.1.168.192.in-addr.arpa from 192.168.1.1
   Oct  7 13:10:00 dnsmasq[153269]: forwarded 146.1.168.192.in-addr.arpa to 192.168.1.1
```

```
-rw-r--r-- 1 pihole pihole 3.2M Oct  7 13:10 /var/log/pihole/FTL.log
   -----head of FTL.log------
   [2022-10-07 00:00:21.008 128977/T128999] Ending rate-limitation of 192.168.1.1
   [2022-10-07 00:00:38.092 128977M] Rate-limiting 192.168.1.1 for at least 43 seconds
```

**Comment by albvar** [comment] 2022-10-22 11:53
I also have the same issue I am not sure if it's proper to use the same thread though?
This is driving me crazy as it happens all the time.

**Versions**
Pi-hole: 5.12.2
Web interface: 5.15.1
FTL: 5.18.1

**Platform**
OS and version: Ubuntu 20.04.5 LTS

Attached pihole_debug.log

[pihole_debug.zip](https://github.com/pi-hole/pi-hole/files/9844246/pihole_debug.zip)

**Comment by Asteliks** [comment] 2022-10-22 12:09
Unfortunately I know that I will not be of much help but I have not figured out what has caused the problem. Though I have tried. My solution was to switch from Ubuntu to TrueNAS Scale and host pihole as an app. Works like a charm

**Comment by oevcil** [comment] 2022-11-15 16:15
Have this issue too, after upgrade to:
Pi-hole v5.14.1 
FTL v5.19.1 
Web Interface v5.17

Operating System: Raspbian GNU/Linux 10 (buster)
Kernel: Linux 5.10.103-v7l+

**Comment by rdwebdesign** [comment] 2022-11-15 17:51
@oevcil 

> Have this issue too, after upgrade to

No, you don't.

Your debug log doesn't show the same PHP error message or any other problems described here.
Please, open a new issue.

**Comment by ChrSch84** [comment] 2022-11-16 12:53
After the last Update "Pi-hole [v5.14.1](https://github.com/pi-hole/pi-hole/releases/v5.14.1) FTL [v5.19.1](https://github.com/pi-hole/FTL/releases/v5.19.1) Web Interface [v5.17](https://github.com/pi-hole/AdminLTE/releases/v5.17)"

My two Piholes Crash after a few hours.

Here is one Debug Log. 

[https://tricorder.pi-hole.net/XAgCGIYq/](url)

**Comment by ChrSch84** [comment] 2022-11-16 16:37
After 5 Minutes Uptime... I Disable Pihole for now :/

[https://tricorder.pi-hole.net/XAgCGIYq/](url)

**Comment by rdwebdesign** [comment] 2022-11-16 18:01
@ChrSch84 

Your debug log **doesn't show** the same PHP error message or any other problems described here.
Please, verify https://github.com/pi-hole/FTL/issues/1478 or open a new issue.

**Comment by oevcil** [comment] 2022-11-16 19:06
![image](https://user-images.githubusercontent.com/70027346/202270448-a4ab4965-01e6-40ac-8ae2-a0ec27b08644.png)

Had the issue todayx again, and it seems like i have the issue too @rdwebdesign

**Comment by rdwebdesign** [comment] 2022-11-16 19:16
@oevcil 

I think you have a different problem, even if this error message is the same. 
_(This PHP error is just a "symptom" of some other problem)_

Your debug log **doesn't show the same errors** we saw on the original poster issue:
- you don't have database "Integrity errors"; 
- also, there is no indication of a forward looping.

---

Can you please open a new issue, with a fresh debug log?

**Comment by rdwebdesign** [comment] 2022-11-17 18:42
Closing this issue. 
Reasons:
- The original issue was solved on [2022-10-22](https://github.com/pi-hole/pi-hole/issues/4961#issuecomment-1287774238);
- other comments were related to a different issue (https://github.com/pi-hole/FTL/issues/1478), also already solved.

**Closed by rdwebdesign** 2022-11-17 18:42 UTC

**Comment by CZEMacLeod** [comment] 2023-05-11 12:26
@rdwebdesign I am getting this on FTL 5.22 / Pi-hole 5.16.2 / Docker 2023.03.01 so I don't think it is actually fixed...

**Comment by rdwebdesign** [comment] 2023-05-11 17:18
This error message is very generic.
This PHP error is just a "symptom" of some other problem. 
It only shows FTL is not answering, but this can be caused by many different issues.

My suggestion is to open a new issue on our [Discourse Forum](https://discourse.pi-hole.net), including a debug log.

**Comment by CZEMacLeod** [comment] 2023-05-12 12:20
@rdwebdesign I did eventually find it - despite having DHCP disabled, it was failing to create a file `/var/lib/misc/dnsmasq.leases` with an access denied. I eventually mapped `/var/lib/misc/` to a host location and then it worked. For reference - I checked and the file is empty.
