### ISSUE TITLE
Long term data remains after pihole -f

### ISSUE THREAD

**Issue by mmotti** [pi-hole/pi-hole#2607] opened 2019-01-29 12:12 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`pihole -f` should clear queries from current query log and long-term data

**Actual behaviour:**

Current query log is flushed but long term data remains. Have to remove the DB and restart the service to clear.

**Steps to reproduce:**

pihole -f and then check long term data for a given period.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

N/A

**Comment by Mcat12** [comment] 2019-01-30 07:02
Run `pihole -d` for a debug token. Flushing only clears the last 24 hours of queries, were you checking beyond that time period?

**Comment by mmotti** [comment] 2019-01-31 11:47
Ah, I had assumed that it would flush everything. Is there currently no way to flush the FTL DB, then?

I have tried replicating the query log / long term data clearing with the same circumstances and can't reliably replicate it now - Typical. Not much point uploading the debug log in this case.

Please feel free to close unless there should be some way in which to fully flush FTL without manually recreating the DB.

**Comment by Mcat12** [comment] 2019-02-01 02:51
You could probably set the [`MAXDBDAYS`](https://docs.pi-hole.net/ftldns/configfile/#maxdbdays) setting to 1 (not zero, as that will just disable the database), restart FTL, run `pihole -f`, then remove/reset the `MAXDBDAYS` setting and restart FTL again.

But as this is not a bug in Pi-hole, I will close the issue.

**Closed by Mcat12** 2019-02-01 02:51 UTC
Labels: triage: Issue
