### ISSUE TITLE
Firefox JS error

### ISSUE THREAD

**Issue by scottsweb** [pi-hole/pi-hole#728] opened 2016-09-27 20:50 UTC
##### Expected Behaviour:

The status and log should load correctly (like in Chrome):

<img width="231" alt="screen shot 2016-09-27 at 21 44 11" src="https://cloud.githubusercontent.com/assets/411945/18891213/29c72d8c-84fc-11e6-9f2e-f11a6a9371e5.png">

##### Actual Behaviour:

The logo and status fail to load:

<img width="231" alt="screen shot 2016-09-27 at 21 47 28" src="https://cloud.githubusercontent.com/assets/411945/18891220/325b888a-84fc-11e6-9917-079371125a07.png">

##### Steps to reproduce this issue:

Open the admin screen in Firefox 50 for Mac. You will see the following error in the console:

`Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://192.168.11.2 'unsafe-eval'").` 

I believe this security policy problem is causing parts of the UI to fail

**Comment by PromoFaux** [comment] 2016-09-27 20:52
Duplicate of https://github.com/pi-hole/AdminLTE/issues/140

**Closed by PromoFaux** 2016-09-27 20:52 UTC

**Comment by PromoFaux** [comment] 2016-09-27 20:55
That said, if you have any suggestions for a solution, please feel free to contribute to the pi-hole/AdminLTE repo!
