### ISSUE TITLE
Solus OS distribution not supported

### ISSUE THREAD

**Issue by vdemir** [pi-hole/pi-hole#2239] opened 2018-06-16 22:16 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1
---
**Expected behaviour:**

working on solus os

**Actual behaviour:**
[✗] OS distribution not supported

**Steps to reproduce:**

~ $ curl -sSL https://install.pi-hole.net | bash

**Comment by dschaper** [comment] 2018-06-16 22:18
Please open a Feature Request on our Discourse, this is not a bug or an issue.

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Closed by dschaper** 2018-06-16 22:18 UTC
