### ISSUE TITLE
Install script doesn't work on AlmaLinux

### ISSUE THREAD

**Issue by tiny6996** [pi-hole/pi-hole#4391] opened 2021-10-16 14:51 UTC
### Versions

- Pi-hole:  v5.5
- AdminLTE:  v5.7 
- FTL:  v5.10.2

### Platform

- OS and version:  AlmaLinux 8.4

- Platform:  proxmox LXC container

### Expected behavior
Install works with no extra flags since almalinux is 1:1 to compatible with RHEL/CentOS

### Actual behavior / bug

In order for the install to work I had to run the installer the following command instead of just piping straight to bash. -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash

### Steps to reproduce

1. run curl -sSL https://install.pi-hole.net | sudo bash
2. receive  this error message Unsupported OS detected: Almalinux 8.4
      If you are seeing this message and you do have a supported OS, please contact support.
3. run curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash and the install completes as expected

## Debug Token

- URL:  https://tricorder.pi-hole.net/PoK2UimG/

I will submit a pull request to update the script and try on rockylinux and centos stream if time allows

**Comment by yubiuser** [comment] 2022-01-08 12:41
Closing, as it is basically a duplicate of https://github.com/pi-hole/pi-hole/issues/4393

**Closed by yubiuser** 2022-01-08 12:41 UTC
Labels: Submitter Attention Required

**Comment by djessich** [comment] 2022-03-06 21:33
Is there any progress on this since closed? Unfortunately, this seems still unresolved, need to skip OS check...

**Comment by PromoFaux** [comment] 2022-03-06 21:39
https://github.com/pi-hole/pi-hole/issues/4393#issuecomment-945200841
