### ISSUE TITLE
[Blacklist Webpage] Long Regex Entries make other columns unreadably small

### ISSUE THREAD

**Issue by OlJohnny** [pi-hole/pi-hole#3618] opened 2020-07-26 21:08 UTC
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate.

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behavior:**

All columns can be read without cutting off other text.
[Example](https://imgur.com/a/MjAfrOj)

**Actual behavior:**

When RegEx Entries are longer than one line, all other columns get compressed to unreadable.
[Example](https://imgur.com/a/64EmV32)

**Steps to reproduce:**

- Add an extra long RegEx statement into the "Blacklist" Page (see example from above)
- See compressed and unreadable columns (Type, Comment)

Side-Note: The Action column seems to be unnecessarily wide.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

I'll pass

**Troubleshooting undertaken, and/or other relevant information:**

Dug around in the DOM.

**Comment by yubiuser** [comment] 2020-07-26 21:13
Thanks for the report. This is a duplicate of
https://github.com/pi-hole/AdminLTE/issues/1458

**Closed** 2020-07-26 21:18 UTC
Labels: Duplicate
