### ISSUE TITLE
Google.com now blocked, but whitelisted

### ISSUE THREAD

**Issue by dxm765** [pi-hole/pi-hole#1802] opened 2017-12-07 15:15 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Pi-Hole honors my whitelists`

**Actual behaviour:**

`Google is blocked, whitelist from GUI, still blocks, whitelist from CLI, still blocked`

**Steps to reproduce:**

`Google exists as a block list`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`014mdg1baa`

**Troubleshooting undertaken, and/or other relevant information:**

When attempting to navigate to Google.com I an unable too, I have cleared my cache via CCleaner, flushed DNS, restarted Pi-Hole multiple times, but every time I reference the GUI it shows Google.com being Pi-Hole'd , however upon running `pihole -w www.google.com google.com` it shows:

-  [i] www.google.com already exists in whitelist, no need to add!
-  [i] www.google.com does not exist in blacklist, no need to remove!
-  [i] www.google.com does not exist in wildcard blacklist, no need to remove!
-  [i] google.com already exists in whitelist, no need to add!
-  [i] google.com does not exist in blacklist, no need to remove!
-  [i] google.com does not exist in wildcard blacklist, no need to remove!

So it me it appears Pi-Hole is not whitelisting properly. 

> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment] 2017-12-07 16:03
What is the output from `dig google.com @127.0.0.1` on the Pi-hole device?

**Comment by dxm765** [comment] 2017-12-07 16:09
`; <<>> DiG 9.10.3-P4-Ubuntu <<>> google.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1319
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		40	IN	A	216.58.218.238

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Dec 07 09:48:57 EST 2017
;; MSG SIZE  rcvd: 55`

**Comment by razzor1984** [comment] 2017-12-07 16:11
both - virustotal.com and www.virustotal.com are withlisted

`dig virustotal.com @127.0.0.1

; <<>> DiG 9.9.5-9+deb8u13-Raspbian <<>> virustotal.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49920
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;virustotal.com.                        IN      A

;; ANSWER SECTION:
virustotal.com.         2       IN      A       192.168.1.40

;; Query time: 9 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Dec 07 17:06:03 CET 2017
;; MSG SIZE  rcvd: 59`

`dig www.virustotal.com @127.0.0.1

; <<>> DiG 9.9.5-9+deb8u13-Raspbian <<>> www.virustotal.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36725
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.virustotal.com.            IN      A

;; ANSWER SECTION:
www.virustotal.com.     2       IN      A       192.168.1.40

;; Query time: 10 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Dec 07 17:06:14 CET 2017
;; MSG SIZE  rcvd: 63`

**Comment by dschaper** [comment] 2017-12-07 16:11
That is the correct response for google.com. What error are you getting on the clients when you try to visit google?

Also you also have some issues with the `gravity.list` file, there is an entry `10.1.10.222 Binary file /etc/pihole/list.preEventHorizon matches` which is invalid.

**Comment by dschaper** [comment] 2017-12-07 16:13
@razzor1984 Can you open a new issue, it gets confusing when there are two issues going on in the same thread. I know we ask you not to duplicate, but since I think you have a separate issue than this threads owner.

**Comment by dxm765** [comment] 2017-12-07 16:14
The webpage does not load, the Web GUI shows blocked, and the pihole -w above shows its whitelisted properly.  I'll have to look at my gravity.list but I can't fathom what a binary file on my Pi-Hole's IP is.

**Comment by dschaper** [comment] 2017-12-07 16:15
It's actually the string `Binary file /etc/pihole/list.preEventHorizon matches`. If you `tail -n10 /etc/pihole/gravity.list` you will see it.

**Comment by dschaper** [comment] 2017-12-07 16:16
Can you get a screenshot of the Web GUI showing exactly what is being blocked?

**Comment by razzor1984** [comment] 2017-12-07 16:17
@dschaper  its not seperate its related what @dxm765  hast - if i want to load virustotal.com and www.virustotal.com which are withlisted they their blocked

**Comment by dschaper** [comment] 2017-12-07 16:19
@razzor1984 I can't do support for two different people in one thread, it ends up confusing both you and I when I ask for information. Please help me with assisting you by opening a new issue.

**Comment by dxm765** [comment] 2017-12-07 16:26
https://i.imgur.com/0Kr3u66.png is before I try and whitelist it, simply having Google.com open, updating Pi-Hole, then trying to refresh yields connection refused ERR_CONNECTION_REFUSED.

**Comment by dschaper** [comment] 2017-12-07 16:29
When a domain is blocked the Pi-hole IP address is sent to the client device. When you whitelist a domain that has been blocked, you either need to wait for the cached Pi-hole IP address to expire or you need to clear the client IP address cache. I can see that `www.google.com` is blocked from the picture, thank you for that. And you have clicked on the `whitelist` button next to the blocked entry on the GUI?

**Comment by dxm765** [comment] 2017-12-07 16:31
Yes, I have clicked whitelist on the GUI and it says successful, and then done the CLI for both google.com and www.google.com, I have cleared my cache and flushed DNS on my computer in addition to rebooting my Pi-Hole VM.

**Comment by dschaper** [comment] 2017-12-07 16:35
Can the Pi-hole device get to google? `curl google.com` from the command line on the Pi-hole.

**Comment by razzor1984** [comment] 2017-12-07 16:47
A temporary fix is to except the concerning ad list which blocks google.com.

**Comment by dschaper** [comment] 2017-12-07 16:48
Which list is that? I can try and add that to a test and see if I can duplicate the problem.

**Comment by razzor1984** [comment] 2017-12-07 17:04
If i search under Query adlists google.com is found under the "Search exact match"
list.0.raw.githubusercontent.com.domains but thats no direct link.
I gues the 0 is the position of the adlist which ist the start.
That would be -  https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts but if search excatly - google.com its not found

**Comment by Agromahdi123** [comment] 2017-12-07 22:27
I dont understand this issue, when i ran pihole -up it said it didnt update that list, so in theory from last version to this version the list was the same, but somehow on this version it blocks google's FQDN, which is strange cause if it WAS blacklisted, the pi wouldnt be able to curl google.com, or dig google.com correctly, but it can, and its the server answering the name requests. so this is confusing. Going through the LeHigh malware domains lists yields 0 entries that are exactly www.google.com

**Comment by razzor1984** [comment] 2017-12-08 08:47
@Agromahdi123 if you overblock like i do its normaly no big deal. You just maintain a good whitelist, but in this case the Pi-hole reacts like no whitelist is present.Thats for me the root cause.
Generally some blocklist arn't well maintained, so if "good" domains are getting in there you can fix this with the concept  of a whitelist!

**Comment by ElliotSmith91** [comment] 2017-12-09 17:18
I too have had this issue since the last update to v3.2 and can confirm white-listing google.com doesn't seem to have an effect. Removing the lehigh.edu list does solve the issue, but is obviously not an ideal fix

**Comment by dschaper** [comment] 2017-12-09 17:27
Thanks for the report, I just set up a test with just that list and it appears that we aren't currently able to successfully parse it. It creates entries in the block list that are invalid and that most likely is what is causing the issue.

```
104.131.38.203 angler techhelplist.com 20171201 20160817 20160502
104.131.38.203 apt safebrowsing.clients.google.com 20171117 20160527 20160405 20160304 20160113 20141126 20131224 20130329
104.131.38.203 attackpage google.com/safebrowsing/ 20171117 20160527 20160304 20150307 20141231 20091101
104.131.38.203 attackpage google.com/safebrowsing 20171117 20160527 20160304 20150307 20141231 20100805
104.131.38.203 attackpage google.com/safebrowsing 20171117 20160527 20160304 20150308 20131123 20120830 20120121
```

**Comment by dschaper** [comment] 2017-12-09 17:28
Have you all had this list working correctly with a previous version of Pi-hole?

**Comment by dxm765** [comment] 2017-12-09 17:32
Apologies for the late reply, upon discovering the issue with google and failure to whitelist it properly I rolled back to the previous snapshot, I can reupdate if needed, but right now on version 3.1 is working perfectly

**Comment by Agromahdi123** [comment] 2017-12-09 17:54
@dschaper i have had this list working since one of the very first builds of pi-hole that was publicly available

**Comment by Agromahdi123** [comment] 2017-12-09 17:57
@dschaper since may 2016 at least

**Comment by samgiuliano** [comment] 2017-12-10 17:32
I am seeing the same issue as well.

**Comment by razzor1984** [comment] 2017-12-10 18:45
@dschaper - the problems begun after the upgrade to 3.2. 
Under 3.1 the listed worked and whitelisting also worked.

**Comment by PromoFaux** [comment] 2017-12-12 00:33
>since may 2016 at least

Are we certain the format of the list itself has not changed? I don't recall Pi-Hole ever being able to parse a list that is formatted like this one...

**Comment by PromoFaux** [comment] 2017-12-12 00:48
OK, just downgraded my local machine to v3.1.4 and added JUST this `lehigh.edu` list to my `adlists.list` file. As you can see from below, no domains are currently pulled from that list.

Basically, this list _never worked_ with pi-hole in the first place, having it in your `adlists.list` file brought 0 domains into gravity, and therefore was doing nothing. The issue we now have is that we're _attempting_ to parse the list, and failing miserably. 

I personally think that this is not so much a bug with Pi-hole (we only parse lists that are in a HOSTS format), but rather an incorrect list being added.

```
pi@raspberrypi:/etc/.pihole$ pihole -g
:::
::: Neutrino emissions detected...
:::
::: Pulling source lists into range... done!
:::
::: Getting malwaredomains.lehigh.edu list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
:::
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 0 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 0 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
::: Whitelisting 61 domains... done!
::: Exact blocked domains: 21
::: Wildcard blocked domains: 3
::: Formatting domains into a HOSTS file... done!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq... done!
::: DNS service is running
::: Pi-hole blocking is Enabled
pi@raspberrypi:/etc/.pihole$ cat /etc/pihole/gravity.list

pi@raspberrypi:/etc/.pihole$ pihole -v
  Pi-hole version is v3.1.4 (Latest: v3.2)
  AdminLTE version is v3.2 (Latest: v3.2)
  FTL version is vDev-437af07 (Latest: v2.12)
```

**Comment by dschaper** [comment] 2017-12-22 21:02
Closed via #1856 (Code change reverted, will still need to address this issue.)

**Closed by dschaper** 2017-12-22 21:02 UTC
Labels: Confirmed Bug, Fixed in next release

**Comment by palaboy** [comment] 2022-10-31 03:14
issue still on Pi-hole v5.13 even whitelist google.com and www.google.com, disable other adlist still not working, but i can ping google.com but not www.google.com

**Comment by jfb-pihole** [comment] 2022-10-31 03:41
You are commenting on a 5 year old thread.  If you have a new issue, please open a new topic on our discourse forum.

**Comment by sinaj2889** [comment] 2022-10-31 06:00
> Yes, I have clicked whitelist on the GUI and it says successful, and then done the CLI for both google.com and www.google.com, I have cleared my cache and flushed DNS on my computer in addition to rebooting my Pi-Hole VM. 

Do Gravity Update
