### ISSUE TITLE
[CentOS7] [WEB-UI] Health status of Adlists is not updating

### ISSUE THREAD

**Issue by ashishkotnala29** [pi-hole/pi-hole#4580] opened 2022-01-27 17:18 UTC
### Versions

- Pi-hole:  5.8.1
- AdminLTE:  5.10.1
- FTL:  5.13

### Platform

- OS and version:  CentOS 7 (7.9.2009)

- Platform:  Linux Deploy container (on Android) and VM (x86_64)

### Expected behavior

The status of the Adlists should be updated after running `pihole -g` for the first time or subsequent times. A green checkmark should be shown if the list was updated a different icon if the list was not updated but downloaded.

### Actual behavior / bug

A question mark icon is shown and status is "**Health status of this list:	List was not downloaded so far**"
This does not affect functionality however. Just seems to be a visual bug.

![image](https://user-images.githubusercontent.com/18037179/151407753-96c699c9-4f7d-4929-9db4-599d583b156f.png)

### Steps to reproduce

1) Have a CentOS 7 VM/docker container and pi-hole on it.
2) `pihole -g`
3) Web UI -> Group Management -> Adlists

You would see no status/checkmarks beside the list.

## Debug Token

- URL: 
(Linux deploy container) https://tricorder.pi-hole.net/I5623RBr/
(VM x86_64) https://tricorder.pi-hole.net/IQvaadx4/

**Comment by DesktopECHO** [comment] 2022-01-27 20:08
FYI, not exactly a fix but a pretty good indicator of what the problem is...  
Updating sqlite3 and reinstalling Pi-hole seems to have fixed the issue.   My RPM's are [here](https://github.com/DesktopECHO/CentOS7-ARMv7)

![image](https://user-images.githubusercontent.com/33142753/151433720-0eb346c3-561f-4188-b296-8825d8370129.png)

**Comment by ashishkotnala29** [comment] 2022-01-27 20:24
Confirmed, fixed by updating sqlite3. @DesktopECHO Many thanks again!

**Comment by ashishkotnala29** [comment] 2022-01-28 04:10
On a second thought seems like this affects Ubuntu 16.04 as well https://www.reddit.com/r/pihole/comments/sdxq2k/incorrect_health_status_of_adlist
And since CentOS7 and Ubuntu 16.04 both are supported OS it's better we make changes to support older sqlite3 versions. Reopening the issue.

**Comment by DL6ER** [comment] 2022-01-28 04:58
> better we make changes to support older sqlite3 versions. Reopening the issue.

Do you have any SQLite3 error messages for us so we can see what would need to be changed and if that's possible at all. Which version was installed before your forced upgrade?

**Comment by DesktopECHO** [comment] 2022-01-28 05:55
``[android@GT-I9100 ~]$ rpm -qa | grep sqlite``
``sqlite-3.7.17-8.el7_7.1.armv7hl``

![image](https://user-images.githubusercontent.com/33142753/151491966-43cb4f4c-3af9-490e-9bc6-9d0a77dd8e80.png)

@ashishkotnala29's Debug logs should show something similar.  ``SQLite3 message: file renamed while open: /etc/pihole/gravity.db (28)`` and here's another: https://tricorder.pi-hole.net/6SJaMqru/

**Comment by DL6ER** [comment] 2022-01-29 18:37
> file renamed while open: /etc/pihole/gravity.db 

This is expected and not an issue.

**Comment by ashishkotnala29** [comment] 2022-01-29 18:40
@DL6ER Could you elaborate then what logs exactly you would need in order to know what could be wrong? I have a test VM running stock RPMs where I can get logs for you.

**Comment by DesktopECHO** [comment] 2022-01-29 18:41
Is there any way to get sqlite to pump out more verbose output?  Or would you like a target system to login to?

**Comment by DL6ER** [comment] 2022-01-29 18:48
I don't think there will be any SQL logs to look at, FTL uses the Pi-hole embedded SQLite3 engine which is always the current release. Is there any warning shown during running `pihole -g` ?

If this is a web bug alone, you may be able to find something in `/var/log/lighttpd/`

**Comment by ashishkotnala29** [comment] 2022-01-29 18:56
@DL6ER  Absolutely no warnings/errors using `pihole-g`
![image](https://user-images.githubusercontent.com/18037179/151673702-9545b8d1-1e82-43bf-a743-7c078f17733d.png)

![image](https://user-images.githubusercontent.com/18037179/151673717-0be523fb-0422-4c02-8070-bdefe93496ea.png)

But visual bug on the web.

Checked lighttpd logs. Nothing unusual as all API calls are status 200. However on the response I see status attribute 0. Not sure what that means...

![image](https://user-images.githubusercontent.com/18037179/151673889-3c1c1f98-0b5e-4983-9c0d-e075fe6dfdb2.png)

**Comment by ashishkotnala29** [comment] 2022-01-29 19:00
Yep, status attribute seems to be an issue. On an updated sqlite3 instance I see status either 2 (list not updated) or 1 (list updated).

**Comment by DL6ER** [comment] 2022-01-29 20:02
There is nothing unusual about the `status` property in the [group.php code](https://github.com/pi-hole/AdminLTE/blob/692d23edb034ce509aee146b895fab077805f19b/scripts/pi-hole/php/groups.php#L935-L960). The `status` column is added [here](https://github.com/pi-hole/pi-hole/blob/3cd662eaeb36025a098cf336b1f8e7211d714f76/advanced/Scripts/database_migration/gravity/13_to_14.sql#L9) and `ALTER TABLE ADD COLUMN` is [supported since SQLite3 version 3.1.3 (2005-02-20)](https://www.sqlite.org/lang_altertable.html). The mentioning of 3.37.0 (2021-11-27). doesn't matter, we are not using `CHECK` constraints on this column.

Could you verify this is indeed not in the database?
``` bash
pihole-FTL sqlite3 /etc/pihole/gravity.db -header -column "SELECT * FROM adlist;"
```

Gravity [silently skips](https://github.com/pi-hole/pi-hole/blob/3cd662eaeb36025a098cf336b1f8e7211d714f76/gravity.sh#L266-L279) setting the status when the column isn't there, what is the output of
``` bash
pihole-FTL sqlite3 /etc/pihole/gravity.db -header -column "SELECT * FROM pragma_table_info('adlist');"
```

?

**Comment by ashishkotnala29** [comment] 2022-01-29 20:19
![image](https://user-images.githubusercontent.com/18037179/151676104-7125774f-a3a8-407e-8b53-a8eb62b9605d.png)

Column seems to be there in both the instances (left is old SQLite 3.7 and right SQLite 3.36)

![image](https://user-images.githubusercontent.com/18037179/151676160-6c33b335-1946-41cb-821b-6242e9e2b696.png)

output of the other command also is same.

![image](https://user-images.githubusercontent.com/18037179/151676289-5ea962fe-08be-44df-a567-d6a78d8a9631.png)

Tried to run these manually too but same output.

**Comment by DL6ER** [comment] 2022-01-29 20:33
Please try
```
pihole checkout core fix/gravity_status
```
and run
```
pihole -g
```

It should tell you if it set the `status` column.

**Comment by DesktopECHO** [comment] 2022-01-29 20:35
I ran those commands against FTL's sqlite and then distro-bundled sqlite:

``````[android@localhost ~]$ pihole-FTL sqlite3 /etc/pihole/gravity.db -header -column "SELECT * FROM adlist;"
id  address                                                           enabled  date_added  date_modified  comment                                 date_updated  number  invalid_domains  status
--  ----------------------------------------------------------------  -------  ----------  -------------  --------------------------------------  ------------  ------  ---------------  ------
1   https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts  1        1642371654  1642371654     Migrated from /etc/pihole/adlists.list  1642371806    0       0                0     

[android@localhost ~]$ sqlite3 /etc/pihole/gravity.db -header -column "SELECT * FROM adlist;"
id          address                                                           enabled     date_added  date_modified  comment                                 date_updated  number      invalid_domains  status    
----------  ----------------------------------------------------------------  ----------  ----------  -------------  --------------------------------------  ------------  ----------  ---------------  ----------
1           https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts  1           1642371654  1642371654     Migrated from /etc/pihole/adlists.list  1642371806    0           0                0         


[android@localhost ~]$ pihole-FTL sqlite3 /etc/pihole/gravity.db -header -column "SELECT * FROM pragma_table_info('adlist');"
cid  name             type     notnull  dflt_value                          pk
---  ---------------  -------  -------  ----------------------------------  --
0    id               INTEGER  0                                            1 
1    address          TEXT     1                                            0 
2    enabled          BOOLEAN  1        1                                   0 
3    date_added       INTEGER  1        cast(strftime('%s', 'now') as int)  0 
4    date_modified    INTEGER  1        cast(strftime('%s', 'now') as int)  0 
5    comment          TEXT     0                                            0 
6    date_updated     INTEGER  0                                            0 
7    number           INTEGER  1        0                                   0 
8    invalid_domains  INTEGER  1        0                                   0 
9    status           INTEGER  1        0                                   0 

[android@localhost ~]$ sqlite3 /etc/pihole/gravity.db -header -column "SELECT * FROM pragma_table_info('adlist');"
Error: near "(": syntax error
``````

...So I dug around a bit and found this:

**2017-01-02 - Release 3.16.0**

Support for PRAGMA functions is added, so that many pragma statements can be used as part of a larger SQL query. This is considered an experimental feature. We do not anticipate any changes to the PRAGMA function interface, but will keep continue to call this interface "experimental" for a few release cycles in case unforeseen issues arise.

**Comment by DesktopECHO** [comment] 2022-01-29 20:36
I ran those commands against FTL's sqlite and then distro-bundled sqlite:

``````[android@localhost ~]$ pihole-FTL sqlite3 /etc/pihole/gravity.db -header -column "SELECT * FROM adlist;"
id  address                                                           enabled  date_added  date_modified  comment                                 date_updated  number  invalid_domains  status
--  ----------------------------------------------------------------  -------  ----------  -------------  --------------------------------------  ------------  ------  ---------------  ------
1   https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts  1        1642371654  1642371654     Migrated from /etc/pihole/adlists.list  1642371806    0       0                0     

[android@localhost ~]$ sqlite3 /etc/pihole/gravity.db -header -column "SELECT * FROM adlist;"
id          address                                                           enabled     date_added  date_modified  comment                                 date_updated  number      invalid_domains  status    
----------  ----------------------------------------------------------------  ----------  ----------  -------------  --------------------------------------  ------------  ----------  ---------------  ----------
1           https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts  1           1642371654  1642371654     Migrated from /etc/pihole/adlists.list  1642371806    0           0                0         


[android@localhost ~]$ pihole-FTL sqlite3 /etc/pihole/gravity.db -header -column "SELECT * FROM pragma_table_info('adlist');"
cid  name             type     notnull  dflt_value                          pk
---  ---------------  -------  -------  ----------------------------------  --
0    id               INTEGER  0                                            1 
1    address          TEXT     1                                            0 
2    enabled          BOOLEAN  1        1                                   0 
3    date_added       INTEGER  1        cast(strftime('%s', 'now') as int)  0 
4    date_modified    INTEGER  1        cast(strftime('%s', 'now') as int)  0 
5    comment          TEXT     0                                            0 
6    date_updated     INTEGER  0                                            0 
7    number           INTEGER  1        0                                   0 
8    invalid_domains  INTEGER  1        0                                   0 
9    status           INTEGER  1        0                                   0 

[android@localhost ~]$ sqlite3 /etc/pihole/gravity.db -header -column "SELECT * FROM pragma_table_info('adlist');"
Error: near "(": syntax error
``````

...So I dug around a bit and found this:

**2017-01-02 - Release 3.16.0**

Support for PRAGMA functions is added, so that many pragma statements can be used as part of a larger SQL query. This is considered an experimental feature. We do not anticipate any changes to the PRAGMA function interface, but will keep continue to call this interface "experimental" for a few release cycles in case unforeseen issues arise.

**Comment by DesktopECHO** [comment] 2022-01-29 20:42
`````

  Current Pi-hole version is fix/gravity_status v5.8.1-23-g5cf6359
  Current AdminLTE version is v5.10.1
  Current FTL version is v5.13

[android@localhost ~]$ pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 103107 domains
  [i] List stayed unchanged
Gravity status column is not found!
`````

**Comment by ashishkotnala29** [comment] 2022-01-29 20:44
@DesktopECHO good find. Seems like the script uses distro-bundled sqlite3 [here](https://github.com/pi-hole/pi-hole/blob/3cd662eaeb36025a098cf336b1f8e7211d714f76/gravity.sh#L241) and many other places while in [one function it uses FTL's sqlite3](https://github.com/pi-hole/pi-hole/blob/3cd662eaeb36025a098cf336b1f8e7211d714f76/gravity.sh#L863)

@DL6ER here's the result
![image](https://user-images.githubusercontent.com/18037179/151676905-444356c8-e2ba-4e2b-aa20-5af1ba710394.png)

**Comment by DesktopECHO** [comment] 2022-01-29 21:40
Heya @DL6ER why do I see FTL-supplied _sqlite_ in parts of Pi-hole and distro-supplied _sqlite_ in others?   Why not just use FTL's and call it a day.  Using two different versions of sqlite to talk to the same database seems... dicey.

Anyway, in gravity.sh I changed:  

`````output=$( { printf ".timeout 30000\\nSELECT EXISTS(SELECT * FROM pragma_table_info('%s') WHERE name='%s');\\n" "${1}" "${2}" | sqlite3 "${gravityDBfile}"; } 2>&1 )`````

to

`````output=$( { printf ".timeout 30000\\nSELECT EXISTS(SELECT * FROM pragma_table_info('%s') WHERE name='%s');\\n" "${1}" "${2}" | pihole-FTL sqlite3 "${gravityDBfile}"; } 2>&1 )`````

Bounced the works, and...

![image](https://user-images.githubusercontent.com/33142753/151678109-0d903811-0ecf-4d1c-8532-7449834cdef1.png)

I can send a pull request if you want but I'm sure there is some backstory about this I am not aware of...

**Comment by DL6ER** [comment] 2022-01-29 21:42
Thanks for trying this. I recall that there have been attempts to replace `sqlite3` by `pihole-FTL sqlite3` but I didn't know they haven't made it into `development`, maybe @PromoFaux or @dschaper remember about them.

Please try
```
pihole checkout core fix/gravity_internal_sqlite3
```
and see if it works, too. I haven't changed it everywhere as this lead to a bunch of FOREIGN KEY violation I don't have time to look into right now.

**Comment by dschaper** [comment] 2022-01-29 21:49
I'd be happy if we used `pihole-FTL sqlite3` or `pihole-FTL` if it can determine there's a call to sqlite3. One less dependency and fewer moving parts to worry about.

I don't know why it hasn't been done yet, I thought we were moving in that direction a bit ago as I do remember a discussion about it.

**Comment by PromoFaux** [comment] 2022-01-29 21:54
Yeah, we should definitely do this if we can! Could we then actually remove `sqlite3` from the dependency list? (and/or would `php-sqlite3` start complaining anywhere?)

**Comment by DesktopECHO** [comment] 2022-01-29 22:00
Unfortunately (in the case of CentOS 7 and PHP 7 at least) PHP uses the distro-supplied version of sqlite3

**Comment by ashishkotnala29** [comment] 2022-01-29 22:06
@DesktopECHO @PromoFaux Does that really matter? I'm sure your could remove the sqlite3 dependency for the manual operations you do via scripts which would now be using FTL's bundled sqlite3.

As for PHP, let that be taken care of by PHP itself. I'm sure when PHP is installed it'll get the required dependencies itself and they need not be mentioned/installed explicitly.

**Comment by ashishkotnala29** [comment] 2022-01-29 22:18
@DL6ER works fine on branch `fix/gravity_internal_sqlite3`

![image](https://user-images.githubusercontent.com/18037179/151679338-a05f2769-69a9-4ed5-8bed-dd7fb92bdc9b.png)

**Comment by DL6ER** [comment] 2022-01-30 09:57
Could you please try again on this branch? Despite its name, the branch now matured into a full replace-all-`sqlite3`-calls branch ensuring our embedded (and always recent) SQLite3 engine is used in all Pi-hole scripts. The installer dependency is dropped, too. We cannot really do much about PHP but that's fine. PHP is scheduled to be dropped on our mid-term roadmap.

I had to do a few more modifications than just replacing `sqlite3` by `pihole-FTL sqlite3` because the more recent SQLite3 engine unveiled some foreign key issues I addressed in this branch as well now.

**Comment by ashishkotnala29** [comment] 2022-01-30 09:59
Thanks, I'll try this on a clean install and existing test VM as well. Give me some time, will report back in a few hours.

**Comment by PromoFaux** [comment] 2022-01-30 14:42
> and clean install as well.

When you did a clean install, did you clone repo and switch branch _before_ install, or install then immediately switch branch?

Following the below process, gives me an unknown pihole status until I check out master and then go back to this branch... Which suggests something happens in `master` that does not currently happen in either dev or this new sqlite3 branch - so I'm trying to determine which change has caused this

```
git clone https://github.com/pi-hole/pi-hole /etc/.pihole && cd /etc/.pihole
git checkout fix/gravity_internal_sqlite3
./automated\ install/basic-install.sh
```

![image](https://user-images.githubusercontent.com/1998970/151704356-9f40714c-e554-4c61-86b1-a0799b727ef7.png)

**Comment by DesktopECHO** [comment] 2022-01-30 16:35
`````
  Pi-hole version is fix/gravity_internal_sqlite3 v5.8.1-26-g8cbffa1 (Latest: v5.8.1)
  AdminLTE version is v5.10.1 (Latest: v5.10.1)
  FTL version is v5.13 (Latest: v5.13)
`````
...Looks good!  Did a re-install, then a clean install to test both scenarios.  Both are working as expected and the Web UI is responding as it should when I add a new blocklist.

**Comment by ashishkotnala29** [comment] 2022-02-03 16:35
Fixed here: https://github.com/pi-hole/pi-hole/pull/4584

Thanks everyone!

**Comment by yubiuser** [comment] 2022-02-12 20:24
Fixed in https://discourse.pi-hole.net/t/pi-hole-ftl-v5-14-web-v5-11-and-core-v5-9-released/53529

**Closed by yubiuser** 2022-02-12 20:24 UTC
Labels: Fixed in next release

**Comment by SethG911** [comment] 2022-10-28 15:35
This is happening again in FTL v5.18.2.

**Comment by ashishkotnala29** [comment] 2022-10-28 15:38
@SethG911 I think CentOS 7 support is officially dropped by Pi-hole so you're on your own.
I'm using Debian bullseye and it's working fine.
