### ISSUE TITLE
DNSSEC - Some sites failing

### ISSUE THREAD

**Issue by martijnb92** [pi-hole/pi-hole#1213] opened 2017-02-03 20:12 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

5

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Multiple sites are not working when DNSSEC is enabled. For example itlearning.com

**[BUG | ISSUE] Actual Behaviour:**
Chrome returns DNS_PROBE_FINISHED_NXDOMAIN
Log shows:
dnsmasq[27874]: dnssec-query[DNSKEY] itslearning.com to 8.8.4.4
dnsmasq[27874]: reply itslearning.com is BOGUS DNSKEY
dnsmasq[27874]: validation result is BOGUS

**[BUG | ISSUE] Steps to reproduce:**
Enable DNSSEC in PI-Hole, Some sites are no longer working
http://serverfault.com/questions/720293/dnsmasq-returns-false-bogus-result-for-dnssec-validation

This appears to be related to an old version of dnsmasq. Dnsmasq needs to be updated to 2.73 to solve this issue
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment] 2017-02-03 20:15
```
pi@raspberrypi:~ $ apt-cache policy dnsmasq
dnsmasq:
  Installed: 2.72-3+deb8u1
  Candidate: 2.72-3+deb8u1
  Version table:
 *** 2.72-3+deb8u1 0
        500 http://mirrordirector.raspbian.org/raspbian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status
```

**Comment by chillgamingAZ** [comment] 2017-02-03 20:52
I get this too, not sure what to do about it other than turn off dnssec for the time being

**Comment by DL6ER** [comment] 2017-02-03 21:01
We recommend to turn it off if it is causing trouble. We have several open discussions. See

https://discourse.pi-hole.net/t/some-remarks-requests-regarding-v2-12/1508/12
https://discourse.pi-hole.net/t/warning-for-dnssec-users/1595
https://discourse.pi-hole.net/t/running-dnscrypt-and-dnssec/1463/7

and possibly even others.

**Comment by chillgamingAZ** [comment] 2017-02-03 21:07
thanks, whenever you can get this issue fixed... I am not in a hurry

**Comment by DL6ER** [comment] 2017-02-03 21:12
From what I can say it seems to be an external issue, since the major issue is that the standard version of `dnsmasq` has broken support for `DNSSEC`. You can follow one of the guides in the links shown above if you are willing to compile the lastest `dnsmasq` from scratch.

However, you should keep in mind, that there are domains out there which you cannot access any longer even if DNSSEC is working correctly - since they are not trusted for one or the other reason (including the Rasbian update mirror!).

Again, much more information is already available on Discourse.

**Comment by jpgpi250** [comment] 2017-02-14 08:47
I've researched dnscrypt-proxy and DNSSEC. You can read the conclusion [here](https://discourse.pi-hole.net/t/the-truth-about-dnscrypt-proxy-and-dnssec/1694).
My starting point for DNSSEC validation was **www.raspberrypi.org** and **archive.raspberrypi.org**.
By following the instructions, I've provided, these domains are now validated as **SECURE**.
The domain you mentioned (**itlearning.com**) does come up as **BOGUS**.
However, if you bypass your pi, by going to [this site](http://dnssec-debugger.verisignlabs.com/), you'll find the site itlearning.com doesn't have valid DNSSEC records, where as the site raspberrypi.org has a perfect score.
If you have a contact person @ itlearning.com, you should ask them to check there DNSSEC related records.
Hope this helps.

**Comment by Recte** [comment] 2017-03-17 19:36
DNSMasq 2.72 has an issue with the **ECDSA**P256SHA256 signature algorithm used by Cloudflare. As a result sites hosted there are likely to give problems. The issue is, as said, related to the DNSMasq version. For the Debian/Raspbian Jessie users [version: 2.72-3+deb8u1 seems to be the most recent stable one](https://qa.debian.org/debcheck.php?list=&package=dnsmasq&arch=&dist=jessie).

Until there is a newer stable version for Jessie, this issue isn't fixable I guess.

**Comment by dschaper** [comment] 2017-03-17 19:44
Jessie won't be getting any feature updates on packages, Debian only updates security related updates and backports. But the next release did freeze last month so hopefully we'll see Stretch come out of testing and go stable soon.

**Comment by jpgpi250** [comment] 2017-03-18 07:03
Jessie will not get any dnsmasq updates, but neither will stretch, I've read on the raspbian forum stretch has been frozen, in order to go to stable. The new test version seems to be called buster, but it isn't available yet (as far as I know).
Even the version (2.76) in stretch has problems, so this will not solve all DNSSEC problems
You can find [here](https://discourse.pi-hole.net/t/the-truth-about-dnscrypt-proxy-and-dnssec/1694) how to get/install the latest version of dnsmasq, all known DNSSEC problems solved.
I've been running it for over a month now, without any problems

**Comment by dschaper** [comment] 2017-03-18 07:09
Stretch: Package: dnsmasq (2.76-5)

**Comment by jpgpi250** [comment] 2017-03-18 07:19
yes 2.76-5, and it doesn't work (DNSSEC issue). I've been communicating with the developer of dnsmasq witch resulted in a working version 2.77test3. In the mean time 2.77test4 is out with a fix for a non DNSSEC related issue.
The article I referred describes how to get, compile and install this version.

**Comment by jpgpi250** [comment] 2017-03-18 07:29
As mentioned in the article I referred:

> Notice (this may not be the case on your system) the message ;; Truncated, retrying in TCP mode., the first line after the dig command, you entered.
This warning is the reason why dnsmasq v2.76-5 doesn't validate DNSSEC records correctly.
The dnscrypt developer indicated: “When local DNSSEC validation is enabled, dnsmasq 2.77 sends multiple queries on the same TCP connection which is incompatible with DNSCrypt”
The dnsmasq developer replied: "Well, that statement may well be true, the first part, about dnsmasq, is, the second part. about dnscrypt, I'd expect to be true also, given it's source."
So the developer needed to fix dnsmasq. AND HE DID

**Comment by jpgpi250** [comment] 2017-03-18 08:48
Here is a script that automatically installs the new dnsmasq version on raspbian jessie lite version march 2017.
create **install.sh**, make the script executable (chmod +x /home/pi/install.sh), run **sudo ./install.sh**
There will be some compiler warnings. According to the developer, they can be ignored (compiler is getting more nervous every release)
```
#!/bin/bash

# first update & upgrade the system from STABLE
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get -yq upgrade

# create the required files (4) to allow updgrade/install from STRETCH
# create /etc/apt/preferences.d/jessie.pref
echo "Package: *
Pin: release a=jessie
Pin-Priority: 900" > /etc/apt/preferences.d/jessie.pref
# create /etc/apt/preferences.d/stretch.pref
echo "Package: *
Pin: release a=stretch
Pin-Priority: 750" > /etc/apt/preferences.d/stretch.pref
# create /etc/apt/sources.list.d/jessie.list
echo "deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi" > /etc/apt/sources.list.d/jessie.list
# create /etc/apt/sources.list.d/stretch.list
echo "deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi" > /etc/apt/sources.list.d/stretch.list

# run sudo apt-get update to allow updgrade/install from STRETCH
sudo apt-get update

# install build-essential from STRETCH
sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install build-essential -t stretch

# install necessary system packages for dnsmasq from STRETCH
sudo apt-get -yq install gettext -t stretch
sudo apt-get -yq install libnetfilter-conntrack-dev -t stretch
sudo apt-get -yq install libidn11-dev -t stretch
sudo apt-get -yq install libdbus-1-dev -t stretch
sudo apt-get -yq install libgmp-dev -t stretch
sudo apt-get -yq install nettle-dev -t stretch

# remove the (4) files that allow upgrade/install from STRETCH
sudo rm /etc/apt/preferences.d/jessie.pref
sudo rm /etc/apt/preferences.d/stretch.pref
sudo rm /etc/apt/sources.list.d/jessie.list
sudo rm /etc/apt/sources.list.d/stretch.list

# run sudo apt-get update to allow updgrade/install from STABLE
sudo apt-get update

# cleanup
sudo apt-get -y autoremove

# dnsmasq
file=dnsmasq-2.77test4
mkdir -p dnsmasq
cd dnsmasq
wget http://www.thekelleys.org.uk/dnsmasq/test-releases/$file.tar.gz
tar xzf $file.tar.gz
cd $file
fakeroot debian/rules binary
cd ..
sudo dpkg -i dnsmasq*.deb
cd ..
```

**Comment by dschaper** [comment] 2017-03-21 12:19
Closing, as this isn't a Pi-hole issue, but one with the OS providing a package that is outdated.

**Closed by dschaper** 2017-03-21 12:19 UTC

**Comment by rugabunda** [comment] 2018-04-10 17:55
I was receiving the same errors using dnssec 2.79 & dnscrypt 2.0.8. 

A ccording to this document http://www.npl.co.uk/upload/pdf/satin2011-Deccio.pdf

B. Bogus validation caused by misconfiguration

In this section we describe some of the causes of validation failures from a perspective of misconfiguration. In any case, an RRset deemed bogus also invalidates any dependent RRsets. For example, a bogus DNSKEY RRset means that all of the RRsets whose RRSIGs would be potentially validated by those DNSKEYs are also bogus

Bogus: The validator is unable to form a chain of trust between the RRset and a trust anchor and is unable to securely show that no such chain should exist. Example: an expired RRSIG covering an RRset in the secure.com results a bogus response; likewise, the presence of a DS for the broken.com zone, in which there are no DNSKEYs present, results in a bogus status for any RRset in the zone

"While a secure validation is ideal, an insecure outcome is also usable and is equivalent to normal, unauthenticated name resolution. However, a bogus outcome is an indicator that validation failed—either because the DNS data has been tampered with or because of misconfiguration. The response returned to a recursive (i.e., on behalf of another client) query which a validator renders bogus has SERVFAIL error status and contains no DNS data, an indication of general name resolution failure. **An end user cannot distinguish a SERVFAIL response caused by data tampering from one caused by misconfiguration.** In either case, however, the end result is the same: the name in question cannot be resolved. This study focuses on bogus validation caused by misconfiguration."

**Comment by rugabunda** [comment] 2018-04-10 18:00
Apr 10 06:32:14 dnsmasq[9549]: reply . is BOGUS DNSKEY
Apr 10 06:32:14 dnsmasq[9549]: validation 15.216.60.185.in-addr.arpa is BOGUS
Apr 10 06:32:14 dnsmasq[9549]: validation result is INSECURE
Apr 10 06:32:14 dnsmasq[9549]: reply click1.email.dailycaller.com is <CNAME>
Apr 10 06:32:14 dnsmasq[9549]: reply click.postup.com is <CNAME>
Apr 10 06:32:14 dnsmasq[9549]: reply click.postup.akadns.net is <CNAME>
Apr 10 06:32:14 dnsmasq[9549]: reply target-zy-atx.postup.com is <CNAME>
Apr 10 06:32:14 dnsmasq[9549]: reply click-zy-atx.postup.com is 96.46.128.252
Apr 10 06:32:14 dnsmasq[9549]: query[PTR] 190.45.18.104.in-addr.arpa from 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: forwarded 190.45.18.104.in-addr.arpa to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: dnssec-query[DNSKEY] . to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: query[PTR] 6.91.13.31.in-addr.arpa from 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: forwarded 6.91.13.31.in-addr.arpa to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: reply . is BOGUS DNSKEY
Apr 10 06:32:14 dnsmasq[9549]: validation 84.52.101.151.in-addr.arpa is BOGUS
Apr 10 06:32:14 dnsmasq[9549]: query[PTR] 22.240.241.192.in-addr.arpa from 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: forwarded 22.240.241.192.in-addr.arpa to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: validation 36.222.20.104.in-addr.arpa is BOGUS
Apr 10 06:32:14 dnsmasq[9549]: query[PTR] 230.210.230.213.in-addr.arpa from 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: forwarded 230.210.230.213.in-addr.arpa to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: validation result is INSECURE
Apr 10 06:32:14 dnsmasq[9549]: reply 31.13.91.52 is instagram-p3-shv-01-ams3.fbcdn.net
Apr 10 06:32:14 dnsmasq[9549]: query[PTR] 15.216.60.185.in-addr.arpa from 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: forwarded 15.216.60.185.in-addr.arpa to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: dnssec-query[DS] arpa to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: validation result is INSECURE
Apr 10 06:32:14 dnsmasq[9549]: reply presstv.com is 107.189.40.42
Apr 10 06:32:14 dnsmasq[9549]: query[PTR] 15.216.60.185.in-addr.arpa from 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: forwarded 15.216.60.185.in-addr.arpa to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: validation 248.144.27.104.in-addr.arpa is BOGUS
Apr 10 06:32:14 dnsmasq[9549]: dnssec-query[DNSKEY] . to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: dnssec-query[DS] arpa to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: validation result is INSECURE
Apr 10 06:32:14 dnsmasq[9549]: reply www.rt.com is <CNAME>
Apr 10 06:32:14 dnsmasq[9549]: reply wpc.en.rt.com is 207.244.80.166
Apr 10 06:32:14 dnsmasq[9549]: query[PTR] 15.216.60.185.in-addr.arpa from 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: forwarded 15.216.60.185.in-addr.arpa to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: reply . is BOGUS DNSKEY
Apr 10 06:32:14 dnsmasq[9549]: validation 15.216.60.185.in-addr.arpa is BOGUS
Apr 10 06:32:14 dnsmasq[9549]: dnssec-query[DNSKEY] . to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: query[PTR] 217.197.79.204.in-addr.arpa from 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: forwarded 217.197.79.204.in-addr.arpa to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: validation 190.45.18.104.in-addr.arpa is BOGUS
Apr 10 06:32:14 dnsmasq[9549]: reply . is BOGUS DNSKEY
Apr 10 06:32:14 dnsmasq[9549]: validation 15.216.60.185.in-addr.arpa is BOGUS
Apr 10 06:32:14 dnsmasq[9549]: validation result is INSECURE
Apr 10 06:32:14 dnsmasq[9549]: reply 31.13.91.52 is instagram-p3-shv-01-ams3.fbcdn.net
Apr 10 06:32:14 dnsmasq[9549]: query[PTR] 40.126.155.216.in-addr.arpa from 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: forwarded 40.126.155.216.in-addr.arpa to 127.0.0.1
Apr 10 06:32:14 dnsmasq[9549]: validation result is INSECURE
Apr 10 06:32:14 dnsmasq[9549]: reply 31.13.91.6 is xx-fbcdn-shv-01-ams3.fbcdn.net
Apr 10 06:32:14 dnsmasq[9549]: validation result is INSECURE
Apr 10 06:32:14 dnsmasq[9549]: reply 192.241.240.22 is nyc2.utraffic.com
Apr 10 06:32:15 dnsmasq[9549]: validation result is INSECURE
