### ISSUE TITLE
PADD displays "Status: Unknown" after update

### ISSUE THREAD

**Issue by christianboyle** [pi-hole/pi-hole#4524] opened 2022-01-06 14:00 UTC
### Versions

- Pi-hole:  5.8.1
- AdminLTE:  5.10.1
- FTL:  5.13

### Platform

- OS and version:  Raspbian GNU/Linux 9.13 (stretch)

- Platform:  Raspberry Pi

### Expected behavior

PADD should display "[•] System is healthy" and "Status: Running"

### Actual behavior / bug

After updating PADD displays "[?] Status unknown!" and "Status: Unknown"

### Steps to reproduce

1. Boot pihole
2. Notice two places where Status shows as Unknown

## Debug Token

- URL:  https://tricorder.pi-hole.net/GPMDiDUh/

### Screenshots

![2022-01-06_07-40-49AM](https://user-images.githubusercontent.com/1605754/148393504-9ea865bd-e154-4254-abd9-88c0efd2924b.png)

### Additional context

Someone else has reported this, but a member of the pihole team responded that it was fixed https://www.reddit.com/r/pihole/comments/rwtou0/pihole_ftl_v513_web_v510_and_core_v58_released/hrf3voh/?context=3 with pull #4522, but this doesn't seem to be correct as I'm running v5.8.1 which has this code merged.

**Comment by PromoFaux** [comment] 2022-01-06 14:14
Duplicate of https://github.com/pi-hole/PADD/issues/183

**Closed by PromoFaux** 2022-01-06 14:14 UTC
