### ISSUE TITLE
Teleporter Restore Doesn't Complete

### ISSUE THREAD

**Issue by notthatwillsmith** [pi-hole/pi-hole#3749] opened 2020-09-13 22:06 UTC
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  Raspbian 10 Buster

- Platform:  Raspberry Pi

### Expected behavior

Moving from one pi-hole to another, I used the Teleporter option in the web UI on the old Raspberry Pi to create a backup. When I look in that file, it included files for DHCP leases, local DNS entries, etc. Then I opened Settings > Teleporter on the new machine, checked that all of the import options were checked (they were), selected the file and hit restore. 

At this point, I expected the new Pi-hole to have the same settings as my old Pi-hole. 

### Actual behavior / bug

It looks like the Teleporter restore process got partway through the process, then stalled without an error. When I ran it multiple times, I ended up with some weird side effects (multiple entries for the same machine in Local DNS entries, etc). When I look in the backup file from the old Pi-hole, it seems to have the data that didn't get brought into the new machine. 

### Steps to reproduce

1. Setup Pi-hole on a new Raspberry Pi 3 using the current version of Raspberry Pi OS
2. Restore teleporter backup on clean install, leaving everything checked at the defaults.
3. Reboot
4. Settings from old machine (Local DNS, Static DHCP, etc) are missing. 

## Debug Token

- URL:  https://tricorder.pi-hole.net/b0110m5p41

**Comment by technicalpyro** [comment] 2020-09-13 22:15
Looking into this it appears to be an SQL error with the teleporter expecting a table to be there that isn't and being unable to create it

**Comment by yubiuser** [comment] 2020-09-14 04:36
From your description I think it is a duplicate of https://github.com/pi-hole/AdminLTE/issues/1537

Looking at the code and tricorder, I think it's the script not working properly. It expects a table `blacklist` which does not exist in the gravity.db. The blacklist is a sub-portion of all domains in table domainlist and not a separate table;  same for `blacklist_regex`

**Closed by yubiuser** 2020-09-14 04:36 UTC
