### ISSUE TITLE
DNS service is not running

### ISSUE THREAD

**Issue by Animal-UK** [pi-hole/pi-hole#4125] opened 2021-04-15 09:01 UTC
### Versions

  Pi-hole version is v5.3.1 (Latest: v5.2.4)
  AdminLTE version is v5.5 (Latest: v5.4)
  FTL version is v5.8 (Latest: v5.7)

### Platform

- OS and version:  QTS 4.3.6 (20210322)

- Platform:  Docker

### Expected behavior

 [✓] Logging has been enabled!,
 ::: Docker start setup complete,
 [✓] DNS service is running,

### Actual behavior / bug

upon startup i get:
 [✓] Logging has been enabled!,
 ::: Docker start setup complete,
 [✗] DNS service is not running,

### Steps to reproduce

1. download latest pihole
2. start with docker

## Debug Token

- URL:  N/A

### Additional context

[_pihole_logs.txt](https://github.com/pi-hole/pi-hole/files/6316578/_pihole_logs.txt)

**Comment by DL6ER** [comment] 2021-04-15 09:07
> ::: Docker start setup complete

Please check out https://github.com/pi-hole/docker-pi-hole and open an issue ticket there (the template has docker-specific questions). Also check if your issue isn't a duplicate of https://github.com/pi-hole/docker-pi-hole/issues/834 or https://github.com/pi-hole/docker-pi-hole/issues/835 before opening a new ticket.

Thanks for using the Pi-hole and sorry for the inconvenience!

**Closed by DL6ER** 2021-04-15 09:07 UTC
