### ISSUE TITLE
Can't Blacklist sub/domains with underscore

### ISSUE THREAD

**Issue by KrunchMuffin** [pi-hole/pi-hole#4316] opened 2021-09-07 16:54 UTC
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.5.1
- FTL:  5.8.1

### Platform

- OS and version:  Unraid

- Platform:  Unraid

### Expected behavior

Be able to add domains or subdomains with underscores

### Actual behavior / bug

error message stating the domain is invalid

### Steps to reproduce

1. go to blacklist
2. enter service_v1.devart.com
3.  save it

## Debug Token

- URL:  https://tricorder.pi-hole.net/28pxiW6o/

### Screenshots

![image](https://user-images.githubusercontent.com/1037197/132382423-a9c1cb13-e0f6-4a84-a24e-72b941bebd72.png)
![image](https://user-images.githubusercontent.com/1037197/132382668-0e30b478-f98d-4ab6-8163-d739931171cb.png)

**Comment by yubiuser** [comment] 2021-09-07 17:00
Thanks. This is a duplicate of https://github.com/pi-hole/AdminLTE/issues/1848.

It will be fixed by https://github.com/pi-hole/AdminLTE/pull/1852 which is included in the next release of Pi-hole

**Comment by KrunchMuffin** [comment] 2021-09-07 17:01
Sorry, I only searched in here.

**Closed by yubiuser** 2021-09-07 17:00 UTC

**Comment by yubiuser** [comment] 2021-09-07 17:01
No problem. Sometimes it is not easy to spot where the underlying issue is.
