### ISSUE TITLE
Adding a static IP address does not take effect until you restart the resolver

### ISSUE THREAD

**Issue by Martynhsmith** [pi-hole/pi-hole#5277] opened 2023-05-20 09:30 UTC
### Versions

 Pi-hole version is v5.16.2 (Latest: v5.16.2)
  AdminLTE version is v5.19 (Latest: v5.19)
  FTL version is v5.22 (Latest: v5.22)

### Platform

Description:    Ubuntu 22.04.2 LTS
Release:        22.04

- Platform: Proxox VM 

### Expected behavior
On a Linux box I would expect the client to pick up the static set IP address from Pi-hole

### Actual behavior / bug

The Linux box finds the next available IP address

### Steps to reproduce

Build a new PC,
Look in pihole for the address convert to a static address and save
reboot the client or dhclient -r 
dhclient 

Not sure if this design or I am trying to quickly but a restart solves the issue

**Comment by DL6ER** [comment] 2023-05-20 10:37
This is expected. Pi-hole reloads its configuration, including static assignments, on a full resolver restart. There are only few exceptions to this (e.g. deleting a (dynamic) DHCP release) and is something we inherit as a limitation from the embedded DNS and DHCP server `dnsmasq`

**Comment by yubiuser** [comment] 2023-05-20 15:12
Reminds me that I need a look at https://github.com/pi-hole/AdminLTE/pull/2547 again...

**Comment by yubiuser** [comment] 2023-06-05 07:23
Closed as duplicate of https://github.com/pi-hole/pi-hole/issues/3063

**Closed by yubiuser** 2023-06-05 07:23 UTC
