### ISSUE TITLE
FTL error while installing

### ISSUE THREAD

**Issue by stephenmd** [pi-hole/pi-hole#3124] opened 2020-02-10 19:35 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{1}`

---
**Expected behaviour:**

`{expect to throughly install pi hole with no interuptions, no ftl error}`

**Actual behaviour:**

`{upon installing, once you pass the interface and it tries to install the FTL Engine. error comes up saying its unable to install the engine and cant reach git hub. change the /etc/resolv.conf and retry and it still causes issue}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{N/A as cant finish installing}`

**Troubleshooting undertaken, and/or other relevant information:**

`{I currently have a rpi 3 model b running HOOBS. It’s headless and it’s to run homebridge. It’s currently on Raspbian 10 codename buster, kernal 4.19.97-v7+

I was able to install pi hole with no problem before but now I am unable to do so.

First the only way i can get the installer to run is by using “wget -q -O - https://install.pi-hole.net | sudo bash - “ then after that everything is fine up until I keep getting the unable to get latest release location from github ftl engine couldn’t be installed error.

Ive tried editing /etc/resolv.conf and I keep running into the same issue.}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment] 2020-02-10 19:40
What is the exact error that you are seeing?

**Comment by PromoFaux** [comment] 2020-02-10 19:40
Sounds like this could be the `tbd` error, and as such is a duplicate of:

#2636 #2970 #2986 #3121 

Please note that this will be fixed in the next release,  but for now can be worked around by adding a call to `get_binary_name` on or around line 2193 of the install script

**Comment by stephenmd** [comment] 2020-02-10 20:00
@dschaper I keep getting the unable to get latest release location from github ftl engine couldn’t be installed error

**Comment by PromoFaux** [comment] 2020-02-10 20:02
Could you please provide a screenshot or a copy paste of the output? Thanks

**Comment by stephenmd** [comment] 2020-02-10 20:06
@PromoFaux hoobs@hoobs:~ $ wget -q -O - https://install.pi-hole.net | sudo bash

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Existing PHP installation detected : PHP version 7.3.11-1~deb10u1
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 6 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] Using interface: eth0
  [i] Using Google (ECS)
  [i] Static IP already configured
  [i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled
  [i] IPv4 address: {i just removed}
  [i] IPv6 address: 
  [i] Web Interface On
  [i] Web Server On
  [i] Logging On.
  [✓] Check for existing repository in /etc/.pihole
  [✓] Update repo in /etc/.pihole

  [✓] Check for existing repository in /var/www/html/admin
  [✓] Update repo in /var/www/html/admin

  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for resolvconf
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php7.3-common
  [✓] Checking for php7.3-cgi
  [✓] Checking for php7.3-sqlite3

  [✓] Enabling lighttpd service to start on reboot...

  [i] FTL Checks...

  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
  [i] Checksums do not match, downloading from ftl.pi-hole.net.
  [✗] Downloading and Installing FTL
  Error: Unable to get latest release location from GitHub
  [✗] FTL Engine not installed

**Comment by stephenmd** [comment] 2020-02-10 20:06
if i try to install any other way, i get that certificate problem

**Comment by PromoFaux** [comment] 2020-02-10 20:15
Hmm, is the time and date correct on your system? If not, that is _possibly_ the source of the cert errors for both curl and the FTL download. (Disregard my comment about the `tbd` error earlier)

**Comment by PromoFaux** [comment] 2020-02-10 20:16
https://wiki.debian.org/DateTime

**Comment by stephenmd** [comment] 2020-02-10 20:23
yea the date and time is correct

**Comment by dschaper** [comment] 2020-02-10 20:25
`sudo apt-get install ca-certificates`

**Comment by stephenmd** [comment] 2020-02-10 20:28
sudo apt-get install ca-certificates
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20190110).

**Comment by dschaper** [comment] 2020-02-10 20:32
`curl: (60) SSL certificate problem: unable to get local issuer certificate`

That means the local certificate store does not have the right files. You'll need to ask the people that make the image you are using for why that is happening.

**Comment by stephenmd** [comment] 2020-02-10 20:37
okay and in regards to the FTL error? because i has that curl issue before and they told me to use the wget installation method and it worked but then i had to reflash my pi and been getting that error w the wget installation since.

**Comment by dschaper** [comment] 2020-02-10 20:40
You need to have `curl` working to install FTL.

**Comment by stephenmd** [comment] 2020-02-10 20:50
okay so i will get in contact with them in regards to that. i dont really understand how it worked previously with the wget installation method but i hope to get this handled soon

**Comment by stephenmd** [comment] 2020-02-10 23:12
i was told to change my command to curl -k https://install.pi-hole.net | bash but that is an issue as well. as i get
curl -k https://install.pi-hole.net | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     5  100     5    0     0      8      0 --:--:-- --:--:-- --:--:--     8
bash: line 1: Found: command not found

**Comment by dschaper** [comment] 2020-02-10 23:26
You were told incorrectly. `curl -k` turns off any checking of the certificates. Akin to fixing a broken door lock by just keeping the door open all the time.

**Comment by stephenmd** [comment] 2020-02-10 23:50
Yea I know, I responded to them telling them that before I posted. Is there anything I can do w/o relying on them?

**Comment by dschaper** [comment] 2020-02-10 23:57
Unfortunately no. Unless you stop using HOOBS/Homebridge and use the OS that Raspberry Pi makes.

**Closed** 2020-02-11 17:57 UTC
Labels: Issue: Not a bug

**Comment by anubister** [comment] 2020-12-10 19:27
For info : i had the same issue on Debian buster

> curl: (60) SSL certificate problem: unable to get local issuer certificate

Upgrading `ca-certificates` from buster-updates ( 20200601~deb10u1 instead of 20190110) corrected the issue.
