### ISSUE TITLE
Creating a Group with a space in the name causes multiple groups to be created

### ISSUE THREAD

**Issue by stevieboy84** [pi-hole/pi-hole#3335] opened 2020-05-11 10:57 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
---
**Expected behaviour:**

When adding a new Group, with a name that includes spaces, the group should be added to the list of available Groups (either with spaces, or spaces replaced with hyphen or underscore)

**Actual behaviour:**

If you add a new group with a name with spaces (e.g. 'Test Group'), individual groups for each word are created, one called 'Test' and the other called 'Group' (using my example).

**Steps to reproduce:**

1. Login to pi.hole/admin
2. Go to Group Management -> Groups
3) Type a name for new group with spaces (e.g. 'Group Name Test')
4) Multiple groups are created

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/x89dhjanua

**Troubleshooting undertaken, and/or other relevant information:**

I've looked at the javascript briefly and it doesn't look like it's splitting the name into multiple calls to the service, so I am pretty sure it must be doing that on the backend.

**Comment by yubiuser** [comment] 2020-05-11 11:06
That's a feature, not a bug. 
https://github.com/pi-hole/AdminLTE/pull/1149

But there might need to be a way to add groups with spaces as well, maybe by escaping the space somehow.

**Comment by stevieboy84** [comment] 2020-05-11 11:13
Comma separated is a more natural delimiter for this kind of behaviour surely? This PR change breaks the ability to have group names with spaces in them..

**Comment by l3ale** [comment] 2020-05-13 12:01
Just adding more weight to the "space is strange delimiter" viewpoint. I also thought this was a bug until I found this issue. Commas would make much more sense IMHO, or at least adding some form of explanation in the default text in the group name box.

**Comment by PromoFaux** [comment] 2020-05-13 12:06
Agreed with this, will take a look into it later

**Comment by stevieboy84** [comment] 2020-05-13 14:05
> Agreed with this, will take a look into it later

I've got a branch with a fix for this, specifically for Groups, but really you should consider a more consistent approach across the board.. I was having issues pushing the branch to create a PR, will have another go, but maybe it's because I'm not a contributor on this repo.. Was getting a 403

**Comment by PromoFaux** [comment] 2020-05-13 14:07
Ah, you'll need to create a fork of this repo to your own namespace first, push the changes to that and PR from there.

**Comment by stevieboy84** [comment] 2020-05-13 14:20
> Ah, you'll need to create a fork of this repo to your own namespace first, push the changes to that and PR from there.

Thanks, will do that!

**Comment by pralor** [comment] 2020-05-13 17:46
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pihole-g-doesnt-update-with-new-adlist/32310/7

**Comment by simX** [comment] 2020-05-23 19:10
Can I suggest that there should at least be a visible note in the Group management page in the web UI that actually calls out the delimiter?  Otherwise, even when using a comma (which I agree is somewhat more natural), you may still get people who think this is a bug.

**Comment by stevieboy84** [comment] 2020-05-23 21:12
In my PR I do set the placeholder text to tell the user the delimiter if
that helps

**Comment by PromoFaux** [comment] 2020-05-23 21:26
We should probably come to a consensus on which method to go with at some point, kind of ended up in a bit of a stalemate in the last week :)

I think DL6ER's solution is the "cleanest" in terms of less things to break. I think the spaces between domains/URLs etc originally came from the web interface directly using the `pihole` command on the CLI, on which you could add multiple domains/URLs to a list this way.

I think the cleanest overall solution is to tidy up the placeholder text so that it does not give the wrong impression on how to enter multiple items, and to add some blurb to the top of the page with a brief explanation on how to use the page.

**Comment by yubiuser** [comment] 2021-08-12 18:54
Fixed by https://github.com/pi-hole/AdminLTE/pull/1292

**Closed by yubiuser** 2021-08-12 18:54 UTC
