### ISSUE TITLE
Please store runtime state files in /run

### ISSUE THREAD

**Issue by mbiebl** [pi-hole/pi-hole#2643] opened 2019-02-19 18:22 UTC
After the recent update of pihole to 4.2.2, I noticed that it places files in /dev/shm
```
# ls -l /dev/shm/
insgesamt 688
-rw------- 1 pihole pihole 2621440 Feb 19 19:14 FTL-clients
-rw------- 1 pihole pihole     108 Feb 19 19:14 FTL-counters
-rw------- 1 pihole pihole  131072 Feb 19 19:14 FTL-domains
-rw------- 1 pihole pihole  163840 Feb 19 19:14 FTL-forwarded
-rw------- 1 pihole pihole      28 Feb 19 19:14 FTL-lock
-rw------- 1 pihole pihole    8192 Feb 19 19:14 FTL-overTime
-rw------- 1 pihole pihole  688128 Feb 19 19:15 FTL-queries
-rw------- 1 pihole pihole   28672 Feb 19 19:14 FTL-strings
```

Please don't misuse `/dev/shm` for that purpose but instead use `/run`, which is widely supported and was specifically designed to hold runtime state files.
It's typical to create an application sudirectory with proper permissions. In this specific case
`/run/pihole/` with mode `770` and owned by `pihole:pihole` seems reasonable.

See also https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by PromoFaux** [comment] 2019-02-19 18:32
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)

-------------------------------------

But also, please see https://github.com/pi-hole/FTL/pull/429, and [here](https://www.cyberciti.biz/tips/what-is-devshm-and-its-practical-usage.html)

**Closed by PromoFaux** 2019-02-19 18:32 UTC

**Comment by Mcat12** [comment] 2019-02-19 18:35
We are not misusing `/dev/shm`, actually we are using that folder exactly as it was designed to be used. Those files are handles to the shared memory used by FTL.

> The POSIX shared memory object implementation on Linux makes use of a
       dedicated tmpfs(5) filesystem that is normally mounted under
       /dev/shm.

http://man7.org/linux/man-pages/man3/shm_open.3.html

**Comment by mbiebl** [comment] 2019-02-19 20:06
> http://man7.org/linux/man-pages/man3/shm_open.3.html

Thanks for the reply.
