### ISSUE TITLE
Pi-hole isn't getting DNS queries

### ISSUE THREAD

**Issue by underscoreQ3** [pi-hole/pi-hole#245] opened 2016-01-26 02:41 UTC
I have posted this on reddit also [here](https://www.reddit.com/r/pihole/comments/42j6aa/pihole_isnt_getting_dns_queries_google_dns_and/).
The pi-hole does seem to properly block ads if I ssh into the pi and run 'sudo ping doubleclick.com', it shows "64 bytes from 005.free-counter.co.uk 192.168.1.42): imcp_...."

192.168.1.42 is the ip of my pi-hole.

But with these settings [here](http://i.imgur.com/fsEMMsf.jpg) and [here](http://i.imgur.com/I1EkcjG.jpg) (IP is shown as 192.168.1.14, but I changed it to 192.168.1.42), ads arn't blocked for the devices connected to the router.
Or if I tell windows to use 192.168.1.42 as its DNS server it wont block ads.

It also seems like the queries arn't getting to the pi-hole because the number will only increase on the web interface if I ping sites while sshed in the pi.

So, how do I make the queries go to the pi-hole?

**Comment by dschaper** [comment] 2016-01-26 03:16
That ping response shows that the Pi-Hole is functional when the Pi is set as the resolver. We need to find the settings that will work for your workstations. Which version of Windows is your client? Also can you run `ipconfig /all` from a Windows command prompt and get us the output for your adapter. We're looking for the DNS servers specifically, You can redact any personal information, we're just looking for the local addressing.

**Comment by DonLexos** [comment] 2016-01-26 14:59
Could it be that in your ip4/6 settings you setup custom nameservers on the client? I know I used to do that on my laptop to bypass bad ISP DNS on some locations, and that means you (manually) bypass the pi-holeDNS handed out by your router yourself.

As @dschaper suggested run a `ipconfig /all` on your system and check for the nameserver settings, which look like this (on a windows 10 machine), in this case the wired connection (using GoogleDNS, not the pi-hole):
```
Ethernet adapter Local Area Connection:

   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Qualcomm Atheros AR8152 PCI-E Fast Ethernet Controller (NDIS 6.30)
   Physical Address. . . . . . . . . : 04-7D-7B-3C-06-43
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.1.17(Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Tuesday, January 26, 2016 11:00:12 AM
   Lease Expires . . . . . . . . . . : Tuesday, January 26, 2016 4:30:11 PM
   Default Gateway . . . . . . . . . : 192.168.1.1
   DHCP Server . . . . . . . . . . . : 192.168.1.1
   DNS Servers . . . . . . . . . . . : 8.8.8.8
                                       8.8.4.4
   NetBIOS over Tcpip. . . . . . . . : Enabled
```

Please note you can run the `ipconfig /all` command from a command prompt.

**Comment by underscoreQ3** [comment] 2016-01-27 03:03
My machine is running Windows 8.1, here is ````ipconfig /all````
````
Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Realtek PCIe GBE Family Controller
   Physical Address. . . . . . . . . : 74-27-EA-66-02-6A
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::60ae:2396:d526:6ba1%4(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.1.20(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Tuesday, January 26, 2016 8:53:04 PM
   Lease Expires . . . . . . . . . . : Wednesday, January 27, 2016 8:53:03 PM
   Default Gateway . . . . . . . . . : 192.168.1.1
   DHCP Server . . . . . . . . . . . : 192.168.1.1
   DHCPv6 IAID . . . . . . . . . . . : 359933930
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1A-1B-1B-0B-74-27-EA-66-02-6A

   DNS Servers . . . . . . . . . . . : 192.168.1.1
   NetBIOS over Tcpip. . . . . . . . : Enabled
````
Even if I change the DNS server within Window's settings, it will still have the same output.

**Comment by DonLexos** [comment] 2016-01-27 10:11
can you do a `ipconfig /flush`, maybe even close the browser to prevent the cache and try again. Your pc seems to be using the router as DNS server, and if your router has the DNS set to the pi it is unclear to me how it can bypass it.

**Comment by PromoFaux** [comment] 2016-01-28 09:59
@underscoreQ3 are you still having problems with this?

**Comment by underscoreQ3** [comment] 2016-01-29 01:51
@PromoFaux Yes I still have a problem with this.

**Comment by dschaper** [comment] 2016-01-29 01:53
So, when you go into Windows and manually set your IPv4 DNS Server to 192.168.1.42, the `ipconfig /all` shows a DNS server of 192.168.1.1?

**Comment by dschaper** [comment] 2016-01-29 01:54
What brand/model is your router/DHCP server?

**Comment by underscoreQ3** [comment] 2016-01-29 01:59
It changed it's DNS to 192.168.1.42 in `ipconfig /all` now when I changed it in windows. It is also blocking ads.
Brand of router is Netgear N600 Wireless Dual Band Gigabit Router model WNDR3700.

**Comment by dschaper** [comment] 2016-01-29 02:00
And are you running the stock firmware on the router?

**Comment by underscoreQ3** [comment] 2016-01-29 02:00
Yes

**Comment by dschaper** [comment] 2016-01-29 02:06
I'll check and see if you can set a custom DNS server for that model's stock firmware.

**Comment by dschaper** [comment] 2016-01-29 02:08
It looks like under the Internet Setup page you have the option for DNS Addresses. Is it currently set to "Get Automatically from ISP"?

**Comment by underscoreQ3** [comment] 2016-01-29 02:08
It seems I might be working, I was trying to test on a Chomebook. But only now I figure I probably uses google's DNS server by default.

**Comment by dschaper** [comment] 2016-01-29 02:09
You could manually configure the individual workstations to have the Pi-Hole as their DNS server.

**Comment by underscoreQ3** [comment] 2016-01-29 02:24
Oh, It doesn't seem to be working properly, I'll try configuring on other computers.

**Comment by dschaper** [comment] 2016-01-29 02:26
You may be able to set the DNS on the router and use the Pi-Hole as the Primary DNS, this would forward all your DNS queries to the Pi-Hole dnsmasq server and would ad-block any client set to use the router as it's DNS

**Comment by underscoreQ3** [comment] 2016-01-29 02:38
That is how it is set up right now, if you look in the OP I have two links to images showing my router configuration. I tired changing the DNS server on another Windows machine but it didn't work.

**Comment by underscoreQ3** [comment] 2016-01-29 03:14
I successfully configured the other Windows machine, still don't know why it isn't working network wide.

**Comment by dschaper** [comment] 2016-01-29 03:31
The first image showed an IP of 192.168.1.14, instead of the Pi's IP address...

**Comment by underscoreQ3** [comment] 2016-01-29 04:14
Ahh, that is just an older image. I decided to change the ip to ...42 because it is easier to rememeber. So that isn't the problem.

**Comment by dschaper** [comment] 2016-01-29 04:17
If manually configuring the client stations DNS to the Pi-Hole address works in blocking advertisements, then we know that the Pi-Hole is working and the problem is somewhere in the networking configuration. I don't know if that stock firmware caches lookups, and and the router needs to be rebooted after the DNS server address is changed in order to purge the cache.

**Comment by PromoFaux** [comment] 2016-01-29 19:44
I'm closing this issue as it does not appear to be related to pi-hole. However please feel free to discuss it on this thread! We're more than happy to help!

**Closed by PromoFaux** 2016-01-29 19:44 UTC
Labels: External issue

**Comment by JaredWith1r** [comment] 2016-01-29 19:49
I'm having a similar issue since reinstalling PiHole yesterday (1/28/16).

The PiHole is set as the DNS both in the router as well as directly on my PC (the only DNS set on my machine). I'm watching the pihole.log to see what queries come out of just this machine (tail -f /var/log/pihole.log | grep '<ip>'), and it definitely is not showing all of the sites I am going to. Upon further investigation, it seems that almost all chrome sites are not showing up in the pihole.log, but my Pandora desktop client and Outlook are showing up.

I have been using web.com, webs.com, etc. to test the Blacklist, and those don't show up in the log, and do not get blocked.

**Comment by JaredWith1r** [comment] 2016-01-29 20:04
Oof, sorry about that. I did `ipconfig /all` a few times today, and never noticed that I was still connected to a VPN and that was being used for DNS suffix. Turned that off and getting better blocking.

Is there a way to make it so the VPN is not used for DNS? I know little about this aspect.

Thanks as usual for the great work.

**Comment by PromoFaux** [comment] 2016-01-29 20:14
:) I know the feeling!

I'm a bit out of my depth with VPNs, but I don't think you can. I could be wrong! Did you set the VPN connection up manually, or is it through some app?

**Comment by JaredWith1r** [comment] 2016-01-29 20:15
If you're still interested:

```
Windows IP Configuration

   Host Name . . . . . . . . . . . . : ****
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

Ethernet adapter Local Area Connection:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Realtek RTL8168C(P)/8111C(P) Family PCI-E
 Gigabit Ethernet NIC (NDIS 6.20)
   Physical Address. . . . . . . . . : 00-1F-D0-D1-D7-41
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::d129:737c:bd91:302%10(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.1.130(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.1.1
   DHCPv6 IAID . . . . . . . . . . . : 234889168
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1B-91-B1-B9-00-1F-D0-D1-D7-41

   DNS Servers . . . . . . . . . . . : fe80::dfea:58f4:dceb:20d6%10
                                       192.168.1.116
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter isatap.{B7C996A5-223C-4F78-907B-008AD6ACF66C}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter Local Area Connection* 11:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
```

**Comment by mitchross** [comment] 2016-09-09 01:07
Im having the same issue. Ive repeated all the steps in this thread with no luck.

**Comment by mitchross** [comment] 2016-09-09 01:26
Figured it out. dnsmasq.d needs to listen on wlan0 not eth0 if you are using wifi.

**Comment by lazear** [comment] 2016-09-13 14:10
@mitchross I just ended up on this topic after some googling, and that just solved the issue for me. 
For any who come after, change the interface line in /etc/dnsmasq.d/01-pihole.conf to wlan0
