### ISSUE TITLE
Client filter with "queries.php?client=" not working

### ISSUE THREAD

**Issue by Perflyst** [pi-hole/pi-hole#2390] opened 2018-08-26 09:48 UTC
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
0

---
**Expected behaviour:**

The requests should be filtered by the selected client.

**Actual behaviour:**

Requests from all clients are shown even if only one client is selected.

**Steps to reproduce:**

Enter manually a client with `queries.php?client=` or press on a client on Dashboard under `Top Clients (blocked only)` or `Top Clients (total)`.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Let me know if you can't reproduce it, I can.

```
Core Commit: v4.0-0-gddbdb51
Web version Commit: v4.0-0-gaf8c926c
FTL: v4.0
dnsmasq version: 2.76
php version: 7.0.30
```

**Comment by Mcat12** [comment] 2018-08-26 15:05
I can't reproduce this on the development version. Is the client IPv6?

**Comment by Perflyst** [comment] 2018-08-26 15:07
No, IPv4

**Comment by technicalpyro** [comment] 2018-08-26 15:17
what browser are you using?

**Comment by Perflyst** [comment] 2018-08-26 20:50
Firefox 61
I will try later with another browser, maxbe it is because of an addon.

On August 26, 2018 3:17:14 PM UTC, technicalpyro <notifications@github.com> wrote:
>what browser are you using?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pi-hole/pi-hole/issues/2390#issuecomment-416046060

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by technicalpyro** [comment] 2018-08-26 20:59
That is a good step we normally see issues like this with chromium based browsersso that is odd.  I'm on firefor myself and unable to reproduce this as well

**Comment by Perflyst** [comment] 2018-08-27 09:53
I tried with a new installation and a new firefox profile. Same result.
I am unable to test with brave or opera, the query log does not render.

**Comment by DL6ER** [comment] 2018-08-27 10:05
Please run the following three commands
```
echo ">getallqueries" | nc pi.hole 4711 | wc -l
echo ">getallqueries-client 127.0.0.1" | nc pi.hole 4711 | wc -l
echo ">getallqueries-client localhost" | nc pi.hole 4711 | wc -l
```
What are the outputs?

Replace `127.0.0.1` and `localhost` also once by the IP address and the hostname of one of your clients and try the commands again.

**Comment by Perflyst** [comment] 2018-08-27 10:07
Output is always `0`

**Comment by DL6ER** [comment] 2018-08-27 10:12
Oh, I forgot to mention that they need to be run on the Pi-hole itself.

**Comment by Mcat12** [comment] 2018-08-29 15:15
What is the output of
```
echo ">stats" | nc localhost 4711
```

**Comment by Perflyst** [comment] 2018-08-29 15:20
```
$ echo ">stats" | nc localhost 4711
domains_being_blocked 1511781
dns_queries_today 15218
ads_blocked_today 11591
ads_percentage_today 76.166382
unique_domains 559
queries_forwarded 3181
queries_cached 447
clients_ever_seen 5
unique_clients 5
dns_queries_all_types 15388
reply_NODATA 0
reply_NXDOMAIN 0
reply_CNAME 1477
reply_IP 15496
status enabled
---EOM---
```

**Comment by Mcat12** [comment] 2018-08-29 15:54
And this command still returns nothing?
```
echo ">getallqueries" | nc localhost 4711
```

**Comment by Perflyst** [comment] 2018-08-30 01:40
Yes

**Comment by DL6ER** [comment] 2018-08-30 08:43
Please post the content of your `/etc/pihole/pihole-FTL.conf`

**Comment by Perflyst** [comment] 2018-08-31 08:48
```
RESOLVE_IPV6=no
AAAA_QUERY_ANALYSIS=no
PRIVACYLEVEL=0
```

**Comment by Mcat12** [comment] 2018-09-02 00:50
What are the contents of `/var/log/pihole-FTL.log`

**Comment by DL6ER** [comment] 2018-09-02 17:27
Also, what are the contents of your `/etc/pihole/setupVars.conf`? Did you maybe set `API_QUERY_LOG_SHOW=nothing` ?

**Comment by Perflyst** [comment] 2018-09-02 17:32
`/var/log/pihole-FTL.log`
```
[2018-09-02 04:34:19.003] Compiled 98 Regex filters and 121 whitelisted domains in 6.5 msec (0 errors)
[2018-09-02 04:34:21.594] /etc/pihole/black.list: parsed 36 domains (took 0.1 ms)
[2018-09-02 04:34:28.071] /etc/pihole/gravity.list: parsed 1512773 domains (took 6477.1 ms)
[2018-09-02 10:30:00.458] Notice: Increasing overTime struct size from 300 to 400
```

`/etc/pihole/setupVars.conf`
```
WEBPASSWORD=xx
PIHOLE_INTERFACE=eth0
IPV4_ADDRESS=192.168.xx
IPV6_ADDRESS=
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true
DNSMASQ_LISTENING=single
PIHOLE_DNS_1=31.171.251.118#53
PIHOLE_DNS_2=85.214.20.141#53
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSSEC=true
CONDITIONAL_FORWARDING=false
API_EXCLUDE_DOMAINS=xx
API_EXCLUDE_CLIENTS=
API_QUERY_LOG_SHOW=all
API_PRIVACY_MODE=false
```

**Comment by DL6ER** [comment] 2018-09-06 15:18
How about
```
echo ">top-domains" | nc localhost 4711
```

**Comment by Perflyst** [comment] 2018-09-06 16:57
```
$ echo ">top-domains" | nc localhost 4711
0 139 youtubei.googleapis.com
1 138 i.instagram.com
2 116 i.ytimg.com
3 108 www.youtube.com
4 75 removed
5 55 2.android.pool.ntp.org
6 55 removed
7 54 android.clients.google.com
8 52 1.debian.pool.ntp.org
9 52 2.debian.pool.ntp.org
---EOM---
```

**Comment by Perflyst** [comment] 2018-09-06 16:59
Now I get an output with `echo ">getallqueries" | nc localhost 4711`.
With the other commands still nothing or `0`.

**Comment by Mcat12** [comment] 2018-09-07 16:04
If you restart FTL, what are the contents of its log?
```
sudo service pihole-FTL restart
cat /var/log/pihole-FTL.log
```

**Comment by Perflyst** [comment] 2018-09-08 11:30
```
[2018-09-08 05:00:12.393] Notice: Increasing overTime struct size from 500 to 600
[2018-09-08 11:29:30.598] ########## FTL started! ##########
[2018-09-08 11:29:30.598] FTL branch: 
[2018-09-08 11:29:30.598] FTL version: v4.0
[2018-09-08 11:29:30.598] FTL commit: 8493df4
[2018-09-08 11:29:30.598] FTL date: 2018-08-05 13:40:30 -0700
[2018-09-08 11:29:30.598] FTL user: pihole
[2018-09-08 11:29:30.599] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
[2018-09-08 11:29:30.599]    SOCKET_LISTENING: only local
[2018-09-08 11:29:30.599]    AAAA_QUERY_ANALYSIS: Hide AAAA queries
[2018-09-08 11:29:30.599]    MAXDBDAYS: max age for stored queries is 365 days
[2018-09-08 11:29:30.599]    RESOLVE_IPV6: Don't resolve IPv6 addresses
[2018-09-08 11:29:30.599]    RESOLVE_IPV4: Resolve IPv4 addresses
[2018-09-08 11:29:30.599]    DBINTERVAL: saving to DB file every minute
[2018-09-08 11:29:30.599]    DBFILE: Using /etc/pihole/pihole-FTL.db
[2018-09-08 11:29:30.599]    MAXLOGAGE: Importing up to 24.0 hours of log data
[2018-09-08 11:29:30.599]    PRIVACYLEVEL: Set to 0
[2018-09-08 11:29:30.599]    IGNORE_LOCALHOST: Show queries from localhost
[2018-09-08 11:29:30.599]    BLOCKINGMODE: Null IPs for blocked domains
[2018-09-08 11:29:30.599]    REGEX_DEBUGMODE: Inactive
[2018-09-08 11:29:30.599] Finished config file parsing
[2018-09-08 11:29:30.605] Compiled 98 Regex filters and 121 whitelisted domains in 5.4 msec (0 errors)
[2018-09-08 11:29:30.606] db_get_FTL_property() - SQL error prepare (1): no such table: ftl
[2018-09-08 11:29:30.606] Query: "SELECT VALUE FROM ftl WHERE id = 0;"
[2018-09-08 11:29:30.606] Database version incorrect, database not available
[2018-09-08 11:29:30.606]  -> Total DNS queries: 0
[2018-09-08 11:29:30.606]  -> Cached DNS queries: 0
[2018-09-08 11:29:30.606]  -> Forwarded DNS queries: 0
[2018-09-08 11:29:30.606]  -> Exactly blocked DNS queries: 0
[2018-09-08 11:29:30.606]  -> Unknown DNS queries: 0
[2018-09-08 11:29:30.606]  -> Unique domains: 0
[2018-09-08 11:29:30.606]  -> Unique clients: 0
[2018-09-08 11:29:30.606]  -> Known forward destinations: 0
[2018-09-08 11:29:30.606] Successfully accessed setupVars.conf
[2018-09-08 11:29:30.611] PID of FTL process: 31739
[2018-09-08 11:29:30.611] Listening on port 4711 for incoming IPv4 telnet connections
[2018-09-08 11:29:30.612] Listening on port 4711 for incoming IPv6 telnet connections
[2018-09-08 11:29:30.612] Listening on Unix socket
[2018-09-08 11:29:30.624] Compiled 98 Regex filters and 121 whitelisted domains in 8.3 msec (0 errors)
[2018-09-08 11:29:30.625] /etc/pihole/black.list: parsed 36 domains (took 0.2 ms)
```

**Comment by Mister-XY** [comment] 2018-09-08 15:04
Have the same problem here.
If I want to look at the queries of a particular client, then I see that of all, although in the URL bar is the right client.

**Comment by Mcat12** [comment] 2018-09-09 17:56
@Perflyst Assuming you still have the behavior of seeing all clients when only one is specified, then it must be that the `>getallqueries-client X` command returns data for some client `X` if the URL path looks like `/admin/queries.php?client=X`. Run that same command using `echo ">getallqueries-client X" | nc localhost 4711` on the Pi-hole. If there's no output, then something must be allowing PHP to run that command, but not you through the command line.

Relevant code:
https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/js/queries.js#L131-L134
https://github.com/pi-hole/AdminLTE/blob/master/api_FTL.php#L260-L264

I did find a function which would refresh the data without regard to the filters (causing the issue described), but I could not find it used anywhere: https://github.com/pi-hole/AdminLTE/blob/master/scripts/pi-hole/js/queries.js#L18-L21

**Comment by Perflyst** [comment] 2018-09-10 18:37
`echo ">getallqueries-client X" | nc localhost 4711`
Shows an output. There are all clients listed.

If I enter e.g. `echo ">getallqueries-client 192.168.1.1" | nc localhost 4711` all clients are listed too.

**Comment by Mcat12** [comment] 2018-09-10 21:18
It looks like this might be fixed in development. Try `pihole checkout ftl development` or `pihole checkout dev`.

The logic in v4.0 seems flawed. It will only skip a query if the client has a name:
https://github.com/pi-hole/FTL/blob/8493df476758650e407d6be83321500fba81f7d6/api.c#L687-L694

It is fixed in dev (note the `&&` is replaced with `||`):
https://github.com/pi-hole/FTL/blob/development/api.c#L650-L658

**Comment by Mcat12** [comment] 2018-09-11 16:28
`pihole checkout master`

**Closed** 2018-09-11 16:29 UTC
Labels: Bug: Confirmed, Fixed in next release
