### ISSUE TITLE
Wrong Mac Adresses in DHCP leases section if there is an IPv6 device

### ISSUE THREAD

**Issue by huggenknubbel** [pi-hole/pi-hole#3114] opened 2020-02-04 20:06 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

`a list of network devices with MAC adresses IPs and Hostnames`

**Actual behaviour:**

`a list of network devices with MAC adresses IPs and Hostnames. But if there is an IPv6 Adress, the MAC adress looks like: 62140057 or just 0 `

**Steps to reproduce:**

`enable DHCP on Pihole. Add IpV6 Devices to the Network`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

[Debug Log](https://tricorder.pi-hole.net/qawcjffthv)

A image tells you what i mean
![grafik](https://user-images.githubusercontent.com/15655280/73782328-35b3e200-4792-11ea-84df-3e2811184fab.png)

**Comment by dschaper** [comment] 2020-02-04 20:14
IPv6 doesn't use MAC, it uses DUID. Those can be in very different formats and can change frequently from IPv6 security features.

**Comment by MayeulC** [comment] 2020-04-13 10:08
Duplicate of #2569 
Though if we assume we are on the same LAN, which we should, I think it would be quite easy to get the MAC address as well.

**Comment by dschaper** [comment] 2020-04-13 16:23
If you know of a way to find out what the MAC is from a DUID/IAID then please share. Especially when Privacy Extensions are enabled and the addresses are randomized and transient.

**Comment by MayeulC** [comment] 2020-04-13 17:51
Not from a DUID, but from an IP address we just gave the host. Of course, that doesn't work for more complex situations like multiple hosts sharing an IP address, but that shouldn't matter.
```
ip neigh show to $IPV6_ADDR | cut -d " " -f 5
```
Should get you there. It only works for online hosts, so this has to be cached. ARP table expires after a while, so you might need to ping the address first.

**Comment by yubiuser** [comment] 2021-08-12 19:45
Closing as duplicate of https://github.com/pi-hole/pi-hole/issues/2569

**Closed by yubiuser** 2021-08-12 19:45 UTC
Labels: Duplicate
