### ISSUE TITLE
settings.php stops working

### ISSUE THREAD

**Issue by ieperlingetje** [pi-hole/pi-hole#1827] opened 2017-12-09 20:04 UTC
After updating to the newest version, the page under http://pi.hole/admin/settings.php just remains blank, nothing gets loaded (as far as I can tell no data is send to the browser). In the lighttpd logs I find the following message when I try to open that page:

`2017-12-09 20:55:04: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Can't use function return value in write context in /var/www/html/admin/settings.php on line 15`

If i check that file, this line should be causing the issue:

`
function command_exist($cmd)
{
    return !empty(shell_exec(sprintf("which %s", escapeshellarg($cmd))));
}
`

I'm using the latest version according to pihole -v:

` Pi-hole version is v3.2 (Latest: v3.2)
  AdminLTE version is v3.2 (Latest: v3.2)
  FTL version is vDev-437af07 (Latest: v2.12)`

**Comment by DL6ER** [comment] 2017-12-09 20:15
Duplicate of https://github.com/pi-hole/AdminLTE/issues/628

**Closed by DL6ER** 2017-12-09 20:15 UTC
