### ISSUE TITLE
Job for dnsmasq.service failed. See 'systemctl status dnsmasq.service' and 'journalctl -xn' for details.

### ISSUE THREAD

**Issue by bmsecades** [pi-hole/pi-hole#487] opened 2016-05-02 06:16 UTC
Tried restarting dnsmasq.

sudo service dnsmasq start and sudo systemctl start dnsmasq

problem : Job for dnsmasq.service failed. See 'systemctl status dnsmasq.service' and 'journalctl -xn' for details.

**Comment by bitterypaul** [comment] 2016-05-02 06:53
did you modify the /etc/dnsmasq.conf file?

**Comment by bmsecades** [comment] 2016-05-02 06:56
nope didnt touch anything bro

**Comment by bitterypaul** [comment] 2016-05-02 07:02
I had a similar problem. I tried moving contents  of /etc/dnsmasq.d/01-pihole.conf to /etc/dnsmasq.conf and removing the duplicate lines in /etc/dnsmasq.conf and deleting the /etc/dnsmasq.d/01-pihole.conf worked for me

**Comment by bmsecades** [comment] 2016-05-02 07:04
maybe ill try to reinstall it by using

sudo apt-get -y install dnsmasq

**Comment by bmsecades** [comment] 2016-05-02 07:04
ok thanks bro ill try to look at it

**Comment by bitterypaul** [comment] 2016-05-02 07:05
try
apt-get remove --purge dnsmasq
rm -r /etc/dnsmasq.d
rm -r /etc/dnsmasq.conf
then 
apt-get install dnsmasq

**Comment by bitterypaul** [comment] 2016-05-02 07:57
any update?

**Comment by bmsecades** [comment] 2016-05-02 08:09
no luck bro

**Comment by bitterypaul** [comment] 2016-05-02 08:12
If you trust me , i will ssh into your pc. I am here to help you
or give me a vnc connection

**Comment by PromoFaux** [comment] 2016-05-02 10:19
@bmsecades please run `pihole -d` and provide the output for us to look at here. 

Output will be found at `/var/log/pihole_debug.log`

**Comment by bmsecades** [comment] 2016-05-03 01:04
IP Addresses of this Pi:
192.168.1.3
127.0.0.1

Gateway check:
ok

#######################################
######## Whitelist Comparison #########
#######################################

#######################################
######## Blacklist Comparison #########
#######################################

#######################################
############ NSLookup Test ############
#######################################
NSLOOKUP of doubleclick.com from PiHole:
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   doubleclick.com
Address: 74.125.203.102
Name:   doubleclick.com
Address: 74.125.203.113
Name:   doubleclick.com
Address: 74.125.203.138
Name:   doubleclick.com
Address: 74.125.203.139
Name:   doubleclick.com
Address: 74.125.203.100
Name:   doubleclick.com
Address: 74.125.203.101


NSLOOKUP of doubleclick.com from 8.8.8.8:
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   doubleclick.com
Address: 103.233.38.59
Name:   doubleclick.com
Address: 103.233.38.50
Name:   doubleclick.com
Address: 103.233.38.39
Name:   doubleclick.com
Address: 103.233.38.20
Name:   doubleclick.com
Address: 103.233.38.44
Name:   doubleclick.com
Address: 103.233.38.25
Name:   doubleclick.com
Address: 103.233.38.24
Name:   doubleclick.com
Address: 103.233.38.55
Name:   doubleclick.com
Address: 103.233.38.35
Name:   doubleclick.com
Address: 103.233.38.45
Name:   doubleclick.com
Address: 103.233.38.29
Name:   doubleclick.com
Address: 103.233.38.40
Name:   doubleclick.com
Address: 103.233.38.30
Name:   doubleclick.com
Address: 103.233.38.54
Name:   doubleclick.com
Address: 103.233.38.34
Name:   doubleclick.com
Address: 103.233.38.49


#######################################
########### Processes Check ###########
#######################################

lighttpd processes status:
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: active (running) since Mon 2016-05-02 05:31:00 UTC; 19h ago
 Main PID: 515 (lighttpd)
   CGroup: /system.slice/lighttpd.service
           ├─515 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─533 /usr/bin/php-cgi
           ├─556 /usr/bin/php-cgi
           ├─557 /usr/bin/php-cgi
           ├─558 /usr/bin/php-cgi
           └─559 /usr/bin/php-cgi

May 02 05:31:00 raspberrypi lighttpd[468]: Syntax OK
May 02 05:31:00 raspberrypi systemd[1]: Started Lighttpd Daemon.

dnsmasq processes status:
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: active (running) since Mon 2016-05-02 08:11:52 UTC; 16h ago
 Main PID: 2734 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─2734 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -r /var/run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5

May 02 08:11:52 raspberrypi dnsmasq[2724]: dnsmasq: syntax check OK.
May 02 08:11:52 raspberrypi dnsmasq[2734]: started, version 2.72 cachesize 150
May 02 08:11:52 raspberrypi dnsmasq[2734]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect
May 02 08:11:52 raspberrypi dnsmasq[2734]: DNS service limited to local subnets
May 02 08:11:52 raspberrypi dnsmasq[2734]: reading /var/run/dnsmasq/resolv.conf
May 02 08:11:52 raspberrypi dnsmasq[2734]: using nameserver 192.168.1.2#53
May 02 08:11:52 raspberrypi dnsmasq[2734]: read /etc/hosts - 5 addresses
May 02 08:11:52 raspberrypi systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
#######################################
############### Dnsmasq ###############
#######################################
onfiguration file for dnsmasq.
domain-needed
bogus-priv
no-resolv
server=208.67.222.222
server=208.67.220.220
interface=eth0
listen-address=127.0.0.1
cache-size=10000
log-queries

#######################################
########### 01-pihole.conf ############
#######################################
No 01-pihole.conf file found!
#######################################
############ lighttpd.conf ############
#######################################
server.modules = (
"mod_access",
"mod_accesslog",
"mod_expire",
"mod_compress",
"mod_redirect",
"mod_setenv",
"mod_rewrite"
)
server.document-root        = "/var/www/html"
server.error-handler-404        = "pihole/index.html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename                      = "/var/log/lighttpd/access.log"
accesslog.format                        = "%{%s}t|%V|%r|%s|%b"
index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
$HTTP["url"] =~ "^/admin/" {
setenv.add-response-header = ( "X-Pi-hole" => "The Pi-hole Web interface is working!" )
}
$HTTP["url"] =~ "^(?!/admin)/.*" {
setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
url.rewrite = ("(.*).js" => "pihole/index.js")
}

#######################################
############ gravity.list #############
#######################################
104408 /etc/pihole/gravity.list

Hostname of this pihole is:
raspberrypi
#######################################
################ Hosts ################
#######################################
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       raspberrypi

#######################################
############## Whitelist ##############
#######################################
raw.githubusercontent.com
adblock.gjtech.net
mirror1.malwaredomains.com
sysctl.org
zeustracker.abuse.ch
s3.amazonaws.com
hosts-file.net

#######################################
############## Blacklist ##############
#######################################

#######################################
############ adlists.list #############
#######################################
No adlists.list file found... using adlists.default!
#######################################
############# pihole.log ##############
#######################################

**Comment by bmsecades** [comment] 2016-05-03 01:06
lets just isolate the problem. if not its easy to reinstall it :)

**Comment by dschaper** [comment] 2016-05-03 01:06
Thanks for the debug run, because formatting is important with the file, could you put it up on PasteBin and post a link?

**Comment by dschaper** [comment] 2016-05-03 01:08
And dnsmasq looks to be running okay per that debug. Can you run ''sudo systemctl status -l dnsmasq' as that will output the full status of dnsmasq and will highlight any errors that would cause it to stop.

**Comment by dschaper** [comment] 2016-05-03 01:10
You're also missing an important file, the  01-pihole.conf which passes some flags for the Pi-hole setup.

**Comment by bmsecades** [comment] 2016-05-03 01:18
http://pastebin.com/D5mSNmqi

**Comment by bmsecades** [comment] 2016-05-03 01:19
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: active (running) since Mon 2016-05-02 08:11:52 UTC; 17h ago
 Main PID: 2734 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─2734 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -r /var/run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5

May 02 08:11:52 raspberrypi dnsmasq[2724]: dnsmasq: syntax check OK.
May 02 08:11:52 raspberrypi dnsmasq[2734]: started, version 2.72 cachesize 150
May 02 08:11:52 raspberrypi dnsmasq[2734]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect
May 02 08:11:52 raspberrypi dnsmasq[2734]: DNS service limited to local subnets
May 02 08:11:52 raspberrypi dnsmasq[2734]: reading /var/run/dnsmasq/resolv.conf
May 02 08:11:52 raspberrypi dnsmasq[2734]: using nameserver 192.168.1.2#53
May 02 08:11:52 raspberrypi dnsmasq[2734]: read /etc/hosts - 5 addresses
May 02 08:11:52 raspberrypi systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.

**Comment by bmsecades** [comment] 2016-05-03 01:21
/etc/dnsmasq.d/01-pihole.conf -> i think i dont have it

**Comment by dschaper** [comment] 2016-05-03 01:25
Dnsmasq is running, however you have some configuration files missing, and your dnsmasq configuration file that is there has a odd first line that's not part of standard syntax. Looking at the resolving tests, your getting public addresses when dnsmasq is queried and the fist batch of tests should return the IP of your Pi-hole. So the easiest solution would be a reinstall, not sure what would cause the configuration files to be missing or have bad settings. Did you install via the suggested install methods and have you installed any other packages on this pi that relate to networking?

**Comment by bmsecades** [comment] 2016-05-03 01:31
yeah bro i tried creating /etc/dnsmasq.d/01-pihole.conf and retarted dnsmasq still no luck same error.


#####################ERROR############################
** Job for dnsmasq.service failed. See 'systemctl status dnsmasq.service' and 'journalctl -xn' for details.**
#####################ERROR############################

**Comment by dschaper** [comment] 2016-05-03 01:34
I'm guessing that you have duplicate flags set in 01-pihole.conf that conflict with your other dnsmasq configuration. Try running the ''sudo systemctl status -l dnsmasq' now and see what error is shown.

**Comment by PromoFaux** [comment] 2016-05-03 10:35
@bmsecades I think it's probably best to start from scratch. Can you re-run the pihole install script to get all the files back in the right place, then we'll go from there...

looks like @bitterypaul advised you to make some changes to `01-pihole.conf`, which I probably wouldn't have advised. 

Please run `curl -L https://install.pi-hole.net | bash` and go through the install process again. (or wipe your SD card and start again, your choice!)

**Comment by bmsecades** [comment] 2016-05-04 08:03
already reinstall pihole now my problem is the web interface. 

systemctl status lighttpd -l

● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: active (running) since Wed 2016-05-04 07:52:21 UTC; 7min ago
  Process: 479 ExecStartPre=/usr/sbin/lighttpd -t -f /etc/lighttpd/lighttpd.conf (code=exited, status=0/SUCCESS)
 Main PID: 577 (lighttpd)
   CGroup: /system.slice/lighttpd.service
           └─577 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf

**Comment by PromoFaux** [comment] 2016-05-04 09:27
Looks like it's running OK....

Can you run `pihole -d` again and pastebin the output file please?

**Comment by dschaper** [comment] 2016-05-28 01:50
@bmsecades Anything to update on this issue?

**Closed** 2016-06-01 05:20 UTC
Labels: question

**Comment by amitdhiman000** [comment] 2023-03-19 19:29
This might be old. 

The main problem is that, `systemd-resolved` is already running on port 53. you can verify that using below command.
```
sudo ss -lp "sport = :domain"
```
If we found the root cause, then there are 2 solutions.
1.) Disable the `systemd-resolved`
```
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
sudo systemctl mask systemd-resolved

# in case you want to revert back

sudo systemctl unmask systemd-resolved
sudo systemctl enable systemd-resolved
sudo systemctl start systemd-resolved
```

2.) Run dnsmasq on a differen port.
```
sudo nano /etc/dnsmasq.conf

# add below line to config.
port=5353
```
Hope it helped :)

**Comment by Wiinter4** [comment] 2024-07-26 13:03
Hi, can you please explain what occurs if I disable system-resolved or if I run dnsmasq on a different port?
