### ISSUE TITLE
Dashboard shows over 100% blocked in version 4.0

### ISSUE THREAD

**Issue by coralgulf** [pi-hole/pi-hole#2376] opened 2018-08-18 11:59 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**
Blocked pages in relation to all pages
`{A detailed description of what you expect to see}`

**Actual behaviour:**
Blocked pages count to >100% within hours/days
`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**
In my case just start version 4.0 and wait. Restart makes no difference, deleting logs no difference (confirmed bug)
`{Detailed steps of how we can reproduce this}`
Dashboard begins with correct values but ist always only counting up (f. e. 192% blocked after 48 hours)
**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`
Restart, flush logs
> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment] 2018-08-18 15:04
Duplicate of #2372 (fixed in dev)

**Closed by Mcat12** 2018-08-18 15:04 UTC
