### ISSUE TITLE
Decreased performance since 2207

### ISSUE THREAD

**Issue by kroese** [pi-hole/pi-hole#4853] opened 2022-08-02 21:22 UTC
I use Smokeping to monitor the DNS query times between two machines in my local network. I noticed that after upgrading the docker image from 2205 to 2207, the query times increased from around 2 ms to about 5 ms. 

As you can see from the below graph, there is a very large difference between the data before the 28th of July and the data after it. I did not modify anything in the configuration files, except for upgrading the container.

![Screenshot from 2022-08-02 23-15-07](https://user-images.githubusercontent.com/5763256/182475715-cbd3421a-fb5f-402e-b329-9249b09c9106.png)

**Comment by yubiuser** [comment] 2022-08-02 21:36
Thanks for your report. I fear we won't be able to reproduce this. The internal FTL component of Pi-hole is responsible for handling the DNS queries. The difference between Docker `22.05` and `22.07` regarding FTL is the release v5.16 (https://github.com/pi-hole/FTL/releases/tag/v5.16). I don't see anything obvious that could have caused the decreased performance.

**Comment by dschaper** [comment] 2022-08-02 22:55
Thanks for the report but I have to be honest and say that a difference in the range of 3ms is negligible and not something I'd call 'very large'. 

Since this issue is lacking hard data or configuration information that we can use I'm going to close it out. Feel free to use our Discourse Forum https://discourse.pi-hole.net for help with your setup.

**Closed by dschaper** 2022-08-02 22:55 UTC

**Comment by markg85** [comment] 2022-10-06 19:54
I find that reasoning slightly weird to be honest. I do much respect the development going into pihole and the components that make up this awesome package! I am using it (or rather again) since a couple weeks and haven't been disappointed about it at all!

But.. This test, even though it's probably difficult to profile does show "something" changed with a negative performance impact. Just a couple ms here and there is obviously nothing but it adds up over time. All i'm saying here is that it's better to investigate early. Investigating in a couple years (when a couple changes might have accumulated in latency) will be much harder.
