### ISSUE TITLE
Compatibility with Google OnHub

### ISSUE THREAD

**Issue by donslice** [pi-hole/pi-hole#346] opened 2016-02-24 03:59 UTC
##### Expected Behaviour:

Top Clients should show all clients utilizing the DNS server.
##### Actual Behaviour:

Only the OnHub router (192.168.86.1) shows up. It seems like the OnHub is only forwarding DNS requests (for caching?), not using a DHCP option to assign DNS servers. Not sure if this can be remedied at all without interfering with OnHub's DHCP, which doesn't seem possible at this point.
##

**Comment by DonLexos** [comment] 2016-02-24 12:20
Not sure how the onHub works but I noticed the DD-WRT installation on my router also had a dnsmasq option (which I disabled) specificly to make sure that this would not happen.

Does the pi-hole work or did Google hard code it's own DNS into the system? If it does work this would only concern the admin-stats page right? Clients banners are blocked?

**Comment by donslice** [comment] 2016-02-24 12:40
That's correct. The pi-hole does work, so only the stats page is affected. When I manually set the DNS on my desktop to the pi-hole, I can see it show up on the stats page.

I'm pretty sure there's no way to get around this without manually setting the DNS on each device, since the DHCP options on OnHub are limited unless I want to run it in Bridge mode. Unfortunately, that's not an option for me at this time. :/

**Comment by dschaper** [comment] 2016-03-01 12:38
Which OnHub do you have?

**Comment by donslice** [comment] 2016-03-01 12:44
TP-Link. Software version 7647.82.0.

**Comment by dschaper** [comment] 2016-03-01 13:04
Is there a Users Guide online that I could get a hold of?

**Comment by donslice** [comment] 2016-03-03 02:38
I haven't been able to find one on TP-Link's website. All of the how-to is on Google... and really, it's simplistic. I doubt there's a way at the moment. :/

https://on.google.com/hub/support/

**Comment by dschaper** [comment] 2016-03-03 03:14
Yeah, that's what I had come up with... It does make some sense that Google would hard code in the resolvers, but without dissecting one and seeing what processes it runs it's kind of difficult.

**Comment by dschaper** [comment] 2016-03-03 08:31
https://support.google.com/onhub/answer/6356383?hl=en&ref_topic=6355909 shows that `dnsmasq` is part of the software packages running on the OnHub, now the problem is configuring that process... I know, not much help...

**Comment by dschaper** [comment] 2016-03-12 22:32
We don't have access to the internals of the OnHub (It's locked down proprietary firmware and all feature enhancements are via a G+ forum, no direct communication to developers is available.) Going to close this, as there is no way Google is going to assist us in blocking their revenue stream.

**Comment by torch2424** [comment] 2016-09-07 23:33
Sorry to bring up a dead post, but I actually got pi hole working on my onHub.

Here's what I did:

* Click the gear in the upper right corner
* Click "Advanced Networking"
* Click "DNS"
* Click "Custom" (This brings additional options)
* Set DNS 1 to the default DNS server, and DNS 2 to the secondary server. In my case, I wanted the default to be google's DNS (8.8.8.8), and I wanted the pi-holes to be the secondary (192.168.86.x)
* "Save" in the upper right corner

Then, you can [follow a guide](http://www.makeuseof.com/tag/adblock-everywhere-raspberry-pi-hole-way/) on configuring your devices to have a static ip and use the pi hole. For me, I set my android phone wifi settings to use static instead of DHCP, and set the ip to an unused ip on the onHub, and set DNS 1 to the pihole ip, and DNS to google's servers. Test, and everything should be working!

Also, I wanted to port forward the admin page to my device, so, [you can go here](https://support.google.com/onhub/answer/6274503?hl=en) for details on port forwarding on the onHub. Select the pihole ip, set the internal port to 80 (since its the default pihole port), and then any external port you would like to expose. Also, note that for some odd reason, port forwarding only works outside of the network. Meaning, connect to another internet connection (Friend's router, or phone hotspot) to test port forwarding. It will not work within your own network.

**Comment by donslice** [comment] 2016-09-07 23:48
That doesn't fix the issue, it only works around it. It's unreasonable to have every device on my home LAN have a static address. It also doesn't take into account any guest that might come into my home.

**Comment by dschaper** [comment] 2016-09-07 23:50
Would a custom DNS setup with Pi-hole as primary and then your clients DHCP reservation pointing to the OnHub solve the issue?

**Comment by donslice** [comment] 2016-09-07 23:56
I think it would, yes. The issue with OnHub is that it forwards requests instead of telling the host what DNS server to use via DHCP.

I'm not sure this is anything that Pi-Hole could remedy at this point, unfortunately. :/

**Comment by dschaper** [comment] 2016-09-08 00:01
This looks like a solution to set where OnHub forwards its requests to. And if this is controllable, setting it to forward to Pi-hole would solve the issue.

**Comment by torch2424** [comment] 2016-09-08 04:27
Actually @donslice if you set the pihole IP as DNS 1 in the onhub settings, all devices will default to using the pi-hole before using google's DNS servers. DNS 2 is just a backup in case DNS 1 is not performing properly.

Yes this is a workaround, but it works, and now I am quite satisfied with my pihole and onhub :smile: 

It did take a lot of unneeded time and elbow grease in my opinion though.

**Comment by jacobsalmela** [comment] 2016-12-26 05:09
@donslice did @torch2424's solution work for you?

**Comment by SteveW25561** [comment] 2016-12-26 07:54
I can confirm that pihole works to block ads on my Google Wifi system by setting the DNS1 in the Google WiFi app to 192.168.86.2 (where I have the pihole static address set), and the secondary DNS to 8.8.8.8 (although I have pihole's own upstream DNS set to OpenDNS).

I understand that Google WiFi and OnHub devices now have the same firmware.

**Comment by dschaper** [comment] 2016-12-29 02:07
Thanks for the update SteveW25561, that should close this out.

**Closed by dschaper** 2016-12-29 02:07 UTC
Labels: Documentation Needed

**Comment by vc1492a** [comment] 2017-04-05 05:20
Can also confirm that setting the DNS1 to the PiHole IP address and the secondary DNS to 8.8.8.8 works on the TP-Link Google OnHub.
