### ISSUE TITLE
fail to load after update 

### ISSUE THREAD

**Issue by David-Afik** [pi-hole/pi-hole#4894] opened 2022-09-04 07:50 UTC
### Versions
  Pi-hole version is v5.8.1 (Latest: v5.12)
  AdminLTE version is v5.10.1 (Latest: v5.14.1)
pihole-FTL: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by pihole-FTL)
pihole-FTL: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by pihole-FTL)
  Latest FTL version is v5.17

### Platform
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Expected behavior

after update the pi-hole service has stop working 

### Actual behavior / bug

 [✗] Unsupported OS detected: Centos 7
      If you are seeing this message and you do have a supported OS, please contact support.

      https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems

      If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:

      e.g: If you are seeing this message on a fresh install, you can run:
             curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash

           If you are seeing this message after having run pihole -up:
             PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r
           (In this case, your previous run of pihole -up will have already updated the local repository)

      It is possible that the installation will still fail at this stage due to an unsupported configuration.
      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/

  Unable to complete update, please contact Pi-hole Support
[opc@pi-hole-pelephone ~]$ PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Checking yum for upgraded packages... 13 updates available
  [i] It is recommended to update your OS after installing the Pi-hole!

  [i] Checking for / installing Required dependencies for OS Check...
  [✓] Checking for grep
  [✓] Checking for bind-utils

  [i] PIHOLE_SKIP_OS_CHECK env variable set to true - installer will continue
  [i] Checking for / installing Required dependencies for this install script...
  [✓] Checking for git
  [✓] Checking for iproute
  [✓] Checking for newt
  [✓] Checking for procps-ng
  [✓] Checking for which
  [✓] Checking for chkconfig
  [✓] Checking for ca-certificates

  [✓] Default SELinux: permissive
  [✓] Current SELinux: Permissive
  [i] Repair option selected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Checking for / installing Required dependencies for Pi-hole software...
  [✓] Checking for cronie
  [✓] Checking for curl
  [✓] Checking for findutils
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for libidn2
  [✓] Checking for psmisc
  [✓] Checking for sqlite
  [✓] Checking for libcap
  [✓] Checking for nmap-ncat
  [✓] Checking for lighttpd
  [✓] Checking for lighttpd-fastcgi
  [✓] Checking for php-common
  [✓] Checking for php-cli
  [✓] Checking for php-pdo
  [✓] Checking for php-xml
  [✓] Checking for php-intl

  [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected x86_64 processor
  [i] Checking for existing FTL binary...
  [✓] Downloading and Installing FTL
  [i] Warning: 'lighty-enable-mod' utility not found
      Please ensure fastcgi is enabled if you experience issues
  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf

  [i] Installing blocking page...
  [✓] Creating directory for blocking page, and copying files
  [i] Backing up index.lighttpd.html
      No default index.lighttpd.html file found... not backing up

  [✓] Installing sudoer file

  [✓] Installing latest Cron script

  [i] Installing latest logrotate script...
        [i] Existing logrotate file found. No changes made.
  [i] Backing up /etc/dnsmasq.conf to /etc/dnsmasq.conf.old
  [✓] man pages installed and database updated
  [i] Testing if systemd-resolved is enabled
  [i] Systemd-resolved is not enabled
  [✓] Restarting lighttpd service...
  [✓] Enabling lighttpd service to start on reboot...
  [i] Restarting services...
  [✓] Enabling pihole-FTL service to start on reboot...
  [✓] Restarting pihole-FTL service...
  [✓] Deleting existing list cache
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [✓] Preparing new gravity database
  [i] Using libz compression

  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Analyzed 136768 domains

  [✓] Storing downloaded domains in new gravity database
  [✓] Building tree
  [✓] Swapping databases
  [✓] The old database remains available.
  [i] Number of gravity domains: 136768 (136768 unique domains)
  [i] Number of exact blacklisted domains: 0
  [i] Number of regex blacklist filters: 0
  [i] Number of exact whitelisted domains: 0
  [i] Number of regex whitelist filters: 0
  [i] FTL is not running
  [✓] Cleaning up stray matter
  [✓] Restarting DNS server

  [✗] DNS service is NOT running
pihole-FTL: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by pihole-FTL)
pihole-FTL: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by pihole-FTL)

  [i] The install log is located at: /etc/pihole/install.log
Update Complete!

### Steps to reproduce

what do to? 

how to fix this bug now ? 

the webpage is not running , can't see requests or evern to know if it's working

**Comment by yubiuser** [comment] 2022-09-04 08:15
Duplicate of https://github.com/pi-hole/FTL/issues/1420.
See the how to work around.

**Closed by yubiuser** 2022-09-04 08:15 UTC
