### ISSUE TITLE
FTL cant start since latest nightly upgrade

### ISSUE THREAD

**Issue by kriz84** [pi-hole/pi-hole#4671] opened 2022-04-02 07:42 UTC
hello,
my pihole is not running anymore since the latest nightly upgrading i made today, the latest upgrade was so 1,5 weeks ago w/o problem.
portainer gives this log:

> Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as pihole
Unable to set inheritable capabilities: Operation not permitted
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as pihole
Unable to set inheritable capabilities: Operation not permitted
Stopping pihole-FTL
pihole-FTL: no process found

and when i ran pihole -v

> Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as pihole
Unable to set inheritable capabilities: Operation not permitted
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as pihole
Unable to set inheritable capabilities: Operation not permitted
Starting pihole-FTL
pihole-FTL: no process found

one time i tried to setting dnsmasquser to root if this fixes but no change
and my debug.log is attached
>
[debug.log](https://github.com/pi-hole/pi-hole/files/8402038/debug.log)

this is something different, not related to this but i wass also getting in pihole diagnosis this error:
this is my mvance unbound server: pihole is 192.168.1.3 on macvlan

> 2022-03-23 03:47:04 | DNSMASQ_WARN | Warning in dnsmasq core:reducing DNS packet size for nameserver 192.168.1.2 to 1232

please what can i do? iam also not familiar with any commands....i dont wont to do from scratdh :/
thanks

my dockers are running on my new Qnap TS 453D Server

**Comment by yubiuser** [comment] 2022-04-02 08:13
This is a docker setup?

**Comment by PromoFaux** [comment] 2022-04-02 08:30
Dupe of https://github.com/pi-hole/docker-pi-hole/issues/1035
 
Please see:

https://github.com/pi-hole/docker-pi-hole/blob/master/README.md#upgrade-notes

**Closed by PromoFaux** 2022-04-02 08:30 UTC

**Comment by kriz84** [comment] 2022-04-02 08:58
Thanks but this doesnt worked.
I enabled NET_ADMIN when i click on duplicate/Edit in portainer under capabilities and clicked on deplay Container, i got the same érror :/

**Comment by PromoFaux** [comment] 2022-04-02 10:23
I've just pushed a new dev build that should hopefully solve this issue once and for all. It only attempts to set capabilities if they are available to the container.

Please try the dev - for those of you that don't need NET_ADMIN, please also unset this when trying the newest dev

Thanks all for your continued patience!

**Comment by kriz84** [comment] 2022-04-02 10:32
> I've just pushed a new dev build that should hopefully solve this issue once and for all. It only attempts to set capabilities if they are available to the container.
> 
> Please try the dev - for those of you that don't need NET_ADMIN, please also unset this when trying the newest dev
> 
> Thanks all for your continued patience!

I Just Trier that w/o NET_ADMIN and SYS_NICE
It die work with no problems

**Comment by PromoFaux** [comment] 2022-04-02 11:10
https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.04.1

(nightly will contain the changes by tomorrow!)
