### ISSUE TITLE
Webinterface / admin: tooltip being cut off in graph area in Firefox (multi platform)

### ISSUE THREAD

**Issue by walter-exit** [pi-hole/pi-hole#2146] opened 2018-04-23 13:41 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
0

---
**Expected behaviour:**

Tooltip with clients, in graph, to be ontop of graph. Displaying properly.

**Actual behaviour:**

Tooltip bound to graph area, often cutting off a part or all of the tooltip. So it cannot be read.

**Steps to reproduce:**

Open the webinterface in Firefox 59+ (Tested on multiple PCs, Windows 10 and Linux Mint 18)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A (not needed either)

**Troubleshooting undertaken, and/or other relevant information:**

I will attach a screenshot in which the problem is clearly visible. Red strokes are added to guide your eyes to the area of the problem. The only visible client has been crossed out with black for privacy reasons.
![pihole-tooltip-underneath](https://user-images.githubusercontent.com/3541555/39130166-b8417eae-470c-11e8-83ee-03aaf14f460d.png)

**Comment by dschaper** [comment] 2018-04-23 13:53
Duplicate of: #1932, #1837 and a few reports at https://github.com/pi-hole/adminlte.

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Closed by dschaper** 2018-04-23 13:53 UTC

**Comment by walter-exit** [comment] 2018-04-23 14:08
@dschaper Thank you for pointing out the other two tickets, I could not find any duplicated, my bad.

The debug token is absolutely unnecessary for reproducing and fixing this issue. It's a shame the lack of this token causes issues to be closed without being fixed.

I understand your time is limited. So is mine, I run a software company. I can hand you the fix if you like though, I wont bother with git checkouts and pull requests though, no time, sorry. But I can provide a detailed fix required, as a comment here. If that helps you guys. Let me know.

**Comment by dschaper** [comment] 2018-04-23 14:14
The issue wasn't closed due to the lack of token, it was the:

> The issue I am reporting isn't a duplicate (see FAQs, closed issues, and open issues).

We have at least half a dozen reports of the issue between this repo and the web interface repository. If you have code to help with the problem we'd accept it, but please use `https://github.com/pi-hole/adminlte` for the issue as that is where the patch would apply.

**Comment by walter-exit** [comment] 2018-04-23 14:19
@dschaper I read the tickets you linked. I see a fix has been merged into the development branch 8 days ago already (discussed at https://github.com/pi-hole/AdminLTE/issues/603). So I expect this to be fixed in the next release. Thank you for your time, and apologies for the duplicate in the wrong section.
