### ISSUE TITLE
Adding domain to whitelist (GUI or command line) yields 'Blocked (gravity)' for queries for that domain

### ISSUE THREAD

**Issue by 9numbernine9** [pi-hole/pi-hole#3398] opened 2020-05-18 04:15 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
A site that I've added to the whitelist, `widget-cdn.rpxnow.com`, resolves correctly when Pihole's DNS server is queried.

**Actual behaviour:**
`dig` for `widget-cdn.rpxnow.com` returns `0.0.0.0` instead, and the query log shows `Blocked (gravity)` for this query.

**Steps to reproduce:**
Using Pihole `5.0`, run `pihole -w widget-cdn.rpxnow.com` and then use `dig` to query Pihole's DNS to get the IP address for `widget-cdn.rpxnow.com`.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`4em6i33bfu`

**Troubleshooting undertaken, and/or other relevant information:**

- Adding the domain through the GUI or through `pihole -w` seems to yield the same behaviour. 
- Attempting to add the domain a second time with `pihole -w` returns `[i] widget-cdn.rpxnow.com already exists in whitelist, no need to add!`, so Pihole believes that the domain is in the whitelist.
- Disabling Pihole through the GUI for 10/30 seconds and then running `dig @192.168.0.2 widget-cdn.rpxnow.com` returns unblocked results. (`192.168.0.2` is the IP address of my Pihole server.)
- `pihole -q -exact` shows domain in whitelist and one ad list:
```
pi@pihole:~ $ pihole -q -exact widget-cdn.rpxnow.com
 Exact match found in exact whitelist
   widget-cdn.rpxnow.com
 Exact match for widget-cdn.rpxnow.com found in:
  - http://sysctl.org/cameleon/hosts 
```

**Comment by dschaper** [comment] 2020-05-18 04:20
This is a bit odd, according to the debug log a `dig` using 8.8.8.8 is returning 0.0.0.0, which shouldn't ever happen. Can you duplicate this?

```plain
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] asgh65tfsdxz.appspot.com is 0.0.0.0 via localhost (127.0.0.1)
[✓] asgh65tfsdxz.appspot.com is 0.0.0.0 via Pi-hole (192.168.0.2)
[✓] doubleclick.com is 0.0.0.0 via a remote, public DNS server (8.8.8.8)
```

**Comment by 9numbernine9** [comment] 2020-05-18 04:29
Indeed I can. 
```
pi@pihole:~ $ dig +short @8.8.8.8 doubleclick.com
0.0.0.0
```
I should probably explain my network setup a bit to resolve the confusion. :-)

My router transparently redirects outbound DNS queries on port 53 back to Pihole inside the network (I try to prevent devices that may have hardcoded DNS settings from doing their own thing). On my Pihole machine, I have `dnscrypt-proxy` running that queries external DNS-over-HTTP servers of my choosing, and Pihole uses that `dnscrypt-proxy` instance as its upstream DNS server. Since DoH queries are on a different port, they are allowed to escape past the router.

**Comment by dschaper** [comment] 2020-05-18 04:35
If that's the case then you'll want to look at your IPv6 configuration, queries on port 53 are resolving.

```plain
*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
[✓] ortaklik.mynet.com is :: via localhost (::1)
[✓] ortaklik.mynet.com is :: via Pi-hole (<GUA REDACTED>)
[✓] doubleclick.com is 2607:f8b0:400b:802::200e via a remote, public DNS server (2001:4860:4860::8888)
```

**Comment by 9numbernine9** [comment] 2020-05-18 04:42
You are indeed correct, and I will need to look into that more. I tried to write a firewall rule for that previously and it didn't work - looks like I forgot to try to fix it again. 😆

**Comment by PromoFaux** [comment] 2020-05-18 06:33
I'm not able to reproduce the results on a stock Pi-hole install.

```
root@raspberrypi:~# pihole -q widget-cdn.rpxnow.com
 Match found in http://sysctl.org/cameleon/hosts:
   widget-cdn.rpxnow.com

root@raspberrypi:~# nslookup widget-cdn.rpxnow.com
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find widget-cdn.rpxnow.com: NXDOMAIN

root@raspberrypi:~# pihole -w widget-cdn.rpxnow.com
  [i] Adding widget-cdn.rpxnow.com to the whitelist...
  [✓] Reloading DNS lists

root@raspberrypi:~# pihole -q widget-cdn.rpxnow.com
 Match found in exact whitelist
   widget-cdn.rpxnow.com
 Match found in http://sysctl.org/cameleon/hosts:
   widget-cdn.rpxnow.com

root@raspberrypi:~# nslookup widget-cdn.rpxnow.com
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   widget-cdn.rpxnow.com
Address: 143.204.169.9
Name:   widget-cdn.rpxnow.com
Address: 143.204.169.19
Name:   widget-cdn.rpxnow.com
Address: 143.204.169.63
Name:   widget-cdn.rpxnow.com
Address: 143.204.169.76
```

Similar results with `dig`

```
root@raspberrypi:~# pihole -q widget-cdn.rpxnow.com
 Match found in http://sysctl.org/cameleon/hosts:
   widget-cdn.rpxnow.com
root@raspberrypi:~#
root@raspberrypi:~# dig widget-cdn.rpxnow.com

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> widget-cdn.rpxnow.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 35724
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;widget-cdn.rpxnow.com.         IN      A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon May 18 07:27:51 BST 2020
;; MSG SIZE  rcvd: 39

root@raspberrypi:~# pihole -w widget-cdn.rpxnow.com
  [i] Adding widget-cdn.rpxnow.com to the whitelist...
  [✓] Reloading DNS lists
root@raspberrypi:~#
root@raspberrypi:~# dig widget-cdn.rpxnow.com

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> widget-cdn.rpxnow.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10026
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;widget-cdn.rpxnow.com.         IN      A

;; ANSWER SECTION:
widget-cdn.rpxnow.com.  59      IN      A       143.204.169.9
widget-cdn.rpxnow.com.  59      IN      A       143.204.169.63
widget-cdn.rpxnow.com.  59      IN      A       143.204.169.76
widget-cdn.rpxnow.com.  59      IN      A       143.204.169.19

;; Query time: 19 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon May 18 07:28:04 BST 2020
;; MSG SIZE  rcvd: 114

root@raspberrypi:~#
```

If you open up a second terminal to the side running `pihole -t ` to tail the logs, what do you see when you attempt to resolve this domain? (both with it on and off of the blocklist)

On whitelist:
```
07:32:13: query[A] widget-cdn.rpxnow.com from 127.0.0.1
07:32:13: forwarded widget-cdn.rpxnow.com to 8.8.4.4
07:32:13: reply widget-cdn.rpxnow.com is 143.204.169.76
07:32:13: reply widget-cdn.rpxnow.com is 143.204.169.63
07:32:13: reply widget-cdn.rpxnow.com is 143.204.169.9
07:32:13: reply widget-cdn.rpxnow.com is 143.204.169.19
```

Off whitelist:

```
07:32:27: query[A] widget-cdn.rpxnow.com from 127.0.0.1
07:32:27: cached widget-cdn.rpxnow.com is ::
```

**Comment by 9numbernine9** [comment] 2020-05-18 15:37
Hey @PromoFaux , thanks for taking the time to help debug this!

I was about to post a comment with all of the information that you requested, but when I went through all of the steps _everything was working_. I am currently _extremely_ confused. `dig` for the whitelisted domain from my Pihole machine is now working correctly, and I truly have no idea why. The _only_ thing that I can think of that's different now is that I started from a clean slate (i.e. no whitelist or blacklist of any kind) and went through all your debugging steps in the above comment using _only_ the command line `pihole` utilities, whereas last night I was trying to get the whitelist working using the GUI. I know that _shouldn't_ make a difference whether I add to the whitelist from the GUI or the command line, but it's the only thing that I can think of that's different between then and now.

I'll try to replicate this issue again if I can, and I apologize for wasting your time.

**Comment by PromoFaux** [comment] 2020-05-18 15:40
> I was about to post a comment with all of the information that you requested, but when I went through all of the steps everything was working. I am currently extremely confused

Funnily enough, I hear this from my colleagues at work all the time 😉 

Let us know if you can replicate!

**Comment by joelmacklow** [comment] 2020-06-10 23:20
I seem to be experiencing this issue as well.  Blocklist seems to be taking precedence over whitelist entries.

On my pi-hole:
`root@Prod-Pi-Hole:~# pihole -q ae01.alicdn.com
 Match found in exact whitelist
   ae01.alicdn.com
 Match found in https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts:
   ae01.alicdn.com

root@Prod-Pi-Hole:~# dig +short @127.0.0.1 ae01.alicdn.com
global-image.aliexpress.com.
global-image.aliexpress.com.gds.alibabadns.com.
us1111.alicdn.com.edgekey.net.
e1429.x.akamaiedge.net.
23.202.168.47
`

On my client:
`nslookup ae01.alicdn.com 45.76.116.201
Server:  Prod-Pi-Hole
Address:  45.76.116.201

Name:    ae01.alicdn.com
Addresses:  ::
          0.0.0.0`

Disabling the block list in GUI on pi-hole and flushdns on client and query again:
`nslookup ae01.alicdn.com 45.76.116.201
Server:  Prod-Pi-Hole
Address:  45.76.116.201

Non-authoritative answer:
Name:    e1429.x.akamaiedge.net
Address:  23.202.168.47
Aliases:  ae01.alicdn.com
          global-image.aliexpress.com
          global-image.aliexpress.com.gds.alibabadns.com
          us1111.alicdn.com.edgekey.net`

So certainly seems that the blocklist is overriding the whitelist entry?

**Comment by notDavid** [comment] 2020-08-24 20:01
I have the same issue, whitelisted domains which are on an 'adlist' still resolve to `0.0.0.0`.

(Pi-hole v5.1.2 / Ubuntu 18.04.4)

**Comment by notDavid** [comment] 2020-08-24 20:22
Okay so i found my issue, not sure if this is what confused others as well;

When you whitelist a domain via the Query log, it is only whitelisted in the "Default" group.
You cannot see this in [whitelist page](http://pi.hole/admin/groups-domains.php?type=white).
You **can** see this in the [domains page](http://pi.hole/admin/groups-domains.php)

**Closed** 2021-08-12 15:43 UTC
