### ISSUE TITLE
Installing on ARM QNAP device with Debian 10 chooses wrong FTL binary

### ISSUE THREAD

**Issue by Archomeda** [pi-hole/pi-hole#3733] opened 2020-09-05 16:06 UTC
### Versions
- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform
- OS and version:  Debian 10
- Platform:  QNAP TS-112

### Expected behavior
The installer should download the correct FTL binary for this device, which is `pihole-FTL-armel-native` that I've verified to work by downloading it manually.

### Actual behavior / bug
Currently the installer chooses `pihole-FTL-arm-linux-gnueabi`. The debian installation on my QNAP TS-112 cannot handle this executable and exists by saying `/usr/bin/pihole-FTL: No such file or directory`.

### Steps to reproduce
1. Follow the automated installation instructions on a QNAP TS-112 with Debian 10
2. It mentions `Supported OS detected` and `Detected ARM architecture`
3. However, during the installation it repeatedly mentions `/usr/bin/pihole-FTL: No such file or directory` and that the DNS service cannot be started

### Additional context
Originally the QNAP TS-112 doesn't come with Debian installed, but rather with QNAP's own firmware. However, Debian can be installed through [this guide](https://www.cyrius.com/debian/kirkwood/qnap/ts-119/install/) and uses the armel architecture.

I dug through the installer script, and noticed that the `Detected ARM architecture` comes from [this line](https://github.com/pi-hole/pi-hole/blob/b5983a3fc1b2c6f3b02ada596d812ed3cd76384d/automated%20install/basic-install.sh#L2432).
I'm glad that the `armel-native` executable is available that does work, but it seems it's considered in docker environments only.
By commenting out some lines so that the installer chooses the "docker" variant, the installation succeeds and FTL can be started.

I don't know how these conditions can be improved to detect the QNAP TS-112 properly myself (and I assume other ARM based QNAP devices benefit from this as well), but I hope this information will help for the person that does:
```console
$ ldd /bin/ls | grep -E '^\s*/lib' | awk '{ print $1 }'
/lib/ld-linux.so.3
$ uname -srvmpio
Linux 4.19.0-10-marvell #1 Debian 4.19.132-1 (2020-07-24) armv5tel unknown unknown GNU/Linux
```

**Comment by Archomeda** [comment] 2020-09-05 22:27
Okay, it seems I might have celebrated too soon that the armel binary works.
It *runs*, but as soon as it tries to forward a DNS query, it crashes without much information.
The only thing I get while running `pihole-FTL debug` is the following:
```console
dnsmasq: query[A] google.nl from 127.0.0.1
Illegal instruction
```

I have no idea on how to debug this. Should I open a new issue for this, or do we keep it here?

**Comment by dschaper** [comment] 2020-09-06 00:56
Open one on FTL's repo. I suggest following the instructions to compile your own FTL on your hardware and see if it's even possible first though.

**Comment by DL6ER** [comment] 2020-09-06 12:13
> Illegal instruction

This means the processor killed the process because it tried to execute machine code that does not exist (on this CPU).

The `armel` binary on compiled for [`ARMv6`](https://developer.arm.com/documentation/dui0471/j/key-features-of-arm-architecture-versions/arm-architecture-v6). The QNAP TS-112 uses a [`Marvel 6282`](https://dtsheet.com/doc/1285657/marvell-88f6282-soc) which is only `ARMv5`-compliant. Hence, there are several instructions missing on this processor and it was pure "luck" that it ran at all so far.

The reason for the issue is likely [the `REV` asm instruction](https://www.keil.com/support/man/docs/armasm/armasm_dom1361289889712.htm) which is not supported by ARMv5 processors but is used in networking code quite a lot ("network byte order"). There isn't anything the application can do to compensate for the CPU mismatch. It's actually the devices fault to not check if it can run the binary at all before executing it.
So much for the background of your error and why there isn't anything in the logs.

I fully agree with @dschaper that the way to go here is to compile locally. Your local compiler is aware of what your particular CPU can do and will only create machine code it can also execute. If, e.g., the `REV` instruction isn't available, it will do this manually which will work equally will. It's just a bit slower as the same thing is done in multiple steps instead of one now.

Please open a ticket on the FTL repo if you have any problems with compiling FTL from source. There is a good page on your official documentation that will walk you through the necessary steps. Once you have all the prerequirements in place, future updates will run much faster. Expect a compiling time of up to half an hour maybe on such a low-end device (ARMv5).

**Comment by Archomeda** [comment] 2020-09-07 06:14
Thanks for the response!
I managed to compile it locally in just about 45 minutes I think, including the dependencies. FTL has been up and running for 10 hours, and so far I don't see any issues.

Are you planning to support compiling and releasing official ARMv5 binaries, and is there anything I can help you with? Or should I continue to compile it myself?

**Comment by DL6ER** [comment] 2020-09-23 12:37
Over the last two weeks, I tried to establish a working CI toolchain for ARMv5TE using the [multiarch/crossbuild](https://github.com/multiarch/crossbuild) toolchain. Unfortunately, setting up an ARMv5 toolchain failed. I'll ping @dschaper for his opinion as he is managing our infrastructure, but I do not want to create any hope. I don't think there is much we can do to add support for ARMv5.

**Comment by dschaper** [comment] 2020-09-23 16:44
I trust your judgement. If there's something we need to add or change to allow building then of course we well add that. But short of getting some ARMv5 hardware to compile natively on, if that would even work, I'll concur that it's not a platform we can handle.

**Comment by Archomeda** [comment] 2020-09-23 22:08
@DL6ER Since you mentioned the CI toolchain, I decided to look how the other FTL builds are made. I took me a bit to find the file that I wanted, [the armhf dockerfile](https://github.com/pi-hole/docker-base-images/blob/master/ftl-build/armhf/Dockerfile).

I changed all mentions of `armhf` to `armel` and `gnueabihf` to `gnueabi`. Building seems to have worked, and it's currently already past the crash from my original post. I'll keep it running in tmux tomorrow to see if it will stay that way.

**Comment by DL6ER** [comment] 2020-09-23 22:13
This is about how we prepare the other binary (the one you tried and which failed). Even when it is done slightly different, you can find in the `arm` Dockerfile that this is exactly what we do:

https://github.com/pi-hole/docker-base-images/blob/8547ffe2ed821926411c8e57b8db366a99eac1b8/ftl-build/arm/Dockerfile#L10

It would be somewhat puzzling if it wouldn't crash and I wouldn't be ready yet to translate this into full ARMv5 compatibility.

**Comment by Archomeda** [comment] 2020-09-23 22:30
That one seems to have armel and gnueabihf mixed, I assume this is because Raspbian's GCC for ARMv6?
In my local dockerfile I've also used gnueabi instead of gnueabihf, which I'm assuming should fully skip the hardfloats. And from what I can see on the Debian Wiki, armel should be ARMv5T compliant (before Debian 10 it was ARMv4T compliant it seems), whereas armhf is ARMv7.
Honestly, all those different versions are getting confusing 😕

Anyhow, I understand that this doesn't necessarily mean that it's fully compatible with ARMv5, even if it's past the first hurdle compared to the ARMv6 binary. Is there any way I can validate it?

**Comment by DL6ER** [comment] 2020-09-24 17:27
> Is there any way I can validate it?

You'd need a tool that checks every instruction to determine exactly which set it belongs to. I'm not aware of a tool that can do it. If you'd know the exact illegal instruction, you could directly search for it, using some sort of `objdump -d | grep ...` chain (`objdump -d` should get you the entire disassembly where you can then just `grep` for bad opcodes).

You could maybe try
```
readelf -a pihole-FTL | grep Tag
```
but I'm not sure if the output will be very reliable.

**Comment by Archomeda** [comment] 2020-09-24 23:49
Searching for specific instructions goes way beyond my current knowledge sadly enough.

I did run readelf against the cross compiled executable, which resulted in:
```
  Tag        Type                         Name/Value
  Tag_CPU_name: "4T"
  Tag_CPU_arch: v4T
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
```

Compared to the one I compiled locally:
```
  Tag        Type                         Name/Value
  Tag_CPU_name: "5TE"
  Tag_CPU_arch: v5TE
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
```

**Comment by DL6ER** [comment] 2020-10-10 19:57
@Archomeda Can you post the entire modified Dockerfile you used? I'll look at adding an automated v5TE binary build process. However, no need to reinvent the wheel so if you already have a working Dockerfile, I should take this one instead of inventing my own :-)

**Comment by DL6ER** [comment] 2020-10-11 10:32
NVM, I found how to get ARMv4T-compliance with the `multiarch` cross compiler.

**Comment by dschaper** [comment] 2020-10-11 19:23
![](http://i.imgur.com/3JDHLkq.gif)

**Comment by Archomeda** [comment] 2020-10-12 10:07
@DL6ER Oh, nice! That's awesome.
I was just looking at my Dockerfile and comparing it to the ones in the docker-base-images repo as I noticed your PR pi-hole/docker-base-images#29 😄

Just for completion's sake, I've added the Dockerfile.
Now I do wonder what benefits the qemu build has compared to cross compiling like the other ARM builds, since they should be building for the same target now.

Anyway, `FROM debian:stretch` makes it build a v4T, `FROM debian:buster` makes it build a v5TE.
I believe the changes are still [the ones that I mentioned a couple of weeks ago](https://github.com/pi-hole/pi-hole/issues/3733#issuecomment-697997984).

<details><summary>Dockerfile</summary>

```dockerfile
FROM debian:stretch

# ghr 0.13.0 2019-09-16
ARG ghrversion=0.13.0

ARG readlineversion=8.0
ARG termcapversion=1.3.1

RUN dpkg --add-architecture armel \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        ca-certificates \
        curl \
        dnsutils \
        file \
        gcc-arm-linux-gnueabi \
        git \
        libc6-dev-armel-cross \
        libcap-dev:armel \
        libcap2-bin \
        libidn11-dev:armel \
        make \
        netcat-traditional \
        nettle-dev:armel \
        ssh \
        sqlite3 \
        wget \
        binutils \
        cmake \
        libc6:armel \
    && rm -rf /var/lib/apt/lists/*
    
# Install ghr for GitHub Releases: https://github.com/tcnksm/ghr
RUN curl -sSL https://github.com/tcnksm/ghr/releases/download/v${ghrversion}/ghr_v${ghrversion}_linux_amd64.tar.gz | \
    tar --strip-components=1 -C /usr/bin/ -xz \
    ghr_v${ghrversion}_linux_amd64/ghr

ENV CC "arm-linux-gnueabi-gcc -isystem /usr/local/include"
RUN ln -s /usr/arm-linux-gnueabi/lib/libm.so /usr/local/lib/

RUN curl -sSL https://ftl.pi-hole.net/libraries/termcap-${termcapversion}.tar.gz | tar -xz \
    && cd termcap-${termcapversion} \
    && ./configure --host=arm-linux-gnueabi --enable-static --disable-shared --disable-doc --without-examples \
    && make -j $(nproc) \
    && make install \
    && ls /usr/local/lib/ \
    && cd .. \
    && rm -r termcap-${termcapversion}

RUN curl -sSL https://ftl.pi-hole.net/libraries/readline-${readlineversion}.tar.gz | tar -xz \
    && cd readline-${readlineversion} \
    && ./configure --host=arm-linux-gnueabi --enable-static --disable-shared --disable-doc --without-examples \
    && make -j $(nproc) \
    && make install-static \
    && ls /usr/local/lib/ \
    && cd .. \
    && rm -r readline-${readlineversion}

# Uncomment the following line to test-compile FTL master during docker container development
# RUN git clone https://github.com/pi-hole/FTL.git && cd FTL && git checkout development \
#     && bash build.sh -DLUA_READLINE=true && readelf -A ./pihole-FTL
```
</details>

**Comment by DL6ER** [comment] 2020-10-12 19:18
> Anyway, `FROM debian:stretch` makes it build a v4T, `FROM debian:buster` makes it build a v5TE (I have not tested running the v5TE variant, even though it does build).

Yeah, this is expected due to 

> **From Debian 10 (buster), 4T is no longer supported and the armel baseline was updated to 5T[E].** ([source](https://wiki.debian.org/ArmEabiPort))


PR https://github.com/pi-hole/docker-base-images/pull/30 will ensure we build one binary per ARM revision so every CPU get the binary with the best optimization potential. Thanks again for your input!

**Comment by Archomeda** [comment] 2020-11-16 21:07
That's great! You're welcome, and thank you for the amazing discussion 😃 (and sorry for this late reaction, I've somehow missed it completely)

**Comment by yubiuser** [comment] 2021-08-10 19:00
Should be fixed by https://github.com/pi-hole/docker-base-images/pull/30

**Closed by yubiuser** 2021-08-10 19:00 UTC
