### ISSUE TITLE
Admin page completely emtpy (as in white) after latest update

### ISSUE THREAD

**Issue by pwyder** [pi-hole/pi-hole#4335] opened 2021-09-19 09:00 UTC
### Versions

- Pi-hole:  5.4
- AdminLTE:  5.6
- FTL:  5.9

### Platform

- OS and version:  CentOS Linux release 7.9.2009

- Platform:  Intel NUC

### Expected behavior

When I go to http://pi-hole.server/admin I can log into and administrate Pi-Hole (as it was before the update)

### Actual behavior / bug

The admin page is completely empty (whiter page). Page source only shows:
<html>
  <head></head>
  <body><body>
</html>

### Steps to reproduce

Just try to open the admin page :)

## Debug Token

- URL:  https://tricorder.pi-hole.net/3eIMctbv/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

Errors I saw under the lighttpd logs are:
2021-09-19 09:47:46: (mod_fastcgi.c.421) FastCGI-stderr: PHP Parse error:  syntax error, unexpected '.' in /var/www/html/admin/scripts/pi-hole/php/auth.php on line 54

**Comment by yubiuser** [comment] 2021-09-19 12:53
Duplicate of
https://github.com/pi-hole/pi-hole/issues/4329.

See there for the solution

**Closed by yubiuser** 2021-09-19 12:53 UTC
