### ISSUE TITLE
Youtube Ads Still Showing on Nexus 9 Running 5.1.1

### ISSUE THREAD

**Issue by le0nard0** [pi-hole/pi-hole#230] opened 2016-01-23 05:36 UTC
I have installed Pi-Hole and change the DNS settings on my Tablet. The ad blocking is working, however ads on Youtube are still showing. 

![screenshot_2016-01-23-00-34-58](https://cloud.githubusercontent.com/assets/6979628/12528592/4c779b48-c169-11e5-8b1e-2299271aff20.png)

Let me know what other information you need.

**Comment by dschaper** [comment] 2016-01-23 05:37
Thanks for opening the issue. Let me do a fresh install of the latest version and see if I can replicate the situation.

**Comment by dschaper** [comment] 2016-01-23 05:53
Is it all YouTube pages, or is there one I could test to see if I can replicate the issue?

**Comment by le0nard0** [comment] 2016-01-23 05:54
My daughter watches the long hour Plus Peppa Pig cartoons. Those are the only ones I have tried. Anything that has a lot of view usually has an ad that starts it off.

**Comment by dschaper** [comment] 2016-01-23 05:55
Okay, thanks, I'll take a look.

**Comment by dschaper** [comment] 2016-01-23 06:26
It looks like the video ads are getting through on some of the channels. I'll flag this as a bug and see if there is a way that we can intercept video advertisements. We hope that the rest of the Pi-Hole is working for you.

**Comment by le0nard0** [comment] 2016-01-23 06:27
Yep, If I have questions where is the best place to ask?

**Comment by dschaper** [comment] 2016-01-23 06:27
Right here, we track the GitHub issues very closely.

**Comment by le0nard0** [comment] 2016-01-23 06:28
Just noticed that some google ad that I can see wont let me click on them. I assume that either they shouldn't show up or I can at least click and follow the link. 

Not a huge deal just wanted to let you know. 

Also I will be following this project very excited. I'll let you know what else comes up.

**Comment by dschaper** [comment] 2016-01-23 06:30
Yes, some of the Sponsored Links that come up from Google searches are displayed, but the actual link to the end website is blocked. Thanks for bringing that up, we'll note that also. Thanks for using the Pi-Hole!

**Comment by snoe** [comment] 2016-02-16 04:48
Any progress on this, or something I could do to help? Video ads are the toughest thing to block on mobile, and if pihole isn't blocking them, I'm not sure it's worth it for me to run.

**Comment by PromoFaux** [comment] 2016-02-16 12:13
>and if pihole isn't blocking them, I'm not sure it's worth it for me to run.

I mean, aside from the benefits of blocking all other ads network wide? :)

Google did some work around september last year to get around ad blockers, and as such video ads were reclassified as "pre-videos" They're not ads, they're videos, same as any other on Youtube.

Basically, in order to block the video ads, you'd have to block all youtube videos. Which really defeats the point.

**Comment by SudoHenk** [comment] 2016-03-23 19:45
@dschaper I'm running my own DNS-blocking mechanism and I can confirm that these kind of videos are in fact served from the same servers as YouTube videos (just as @PromoFaux mentioned). 

There is basicly no way to block these on a network level, right? YouTube keeps serving me these videos because they know I'm not watching the ads.

**Comment by dschaper** [comment] 2016-03-23 19:49
YouTube blocking has been a long term goal. It's difficult to block using a
DNS blocker since the domains look the same. Hard to differentiate ad vs
legit bid.

Dan Schaper via GS3
Ganymeade Systems

**Comment by nate-ubiquisoft** [comment] 2016-03-23 19:51
I will do some wireshark testing tonight to see if there is a specific endpoint that youtube uses for the ad-specific videos that could be blocked by pi-hole. This would still not be a complete fix as the "video" would still play, but just as a black screen during the skip/finished playing timeout before the requested video begins.

**Comment by SudoHenk** [comment] 2016-03-23 20:25
@nate-ubiquisoft you mean that the "promo" videos will play as a black screen?

I'm succesfully blocking the original ads, without them playing at all with a DNS block. This is what pi-hole does too right?

**Comment by jacobsalmela** [comment] 2016-03-23 20:33
I was thinking we could write a lighttpd rule for these similar to how we do it for the admin page now.  But it will be a matter of finding out the URLs being requested.

**Comment by nate-ubiquisoft** [comment] 2016-03-23 21:22
@jacobsalmela I can find those out tonight and reply back here with them. I will also start a new branch on my fork for the lighttpd rules and begin testing that. I am running my current master branch with the debugging enabled without error since I submitted the pull request if you guys want to merge that and close out the roadmap item.

**Comment by nate-ubiquisoft** [comment] 2016-03-23 22:50
Okay so looking at the [following video](https://www.youtube.com/watch?v=nIVU6W3EDcU), @SudoHenk , I see that youtube is loading internal ads from www.youtube.com/stats/api/ads* which I blacklisted on my local PiHole. Can you send the video link that you are seeing the ads on? (Don't worry, I wont judge XD). You can test yourself as well by running `blacklist.sh www.youtube.com/api/stats/ads`

**Comment by PromoFaux** [comment] 2016-03-23 23:53
@nate-ubiquisoft I was under the impression dnsmasq could only block as far as the tld... Are you seeing those requests successfully blocked?

**Comment by PromoFaux** [comment] 2016-03-23 23:59
In fact I'm quite certain on that.  You can only block host names,  not `/directory`  or `/file`. 

E.g you could block `news.somesite.com` but not 'somesite.com/news`

**Comment by nate-ubiquisoft** [comment] 2016-03-24 04:30
Yes my mistake I was under the impression dnsmasq could take subsites. Been spending too much time with Spring security recently XD. I am currently working on getting the lighttpd setting idea that @jacobsalmela mentioned earlier.

**Comment by jacobsalmela** [comment] 2016-03-25 02:14
So the lighttpd config would look something like this (I haven't tested this yet):
```
$HTTP["host"] =~ "youtube.com" {
	url.rewrite = ( "^/api/stats/ads/(.*)" => "pihole/index.html")
}
```
or 
```
$HTTP["url"] =~ "^(?!//api/stats/ads)/.*" {
	url.rewrite = ( ".*" => "pihole/index.html")
}
```

**Comment by nate-ubiquisoft** [comment] 2016-03-26 00:33
@le0nard0 Can you give me the URL of the youtube video you are still getting ads with? I am testing @jacobsalmela's change to lighttpd.conf and I am successfully forcing a 204 status on all /api/stats/ads/

**Comment by PromoFaux** [comment] 2016-03-26 17:03
Does YouTube not use https by default? I wonder if that will cause issues....

**Comment by le0nard0** [comment] 2016-03-26 17:10
Hey @nate-ubiquisoft I don't have any specific URL, my daughter watches Peppa Pig and sometimes gets ads.

**Comment by dschaper** [comment] 2016-03-26 20:00
It's a combo of things I think, they did switch to HTML5 player as default a while ago, but video ads are an ongoing research project just because of the nature of them. And I think they have the CDN for the adverts on the same CDN as the video. (So another self-hosting circle)

**Comment by sensi277** [comment] 2016-06-24 07:04
Just wondering if there's been any progress on this issue. I just installed pi-hole earlier today and it hasn't blocked any YouTube ads so far. Not in the Android app, and not on the web either. All other ads are blocked just fine (no IPv6 connection on my local network, all IPv4).

**Comment by SudoHenk** [comment] 2016-06-28 11:58
Well I don't believe this is possible. If I'm not mistaken YouTube uses HTTPS which does not allow you to directly block certain paths that your YouTube app requests (with HTTPS you cannot see the GET request). You could Man in the Middle all traffic and strip SSL off it, but the app would surely deny HTTP traffic.

I inspected the traffic a while back from my Chromecast with wireshark, but without directly MitM the traffic there is no way you can block the ad, because it comes from the same server/IP/SSL connection.

**Comment by jacobsalmela** [comment] 2016-09-15 14:25
Not really a bug.  YouTube is just a moving target.  Closing.

**Closed by jacobsalmela** 2016-09-15 14:25 UTC
