### ISSUE TITLE
Dynamic tables [$5]

### ISSUE THREAD

**Issue by ldrrp** [pi-hole/pi-hole#1249] opened 2017-02-15 22:01 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_5_

---
**[FEATURE REQUEST]:**

Load datatables dynamically to improve page performance and reduce load when trying to find stuff.

Example: https://datatables.net/examples/data_sources/ajax.html

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by ldrrp** [comment] 2017-02-15 22:03
Before anyone comments. I put this feature request on github so that i can put a bounty on it for bountysource

**Comment by ldrrp** [comment] 2017-02-17 16:08
Can probably be done after this https://pi-hole.net/2017/01/10/coming-soon-to-a-pi-hole-near-you-ftl/

**Comment by DL6ER** [comment] 2017-02-17 16:18
You might find that it is not necessary anymore once `FTL` comes to you. Since the preview movie the speed increases drastically by applying some tricks and optimizations. The Query Log page starts to show the most recent queries within a fraction of a second on a Pi B now. Note that the log contains almost 90'000 queries at that time.

**Comment by dschaper** [comment] 2017-03-21 12:14
This has probably become a Won't-Fix as the issue is resolved with the FTL engine.

**Comment by dschaper** [comment] 2017-05-13 23:07
Leaving open for the bounty if any one wants to implement and claim.

**Comment by jacobsalmela** [comment] 2017-07-07 00:48
@ldrrp just curious if FTL solves this issue for you, since the end goal was to increase performance?  If so, @DL6ER could claim the bounty.

**Comment by dschaper** [comment] 2017-07-21 20:28
Ping @ldrrp before closing the issue.

**Comment by ldrrp** [comment] 2017-07-25 15:48
Hello, sorry i wasn't on for a while. How many records has FTL been tested with, because i was hitting 1.2million or something before. Im using this in a VM for 4 houses.

**Comment by Mcat12** [comment] 2017-07-25 16:03
Many queries:
![](https://i1.wp.com/pi-hole.net/wp-content/uploads/2017/04/ftl-blast.gif)

**Comment by Mcat12** [comment] 2017-07-25 16:04
The query log currently loads the last 10min of activity, so it is still (relatively) fast with that many queries. However, if you want to look beyond 10min, that's where it probably doesn't work.

**Comment by ldrrp** [comment] 2017-07-25 16:32
Seems legit, how do i award @DL6ER, i think he has to claim it on bountysource

**Closed** 2017-07-26 12:05 UTC
Labels: Submitter Attention Required
