### ISSUE TITLE
Nest thermostat offline after installing Pi-Hole

### ISSUE THREAD

**Issue by pgattu** [pi-hole/pi-hole#1034] opened 2016-12-24 16:23 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Nest thermostat should be online and should be controlled by Nest mobile app/web UI.  I also have Nest cameras and they are working fine.

**[BUG | ISSUE] Actual Behaviour:**
Nest thermostat shows offline and not cannot be accessed from Mobile app/web UI.

**[BUG | ISSUE] Steps to reproduce:**
Install Nest thermostat.  Install Pi-Hole connected to the router.
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**
1rn87fe1wd

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment] 2016-12-24 17:45
The only domain that's blocked in the log snippet is `device-metrics-us.amazon.com`. You can also run `pihole -t` or `tail -F /var/log/pihole.log | grep /etc/pihole/gravity.list` to see the current log in real time. The second command will limit the output to only blocked queries.

**Comment by xxcriticxx** [comment] 2016-12-25 16:09
@pgattu i know am not helping i have ver 2 thermostat and it works after upgrade to Pi-hole Version v2.10.1 Web Interface Version v2.2

did you try to connect with pihole off?

i would check your router/modem make sure you have connection and make sure wifi pass did not change. try restarting your phone or tablet couple times.

**Comment by smallpygmy** [comment] 2016-12-26 20:52
I had this same issue after the latest upgrade and I managed to trace it to the DHCP server no longer being configured.

I had to go in to the settings and turn off dhcp, save then turn it back on again.  It looks like the dhcp settings in /etc/dnsmasq.d/01-pihole.conf weren't re-added after the update.

**Comment by DL6ER** [comment] 2016-12-26 21:39
That might be an issue in the updater. I'll look into this. Also, in the next release (when we add IPv6 support for our DHCP server) the DHCP settings are going to be saved in a different place.

**Comment by pgattu** [comment] 2016-12-26 21:49
**Update to the initial issue**:  Nest thermostat is connecting to the internet some times, and it is not connecting some times.  I have not been able to identify a pattern of when it is vs. is not working.  I just removed Pi-Hole as my DNS server in the router settings -- Nest thermostat is connecting to the internet consistently.

**Comment by pgattu** [comment] 2016-12-26 21:55
@smallpygmy Can you please clarify the steps you performed?

1) In Pi-Hole admin console, in the Settings page, "DHCP server enabled" is unchecked.  Is this an issue?

2) The contents of my 01-pihole.conf file (DHCP settings) are below:

addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/local.list

domain-needed

bogus-priv

no-resolv

server=8.8.8.8
server=8.8.4.4

interface=eth0

cache-size=10000

log-queries
log-facility=/var/log/pihole.log

local-ttl=300

log-async

**Comment by dschaper** [comment] 2016-12-26 21:56
Do you have both a primary and a secondary DNS entry in you router configuration (DHCP server?)

**Comment by smallpygmy** [comment] 2016-12-26 21:57
@pgattu Where you using the DHCP server before the last update?

**Comment by pgattu** [comment] 2016-12-26 23:13
@dschaper I have primary DNS entry only in the router configuration.

**Comment by pgattu** [comment] 2016-12-26 23:14
@smallpygmy I was not using the DHCP server before the last update.

**Comment by pgattu** [comment] 2016-12-26 23:15
My DHCP settings in Pi-Hole admin console in the Settings page: (see image)

![image](https://cloud.githubusercontent.com/assets/8840613/21487453/323a84f0-cb97-11e6-88bc-8d36a686460e.png)

**Comment by smallpygmy** [comment] 2016-12-27 00:21
@pgattu the issue for me was the DHCP settings but if you're not using DHCP then it must be a different issue

**Comment by DL6ER** [comment] 2016-12-27 00:50
@pgattu What you show in the image means just that you don't use Pi-holes own DHCP server. The fields are pre-populated for you to assist you in case you want to enable Pi-hole's DHCP server. As long as the check box is unchecked you don't use our DHCP server.

Just an idea: I have seen a similar issue like you see in the past with an Apple laptop (Internet sometimes worked, sometimes not - failed with Safari browser and worked with Chrome and the other day vice-versa). The solution was to disable IPv6 on the client. However, in this case the Apple laptop wasn't already working reliably before installing Pi-hole so it was quite clear that Pi-hole wasn't the problem.

**Comment by pgattu** [comment] 2016-12-27 00:53
@DL6ER  I don't think Nest thermostat provides the capability to disable IPv6.  Do you have any information?

**Comment by DL6ER** [comment] 2016-12-27 00:56
@pgattu Please open another issue for your problem since it seems unrelated by the issue of the original poster (which was fixed by re-enabling Pi-hole's DHCP server)! We will have to investigate in your Query Log if you see IPv6 entries for the thermostat. I don't know anything about this device and would have to do the same web searching you surely already have done.

@smallpygmy I see that in the updater I changed the code to preserve the user settings in the Pi-hole config (hence it was still displayed as enabled on the Settings page). However, I seems like that I forgot to modify the part of the code that deals with the `01-pihole.conf` file. I will mark this issue as `Confirmed bug` and will work on a fix over the next couple of days.

**Comment by DL6ER** [comment] 2016-12-27 00:58
General note: If other users find a similar issue: It is not necessary to disable and then re-enable the DHCP server. You can also simply click on `Save` without changing anything. It will properly update the `dnsmasq` settings

**Comment by jacobsalmela** [comment] 2017-01-29 02:49
@pgattu can you see if this is fixed in 2.12/2.4?  According to @DL6ER, #1048 should fix this.

**Comment by pgattu** [comment] 2017-02-16 04:35
I just reinstalled pi-hole with the latest version today.  I haven't
noticed any Nest thermostat or camera issues in the past hour since I
installed it.  That's better than before, when I couldn't even go 1 hour
without Nest issues.  If something changes tomorrow, I will let you know.
Version I am running is:

Pi-hole Version v2.12.1 Web Interface Version v2.4


-- Praveen

**Comment by ldrrp** [comment] 2017-02-17 16:03
I just bought a nest today, will be testing this as well with the latest.

**Comment by pgattu** [comment] 2017-02-17 18:09
Two days after Pi-hole install... Nest is working without any issues.


-- Praveen

**Comment by jacobsalmela** [comment] 2017-02-18 02:38
Closing since it seems to be working now.

**Closed by jacobsalmela** 2017-02-18 02:38 UTC
Labels: Confirmed Bug
