### ISSUE TITLE
Query Log not populating after update

### ISSUE THREAD

**Issue by jmjm003** [pi-hole/pi-hole#1016] opened 2016-12-23 01:07 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [x] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Click on query log and expect to see visited and pi hold domains

**[BUG | ISSUE] Actual Behaviour:**
Click on query log and it doesn't begin to load as before the update
**[BUG | ISSUE] Steps to reproduce:**
Click on query log.
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

Just updated to Pi-hole Version v2.10 Web Interface Version v2.0 within the last 45 minutes or so and have found that the query log no longer populates.

**Comment by Mcat12** [comment] 2016-12-23 03:36
I've added the issue template back to your issue, please fill it out like it says: "Failure to fill the template will close your issue"

**Comment by jmjm003** [comment] 2016-12-23 05:58
Problem exist in Google chrome, works fine on Firefox.

**Comment by Hink01** [comment] 2016-12-23 10:41
Same here with Chrome, Firefox and IE. The whitelist and blacklist menu items are also missing after the update to 2.10.

**Comment by oMadMartigaNo** [comment] 2016-12-23 11:32
Same here with Chrome v56.0.2924.28 beta (64-bit)

**Comment by netcarver** [comment] 2016-12-23 12:45
Just updated and seeing this as well.

**Comment by Nevexo** [comment] 2016-12-23 13:27
Same here in Firefox stable.

**Comment by Mcat12** [comment] 2016-12-23 15:54
Make sure to clear your browser cache/browse in incognito mode to make sure it's not a cache issue, as those have been the cause of a lot of issues on update.

**Comment by jmjm003** [comment] 2016-12-23 15:57
Did a quick check using Chrome in incognito and it loaded.

**Comment by Mcat12** [comment] 2016-12-23 15:58
Also check how many queries you have, because over a certain amount your Pi-hole might not be powerful enough to generate the stats within the timeout period (usually 30 seconds). This is a result of having to parse the whole log file, and will be fixed when we convert to using a database for log entries.

**Comment by PTRFRLL** [comment] 2016-12-23 17:22
I had this problem after the update on Chrome, did a force refresh (`Shift + F5` or Hold Shift while clicking refresh) and it went away. Definitely a cache issue.

**Comment by Mcat12** [comment] 2016-12-23 17:23
Ok, so this seems to be a cache issue, which can be easily solved various ways depending on your browser. Good to know for future releases.

**Closed by Mcat12** 2016-12-23 17:23 UTC
