### ISSUE TITLE
Pi-hole not working

### ISSUE THREAD

**Issue by alexlab963** [pi-hole/pi-hole#2091] opened 2018-04-06 21:35 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I expect to not see any ads

**Actual behaviour:**

I see ads

**Steps to reproduce:**

Opening the test webpage provided in the pihole website

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

i6ugychwv6

**Troubleshooting undertaken, and/or other relevant information:**

Uninstalled pi-hole and dnsmasq mutliple times

**Comment by PromoFaux** [comment] 2018-04-06 21:38
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by dschaper** [comment] 2018-04-06 21:47
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by alexlab963** [comment] 2018-04-06 21:55
Now using template

**Comment by Mcat12** [comment] 2018-04-07 00:35
See https://discourse.pi-hole.net/t/why-cant-i-run-pi-hole-v3-3-on-raspbian-jessie-or-with-dnsmasq-v2-72/8052

**Closed by Mcat12** 2018-04-07 00:35 UTC
Labels: triage: Issue

**Comment by alexlab963** [comment] 2018-04-07 04:40
After finally getting it to work, I cannot see the stats in the admin website

**Comment by alexlab963** [comment] 2018-04-07 16:44
That's a step in the right direction, but I am not using raspbian, I am using dietpi therefore cannot install armhf packages, so could you please refrain from closing my thread without any evidence that my issue is solved?

**Comment by dschaper** [comment] 2018-04-07 17:43
The issue is that `dnsmasq` v2.72 will not work. You have to back down to a previous release if you can not upgrade the package. Does DietPi not have a Stretch release that you can upgrade to?

**Comment by dschaper** [comment] 2018-04-07 17:45
> There are two options if you can’t or don’t want to update past Jessie:

>   1. Stay on Raspbian Jessie and run Pi-hole v3.2.1
>   2. Upgrade dnsmasq manually to v2.76 (v2.73+)

If you can not do step 2, you need to follow the directions for step 1.

**Comment by alexlab963** [comment] 2018-04-07 17:48
I did find a compatible version of dnsmasq 2.76 for debian arm64 [here](https://packages.debian.org/stretch/dnsmasq). However, I cannot install it due to the excessive amound of dependencies. What would be the drawbacks of downgrading?

**Comment by dschaper** [comment] 2018-04-07 18:12
You wouldn't be able to use the extended logging. On the other hand, you would have a working Pi-hole again :)

**Comment by alexlab963** [comment] 2018-04-08 00:35
Thanks for the help! After working with the dependencies for some time, I finally managed to install version 2.76.

**Comment by alexlab963** [comment] 2018-04-08 05:00
UPDATE: Noticed that there are no query logs even though ad blocking seems to work

**Comment by alexlab963** [comment] 2018-04-08 16:44
UPDATE: Noticed that there are no query logs even though ad blocking seems to work

**Comment by Mcat12** [comment] 2018-04-08 22:09
Make a new issue with more information (and a debug token)
