### ISSUE TITLE
DNS service suppossedly not running (in WebGUI)

### ISSUE THREAD

**Issue by dawid-woitaschek** [pi-hole/pi-hole#4516] opened 2022-01-05 07:10 UTC
### Versions

- Pi-hole version is v5.7 (Latest: v5.7)
- AdminLTE version is v5.9 (Latest: v5.9)
- FTL version is v5.12.1 (Latest: v5.12.1) 

### Platform

- OS and version:  RasPi OS (5.10.63)

- Platform:  Docker 20.10.12

### Expected behavior

The WebGUI should show you, that the DNS service is indeed running.

### Actual behavior / bug
Well, it's not... :)
I observed this after my internet connection broke and I checked the DNS server at first... But further nslookup'ing showed me, that the service is clearly running and answering my requests just fine.

See the screenshot at the bottom.

Please note both buttons "Disable" (with it's sub options) and "Enable"...

### Steps to reproduce

Really don't know... Without looking into the current releases, I assume that this could be an error after an update to the current image. I'm doing updates via Watchtower on Docker.

## Debug Token

[✓] Your debug token is: https://tricorder.pi-hole.net/4OzXM803

### Screenshots

![image](https://user-images.githubusercontent.com/34062137/148173924-c7ce78dd-0670-41e8-9ae5-9ec3ddff01a7.png)
![image](https://user-images.githubusercontent.com/34062137/148175058-7d824c24-3bc8-4b55-955d-f7bd74797760.png)

**Comment by yubiuser** [comment] 2022-01-05 07:47
Duplicate of https://github.com/pi-hole/docker-pi-hole/issues/734

**Closed by yubiuser** 2022-01-05 07:47 UTC
