### ISSUE TITLE
Repeated settings in dnsmasq should overwrite previous settings instead of throwing an error.

### ISSUE THREAD

**Issue by h88e22dgpeps56sg** [pi-hole/pi-hole#3194] opened 2020-03-04 13:27 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

pihole-FTL should overwrite the previous setting with the more recent one, maybe show a warning, and continue to work.

**Actual behaviour:**

pihole-FTL throws an error and will not start.

**Steps to reproduce:**

Create a file `/etc/dnsmasq.d/10-custom.conf` with the line `cache-size=0` and restart pihole-FTL.

**Reasoning:**

There are cases where you want to change some of the standard settings from `/etc/dnsmasq.d/01-pihole.conf`. E. g. if you have a DNS resolver running, which does its own caching, you might want to disable Pi-hole's caching (`cache-size=0`). The aforementioned file is overwritten every update and if you try to set it in another file (like `/etc/dnsmasq.d/10-custom.conf`) an error will be thrown: `pihole-FTL[14728]: dnsmasq: illegal repeated keyword at line 1 of /etc/dnsmasq.d/10-custom.conf` (see issues [here](https://github.com/pi-hole/pi-hole/issues/1521) and [here](https://github.com/pi-hole/pi-hole/issues/1208)). This means that there is no way to change settings from `/etc/dnsmasq.d/01-pihole.conf` consistently. And I don't really see a reason why.

**Comment by PromoFaux** [comment] 2020-03-04 13:34
You can change the value in `01-pi-hole.conf`, however as stated at the top of the file, any changes will be overwritten (either on next update or if doing a repair with `pihole -r`)

There is a PR open for custom cache size:

https://github.com/pi-hole/pi-hole/pull/3170

**Comment by dschaper** [comment] 2020-03-04 16:22
This isn't really specific to `ftl`, this is something that is in the upstream `dnsmasq`. To me this isn't a bug, I don't know of very many applications that would allow multiple directives of the same configuration flag to be issued. Which one wins? The first one read or the last one read? 

I'm for calling this a feature request.

**Comment by h88e22dgpeps56sg** [comment] 2020-03-04 20:28
Yes, it's a feature request. The last option to be read "wins".

It would be fine for me if it was part of the setupVars like in the [issue](https://github.com/pi-hole/pi-hole/pull/3170) @PromoFaux mentioned. But maybe there are circumstances where you want to change other settings as well. That's why I would prefer the "overwrite" approach.

From the top of my head I know of two applications which would allow this: unbound and Firefox's user.js.

**Comment by PromoFaux** [comment] 2020-03-04 20:32
I think if we were going to have overrides for all the default values, they should be in `setupVars.conf`, I'm not a fan of the idea of allowing a setting to be overridden simply by setting it again further down the file.

**Comment by dschaper** [comment] 2020-03-04 20:40
If there is one main conf file and one file that can override then it's relatively sane. When you get to confdir's then things go hairy. Lexicographical enumeration. (setupVars.conf >> 01-pihole.conf >> 02-override.conf >> 40-this-is-it.conf >> 99-GOD.conf)

**Comment by jlagermann** [comment] 2020-03-06 01:52
> I think if we were going to have overrides for all the default values, they should be in `setupVars.conf`, I'm not a fan of the idea of allowing a setting to be overridden simply by setting it again further down the file.

I'm submitting my PR tonight that will address this.  It's mostly about validating setupVars.conf but it also enables the ability to use setupVars.conf to modify any variable, even if the variable name changes between files, like CACHE_SIZE and cache-size.

**Comment by rdslw** [comment] 2020-07-17 17:34
In addition to 'cache-size', I'm also modyfing 'local-ttl' and current approach wreaks havoc on every update. 
I must manually inspect /etc/dnsmasq.d/01-pihole.conf and fix it.

@jlagermann does #3170 address this, or maybe help is needed (I can help) ?

**Comment by dschaper** [comment] 2020-07-17 17:51
If you want that behavior then you'll need to get `dnsmasq` to change it.

**Comment by rdslw** [comment] 2020-07-18 08:11
yeah, I understand that root cause is dnsmasq.
As pihole currently creates /etc/dnsmasq.d/01-pihole.conf would you consider a solution where this auto step would check if there are any duplicates and removes them on 01-pihole.conf creation?

**Comment by jlagermann** [comment] 2020-07-18 16:11
That's what I'm doing in my own version.  I'm using this autoinstall in a
production environment and it works perfectly.

I've made a few additions that are not in this PR that have it sending the
logs to an external syslog-ng server.  That server has Splunk Universal
Forwarder sending the logs to the appropriate index in Splunk.

When I get some free time I can readdress this PR.  However, I doubt it
will ever be accepted because I'm fixing too many things (all related to
each other).


Thank you,

*James Lagermann* | Cybersecurity Systems Engineer
c: 636-575-7249
james.lagermann@corelight.com

[image: Corelight]
<https://app.salesforceiq.com/r?target=5e7232c4c9e77c0076f38131&t=AFwhZf1GBKQ82RfBl_ysPyfYtIb4-WUzgM9l0iNVWBIqb_rgJA6A_i_PiheVB7MySqXaf4jk7R3BN_1qqCJwESAmpTGqB3USK-m7p13jpRaw7yrTkQE7BefEBLoHXx0GG29WYKwQp0eW&url=https%3A%2F%2Fwww.corelight.com%2F>

**Comment by SaswatPadhi** [comment] 2020-11-24 21:14
I am facing this issue with `local-ttl`.
1. `01-pi-hole.conf` gets overwritten
2. `02-custom.conf` throws `illegal repeated keyword error`

:man_facepalming:

**Comment by dschaper** [comment] 2020-11-24 21:19
What situation are you needing to change the local-ttl for? Modifying that value will change how effective white/blacklisting is.

**Comment by SaswatPadhi** [comment] 2020-11-24 21:22
Hi @dschaper,

True, I understand. I am trying to increase the `local-ttl` to resolve an issue with my Ubiquity devices. They are currently querying for the controller's IP thousands of times per minute, and the root cause (as per discussions in Ubiquity forums) seems to be the super short (2s) `local-ttl`.

**Comment by DL6ER** [comment] 2020-11-24 22:08
Note that the documentation says
> When replying with information from `/etc/hosts` or configuration or the DHCP leases file `dnsmasq` **by default sets the time-to-live field to zero**, meaning that the requester should not itself cache the information. This is the correct thing to do in almost all situations. This option allows a time-to-live (in seconds) to be given for these replies. This will reduce the load on the server at the expense of clients using stale data under some circumstances. 

I'd say try changing it in `01-pi-hole.conf` to ensure this is the proper solution, first.

**Comment by SaswatPadhi** [comment] 2020-11-24 22:34
Thanks, @DL6ER.

I tried changing it in `01-pi-hole.conf` and ran `pihole restartdns` -- the number of queries for the network controller's IP seem to have reduced a lot -- basically they seem to query right after TTL expires.

This is acceptable for now, but my changes will be gone when I update / restart my docker container.

**Comment by yubiuser** [comment] 2021-08-12 19:30
I'm going to close this issue:

The OP requested that newer/later config options in different files in `/etc/dnsmasq.d/` override previous settings. This is clearly a feature request that must be addressed upstream at `dnsmasq`'s code.

`CACHE_SIZE` can be set in `setupVars.conf` by now (https://github.com/pi-hole/pi-hole/pull/3170)

For changes regarding the `TTL` please open a new ticket or in case of a feature request use discourse https://discourse.pi-hole.net/c/feature-requests/8

**Closed by yubiuser** 2021-08-12 19:30 UTC

**Comment by rdslw** [comment] 2021-08-13 15:15
I personally don't see this as upstream code's problem (dnsmasq's).

It is pihole which  creates /etc/dnsmasq.d/01-pihole.conf with conflicting content. In other words: it's pihole which creates erroneous/wrong configuration. Pihole should create proper 01-pihole.conf (simply checking for those 3 or 4 values if they are, or not already set).

IMO this is bug in current pihole installation/upgrade logic responsible for creating wrong 01-pihole.conf

**Comment by dschaper** [comment] 2021-08-13 15:29
That's one point of view. This issue was to request that repeated lines of the same config should override and that is something that the upstream code does not allow. 

Pi-hole sets the config file for what Pi-hole needs. If you set additional config files with commands that Pi-hole is unaware of then you need to make sure the additional config files do not contain conflicting config entries.

**Comment by rdslw** [comment] 2021-08-13 15:38
Agree, that it's borderline. 

That problem may be however reduced to 01-pihole.conf being simply overwritten by pihole (even if exists with user changes). That shall not happen IMO, and this was OP report ("...overwrite...").

**Comment by dschaper** [comment] 2021-08-13 16:19
I appreciate the view but I did not intend to say that it's borderline. There's a reason for the values that we set and are not changeable and `01-pihole.conf` shows pretty clearly that the file should not be modified with a large header that explains this fact.

But we're not going to agree I feel so the closure of this issue was correct. If you'd like to open a feature request then we can place it to community vote for ranking.

**Comment by DL6ER** [comment] 2021-08-13 16:27
Since when this issue was first opened, the way in which `dnsmasq` reads in config files changed from unpredictable to lexicographic. So it *may* be reconsidered upstream that - now that the reading order is deterministic - multiply defined values may overwrite prior ones. I still disagree with this idea because it leave some ambiguity about what the actual config will be if you don't real *all* files in a config directory. Currently, when you see `cache-size=xyz` you know this is a fact.

What you are asking for (do not overwrite `01-pihole.conf`) has the consequence that we cannot change something if we have to. New config could be added by counting up (like `06-additional-stuff.conf` followed by `07-even-more-stuff.conf`), however, removing incorrect/outdated/replacement-worthy stuff could only be done by manipulating the existing file (with arbitrary user changes!) instead of simply replacing it with a file known to work. This would be tricky. You can never ensure you're not breaking something someone has changed somehow.

Hence, I agree with @dschaper that the header is there for a reason. If it turns out some of the setting in this file should survive non-standard after an upgrade (which, similarly to `pihole -r`, should always bring you into a guaranteed-to-work state) we made this configurable. Like you can configure the cache size in `setupVars.conf` and the Pi-hole updater/repair option will acknowledge and use this changed value. I think this is the best (and already available) solution to this issue.

**Comment by h88e22dgpeps56sg** [comment] 2021-08-13 19:18
I agree with  @dschaper and @yubiuser. I'm fine with closing this issue.
