### ISSUE TITLE
lighthttpd.conf port config is overwritten on every update

### ISSUE THREAD

**Issue by hoergen** [pi-hole/pi-hole#4022] opened 2021-01-28 08:23 UTC
### Versions
  Pi-hole version is v5.2.2 (Latest: v5.2.4)
  AdminLTE version is v5.2.2 (Latest: v5.3.2)
  FTL version is v5.3.4 (Latest: v5.6)

### Platform
OS: Debian 9.13 stretch
Kernel: armv7l Linux 3.14.60-fslc-imx6-sr
Platform:  Cubox

### Expected behavior

I am runnning an Apache Webserver port 80 and Pihole (lighthttpd) port 8080 on the same machine.
When I update pihole should keep the port 8080.

### Actual behavior / bug

On every update the lighthttpd port configuration is resetted to port 80 so that it conflicts with my apache webserver. Then I have to manually change back the /etc/lighthttpd/lighthttpd.conf port configuration.

### Steps to reproduce

Starting an update.

**Comment by yubiuser** [comment] 2021-01-28 13:22
Thanks for the report. This is a duplicate of
https://github.com/pi-hole/pi-hole/issues/2550

I guess, the developers opinion `not a bug` has not changed.

Side note: The developers working on the direct integration of a web server into Pi-hole FTL. This would make Pi-hole independent of any existing web server.

**Closed** 2021-01-28 17:09 UTC
Labels: Duplicate

**Comment by hoergen** [comment] 2021-01-29 08:29
Thanks for the information. Sad to hear in short term. Good to hear in long term. Is there a raodmap fo the "when" ?

**Comment by yubiuser** [comment] 2021-01-29 08:34
There is no roadmap, it's done when it's done. Hopefully in 2021.
https://wowwiki.fandom.com/wiki/Soon

**Comment by hoergen** [comment] 2021-01-29 10:07
hahaha nice link, thanks for the info  :+1:

**Comment by VLoub** [comment] 2022-03-07 19:01
For anyone interested in this, I'm using it on Synology and this is my solution 
Mounting external.conf to lighttpd 
```    
ports:
    - 53:53/tcp
    - 53:53/udp
    - 7780:7780/tcp
volumes:
    - ./etc-pihole:/etc/pihole
    - ./etc-dnsmasq.d:/etc/dnsmasq.d
    - ./hosts:/etc/hosts
    - ./external.conf:/etc/lighttpd/external.conf
```
And external.conf file with 
```
$HTTP["host"] == "pihole.example.com" {
  setenv.add-environment = ("fqdn" => "true")
  $SERVER["socket"] == ":7780" {
  }
}
```

**Comment by dschaper** [comment] 2022-03-07 19:18
Why not just set the port configuration to:

```plain
- 7780:80
```
