### ISSUE TITLE
Unable to install / upgrade pi-hole on 64bit machine with a 32bit OS

### ISSUE THREAD

**Issue by Gartonious** [pi-hole/pi-hole#1998] opened 2018-02-22 07:21 UTC
Edited:
**In raising this issue, I confirm the following:**
    [x] I have read and understood the contributors guide.
    [x] The issue I am reporting can be replicated.
    [x] The issue I am reporting isn't a duplicate (see FAQs, closed issues, and open issues).

**How familiar are you with the source code relevant to this issue?:** 1

**Expected behaviour:** Able to install/upgrade pi-hole without errors.

**Actual behaviour:** Setup terminates without fully going through the full setup. The installation then is corrupted.
![1](https://user-images.githubusercontent.com/36725136/36605532-e857f4b0-18b8-11e8-975c-73fdae77836b.PNG)
![2](https://user-images.githubusercontent.com/36725136/36605539-eb6dde9e-18b8-11e8-9a9c-f97e4c73c333.PNG)

**Steps to reproduce:**
1) Download raspberry Pi Desktop from https://www.raspberrypi.org/downloads/raspberry-pi-desktop/ and install onto PC/virtual machine
2) Run "sudo apt-get update"
3) Run "sudo apt-get upgrade"
4) Run "sudo reboot"
5) Once back online, run pi-hole installer "curl -sSL https://install.pi-hole.net | bash"

**Debug token provided by uploading pihole -d log:** bsglqnpute

**Troubleshooting undertaken, and/or other relevant information:**
I have tried reinstalling raspberry Pi Desktop a few times - same issue
I have tried both the "One-Step Automated Install" and the "Method 1: Clone our repository and run" methods but both fail

_----Previous----
Hello Pi-Hole Team,
I would like to report an issue with the installer running on raspbian OS. The setup gets as far as "Starting dnsmasq service..." then the setup terminates without further errors or warning. Pi-Hole will not load and has corrupted the install. I have restored the OS back and tried again both using the auto install (curl -sSL https://install.pi-hole.net  | bash) and the "Method 1: Clone our repository and run" way but both are doing the same thing. I have run apt-get update / upgrade before the install and also tried sudo -i before running the bash install but no effect. Can you please help/update the installer? I have attached a print screen.
![pihole](https://user-images.githubusercontent.com/36725136/36525215-df7430ac-17a0-11e8-9e61-ce8ce2d15d26.PNG)
Kind Regards._

**Comment by technicalpyro** [comment] 2018-02-22 14:02
what version of raspbian are you running ? 

there is a known issue with 8 (hessie) 

the fix can be found here : https://discourse.pi-hole.net/t/pi-hole-v3-3-released-its-extra-special/7159

**Comment by Gartonious** [comment] 2018-02-22 17:10
Thank-you for your reply. I did try the fix mentioned but this also did not work. I'm using the latest version with all the latest updates (9 Stretch). 

The install of dnsmasq failed to install.

![capture](https://user-images.githubusercontent.com/36725136/36553031-37fa41c4-17f3-11e8-9ddc-11fbb9398656.PNG)

Kind Regards.

**Comment by Mcat12** [comment] 2018-02-22 18:53
Those instructions are for raspberry pi devices (Raspbian armhf), not x86 Debian machines. You should already have an up to date dnsmasq since you're on Stretch. What is the output of `sudo service dnsmasq status`? Run `pihole -d` for a debug token.

**Comment by Gartonious** [comment] 2018-02-23 01:00
Thank-you for your reply.

So I have done a clean install of the OS and run apt-get update/update and rebooted.

The auto installer seems to be getting further now with the installer but still stops at a new place. I have attached some printscreens of this.
![1](https://user-images.githubusercontent.com/36725136/36572440-b796aefa-1833-11e8-9afc-bd58c6496d13.PNG)
![2](https://user-images.githubusercontent.com/36725136/36572449-c063bc4e-1833-11e8-9e62-f32a2bf26887.PNG)

I have run "sudo service dnsmasq status" and "pihole -d" after the install and again after a reboot.
Before Reboot:
![3](https://user-images.githubusercontent.com/36725136/36572477-ecc077a0-1833-11e8-9e2e-ff11a57a28ec.PNG)
Debug token is: bsglqnpute

After Reboot:
![4](https://user-images.githubusercontent.com/36725136/36572506-1b2eefb8-1834-11e8-98de-14e65e80571a.PNG)
![5](https://user-images.githubusercontent.com/36725136/36572516-2a2bc252-1834-11e8-8723-6358bca0a893.PNG)
The log after the reboot was unable to upload to server and to get a key so have attached the local copy instead.
[pihole_debug-sanitized.log](https://github.com/pi-hole/pi-hole/files/1750105/pihole_debug-sanitized.log)
![6](https://user-images.githubusercontent.com/36725136/36572634-d592c6ea-1834-11e8-8af9-86f7d968b2f6.PNG)

Kind Regards.

**Comment by Gartonious** [comment] 2018-02-23 01:27
The image I have used is from: https://www.raspberrypi.org/downloads/raspberry-pi-desktop/

I did have this previously working not so log ago and has been fine but I never backed the server up before running the upgrades but now even with a clean install I cannot get pi-hole to install :/

**Comment by dschaper** [comment] 2018-02-23 01:29
That image has a modified `dnsmasq` configuration that is not compatible with Pi-hole. They have it set up to be a DHCP server for other Raspberry Pi devices. Some users have found that removing the `/etc/dnsmasq.d/piserver` file will work, but that hasn't been tested by any of the developers.

**Comment by Gartonious** [comment] 2018-02-23 01:32
This is interesting. Like I say I have had this working just fine without any errors or problems but on a older version - Not sure which one it would have been now but it would have been within the last month I had upgraded everything last without issues.

**Comment by dschaper** [comment] 2018-02-23 01:36
https://www.raspberrypi.org/blog/piserver/ Looks like it was added in January of 2018.

**Comment by Gartonious** [comment] 2018-02-23 01:51
I have removed piserver from add/remove software and reboot
run apt-get update/upgrade again - said to run sudo apt autoremove as some files was no longer needed. I did this and rebooted again. Run the auto pi-hole installer but was faced with the same "/opt/pihole/updatecheck.sh: line 56: /usr/bin/pihole-FTL: No such file or directory" error as before.

**Comment by dschaper** [comment] 2018-02-23 01:53
`pihole -r` > repair should attempt to download the latest FTL binary. If this doesn't work, we'll need to run the check in a more verbose mode to see exactly why it's not getting the proper files for you.

**Comment by Gartonious** [comment] 2018-02-23 01:55
Just run "pihole -r" then repair but got the same error

**Comment by dschaper** [comment] 2018-02-23 01:56
Okay, this will produce a lot of output but it should narrow down where the problem is. Try:

    curl -sSL https://install.pi-hole.net | sudo bash -xv

**Comment by Gartonious** [comment] 2018-02-23 01:59
![7](https://user-images.githubusercontent.com/36725136/36574333-27ff973e-183d-11e8-8b8e-4a427a51c1f8.PNG)

**Comment by dschaper** [comment] 2018-02-23 02:16
Can you pastebin the entire output, the portion you've provided is missing the section that should be pulling the FTL binary.

**Comment by Gartonious** [comment] 2018-02-23 02:37
[output.txt](https://github.com/pi-hole/pi-hole/files/1750287/output.txt)

**Comment by Gartonious** [comment] 2018-02-23 02:50
I am having problems trying to get all the data for you. Terminal/putty only shows so much of the data and unable to scroll right back up to the top. I have tried to run "curl -sSL https://install.pi-hole.net | sudo bash -xv > output.txt" but it only records so much in the txt file. Think it stops when the full screen windows comes up asking for config settings. 
[output.txt](https://github.com/pi-hole/pi-hole/files/1750307/output.txt)

**Comment by dschaper** [comment] 2018-02-23 02:59
One of the other devs may be able to help, but I think there's a way to increase the scrollback buffer in Putty, and then you can select all the text in the putty window and copy/paste that to a place like hastebin. I'd suggest just piping it to the tricorder but that has a limit on the length. I'll try to see if I can come up with a way to get the parts of the dump that would be helpful.

**Comment by dschaper** [comment] 2018-02-23 03:01
`curl -sSL https://install.pi-hole.net | sudo bash -vx | nc tricorder.pi-hole.net 9999` may work and get us most of what we are looking for.

**Comment by Gartonious** [comment] 2018-02-23 03:35
The command seems to terminate after the dialog box come up apart of the pi-hole setup

**Comment by Gartonious** [comment] 2018-02-23 03:38
I have been able to get Putty to record the session to a file!
[putty output.log](https://github.com/pi-hole/pi-hole/files/1750401/putty.output.log)

**Comment by dschaper** [comment] 2018-02-23 03:49
Great! Thanks! I'm seeing that the proper FTL binary is indeed transferred, and it passes the hash check, so there is no problem there. 

```
+ local FTLversion=
++ curl -sI https://github.com/pi-hole/FTL/releases/latest
++ grep Location
++ awk -F / '{print $NF}'
++ tr -d '\r\n'
+ local FTLlatesttag=v3.0
+ [[ '' != \v\3\.\0 ]]
+ FTLinstall pihole-FTL-linux-x86_64
+ local binary=pihole-FTL-linux-x86_64
+ local latesttag
+ local orig_dir
+ local 'str=Downloading and Installing FTL'
+ echo -ne '  [i] Downloading and Installing FTL...'
+ orig_dir=/etc/.pihole
  [i] Downloading and Installing FTL...++ curl -sI https://github.com/pi-hole/FTL/releases/latest
++ grep Location
++ awk -F / '{print $NF}'
+ latesttag=$'v3.0\r'
+ [[ ! v3.0
 == v* ]]
+ curl -sSL --fail https://github.com/pi-hole/FTL/releases/download/v3.0/pihole-FTL-linux-x86_64 -o /tmp/pihole-FTL-linux-x86_64
+ curl -sSL --fail https://github.com/pi-hole/FTL/releases/download/v3.0/pihole-FTL-linux-x86_64.sha1 -o /tmp/pihole-FTL-linux-x86_64.sha1
+ cd /tmp
+ sha1sum --status --quiet -c pihole-FTL-linux-x86_64.sha1
+ echo -n 'transferred... '
+ stop_service pihole-FTL
transferred... + install -T -m 0755 /tmp/pihole-FTL-linux-x86_64 /usr/bin/pihole-FTL
+ rm /tmp/pihole-FTL-linux-x86_64 /tmp/pihole-FTL-linux-x86_64.sha1
+ cd /etc/.pihole
+ install -T -m 0755 /etc/.pihole/advanced/pihole-FTL.service /etc/init.d/pihole-FTL
+ echo -e '\r[K  [[32m✓[0m] Downloading and Installing FTL'
+ return 0
```

Can you do a `ls -lach /usr/bin` and we'll see if there are permissions problems there? And as an aside, that function could use some changes, `pushd` and `popd` directories instead of `cd`, but that's an internal thing we need to look at.

**Comment by Gartonious** [comment] 2018-02-23 03:51
[putty.log](https://github.com/pi-hole/pi-hole/files/1750425/putty.log)

**Comment by dschaper** [comment] 2018-02-23 03:53
According to that, you have `/usr/bin/pihole-FTL`, can you run `sudo /usr/bin/pihole-FTL`?

**Comment by Gartonious** [comment] 2018-02-23 03:59
When running the command I get "sudo: unable to execute /usr/bin/pihole-FTL: No such file or directory". I have used WinSCP to connect to the files and the file does exist in there. 
[pihole-FTL.txt](https://github.com/pi-hole/pi-hole/files/1750442/pihole-FTL.txt) (added .txt)

**Comment by dschaper** [comment] 2018-02-23 04:00
Okay, how about `ls -lachZ /usr/bin/pihole-FTL` and we'll see if it's executable.

**Comment by Gartonious** [comment] 2018-02-23 04:02
That command comes back with:
-rwxr-xr-x 1 root root ? 1.5M Feb 23 03:37 /usr/bin/pihole-FTL

**Comment by jerm** [comment] 2018-02-23 06:34
Sooo... can you put in a check to _not_ let people on jessie upgrade if dnsmasq isn't updated?  The current situation breaks the pihole server, and then you have to go rejigger DNS just to come search for a solution. Not a great experience when there's a known breaking issue with upgrading.

**Comment by dschaper** [comment] 2018-02-23 07:40
@jerm Can you open a new issue, this one is tracking a different problem.

**Comment by Mcat12** [comment] 2018-02-23 15:29
It sounds like you have an architecture mismatch. What is the output of these commands?
```
file /usr/bin/pihole-FTL
uname -a
dpkg --print-architecture
```

**Comment by PromoFaux** [comment] 2018-02-23 15:41
**Offtopic housekeeping note:**

@Gartonious We can let it slide this time, but in future when you open a new issue, please ensure you follow the [issue template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md). It helps us to help you. Please can you edit your OP to include the requested information? Cheers

**Comment by Gartonious** [comment] 2018-02-23 16:20
```
pi@raspberry:~ $ file /usr/bin/pihole-FTL
/usr/bin/pihole-FTL: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=500fb341f98c98a77dc00e53be9cd8b1c5e22ec6, not stripped
pi@raspberry:~ $ uname -a
Linux raspberry 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
pi@raspberry:~ $ dpkg --print-architecture
i386
```

**Comment by Gartonious** [comment] 2018-02-23 16:43
@PromoFaux Sorry about this - I had asked for assistance via Twitter at first and they replied advising to submit a issue via https://t.co/wo5RIimsmq . Due to this I did not see the template. I shall fill this in now.

**Comment by dschaper** [comment] 2018-02-23 16:45
@DL6ER Is there a documented process for i386 systems using the x86_64 FTL binary?

**Comment by PromoFaux** [comment] 2018-02-23 17:01
Cheers @Gartonious , you da real MVP 😘

**Comment by Mcat12** [comment] 2018-02-24 03:48
Did you purposefully install a 32 bit OS on a 64 bit machine?

**Comment by Mcat12** [comment] 2018-02-24 03:51
Check this solution to a very similar issue: https://discourse.pi-hole.net/t/no-access-to-admin-page-after-pihole-installation/6893/16?u=mcat12

**Comment by Mcat12** [comment] 2018-02-24 04:02
What OS did you choose? It looks like you chose a 32 bit image instead of a 64 bit one.

**Comment by Gartonious** [comment] 2018-02-24 04:07
Downloaded from https://www.raspberrypi.org/downloads/raspberry-pi-desktop/
Direct: http://downloads.raspberrypi.org/rpd_x86/images/rpd_x86-2017-12-01/2017-11-16-rpd-x86-stretch.iso

Did not know there was a 64bit version to be honest? They have not listed it on their site.

**Comment by Mcat12** [comment] 2018-02-24 04:11
Follow the instructions from the discourse link, it sounds like your exact situation.

**Comment by Gartonious** [comment] 2018-02-24 04:13
So just to confirm, need to run `sudo apt install libc6:amd64` then try to install pi-hole again?

**Comment by Mcat12** [comment] 2018-02-24 04:24
Try it

**Comment by Gartonious** [comment] 2018-02-24 04:52
So yes that does seem to make it work before rebooting the OS.


What I did was:
1) restored the virtual machine back to a clean install and apt-get upgraded snapshot
2) Run `sudo apt install libc6:amd64`
3) Run `sudo reboot`
4) Run `curl -sSL https://install.pi-hole.net | bash` and followed the setup setups with NO errors and said setup complete this time.
5) I was able to navigate to the pi-hole admin webpage and it appears to be working.

However, I then rebooted the server and upon reboot the pi-hole admin page says "DNS service not running".
I run `sudo service dnsmasq status` and it said the following:
![image](https://user-images.githubusercontent.com/36725136/36625772-d611fe3a-191d-11e8-9491-4b55428bc192.png)

Just to advise as well, in the past I have never had to `run sudo apt install libc6:amd64` before installing pi-hole and I have always used the 32bit version from the https://www.raspberrypi.org website.

**Comment by Gartonious** [comment] 2018-02-24 05:02
So might have fixed this...
I followed the steps again like above but I removed the piserver like previously mentioned between steps 1 and 2. installed all ok again. can access the admin page etc. rebooted and now the admin page shows as "Active" and so `does sudo service dnsmasq status`.

**Comment by Gartonious** [comment] 2018-02-24 05:06
Work around to uninstall piserver and run `sudo apt install libc6:amd64` before installing pi-hole via the auto installer.

Would there be any reason to why a user would need to run `sudo apt install libc6:amd64` first as this step was never required in the past?

Also, moving forward, would pi-hole be made compatible to run alongside piserver?

**Comment by Mcat12** [comment] 2018-02-24 14:45
The reason you needed to run that command was because you had a 32 bit OS on a 64 bit kernel, which is not usual. The piserver config doesn't work with Pi-hole because it tries to set some settings which Pi-hole already sets, which is an error to dnsmasq. We have yet to find a way to disable that config, but we will try to work around it.

**Comment by Mcat12** [comment] 2018-02-25 02:58
@Gartonious If you run `pihole checkout core tweak/32bitOS_on_64bitCPU`, what is the output of `file $(which pihole-FTL)`

**Comment by Mcat12** [comment] 2018-02-25 03:23
Without running the libc install. It shouldn't be needed.

**Comment by Gartonious** [comment] 2018-02-25 03:27
The output is:
`/usr/bin/pihole-FTL: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=500fb341f98c98a77dc00e53be9cd8b1c5e22ec6, not stripped`

**Comment by Gartonious** [comment] 2018-02-25 03:32
Also, I have noticed earlier today that previous desktop builds of raspberry pi OS was alot larger and the architecture was not mentioned so not sure if they have changed / removed things from the latest build?
Old image name "2017-09-07-raspbian-stretch.iso" @ 4.57GB
New image name "2017-11-16-rpd-x86-stretch.iso" @ 2.22GB

**Comment by tambnguyen** [comment] 2018-02-26 00:31
I'm experiencing the same problem as well. I can't get it to update to v3.3. I'm stuck at v3.2.1.

```pi@pi3:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@pi3:~ $ ```

**Comment by Gartonious** [comment] 2018-02-26 00:35
@tambnguyen  If you are using the Raspberry Pi Desktop as I am then the work around would be to install `sudo apt install libc6:amd64` first then run the pi-hole installer again. If you are not using Raspberry Pi Desktop version then your issue might not be related to this one.

**Comment by Gartonious** [comment] 2018-02-26 00:52
@tambnguyen Out of curiosity I have managed to successfully install pi-hole on a raspberry pi 3 without any problems.
I downloaded and installed the "Raspbian Stretch with desktop" image from https://www.raspberrypi.org/downloads/raspbian/ and wrote the image to a SD card. After the system had booted up I had run `sudo apt-get update` and `sudo apt-get upgrade ` then `sudo reboot`. I then resized the SD card in `sudo raspi-config` and run `sudo reboot` again.
Once back online I then run the pi-hole installer command `curl -sSL https://install.pi-hole.net | bash` and followed through the setup steps without any problems. After another reboot, pi-hole was still running as it should.
You might have a corrupt file or something on your current PI image. Maybe save what you need from it and download and write the current image from the raspberry pi website to your SD card and try the steps mentioned above. Worked for me on a Raspberry Pi 3.

**Comment by E3V3A** [comment] 2018-03-22 07:47
@dschaper Maybe add a new issue tag as `non-arm`, `non-pi-hw` or `i386 arch` or something that would make sense? I came across this issue, thinking I might be able to help out and was quite intrigued by the non-exec error in the middle of the post, just to find out in the very end that the issue doesn't relate to ARM or RPi HW at all.

**Comment by DeveloperACE** [comment] 2018-03-27 03:56
I am having this issue too:

cat /etc/os-release:
```
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
sudo /usr/bin/pihole-FTL:
```
FTL started!
```

**Comment by dschaper** [comment] 2018-07-10 05:36
Should be resolved now, FTL checks for platform correctly. Closing

**Closed by dschaper** 2018-07-10 05:36 UTC
Labels: Investigating
