### ISSUE TITLE
wildcarded blocked URLs don't appear in list of top advertisers

### ISSUE THREAD

**Issue by frankrpi3** [pi-hole/pi-hole#1350] opened 2017-03-23 07:31 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
URLs which are blocked by a wildcard entry should also appear in the list of the Top Advertisers.
So if the entry is "samsungcloud" it should list "xxx.samsungcloud.com" and "samsungcloudyyy.net".

**[BUG | ISSUE] Actual Behaviour:**
If I add a wildcarded URL in the wildcard blocking list, the blocked URL does not appear in the list of the top advisers. Even if it is blocked very often.

**[BUG | ISSUE] Steps to reproduce:**
not needed, always reproducable

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment] 2017-04-13 14:36
Confirmed. The problem is that the variable that counts the number of how often a website is blocked is only incremented for exact blocking.

It is fixed in https://github.com/pi-hole/FTL/commit/882756a2ad3ab85ccb485e3c2f3ade0f0808543f

![screenshot at 2017-04-13 16-24-27](https://cloud.githubusercontent.com/assets/16748619/25009572/592d3aec-2067-11e7-90eb-8d67dabf5abe.png)
![screenshot at 2017-04-13 16-24-13](https://cloud.githubusercontent.com/assets/16748619/25009574/5b6effb6-2067-11e7-823d-b738b9553161.png)
![screenshot at 2017-04-13 16-33-43](https://cloud.githubusercontent.com/assets/16748619/25009566/545ec274-2067-11e7-89f3-a3dbb63b8dfb.png)

**Comment by frankrpi3** [comment] 2017-04-14 12:54
Very nice - danke !
As it is fixed in FTL - I am using the dev version - is it also fixed in the regular pi-hole version for the other users? I don't understand the exact relation between pi-hole and FTL :-/

Gruß, Frank

**Comment by DL6ER** [comment] 2017-04-14 13:43
The FTL engine will drive the next version of Pi-hole. Since this is a major transition we have to make sure that everything works nicely before releasing it for all users. Since the more people contribute in testing, the higher the likeliness of being able to identify bugs and other catches, we decided to add the `checkout` feature that allowd users to actively contribute in testing the next version of Pi-hole. 

Thank you for contributing in this program!

**Comment by dschaper** [comment] 2017-05-02 22:11
Fixed in 3.0 release

**Closed by dschaper** 2017-05-02 22:11 UTC
Labels: Confirmed Bug, Fixed in next release
