### ISSUE TITLE
Pihole unattended installation requires user interaction

### ISSUE THREAD

**Issue by zebulon501** [pi-hole/pi-hole#3617] opened 2020-07-26 17:09 UTC
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

5

---
**Expected behavior:**

Running the installer with the flag `--unattended` and a populated `/etc/pihole/setupVars.conf` would terminate without interaction.

**Actual behavior:**

A whiptail call (from displayFinalMessage) is made which has to be dismissed by hitting return to finish the installation.

**Steps to reproduce:**

Run the installer with the flag `--unattended` and a populated `/etc/pihole/setupVars.conf`.

**Debug token:**

None, not related to the Pihole runtime, but its installer logic
Core 5.1.1
Web 5.1
FTL 5.1

**Troubleshooting undertaken, and/or other relevant information:**

In `automated install/basic-install.sh`, line 1928:
`source "${PI_HOLE_LOCAL_REPO}/advanced/Scripts/webpage.sh"`
In `advanced/Scripts/webpage.sh`, line 26:
`source "${PI_HOLE_FILES_DIR}/automated install/basic-install.sh"`

This redefines `useUpdateVars` to `false` which leads to the dialog being displayed at the end of the supposed unattended installation.

**Comment by terryfroy** [comment] 2020-11-08 21:40
I can confirm this issue exists on CentOS 7.8 x86_64 as I just hit it while running an Ansible playbook to re-deploy one of our local Pi-Hole hosts.

This could be fixed without major refactoring by replacing the variable declaration in the basic-install.sh file:

`useUpdateVars=false`

with

`if [ -z "$useUpdateVars" ]; then useUpdateVars=false; fi`

It is difficult to workaround locally when deploying because even if I retrieve the script via curl and then pipe it through sed before passing it to bash; the script clones the basic-install.sh file from GitHub (without the fix) and sources it as per @zebulon501's initial report which renders the workaround ineffective.

As this is a trivial patch, it would be very much appreciated if it could be reviewed and added into the Pi-Hole basic-install.sh soon.

**Comment by PromoFaux** [comment] 2020-11-16 22:22
> This redefines `useUpdateVars` to `false` which leads to the dialog being displayed at the end of the supposed unattended installation.

Agreed, we actually had this issue with another variable somewhere along the line, though I cannot for the life of me find which one it was!

**Comment by mwoolweaver** [comment] 2020-11-17 04:43
> It is difficult to workaround locally when deploying because even if I retrieve the script via curl and then pipe it through sed before passing it to bash; the script clones the basic-install.sh file from GitHub (without the fix)

this was addressed in pi-hole/pi-hole/pull/3827 I believe

**Closed** 2020-11-28 19:05 UTC
Labels: Investigating, triage: Issue
