### ISSUE TITLE
Blocking raspberrypi?

### ISSUE THREAD

**Issue by camdenorrb** [pi-hole/pi-hole#543] opened 2016-06-25 05:56 UTC
##### Expected Behaviour:
Shouldn't block localhost.

##### Actual Behaviour:
Blocks local host
Shown in: https://i.gyazo.com/e0122a42fb93328cfca27a715b07aeae.png

##### Steps to reproduce this issue:
Normal curl installation

**Comment by dschaper** [comment] 2016-06-25 06:02
Hi, do you have another webserver running on the Pi-Hole? It looks like you are able to access the Admin page at http://raspberrypi/admin/ from the screenshot. Is this possibly a duplicate of #496?

**Comment by camdenorrb** [comment] 2016-06-25 08:17
Possibly, and yes I do. It's running off my raspberry pi.

**Comment by dschaper** [comment] 2016-06-25 10:53
Okay, is the other webserver daemon being blocked? (I assume you either have it at another IP address on the Pi, or you are using another port number for it?)

**Comment by camdenorrb** [comment] 2016-06-25 16:13
I did not configure any settings after the normal installation. And I can access the webserver through it's local ip address.

**Comment by dschaper** [comment] 2016-06-25 18:11
Would you be able to provide us with the output from `pihole -d`?

**Comment by camdenorrb** [comment] 2016-06-25 18:16
https://pastebin.com/5AC9NW4e

**Comment by dschaper** [comment] 2016-06-25 18:20
Thank you, the log appears to show that everything is working. What exactly are the problems that you are seeing with your installation?

**Comment by camdenorrb** [comment] 2016-06-25 18:22
As shown here: https://i.gyazo.com/e0122a42fb93328cfca27a715b07aeae.png

It appears to be blocking raspberrypi (127.0.0.1) which doesn't make any sense to me.

**Comment by jacobsalmela** [comment] 2016-06-25 18:23
What other Webserver are you running?

**Comment by camdenorrb** [comment] 2016-06-25 18:24
I have apache on there, it's hosting Mini-mc.net (my testing site currently) but it doesn't appear to be blocking it.

**Comment by jacobsalmela** [comment] 2016-06-25 18:27
Considering the debug log looks OK, could you temporarily disable that site, flush the log `pihole -f`, and see if it still happens?

**Comment by camdenorrb** [comment] 2016-06-25 18:28
Hm sure, let me figure out how to stop it. Because I already removed apache but it still appears to be running.

**Comment by Mcat12** [comment] 2016-06-26 17:13
It shows up as blocked because the Pi-hole uses itself as a DNS server, and since the hostname of the device is added to the block list (in order for you to be correctly redirected). So it's not being blocked, but is being redirected to the correct address. `pi.hole` is the other domain manually added to the blocklist. Adding those two domains is explained [here](https://www.reddit.com/r/pihole/comments/4oqzdv/pihole_blocking_itself/).

**Comment by camdenorrb** [comment] 2016-06-26 17:28
Ok :3 thank you very much I was about to give up on the issue.

**Closed** 2016-06-26 17:29 UTC
