### ISSUE TITLE
polish language filters

### ISSUE THREAD

**Issue by xxcriticxx** [pi-hole/pi-hole#637] opened 2016-08-28 13:47 UTC
i would like to add polish language filters to my pi-hole. can somebody provide some simple instructions?

**Comment by Mcat12** [comment] 2016-08-28 17:14
Do you mean translating the Pi-hole web interface to Polish? If so, check out [this](https://poeditor.com/projects/view?id=66305) site. You should be able to add Polish to the list of languages.

**Comment by xxcriticxx** [comment] 2016-08-28 17:21
@Mcat12 i would like to add polish list to my setup

**Comment by Mcat12** [comment] 2016-08-28 17:32
A list of polish ad domains? [This](https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists) might be useful. Basically, make sure that somehow you can get the list in a hosts file format so that the gravity script can parse it. If I may ask, do you have a link to the list?

**Comment by xxcriticxx** [comment] 2016-08-28 17:36
yes but not in host format

https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock.txt

**Comment by Mcat12** [comment] 2016-08-28 18:42
It looks like that list might work, although you will have to put in some custom parsing in order to get the domains. The list is in AdBlock Plus's format, and has similar syntax to the example list on that page I just linked, so use that as a starting point to parsing it.

**Comment by xxcriticxx** [comment] 2016-08-28 18:45
i will try and get back to you guys

**Comment by xxcriticxx** [comment] 2016-08-31 02:22
i made something like this will this work? whats is better format 0.0.0.0 or 127.0.0.1?

[hosts.txt](https://github.com/pi-hole/pi-hole/files/446277/hosts.txt)

**Comment by dschaper** [comment] 2016-08-31 02:27
You just need the domain names, Pi-hole's parsing script will assign the proper IP address to the lead of each line. Also there have been reports that comments with URL's in them may cause issues, but that hasn't been confirmed as of yet. You also don't need the localhost information there, again, just a list of the domains that you would like to block. The file should look like the very last block on the https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists page that Mcat12 listed.

**Comment by xxcriticxx** [comment] 2016-08-31 10:46
got it i will try to make all necessary changes to my host file

under this there is no more host file: http://adblock.gjtech.net/?format=unix-hosts
this one has ip in it: http://hosts-file.net/ad_servers.txt

**Comment by PromoFaux** [comment] 2016-08-31 11:15
>this one has ip in it: http://hosts-file.net/ad_servers.txt

That's fine. Our parser will replace the IP in any given host file with the IP address of your Pi :)

**Comment by jacobsalmela** [comment] 2016-10-08 15:05
Closing due to inativity

**Closed by jacobsalmela** 2016-10-08 15:05 UTC
Labels: QUESTION
