### ISSUE TITLE
Error when saving Upstream DNS Servers configuration

### ISSUE THREAD

**Issue by markus07** [pi-hole/pi-hole#4452] opened 2021-12-05 13:20 UTC
### Versions
- Pi-hole:  v5.6
- AdminLTE:  v5.8
- FTL:  v5.11

### Platform
- OS and version:  Raspbian 10.11
- Platform:  Raspberry Pi

### Expected behavior

Save config for Upstream DNS servers

### Actual behavior / bug
Blue info shows:
The DNS settings have been updated (using 15 DNS servers) 

The red error pops up:
_There was a problem applying your settings.
Debugging information:
PHP error (2): Undefined array key "v6_2" in /var/www/html/admin/scripts/pi-hole/php/savesettings.php:212_ 

### Steps to reproduce

1. Go to 'Settings->DNS'
2. Click on 'Upstream DNS servers'
3. See error

**Comment by yubiuser** [comment] 2021-12-05 13:25
Duplicate of https://github.com/pi-hole/AdminLTE/issues/1754. Fixed by https://github.com/pi-hole/AdminLTE/pull/1970 in the next release.

**Closed by yubiuser** 2021-12-05 13:25 UTC
Labels: Duplicate
