### ISSUE TITLE
Passwords with special characters in the middle are broken.

### ISSUE THREAD

**Issue by PsycloneTM** [pi-hole/pi-hole#5771] opened 2024-09-14 19:24 UTC
### Versions

- Pi-hole:  v5.18.3
- AdminLTE:  v5.21
- FTL:  v5.25.2

### Platform

- OS and version:  Debian Buster

- Platform:  VM

### Expected behavior

Upon logging in it show work.

### Actual behavior / bug

When creating a password with special character in the middle. Upon logging in it says the password is incorrect.

### Steps to reproduce

1. Go to command line
2. Type pihole -a -p (password with a special char) ex. gQ$f6
3. Open website console and try to login.

## Debug Token

- URL:

**Comment by yubiuser** [comment] 2024-09-14 19:36
Thanks for the report. I've tried to reproduce it with our current `development` branch (Pi-hole v6) but everything works as expected with the password you suggested (`gQ$f6`).

**Comment by PsycloneTM** [comment] 2024-09-14 20:04
> Thanks for the report. I've tried to reproduce it with our current `development` branch (Pi-hole v6) but everything works as expected with the password you suggested (`gQ$f6`).

Great to hear. Is there any reason you guys don't have some kind of nightly branch for a more stable build of dev for people who wanna try new features?

**Comment by yubiuser** [comment] 2024-09-14 20:13
We only have a single `dev` branch which is considered 'stable dev'. For V6 we had a instable branch for a looong time and conducted a many-month beta periode with public beta tests. Recently, we merged that branch into `develoment` because we think it's stable now. `development` will become the next master branch soon.

If you want to try it you need to checkout the `development` branch of all 3 Pi-hole components.

**Comment by yubiuser** [comment] 2024-09-14 20:14
And of course you can use Pi-hole as docker container where we have a nightly build...

**Comment by rdwebdesign** [comment] 2024-09-14 20:31
I just tried the same password on a **v5** container and the password `gQ$f6` was accepted.
I was able to access the web interface with this password, without issues.

Are you trying to change the password manually (on a terminal), using a script, or something else?

**Comment by PsycloneTM** [comment] 2024-09-14 20:37
> Are you trying to change the password manually (on a terminal), using a script, or something else?

Yes I'm using the terminal.

**Comment by rdwebdesign** [comment] 2024-09-14 20:41
I tested using 2 different terminals and it worked in both cases. I'm not sure why it is failing for you.

When you set the password to `gQ$f6`, are you able to login using `gQ` as password?

**Comment by PromoFaux** [comment] 2024-09-14 20:43
> If you want to try it you need to checkout the `development` branch of all 3 Pi-hole components.

Just keep in mind that with the current state of `development` (with it being prepped for v6) that switching from `master` to `development` is a strictly one way operation until such time as v6 is released on the `master` branch.

**Comment by PsycloneTM** [comment] 2024-09-14 20:54
> When you set the password to `gQ$f6`, are you able to login using `gQ` as password?

Yes gQ$ works fine as soon as I add something after the $ it doesn't work.

**Comment by PsycloneTM** [comment] 2024-09-14 20:57
I'm currently using raspberry-pi-desktop for my pi hole. @rdwebdesign are you testing on that?

**Comment by PsycloneTM** [comment] 2024-09-14 21:16
![image](https://github.com/user-attachments/assets/0dc32cc5-9930-4988-a88d-2568426ac5d7)
Maybe its a Debian thing idk

**Comment by rdwebdesign** [comment] 2024-09-14 21:19
The Pi-hole used on the test is a v5 container. The host is a Raspberry Pi (running Raspberry Pi OS).

I used 2 terminals to test: PuTTY and the Portainer console. It worked in both cases.

For some reason, your terminal is considering `$f6` as a variable.
When you type `gQ$f6` it is expanding `$f6`, but since there is no `f6` variable, it results in `gQ`.

**Comment by rdwebdesign** [comment] 2024-09-14 21:21
Hmmm... 
Just try to use the command `pihole -a -p` and hit <kbd>ENTER</kbd>. 
Type your password when asked (twice).

**Comment by PsycloneTM** [comment] 2024-09-14 21:28
> For some reason, your terminal is considering `$f6` as a variable. When you type `gQ$f6` it is expanding `$f6`, but since there is no `f6` variable, it results in `gQ`.
> Hmmm... Just try to use the command `pihole -a -p` and hit ENTER. Type your password when asked (twice).

Ah that worked, your right its only when I use $ in my password, but the method you posted works with the $.

**Comment by rdwebdesign** [comment] 2024-09-14 21:34
> Ah that worked

You can also achieve the same effect using single quotes, like this:
```
pihole -a -p 'gQ$f6'
```

When you use double quotes (`"$var"`) on a shell, you are actually asking the shell to expand variables and control characters (this also happens without any kind of quoting).

**Closed** 2024-09-14 21:35 UTC
Labels: Fixed in Pi-hole v6.0

**Comment by PsycloneTM** [comment] 2024-09-14 21:38
@yubiuser Are you able to replicate my issue using my method on v6? 



> > Ah that worked
> 
> You can also achieve the same effect using single quotes, like this:
> 
> ```
> pihole -a -p 'gQ$f6'
> ```
> 
> When you use double quotes (`"$var"`) on a shell, you are actually asking the shell to expand variables and control characters (this also happens without any kind of quoting).

Looks like I have the same thing on v6 guess its just terminal thing. Not something pi hole can fix

**Comment by rdwebdesign** [comment] 2024-09-14 21:53
This is the same for v6.

The v6 command is `pihole setpassword`:
- if called without passing a password (like the video above - `pihole setpassword`), it will work.
- if called with a password without quotes or using double quotes: `pihole setpassword gQ$f6`, it will fail (this is expected);
- if called with a password in single quotes: `pihole setpassword 'gQ$f6'`, it will work.
