### ISSUE TITLE
Installer does not fail with blank IP address blocks.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#1403] opened 2017-04-26 16:51 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

10

---
**[BUG]:**

**[BUG] Expected Behaviour:**
If the installer or reinstaller detects that `setupVars` is not in the correct format, it should error out.

See https://discourse.pi-hole.net/t/new-install-and-not-blocking-ads/2781

**[BUG] Actual Behaviour:**
If IPV4 address or IPv6 address is listed, but blank, installer thinks that blank is a valid IP address.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by PromoFaux** [comment] 2017-10-31 20:01
The IPv6 field is always there, even if IPv6 is not configured (Do we want to change this?)

That said, I've just tried blanking out both IP addresses is my `setupVars.conf` and I get the following message when running the installer:

![image](https://user-images.githubusercontent.com/1998970/32246181-0e90f336-be76-11e7-87ff-9df9fa7dcb88.png)

It seems to be working as intended.. however, do we wish to actually remove the field if it has a blank value?

**Comment by jacobsalmela** [comment] 2017-11-25 20:08
Yes, @PromoFaux I think you fixed this [here](https://github.com/pi-hole/pi-hole/commit/8cb72d87e46e8b9091d82aab105c48a7ec90510e#diff-9e53ae7c3c4f9235e5908d902fb93c8a).  If @dschaper or anyone else can confirm this is no longer an issue, we can close this issue.

**Comment by jacobsalmela** [comment] 2017-12-08 00:56
This is indeed fixed.  The installer shows
```
  You may now configure your devices to use the Pi-hole as their DNS server
  [i] Pi-hole DNS (IPv4): xxx.xxx.xxx.xxx
  [i] Pi-hole DNS (IPv6): ::1
  If you set a new IP address, please restart the server running the Pi-hole

  [i] The install log is located at: /etc/pihole/install.log
  Installation Complete! 
```
and
```
root@pihole:~# pihole -g
  No IP addresses found! Please run 'pihole -r' to reconfigure
```

**Closed by jacobsalmela** 2017-12-08 00:56 UTC
