### ISSUE TITLE
Queries over time do not work

### ISSUE THREAD

**Issue by Przemo78** [pi-hole/pi-hole#1339] opened 2017-03-17 14:05 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
When connected to admin page I should see "Queries over time" graph.

**[BUG | ISSUE] Actual Behaviour:**
When connected to admin page I can not see queries over time graph, only loading circle.

**[BUG | ISSUE] Steps to reproduce:**

Connect to your pihole admin page via HTTP.

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<vdttty3ibk>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment] 2017-03-17 19:36
I see a lot of out of memory errors:
```
(mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 68 bytes) in /var/www/html/admin/scripts/pi-hole/php/data.php on line 756
```
This is probably because the log is too big to be processed. Check if you see any queries after running `pihole -f`. The upcoming release of FTL will fix these memory and timeout errors.

**Comment by Przemo78** [comment] 2017-03-18 14:23
I have flushed logs before sending issue info. I have flushed logs after your suggestion. No change.
Still not working. 

Load and memory usage: 
Load:  0.08  0.06  0.01
Memory usage:  18.0%

**Comment by PromoFaux** [comment] 2017-03-18 19:46
`/etc/pihole/gravity.list is 1787726 lines long.`

@Przemo78 I notice from your debug log that you have quite a lot of extra lists added.. I think that could be the cause of the issue, as you're blocking nearly 1.8M domains!

[See here for a similar discussion on our forums](
19:42
https://discourse.pi-hole.net/t/adlists-list-modified-with-wally3k/2282)

I'm not sure if it will make a difference, but you could also try our development branch (with `FTL` enabled) to see if this resolves the issue.

To try it, run `pihole checkout dev` (and to revert to mainline it's `pihole checkout master`_

**Comment by technicalpyro** [comment] 2017-03-19 17:36
Running FLT with just over 1.5M blocked ... unless there is something else causing your issue running the dev branch should solve your problems

**Comment by dschaper** [comment] 2017-04-27 16:26
Timeout, closing.

**Closed by dschaper** 2017-04-27 16:26 UTC
