### ISSUE TITLE
New feature [Clients(over time)] not work properly

### ISSUE THREAD

**Issue by Jacopx** [pi-hole/pi-hole#1813] opened 2017-12-08 13:11 UTC
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`10`

---
**Expected behaviour:**

`I want to see the number of queries for each client.`

**Actual behaviour:**

`The window pop up, when you go over the graph with the mouse, falls under the graph base.`

**Photos:**
[Example of Bug](https://i.imgur.com/L1vlcfw.png)

**Version:**
```
$ pihole -v
  Pi-hole version is v3.2 (Latest: v3.2)
  AdminLTE version is v3.2 (Latest: v3.2)
  FTL version is vDev-437af07 (Latest: v2.12)
```

**Comment by PromoFaux** [comment] 2017-12-08 13:47
Duplicate of https://github.com/pi-hole/AdminLTE/issues/627

**Closed by PromoFaux** 2017-12-08 13:47 UTC
