### ISSUE TITLE
Solved: Debian Stretch x86_64 install fail silently (incompatible with backports)

### ISSUE THREAD

**Issue by AndreasKieling** [pi-hole/pi-hole#2801] opened 2019-06-15 20:18 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Installer completes

**Actual behaviour:**

It wont. Similar behaviour to:
https://github.com/pi-hole/pi-hole/issues/2392
Tried to install php-cgi and php-sqlite3 as suggested there. Doesnt work.
Dialog thing pops up after scrolling checkmarks of to be installed pkgs.
"0%" wait 2s "100%" Script ends, no pihole installed except in /etc/.pihole.

**Steps to reproduce:**

KVM/Libvirt VM on AMD Host, install debian stretch from the dvd, select only basic packages, add stretch and stretch-backports to sources.list, as a http mirror instead of from dvd, update, reboot, git clone pihole, run script. 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

{} # Not yet available

**Troubleshooting undertaken, and/or other relevant information:**

bash -x and > log.wtf
Wants libsqlite3-0 (= 3.16.2-5+deb9u1) but 3.27.2-3~bpo9+1 shall be installed.
Enabled backports are the culprit.

**Comment by AndreasKieling** [comment] 2019-06-15 20:18
Feel free to close here. But its worth mentioning.

**Comment by technicalpyro** [comment] 2019-06-15 21:36
the reason it it failing is due to using a OS image that does not include packages that it should see #2798 for more detail

**Comment by dschaper** [comment] 2019-06-15 23:30
Well, not to be "that guy" but this is pretty self-inflicted. Backports isn't something that should be enabled without apt pinning and selecting the specific package that you need from that repository. Definitely not a bug nor something for us to fix.

**Comment by Mcat12** [comment] 2019-06-16 04:38
Closing as this is not a bug or something Pi-hole can fix.

**Closed by Mcat12** 2019-06-16 04:38 UTC
Labels: Issue: Not a bug, triage: Issue
