### ISSUE TITLE
Error after flushing Network table via Webinterface

### ISSUE THREAD

**Issue by lastsamurai26** [pi-hole/pi-hole#3663] opened 2020-08-09 13:40 UTC
### Versions

- Pi-hole:  5.1.1
- AdminLTE:  5.1
- FTL:  5.1

### Platform

- OS and version:  RaspianOS (Buster)

- Platform:  Raspberry Pi 3b+

### Expected behavior

I tried to flush the Network table via webinterface 

### Actual behavior / bug

 Error
There was a problem applying your settings.
Debugging information:
PHP error (2): implode(): Invalid arguments passed in /var/www/html/admin/scripts/pi-hole/php/savesettings.php:741
### Steps to reproduce

1. open the Webinterface
2. Login and Go to Seetings 
3. Flush Network table 

## Debug Token

- URL:  

### Screenshots

![Bildschirmfoto 2020-08-09 um 15 37 46](https://user-images.githubusercontent.com/3257844/89733520-494c4800-da56-11ea-928a-2c0971667370.png)

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment] 2020-08-09 13:44
Thanks for the report.
Duplicate of https://github.com/pi-hole/AdminLTE/issues/1493

**Closed by yubiuser** 2020-08-09 13:44 UTC
