### ISSUE TITLE
/etc/pihole/setupVars.conf values wrong on update

### ISSUE THREAD

**Issue by PromoFaux** [pi-hole/pi-hole#681] opened 2016-09-12 22:11 UTC
As reported on twitter, [here](https://twitter.com/LinkLayer/status/775408460091490308).

Though, looking through the code, that should not be possible....

The only place that sets the variable `piholeInterface` is [here](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L196)

The only place that writes that variable to `/etc/pihole/setupVars.conf` is [here](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L801)

Although I've not tested this (currently have no device with wi-fi in a state to test!) There are only two ways the value in `/etc/pihole/setupVars.conf` can change... Which is if the install script is ran again and a different option is chosen, or if the file is manually edited before running the update script.

I might be wrong, and if anyone can offer any insight, it would be greatly appreciated!
##

**Comment by Dot-Dash** [comment] 2016-09-13 19:33
I reported this originally via Twitter. I had thought that perhaps the entire file was replaced.

**Comment by diginc** [comment] 2016-09-13 20:37
I've been working on reproducing this bug programmatically (automated tests).  I'm going about this by stubbing the entire basic-install script so I can call the install's inner functions one by one, so I can test the saving of the setupVars and then test the reading of setupVars in separate unit tests while trying to keep it as close to the real execution as possible.  If there aren't problems with those 2 then I can look at the interfaces function for problems...though stubbing whiptail and mocking user input will be trickier.

I did have issues with the code that read/sourced in the variables in my test framework but I'm not sure if that was the bug or something not being 1:1 in my tests.  I plan on investigating more tonight.

**Comment by diginc** [comment] 2016-09-14 04:35
@Dot-Dash  do you happen to have your  /etc/pihole/install.log from the bad upgrade?  Did you have any prompts about it being an upgrade?

I haven't been able to reproduce, I made my tests more 1:1 to the script and that removed any issues I had last night.

**Comment by PromoFaux** [comment] 2016-09-18 17:53
Bumping for update. Has this issue affected you again since? Tried on my Pi3 and was unable to reproduce.

**Comment by Dot-Dash** [comment] 2016-09-18 22:10
I haven't revisited this -- may be related to #686, which I have agreed to try to reproduce.  I'm new here.  Use your judgement if you want to close this or not.

**Comment by PromoFaux** [comment] 2016-09-18 22:22
Happy to keep it open, just pinging for an update is all :)

**Comment by dschaper** [comment] 2016-12-24 00:50
Closing due to age.

**Closed by dschaper** 2016-12-24 00:50 UTC
Labels: Possible Bug, Unable to replicate
