### ISSUE TITLE
Official installation support for CentOS 8/ RHEL 8

### ISSUE THREAD

**Issue by jatin-cbs** [pi-hole/pi-hole#2977] opened 2019-10-26 01:58 UTC
Provide official installation support for CentOS 8 and RHEL 8. 
The PHP version in the RHEL 8 app stream is 7.2.11 which will be updated a little in RHEL 8.1.
Other dependencies (if not available) i can request on RHEL bugzilla for EPEL 8. :) +1

**Comment by bcambl** [comment] 2019-10-26 02:11
We need `lighttpd` and `lighttpd-fastcgi` in EPEL. This is our current blocker.

**Comment by jatin-cbs** [comment] 2019-10-26 02:15
ok i file a package request for EPEL.

**Comment by jatin-cbs** [comment] 2019-10-27 16:05
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-dd549097c7

@bcambl  
🙂

**Comment by jatin-cbs** [comment] 2019-10-27 16:06
lighttpd packages are sent for epel testing

**Comment by bellwood** [comment] 2019-11-14 15:47
Will this get us official CentOS support on the rPi without having to resort to the hackery in the Wiki?

**Comment by jatin-cbs** [comment] 2019-11-16 15:08
Lighttpd packages are now in epel testing just wait for landing it in stable i will update when it does.

**Comment by bcambl** [comment] 2019-11-16 15:14
@jatin-cbs The link you provided looks to only be `lighttpd`.  
Has `lightppd-fastcgi` also been requested?

**Comment by bcambl** [comment] 2019-11-16 15:17
@bellwood CentOS support is only on x86_64.  
Please use the latest Fedora or one of the Debian derivatives for RaspberryPi

**Comment by bellwood** [comment] 2019-11-16 18:37
@bcambl isn't that due to lack of EPEL for ARM which appears to be less of an issue now (unless I'm mis-understanding)

**Comment by jatin-cbs** [comment] 2019-11-16 19:57
@bcambl  firstly 32 bit support is dropped even in fedora, 2nd 32 packages however are still included in RHEL appstream and also in EPEL amd rpm fusion.. Also in fedora.

**Comment by jatin-cbs** [comment] 2019-11-16 19:59
@bcambl and yes all lighttpd packages are in epel testing

**Comment by jatin-cbs** [comment] 2019-11-17 05:32
Lighttpd has been pushed to epel 8 stable 🙂

**Comment by karloluiten** [comment] 2019-12-01 13:02
A default centos8 will try to install lighttpd-fastcgi which currently does not work. Anyone got this solved? Disabling the web server "fixes" this but that is not what we are looking for ;)

```
[root@localhost automated install]# dnf install -y psmisc lighttpd-fastcgi php-common php-cli php-pdo
Last metadata expiration check: 0:03:59 ago on Sun 01 Dec 2019 01:56:11 PM CET.
Package psmisc-23.1-3.el8.x86_64 is already installed.
Error:
 Problem: conflicting requests
  - nothing provides spawn-fcgi needed by lighttpd-fastcgi-1.4.54-4.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[root@localh[root@localhost automated install]# dnf install -y psmisc lighttpd-fastcgi php-common php-cli php-pdo
Last metadata expiration check: 0:03:59 ago on Sun 01 Dec 2019 01:56:11 PM CET.
Package psmisc-23.1-3.el8.x86_64 is already installed.
Error:
 Problem: conflicting requests
  - nothing provides spawn-fcgi needed by lighttpd-fastcgi-1.4.54-4.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by bcambl** [comment] 2019-12-01 13:14
@karloluiten CentOS8 is currently not supported due to missing dependencies (which is the topic of this issue...)

You _could_ install `spawn-fcgi` from testing: 
```
sudo dnf install spawn-fcgi --enablerepo=epel-testing
```
.. but this is not supported and we will not be providing any support for CentOS8 until all dependencies are in the non-testing EPEL repos.

**Comment by jatin-cbs** [comment] 2019-12-01 13:24
EPEL testing is fine, playground ones are alot unstable and whem it moves to stable branch it will automaticaly be removed from testing branch so no issues.

**Comment by karloluiten** [comment] 2019-12-01 13:27
Thanks. Seems to work now. Please not that on Centos8 I had to install `php-json` as well, so I do not get:

`2019-12-01 14:25:07: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function json_encode() in /var/www/html/admin/api.php:139`

Maybe this has to be put in a requirements file somewhere.

**Comment by bcambl** [comment] 2019-12-01 13:39
@karloluiten Yes, we know about `php-json` as we had to install it only on the Fedora side in the past. This is normal as changes in Fedora typically make their way into CentOS.  
Once the required packages are available in EPEL, we will be slightly re-working the installer for CentOS/Fedora appropriately.

Related Lines:  
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L302  
https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L306

**Comment by GitJamz** [comment] 2020-03-02 11:24
Im sorry Im a little confused on github.. Tried to follow what is said here but..
Is pihole still not running on CentOS 8 or Fedora 31?
I fired up a VM. Set SELinux on permissive mode and disabled firewall - to test it.
Everything seems to install fine and in the end I can log in to the webGUI. However the dahsboard graphs just keeps loading.. So Something is wrong for sure.. 
Any fix?

**Comment by TheFiZi** [comment] 2020-03-13 03:49
The CentOS 8 install is 99% of the way there I think. Only step missing:

`yum install php-json`

After manually running that and a `systemctl restart lighttpd` the graphs started loading

**Comment by Cyb0rk** [comment] 2020-03-18 17:27
> The CentOS 8 install is 99% of the way there I think. Only step missing:
> 
> `yum install php-json`
> 
> After manually running that and a `systemctl restart lighttpd` the graphs started loading

I can confirm this.

**Comment by GitJamz** [comment] 2020-03-18 17:30
Ok cool. But how do you deal with selinux?

**Comment by TheFiZi** [comment] 2020-03-18 17:37
> Ok cool. But how do you deal with selinux?

From the installation script:

`Pi-hole currently does not support SELinux, but you may still continue with the installation.`

**Comment by GitJamz** [comment] 2020-03-18 17:40
Right thats why I asked.
How do you deal with selinux?

**Comment by TheFiZi** [comment] 2020-03-18 17:49
> Right thats why I asked.
> How do you deal with selinux?

Oh! I miss understood.

https://linuxize.com/post/how-to-disable-selinux-on-centos-8/

**Comment by GitJamz** [comment] 2020-03-18 18:34
> > Right thats why I asked.
> > How do you deal with selinux?
> 
> Oh! I miss understood.
> 
> https://linuxize.com/post/how-to-disable-selinux-on-centos-8/

I dont think disabling selinux is the way to go. There has to be ways to simply allow the parts pihole needs?

**Comment by bcambl** [comment] 2020-03-18 18:51
We can all agree that disabling selinux is not acceptable.  
That said, creating an selinux policy for the project in its current state would require softening the enforcement far more than what we are comfortable shipping or supporting. Some of the issues include the PHP front-end and how it currently functions, some file locations, as well as a few other factors.  
There is plans to re-write the portions of the project which use PHP to be more API driven and re-work some of how the backend works.. but until that time, you will need to either:
a) set selinux to permissive mode
b) create your own policy by following official selinux documentation
c) install on a debian based distro (no selinux based security)

**Comment by GitJamz** [comment] 2020-03-18 18:55
> We can all agree that disabling selinux is not acceptable.
> That said, creating an selinux policy for the project in its current state would require softening the enforcement far more than what we are comfortable shipping or supporting. Some of the issues include the PHP front-end and how it currently functions, some file locations, as well as a few other factors.
> There is plans to re-write the portions of the project which use PHP to be more API driven and re-work some of how the backend works.. but until that time, you will need to either:
> a) set selinux to permissive mode
> b) create your own policy by following official selinux documentation
> c) install on a debian based distro (no selinux based security)

Thank you for the detailed answer.
I think as a newbie in Linux and security I dont feel comfortable putting my pihole on a centos8 right now..
But I have no experience in debian based distros.. Would I have better luck with Centos7 ? Or should I just try to learn the Debian style?
I actually have my pihole on a RPI3b+ right now but I also have a powerful server running ESXi that I thought would be better to serve the pihole on..

**Comment by bcambl** [comment] 2020-03-18 19:11
If you are not comfortable running selinux in permissive mode.. then you would likely never want to run debian as it does not have selinux.

**Comment by stratus-ss** [comment] 2020-03-19 14:12
Putting SELinux in permissive mode and installing 'php-json' before running the install script seemed to have worked just fine on CentOS 8 Stream

**Comment by GitJamz** [comment] 2020-03-19 19:32
> Putting SELinux in permissive mode and installing 'php-json' before running the install script seemed to have worked just fine on CentOS 8 Stream

Right but you have to keep SELinux in permissive mode forever still, right ?

**Comment by bcambl** [comment] 2020-03-19 19:35
Right. 
The project is not selinux friendly in the current state. You would either need to set to `permissive` or deploy on a supported distro that does not have selinux security (debian).

**Comment by GitJamz** [comment] 2020-03-19 19:37
> Right.
> The project is not selinux friendly in the current state. You would either need to set to `permissive` or deploy on a supported distro that does not have selinux security (debian).

Right you said so and I believe thats where we ended the discussion. But now this guy came from nowhere and said something that sounded like it would work if you install it in a certain way...

**Comment by stratus-ss** [comment] 2020-03-19 19:40
If I have some time I may dig into how to exclude the pihole stuff from specific SELinux domains so that you don't need to disable it for the entire system, just specific parts for pihole

**Comment by GitJamz** [comment] 2020-03-19 19:42
> If I have some time I may dig into how to exclude the pihole stuff from specific SELinux domains so that you don't need to disable it for the entire system, just specific parts for pihole

That would be godlike.. I know from hanging out in #centos and #pihole on freenet/IRC that Im not the only one interested in this. 
Would be really really awesome!

**Comment by bcambl** [comment] 2020-03-19 19:51
@stratus-ss as mentioned, the main issue is PHP and how things currently work. The PHP code executes system commands and it is very unusual to have the httpd context allowed to run commands. There are a few context collisions that would require custom contexts to be created and various other softening which would result in weaking the system as a whole or causing other applications to be at risk.  
I have taken various attempts at creating a no-warranty policy for the project.. but I always stop once the policy starts getting too _evil_ for my conscience.
At this time, you would be better served by running the project inside a container instead of softening your host selinux policy. This is completely imo and you are welcome to do as you please with your systems.

**Comment by TheFiZi** [comment] 2020-03-19 19:53
@GitJamz You could also create a policy yourself and contribute it back to the project: https://wiki.centos.org/HowTos/SELinux

**Comment by GitJamz** [comment] 2020-03-19 19:54
> @GitJamz You could also create a policy yourself and contribute it back to the project: https://wiki.centos.org/HowTos/SELinux

Dude Im sorry.. Ive been using linux for about 6 months. All I know is how to follow tutorials so far and even then Im having trouble..

**Comment by Trapacid** [comment] 2020-09-13 17:27
Have we made any progress on this?

I was able to get PHP and Nginx working with SELinux on permissive and PHP running as an elevated user, but as soon as I logged in PHP errors were being displayed things like DNSMasq was not running and FTL was having some weird permission issues. This is on Red Hat Enterprise Linux 8.2.
All of this, as expected. I'm just wondering if we've gotten any progress on this.

**Comment by bcambl** [comment] 2020-09-13 18:34
Yes, The latest installer should support CentOS 8.   

RHEL is not officially supported but should not be too hard to get working. As for your permissions errors, please ensure you are on the latest release and run a repair. Some of your issues may be related to using nginx instead of the default lighttpd.   

I am going to close this issue as CentOS8 compatibility has been merged quite a while ago.

**Closed by bcambl** 2020-09-13 18:34 UTC
