### ISSUE TITLE
Check for CentOS version crashes the installer for CentOS Stream 8

### ISSUE THREAD

**Issue by uncovery** [pi-hole/pi-hole#3983] opened 2021-01-12 09:53 UTC
### Versions

  - Pi-hole version is v5.2.2 (Latest: v5.2.2)
  - AdminLTE version is v5.2.2 (Latest: v5.2.2)
  - FTL version is v5.3.4 (Latest: v5.3.4)

### Platform
- OS and version:  CentOS Stream 8
- Platform:  Virtualbox on QNap

### Expected behavior
installation to end with success or throw a meaningful error

### Actual behavior / bug
The installation script crashes without comment, error or logfile entries
The reason is in [this line](https://github.com/pi-hole/pi-hole/blob/41bdb741b7e1a70184ecd7dbfc23f3ebcaa5e3bc/automated%20install/basic-install.sh#L411): `CURRENT_CENTOS_VERSION=$(grep -oP '(?<= )[0-9]+(?=\.)' /etc/redhat-release)`
The version string on this version of linux is "`CentOS Stream release 8`"

### Steps to reproduce

1. change your /etc/redhat-release to say `CentOS Stream release 8`
2. try any type of installer

### Workaround
changing the above line to `CURRENT_CENTOS_VERSION=8`

### Remark
Given that CentOS 8 is going away and CentOS stream is one of the succeeding distros, it would make sense to change this check to support this version as well.

**Comment by yubiuser** [comment] 2021-01-12 10:21
Thanks for the report. This is a duplicate of
https://github.com/pi-hole/pi-hole/issues/3947

Fix already in the pipeline.

**Closed by yubiuser** 2021-01-12 10:21 UTC
