### ISSUE TITLE
domains on blocklist

### ISSUE THREAD

**Issue by xxcriticxx** [pi-hole/pi-hole#3424] opened 2020-05-22 02:08 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`In ver 4 when pihole was disabled domains on blocklist would show 0. In ver 5.0 if i disable pihole disable on block list still shows number of loaded domains even if pihole is disabled. `

**Actual behaviour:**

`I see a number under domains on blocklist even when pihole is disabled. `

**Steps to reproduce:**

`Disable pilhole for 5 min and check domains on blocklist.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/jyypp4luuw`

**Troubleshooting undertaken, and/or other relevant information:**

`just want to add this system been upgraded from ver 4 to 5 recently`

**Comment by triatic** [comment] 2020-05-23 12:15
I can confirm the same behaviour, although it's arguable whether that number **should** be set to zero when Pi-hole is temporarily disabled.

**Comment by PromoFaux** [comment] 2020-05-23 14:55
Basically, in versions `<=v4.4`, disabling was done by swapping out the `gravity.list` file with an empty one. This had the effect of Pi-hole still running, but the main list file being empty... this had the knock-on effect of the Domains on Blocklist count being 0.

Since we switched to `gravity.db` in 5.0, the behaviour is somewhat different, and there is no need to "trick" blocking into be disabled by removing all the domains.

Closing as it is by design :)

**Closed by PromoFaux** 2020-05-23 14:55 UTC
