### ISSUE TITLE
Can't resolve local Hostnames with Linux (Windows works!)

### ISSUE THREAD

**Issue by pidiet** [pi-hole/pi-hole#1493] opened 2017-05-24 07:45 UTC
Hello everybody!

[x] check; [x] check; [x] check; ...

Since we use Pi-hole in our network (only as DNS, DHCP is controlled by the router) there is one Linux Client (*buntu 14.04) which can't resolve local hostnames anymore. Using IP is working.
Wierdest thing is that windows-clients (v10) are able to resolve hostnames.

Error message which is returned to the linux client when putting a local hostname in the browser is:

`DNS_PROBE_FINISHED_NXDOMAIN`

When i give a look in the query log I see then everything is OK (cached)

**Comment by Mcat12** [comment] 2017-06-10 19:07
What is the output if you run `dig some-hostname`? (replace with the appropriate hostname) Try to find the log entry when this happens, using the Tail pihole.log function on the web interface or `pihole -t`.

**Comment by e9169** [comment] 2017-06-16 18:23
@pidiet Can you check if the Ubuntu machine has more than one DNS server configured? I suppose that pi-hole can not resolve local domains, so... unless you have another DNS server resolving for that machine, it seems a expected behaviour not to resolve local hostnames. Look at /etc/resolv.conf just in case, and also test the dig thing @Mcat12 told you before.

**Comment by jacobsalmela** [comment] 2017-07-07 02:42
@pidiet what's the status of this issue?  Are you running into it on the latest version?

**Comment by WaLLy3K** [comment] 2017-10-09 04:56
Closing ticket due to inactivity.

**Closed by WaLLy3K** 2017-10-09 04:56 UTC
