### ISSUE TITLE
Resolving .local names in VPN tunnel

### ISSUE THREAD

**Issue by Jacopx** [pi-hole/pi-hole#1528] opened 2017-06-15 19:44 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

---
**[OTHER]:**
I have setup, in the DHCP Lease section, the name for my VMs in the network. If I use the hostname defined for accessing to the WEB GUI they works, like `gogs.local:3000`, if I do It inside the VPN tunnel it not works. 
The DNS, during the tunnel works, I have try to ping website like `google.com` and everything goes fine. If I try to ping `192.168.2.5` (that is the gogs.local addres) it works instead, if I try to ping `gogs.local`, it not works. The result of `dig gogs.local` is the same under the tunnel and out of the tunnel.
**[ISSUE] Expected Behaviour:**
`http://gogs.local == http://192.168.2.5` (NO VPN)
`http://gogs.local == http://192.168.2.5` (VPN)

**[ISSUE] Actual Behaviour:**
`http://gogs.local == http://192.168.2.5` (NO VPN)
`http://gogs.local == ERROR` (VPN)

**Comment by DL6ER** [comment] 2017-06-15 20:12
> The result of dig gogs.local is the same under the tunnel and out of the tunnel.

Please provide the full output of `dig`

**Comment by Jacopx** [comment] 2017-06-15 20:51
I have only photos because away form home:
<img width="509" alt="screenshot 2017-06-14 15 07 32" src="https://user-images.githubusercontent.com/14002538/27201197-183bf43c-521d-11e7-8eb1-a85464601116.png">
<img width="504" alt="screenshot 2017-06-14 15 08 54" src="https://user-images.githubusercontent.com/14002538/27201198-184691a8-521d-11e7-9461-3c6207019d40.png">

You can see the difference of VPN or no from the DNS server address.

**Comment by Mcat12** [comment] 2017-06-15 20:53
Those appear to be outputting the expected values?

**Comment by Jacopx** [comment] 2017-06-15 20:55
Yes, the output is correct and this is the problem... Why I can't reach the site?

**Comment by Mcat12** [comment] 2017-06-15 20:57
Since it's resolving to the same IP address, do you have access to the server via other means (SSH)?

**Comment by Jacopx** [comment] 2017-06-15 21:05
It's not work... It's incredible:
<img width="627" alt="screenshot 2017-06-15 23 03 28" src="https://user-images.githubusercontent.com/14002538/27201738-0c5723c4-521f-11e7-88f5-d583980fab44.png">

I have just retried to use `dig` and the output is correct...

**Comment by dschaper** [comment] 2017-06-15 21:12
What does the output from `curl` look like?

`curl -I http://192.168.2.5` and `curl -I http://gogs.local`?

**Comment by Jacopx** [comment] 2017-06-15 21:33
It can't solve the name:
<img width="963" alt="screenshot 2017-06-15 23 31 31" src="https://user-images.githubusercontent.com/14002538/27202732-fab91aa6-5222-11e7-8757-b01b264e82a5.png">

**Comment by dschaper** [comment] 2017-06-15 23:01
Which VPN solution are you using? And can you paste to config files contents (with sensitive information removed) for us to look at?

**Comment by thomasleveil** [comment] 2017-06-16 00:25
take a look at `/etc/nsswitch.conf`, around `hosts:          files mdns4_minimal [NOTFOUND=return] dns`.

I had a similar issue (not with VPN though) today and my workaround was to change that line to `hosts:          files dns` + `service networking restart`

**Comment by dschaper** [comment] 2017-06-16 00:30
I was wondering if Bonjour (mDNS) would have some issues with the `.local` domain.

**Comment by Jacopx** [comment] 2017-06-16 05:25
I'm using OpenVPN, i Will paste the configuration as soon as I can! 👍🏻

I haven't understand what have you suggested to me @thomasleveil ...

**Comment by dschaper** [comment] 2017-06-16 06:23
Post the output from `cat /etc/nsswitch.conf` to see if you are getting an error from `mdns4` returning on an error.

**Comment by Jacopx** [comment] 2017-06-16 14:44
This is the output of cat:
`# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat
gshadow:        files

hosts:          files mdns4_minimal [NOTFOUND=return] dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis`

Uhmmmmmmm... The DNS files is `dnsmasq.conf` ?

**Comment by Jacopx** [comment] 2017-06-16 15:04
The OpenVPN server configuration is:
```
pi@rasp:~ $ cat /etc/openvpn/server.conf
dev tun
proto tcp

topology subnet
server 10.8.0.0 255.255.255.0

# server and remote endpoints
ifconfig 10.8.0.1 10.8.0.2

# Add route to Client routing table for the OpenVPN Server
push "route 10.8.0.1 255.255.255.255"

# Add route to Client routing table for the OPenVPN Subnet
push "route 10.8.0.0 255.255.255.0"

# your local subnet
push "route 192.168.2.0 255.255.255.0"

# Set your primary domain name server address for clients
push "dhcp-option DNS 10.8.0.1"

# 128.0.0.0/1 rather than 0.0.0.0/0. This has the benefit of
# overriding but not wiping out the original default gateway.
push "redirect-gateway def1"
client-to-client
duplicate-cn

# Generated for use by PiVPN.io
```

**Comment by dschaper** [comment] 2017-06-16 17:06
The suggestion was to change the `/etc/nsswitch.conf` file so that the line reads:

`hosts:          files dns` 

exactly like that, and then once you have made that change, restart networking by issuing the command, `sudo service networking restart`. Did you restart the networking after you made the change to `/etc/nsswitch.conf`?

**Comment by Jacopx** [comment] 2017-06-16 18:04
I have undestand perfectly and is what I have done ..:(

**Comment by dschaper** [comment] 2017-06-16 18:10
@thomasleveil Did you make those changes to `/etc/nsswitch.conf` on the Pi-hole device or on your local machine? I think the problem is that the MacBook is trying to use `mDNS` and failing that way.

**Comment by thomasleveil** [comment] 2017-06-16 18:55
it was on a Ubuntu vm in virtualbox in Windows 10. [This](https://askubuntu.com/a/81807/94174) was my solution.

I had an issue with domains ending with `.local`

**Comment by Jacopx** [comment] 2017-06-16 21:20
I have change the settings on the Rasp, not on my MBP. I hace noticed that the search domains change on OPENVPN by deflaut when i start the tunnel, i have tried to change it but i haven't gain nothing!

When I back home I will try on the MacBook.

**Comment by Jacopx** [comment] 2017-06-17 06:21
MacBook doesn't have `nsswitch.conf` and is not possible to map that... I have also tried to change:
```
.local --> .abcd
```
but, as you can imagine...

**Comment by martimarkov** [comment] 2017-06-20 10:47
+1

I have the same issue but it extends to all DNS traffic. I'll do a bit more investigation and see what is going on.

**Comment by Jacopx** [comment] 2017-06-20 11:40
> I have the same issue but it extends to all DNS traffic. I'll do a bit more investigation and see what is going on. 

This could be related to the configuration of the VPN, you need to have this specification:
`push "dhcp-option DNS 10.8.0.1"`

I still haven't solve my problem...

**Comment by martimarkov** [comment] 2017-06-20 12:18
My DNS setting is using the rpi address: 192.168.1.1

**Comment by Jacopx** [comment] 2017-06-20 13:07
Open another Issue! ;)

> My DNS setting is using the rpi address: 192.168.1.1

You new to use the address of the rasp in the VPN tunnel, try tu use the code that I have posted. Copy it in: `/etc/openvpn/server.conf`

**Comment by dschaper** [comment] 2017-07-21 20:31
What is the current status on this issue?

**Comment by Jacopx** [comment] 2017-07-21 20:44
I haven't solved the problem! I have changed my home environment and my raspberry is no more my OpenVPN server and I can't try It anymore... :/

**Comment by dschaper** [comment] 2017-07-21 21:51
Okay, I'll close out the Issue then, but feel free to open a new one if you run into any new issues.

**Closed by dschaper** 2017-07-21 21:51 UTC
Labels: Submitter Attention Required
