### ISSUE TITLE
pihole not answering when listening on all interfaces

### ISSUE THREAD

**Issue by hexxone** [pi-hole/pi-hole#3073] opened 2020-01-07 13:00 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

--
**Expected behaviour:**

The Tutorial for setting up OpenVPN in parallel suggested to switch the interface-listening mode into "all interfaces". Probably so the "tun" interface could be listened aswell.

**Actual behaviour:**

However as soon as the listening interface is switched, not a single DNS query could reach the pihole. Its also not query-logging anything, even though the device is still ping-able from the network.

**Steps to reproduce:**

I am running OpenVpn in parallel with Pihole on a Raspberry Pi Zero Wireless.
The Pihole is located in a local network behind a DS-Lite router (Fritz-Box) and hence has ipv6 support enabled to be reachable. The router does provide a DNS forwarding which is not used. Instead Dhcp is used to directly push the pihole ipv4 as DNS.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

t9vo8y9ruk

NOTE: the debug was created the the time of listening on interface wlan0. However this probably doesnt have any value at all since localhost querys never fail to resolve. Its just the external ones...

**Troubleshooting undertaken, and/or other relevant information:**

tried switching interface listening to "allow all origins" - with no success.

switched back to wlan0 interface - connectivity was restored.

Edit: I do have the usb0 ethernet interface enabled so I could still connect it to my pc and shh into it without Wlan. Perhaps this might be causing an issue..

Thanks in advance.

**Comment by dschaper** [comment] 2020-01-07 17:32
None of the assigned IPv6 addresses are actually configured on the Pi. IPv6 can cause a number of issues, is there a need to have it enabled on your network?

**Comment by Hexxonite** [comment] 2020-01-07 21:14
Can you maybe specify where to find these "assigned" ipv6 addresses?
I am not sure what exactly this means, as it is my first time setting something up over ipv6.

I guess for DNS resolving in the LAN ipv6 could be turned off indeed. However because of DS-Lite my router doesnt get a dedicated ipv4 address. Instead it receives a ipv6-zone which may also change after some days. So if I want to run the OpenVPN-server I guess turning it off isn't an option.

To overcome the issue of changing addresses I have an external VPS with domain, ipv4 and ipv6 address which will act as proxy, receive the current ipv6 with a script and tunnel the connection to the pihole (Relevant port forwarding has been done).
This works fine so far, however I can't seem to access the pihole DNS from within the VPN if the interface listening setting set to "wlan0".
And with "all interfaces" it doesnt work at all like I mentioned.

**Comment by dschaper** [comment] 2020-01-07 21:46
On the Pi-hole node the command `ip -4 address show` will show the v4 addresses on the interfaces. Similarly `ip -6 address show` will show v6 addresses.

This situation sounds like it's a configuration problem and not a bug in the Pi-hole code. We have a large community of users that can help with finding out what configuration options are needed at https://discourese.pi-hole.net and that would be the best place to try to get a working configuration for your network.

**Comment by PrototypeNM1** [comment] 2020-04-08 17:44
Maybe related? https://www.reddit.com/r/WireGuard/comments/dhae4x/wireguard_and_access_to_local_pihole/f3lktbp/

**Comment by dschaper** [comment] 2020-04-08 17:50
"All Interface" removes the `interface` lines from the Pi-hole configuration. If you add another service that includes configuration files with `interface` lines then you will lock FTL to that interface.

**Comment by yubiuser** [comment] 2021-08-12 20:02
Does the issue still persists?

**Closed** 2021-12-15 04:32 UTC
Labels: Submitter Attention Required, triage: Issue
