### ISSUE TITLE
[Possible Duplicate] Aggressive non-domain filtering

### ISSUE THREAD

**Issue by saint-lascivious** [pi-hole/pi-hole#5258] opened 2023-04-21 11:42 UTC
### Versions

- Pi-hole version is v5.16.2 (Latest: v5.16.2)
- AdminLTE version is v5.19 (Latest: v5.19)
- FTL version is v5.22 (Latest: v5.22)

### Platform

- OS and version:  Ubuntu 23.04

- Platform:  RPi 3

### Expected behavior

Valid domains not listed as non-domain entries.

### Actual behavior / bug

Valid domains listed as non-domain entries.

### Steps to reproduce

Update gravity

### Additional context

Sample of output, each case shown has one or more domains that are valid.

  [i] Target: https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts
  [✓] Status: Retrieval successful
  [i] Imported 6419 domains, ignoring 2 non-domain entries
      Sample of non-domain entries:
        - xiaoqiang
        - mishop.pandora.xiaomi.com.

  [i] Target: https://v.firebog.net/hosts/Easylist.txt
  [✓] Status: Retrieval successful
  [i] Imported 22899 domains, ignoring 1 non-domain entries
      Sample of non-domain entries:
        - ejghgjhhgadcdchjaada.ru.

  [i] Target: https://www.github.developerdan.com/hosts/lists/tracking-aggressive-extended.txt
  [✓] Status: Retrieval successful
  [i] Imported 171667 domains, ignoring 1 non-domain entries
      Sample of non-domain entries:
        - _udp.loopsx.duckdns.org

  [i] Target: https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt
  [✓] Status: Retrieval successful
  [i] Imported 42711 domains, ignoring 13 non-domain entries
      Sample of non-domain entries:
        - emptyfullsequel-bhd-.bhg406.repl.co
        - inpost.pl@09ih-post.6574343.xyz
        - ljjz0pzy1w.trailmagic.org.
        - qhl.ljh.modelgoldjewelery.com.
        - ra.kiech.correarealtygroup.cl.

Sample of valid domains:

- mishop.pandora.xiaomi.com. (valid)
- ejghgjhhgadcdchjaada.ru. (valid)
- _udp.loopsx.duckdns.org (valid for SRV)
- ljjz0pzy1w.trailmagic.org. (valid)
- qhl.ljh.modelgoldjewelery.com. (valid)
- ra.kiech.correarealtygroup.cl. (valid)

I happened to notice this by chance, so there may have been more I missed. The parser seems to dislike trailing periods, and leading underscores.

**Comment by yubiuser** [comment] 2023-04-21 17:58
Yeah, this is more or less a duplicate of https://github.com/pi-hole/pi-hole/issues/5239.

We are discussing internally as well how to proceed and which domains should be "allowed". Also the "trailing dot issue" is already known (https://github.com/pi-hole/AdminLTE/pull/2541)

**Comment by yubiuser** [comment] 2023-05-23 20:12
The underscore part is fixed with https://github.com/pi-hole/FTL/pull/1563

**Comment by yubiuser** [comment] 2023-05-24 19:14
And the trailing dot as well by

https://github.com/pi-hole/FTL/blob/825146fa5957c8976f4188534021aad99bec4e2a/src/gravity-tools.c#L181-L183

**Comment by yubiuser** [comment] 2023-05-28 19:59
Fixed with https://github.com/pi-hole/FTL/releases/tag/v5.23

**Closed by yubiuser** 2023-05-28 19:59 UTC
Labels: Fixed in next release
