### ISSUE TITLE
Pi-hole FTL won't start with Docker image 2022.04

### ISSUE THREAD

**Issue by declan-wade** [pi-hole/pi-hole#4673] opened 2022-04-02 07:46 UTC
### Versions

- Pi-hole:  v5.9.1
- AdminLTE:  v5.11
- FTL:  v5.14
- Docker Image: 2022.04

### Platform
- OS and version:  Windows 11 Pro 64-bit 
- Platform:  Docker Desktop version 4.5.1 (74721) (WSL2)

### Expected behavior

The Pi-hole FTL daemon / proccess should start correctly upon boot.
Using Docker image 2022.02 works perflectly fine on the same machine. 

### Actual behavior / bug

Upon the container starting, the following error messages are displayed on a loop:

```
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
      
.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 05-changer-uid-gid.sh: executing... 
[cont-init.d] 05-changer-uid-gid.sh: exited 0.
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
Assigning random password: LrCXGREJ

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Installing /etc/dnsmasq.d/01-pihole.conf...
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 05-changer-uid-gid.sh: executing... 
[cont-init.d] 05-changer-uid-gid.sh: exited 0.
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole
Assigning random password: VDZFJzc0

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [i] Installing /etc/dnsmasq.d/01-pihole.conf...
  [✓] Installed /etc/dnsmasq.d/01-pihole.conf
  [i] Installing /etc/.pihole/advanced/06-rfc6761.conf...
  [✓] Installed /etc/dnsmasq.d/06-rfc6761.conf
/opt/pihole/updatecheck.sh: line 77: /usr/bin/pihole-FTL: Operation not permitted
/opt/pihole/updatecheck.sh: line 91: /usr/bin/pihole-FTL: Operation not permitted
Existing DNS servers detected in setupVars.conf. Leaving them alone
::: Pre existing WEBPASSWORD found
DNSMasq binding to default interface: eth0
Added ENV to php:
			"TZ" => "",
			"PIHOLE_DOCKER_TAG" => "2022.04",
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "0.0.0.0",
			"CORS_HOSTS" => "",
			"VIRTUAL_HOST" => "0.0.0.0",
Using IPv4 and IPv6
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
::: Enabling Query Logging
  [i] Enabling logging...

  [✓] Logging has been enabled!
 ::: Docker start setup complete
  Checking if custom gravity.db is set in /etc/pihole/pihole-FTL.conf
  Pi-hole version is v5.9.1 (Latest: v5.9.1)
  AdminLTE version is v5.11 (Latest: v5.11)
/opt/pihole/version.sh: line 23: /usr/bin/pihole-FTL: Operation not permitted
/opt/pihole/version.sh: line 127: /usr/bin/pihole-FTL: Operation not permitted
  Latest FTL version is v5.14
  Container tag is: 2022.04
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting pihole-FTL (no-daemon) as pihole
Starting lighttpd
Starting crond
[services.d] done.
Unable to set inheritable capabilities: Operation not permitted
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as pihole
Unable to set inheritable capabilities: Operation not permitted
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as pihole
Unable to set inheritable capabilities: Operation not permitted
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as pihole
Unable to set inheritable capabilities: Operation not permitted
Stopping pihole-FTL
pihole-FTL: no process found
```
REPEATS forever

### Steps to reproduce

1. Pull latest docker image
2. Start container with latest image
3. Observe logs

## Debug Token

- URL:  https://tricorder.pi-hole.net/tuo3MTkq/

**Comment by PromoFaux** [comment] 2022-04-02 08:31
Dupe of https://github.com/pi-hole/docker-pi-hole/issues/1035
 
Please see:

https://github.com/pi-hole/docker-pi-hole/blob/master/README.md#upgrade-notes

**Closed by PromoFaux** 2022-04-02 08:31 UTC

**Comment by PromoFaux** [comment] 2022-04-02 10:23
https://i.4cdn.org/gif/1648770118095.webm

**Comment by PromoFaux** [comment] 2022-04-02 10:23
I've just pushed a new dev build that should hopefully solve this issue once and for all. It only attempts to set capabilities if they are available to the container.

Please try the dev - for those of you that don't need NET_ADMIN, please also unset this when trying the newest dev

Thanks all for your continued patience!

**Comment by PromoFaux** [comment] 2022-04-02 11:10
https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.04.1

**Comment by declan-wade** [comment] 2022-04-02 11:57
> https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.04.1

Worked like a charm - thanks so much for your help!
