### ISSUE TITLE
Bug/design flaw: /etc/pihole/pihole-FTL.db is on an SD card

### ISSUE THREAD

**Issue by graysky2** [pi-hole/pi-hole#1839] opened 2017-12-11 21:29 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
 5

This isn't a bug in the code but more concern relating to the design/strategy.  I am noticing that `/etc/pihole/pihole-FTL.db` is written once per minute.  My concern is that for the intended hardware (Raspberry Pi), this file system resides on an SD card which has a finite number of writes before it will wear out and that writing the file at this frequency will contribute to wearing the media.

* Based on watching the DTS, I believe it is re-written once per minute.
* Since `/etc/pihole/pihole-FTL.db` is a proper database, am I correct in assuming that the entire file is written out (ie we aren't just appending lines to the file, but are writing out up to the entire file once per minute)?  If so, unless you are limiting the size of the file, the minutely writes could amount to 10s of megs per hour.

**Comment by DL6ER** [comment] 2017-12-11 21:46
> which has a finite number of writes before it will wear out.

This is often overestimated. I'm running a Raspberry Pi B+ since almost 5 years non-stop with several years of Pi-hole with fully enabled logging. I'm still using the very first no-name 4GB SD card and don't see any wearing out. Have a look at `wear leveling` since I'm sure that most flash drives (including SD card) use it to protect themselves of extensive wearing-out of single bytes by repeated writes to the same address.

> am I correct in assuming that the entire file is written out

No, `FTL` and `SQLite` are designed to explicitly avoid extensive I/O operations. The database file is organized in "pages" which are **appended** on demand and used to store data. `FTL` does never perform actions that would require a complete re-write of the database.
In the case of garbage collection, the database will be reorganized by deleting the oldest entries. However, even this won't result in extensive writes to the disk as the data is kept but only marked as discarded in the database file. The pages can then be reused with new data so that the database file size is expected to stay the same after some point in time.

More details also here https://www.sqlite.org/fileformat.html

**Comment by graysky2** [comment] 2017-12-11 21:51
@DL6ER - Thank you for the quick and thoughtful reply.  I wonder if exposing this as a user tuneable would be nice feature?  Can you point me to somewhere in the code that currently does the once-per-minute (and would I could manually edit)?  Perhaps a longer term feature could be a place in the web GUI?

**Comment by DL6ER** [comment] 2017-12-11 21:55
The duration after which queries are "deleted" is already adjustable via `FTL`'s config file (can e.g. be set to a larger value if disk space is of no concern).

The database update interval is currenty hard-coded to 60 seconds here:
https://github.com/pi-hole/FTL/blob/master/FTL.h#L69
I'll consider to make it a likewise user adjustable period soon as I find this an useful addition.

**Comment by DL6ER** [comment] 2017-12-11 21:56
> and would I could manually edit

Yes, however, you'd have to compile `FTL` yourself.

**Comment by graysky2** [comment] 2017-12-11 22:24
> I'll consider to make it a likewise user adjustable period soon as I find this an useful addition.

That would excellent!  Am I correct in that only the "long term data" functions use this database?

**Comment by DL6ER** [comment] 2017-12-11 22:31
> Am I correct in that only the "long term data" functions use this database?

Yes!

**Comment by DL6ER** [comment] 2017-12-12 18:05
@graysky2 See https://github.com/pi-hole/FTL/pull/172

**Comment by graysky2** [comment] 2017-12-13 12:33
@DL6ER - I can confirm that changing the default value from 60 to 120 or to 600 works after compiling/restarting.  When I used a value of 3600, however, the commit never happened even overnight.

See this discussion as well: https://aur.archlinux.org/packages/pi-hole-ftl/#news

**Comment by DL6ER** [comment] 2017-12-13 16:55
> Using a value of 3600, the commit never happened even running overnight.

Yeah, I can confirm that. Every hour the database is checked for consistency (that is read-only). When this is done, no additional data is stored in the DB to not interrupt the scan. So, what happened before was, e.g.
```
...
 8:58 - wrote data to DB
 8:59 - wrote data to DB
 9:00 - checked for consistency, wrote no data to DB
 9:01 - wrote data to DB
...
```

When you specify now to dump every 60 minutes, the behavior will look like this:
```
...
 8:00 - checked for consistency, wrote no data to DB
 9:00 - checked for consistency, wrote no data to DB
10:00 - checked for consistency, wrote no data to DB
...
```
As you can see, the priorization of the check lead to a situation where no data was stored ever. I have not checked for this, but will push another change to the still open pull request to always write the data *immediately after* the check instead of relying on that it will be written later (what works perfectly fine with once per minute saving).

> The behavior is odd... Using a value of 1200, I booted the pihole box at 9:48 AM local time. The database did not update at 10:08 AM (ie 20 min after the boot and start of pi-hole-ftl). It did however update at 10:20 AM which is unexpected since the box and service had been running for over 30 min. It is just just past 10:41 AM and a 2nd update occurred at 10:40 AM.

This is expected and actually designed behavior. `FTL` does not work on relative time (i.e. minutes after startup) but on absolute time (i.e. wall clock time). Hence, when you specify "every 20 minutes", then the data will be saved at 10:00, 10:20, 10:40, 11:00, etc. This allows the user to predict when data is written and e.g. backup the database to somewhere else shortly after.

**Comment by graysky2** [comment] 2017-12-13 18:02
Thanks for the explanation.  A good work-around would be to use an odd-ball time in my case... not 3600 (hourly) but something like 3630 (~1 hour) or 21630 (~6 hours).

**Comment by DL6ER** [comment] 2018-01-14 12:41
Closing this because I think all open questions have been answered. Feel free to reopen of that is not the case.

**Closed by DL6ER** 2018-01-14 12:41 UTC
Labels: Discussion, Not a bug
