### ISSUE TITLE
dnsmasq core: reducing DNS packet size for nameserver 127.0.0.1 to 1280

### ISSUE THREAD

**Issue by Spanishu** [pi-hole/pi-hole#4501] opened 2022-01-02 09:36 UTC
### Versions

- Pi-hole:  v 5.7
- AdminLTE:  
- FTL:  v 5.12.1

### Platform
- OS and version:  Debian buster 
- Platform:  Raspberry PI

### Actual behavior / bug
Since yesterday I have a flashing warning sign on my raspberry pi running pi-hole with this message
`
DNSMASQ_WARN | Warning in dnsmasq core:reducing DNS packet size for nameserver 127.0.0.1 to 1280
-- | --
`
## Debug Token

- URL:  https://tricorder.pi-hole.net/0Ilkcacl/

**Comment by DL6ER** [comment] 2022-01-02 09:56
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, please have a look here https://discourse.pi-hole.net/t/dnsmasq-warn-reducing-dns-packet-size/51803/8 where your question has already been addressed.

The particular post I'm linking to shows you what you can do to avoid these warnings. Nevertheless, the entire discussion is worth reading if you want to understand where this is coming from, why it isn't a severe issue and also why it is not caused by Pi-hole but the upstream server you selected.

I'll close this issue as it is not a bug. If you need additional help after reading the community forum thread, we're here to help you.

**Closed by DL6ER** 2022-01-02 09:56 UTC
