### ISSUE TITLE
Warning that i've used 18.4EB of storage 

### ISSUE THREAD

**Issue by coltoneshaw** [pi-hole/pi-hole#4687] opened 2022-04-08 13:46 UTC
### Versions
  Pi-hole version is v5.9.1 (Latest: v5.9.1)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform
- OS and version:  macOS M1 12.3
- Platform:  Docker

### Expected behavior

The storage should display correctly. 

### Actual behavior / bug

PiHole is convinved that I'm running a Google level data center from my tiny mac mini. 

```
Disk shortage (/etc/pihole/pihole-FTL.db) ahead: 75257996% used
/etc/pihole: 18.4EB used, 245.1GB total
```

### Steps to reproduce

It's just one of the warnings that keeps popping up in `Pi-hole diagnosis`

## Debug Token

[✓] Your debug token is: https://tricorder.pi-hole.net/Augi7whg/

### Screenshots

![Screen Shot 2022-04-08 at 9 45 11 AM](https://user-images.githubusercontent.com/46071821/162448241-197cb551-4683-41a6-9107-60866c02e8fb.png)

### Additional context

Running this on mac with docker.

**Comment by yubiuser** [comment] 2022-04-08 14:32
Duplicate of https://github.com/pi-hole/docker-pi-hole/issues/951

**Closed by yubiuser** 2022-04-08 14:32 UTC

**Comment by russalex83** [comment] 2022-09-24 23:41
https://docs.pi-hole.net/ftldns/configfile/#check_disk

vi /etc/pihole/pihole-FTL.conf

#add variable:

CHECK_DISK=0
