### ISSUE TITLE
Admin Page Not Fully Loading

### ISSUE THREAD

**Issue by iamthebammbamm** [pi-hole/pi-hole#3686] opened 2020-08-13 02:17 UTC
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  Debian 10.4

- Platform:  Raspberry Pi

### Expected behavior

Numbers for Queries Blocked and Percent Blocked, and data for Client Activity, Query Types, and Queries answered by.

### Actual behavior / bug

None of the expected behavior. "---" or loading wheels

### Steps to reproduce

1. Go to Admin page
![Pihole](https://user-images.githubusercontent.com/35617633/90086787-3e5d1600-dce9-11ea-9f85-6665ea6172c4.png)

## Debug Token

- URL:  https://tricorder.pi-hole.net/rwpn1un7i1

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by jfb-pihole** [comment] 2020-08-13 02:46
Clear the browser cache and reload the page.

**Comment by spyesx** [comment] 2020-08-14 10:47
Thx @jfb-pihole, I thought about everything but this! Always miss the simple things.
@iamthebammbamm you can try and close the issue if it works for you too :)

**Comment by liquidat** [comment] 2020-08-27 23:02
Fixed it for me. Thanks @jfb-pihole 
@iamthebammbamm Can you please verify and close this issue?

**Comment by antwal** [comment] 2020-09-30 11:21
> Clear the browser cache and reload the page.

the problem is not the browser cache; but the size of the SQLite database; if it is too large this problem occurs

**Comment by dschaper** [comment] 2020-09-30 12:57
No, it's a cache problem.

**Closed** 2020-09-30 12:58 UTC

**Comment by antwal** [comment] 2020-09-30 13:16
hi, with the cache disabled I have the exact same problem. if I empty the database and set it to a minimal level, the problem does not occur. but if you say it is a cache problem you are right. thanks,

**Comment by dschaper** [comment] 2020-09-30 13:27
You disable the cache in `lighttpd` and in your web browser? Or you disable DNS cache? Two very different things and completely unrelated.

**Comment by PromoFaux** [comment] 2020-09-30 14:08
For reference, in the next release we (should) no longer have the javascript caching issue thanks to the cache busting variables introduced here:

https://github.com/pi-hole/AdminLTE/pull/1550

**Comment by antwal** [comment] 2020-09-30 14:29
> You disable the cache in `lighttpd` and in your web browser? Or you disable DNS cache? Two very different things and completely unrelated.

Hi

on lighttpd I currently have set

`setenv.add-response-header = ( "Cache-Control" => "private, no-cache" )`

I also tried with

`setenv.add-response-header = ( "Cache-Control" => "no-store, no-cache, must-revalidate" )`

and

setenv.add-response-header  = ("Cache-Control" =>"max-age=0")

on the browser i tried disabling the cache in dev-tools

![image](https://user-images.githubusercontent.com/410736/94697455-83d8af80-0338-11eb-9633-850ab1ea697b.png)

when I try to open the administration the browser freeze after a few seconds trying to load the data. 

if instead I empty the database with all the log information then it works; as it exceeds 50mb the problem recurs

the problem occurs only with the first 3 settings, if I set the log to anonymous there are no problems

![image](https://user-images.githubusercontent.com/410736/94698315-766ff500-0339-11eb-8b47-5cf48d6f91ac.png)

Thanks.

**Comment by dschaper** [comment] 2020-09-30 14:31
Put everything back to how it was set by the installer. Don't muck with the configurations, don't delete databases.

This is a well known and easily solved issue. 

The reason I'm being very abrupt with you is that people will search for this topic and apply your broken instructions and we'll have to fix that.

**Comment by antwal** [comment] 2020-09-30 15:27
> Put everything back to how it was set by the installer. Don't muck with the configurations, don't delete databases.
> 
> This is a well known and easily solved issue.
> 
> The reason I'm being very abrupt with you is that people will search for this topic and apply your broken instructions and we'll have to fix that.

there are no problems; I hope the problem is solved

**Comment by trickiegt** [comment] 2021-03-03 17:47
Mine had issues too because the database was enormous -- I allowed port forwarding to port 53 and the entire internet started using it lmao -- I disabled that port forwarding rule and flushed the logs
