### ISSUE TITLE
function piholeStatus() is flooding syslog with www-data sudo to root messages

### ISSUE THREAD

**Issue by thelner** [pi-hole/pi-hole#4615] opened 2022-02-15 18:40 UTC
### Versions
  Pi-hole version is v5.9 (Latest: v5.9)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)

### Platform
- OS and version:  
Debian GNU/Linux 11 (Raspberry Pi OS (64-bit))

- Platform:  
Raspberry Pi 4

### Actual behavior / bug

With the addition of "Use piholeStatus() in header.php #2062", every time "function piholeStatus()" (scripts/pi-hole/php/func.php) is called, this is written to the systemd journal once per second the entire time the pi-hole web page is loaded:

Feb 15 12:11:50 pihole4 sudo[120279]: www-data : PWD=/var/www/html/admin ; USER=root ; COMMAND=/usr/local/bin/pihole status web
Feb 15 12:11:50 pihole4 sudo[120279]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=33)
Feb 15 12:11:50 pihole4 sudo[120279]: pam_unix(sudo:session): session closed for user root

This is not only flooding the systemd journal but causing high system loads because of IO wait.

### Steps to reproduce

1. Load Pi-Hole webpage
2. View systemd journal: $ sudo journalctl -xe

## Debug Token
https://tricorder.pi-hole.net/YqF94i7Y/

## Additional Info
To temporarily solve this, I edited scripts/pi-hole/php/func.php to stop calling `pihole_execute('status web')`:

 function piholeStatus()
 {
     // Receive the return of "pihole status web"
     // $pistatus = pihole_execute('status web');
     $pistatus = '53';
     return isset($pistatus[0]) ? intval($pistatus[0]) : -2;
 }

**Comment by zoqaeski** [comment] 2022-02-15 23:46
I've also noticed this behaviour since the new update.

**Comment by yubiuser** [comment] 2022-02-16 09:23
I can confirm the behavior but I'm not sure if this is new. Before https://github.com/pi-hole/AdminLTE/pull/2062 `header.php` directly called `pihole_execute('status web')`. Now it calls `piholeStatus()` in `func.php` which itself also only calls `pihole_execute('status web')`


https://github.com/pi-hole/AdminLTE/blob/64bbce906b31c213183db7b6f0547513423e4bbf/scripts/pi-hole/php/func.php#L487-L491

**Comment by yubiuser** [comment] 2022-02-16 09:26
I think the "real" issue is a more general one: the `pihole` script checks for root privileges right at the start and not only for functions that are needed. E.g. `pihole status` and `pihole -h` should not require root access. See https://github.com/pi-hole/pi-hole/issues/2927

**Comment by yubiuser** [comment] 2022-03-18 14:14
Should be mitigated by https://github.com/pi-hole/AdminLTE/pull/2126

**Comment by ChrisWNY** [comment] 2022-04-20 17:01
Thanks for posting this info. I also changed the function piholeStatus() to stop pi-hole from spamming Syslog every time it was loaded into a browser. 

Quick question...what is the reason for setting $pistatus to '53'?

**Comment by rdwebdesign** [comment] 2022-04-20 17:03
Actually, when all is running fine the status reports the port number: `53` in most cases.

**Comment by yubiuser** [comment] 2022-04-20 18:59
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.10

**Closed by yubiuser** 2022-04-20 18:59 UTC
Labels: Fixed in next release, Investigating
