### ISSUE TITLE
Incorrect domain parsing

### ISSUE THREAD

**Issue by dumprop** [pi-hole/pi-hole#3971] opened 2021-01-06 08:46 UTC
### Expected behavior

Domain was added to blocklist

### Actual behavior / bug

Domain are skipped (as invalid)

### Steps to reproduce

add to adlist https://raw.githubusercontent.com/stonecrusher/filterlists-pihole/master/watchlist-internet-ph.txt (for example value: e-geräteundhaus.com)

### Screenshots

<img width="883" alt="image" src="https://user-images.githubusercontent.com/34004367/103748154-bddedf00-5014-11eb-8a21-ec06209cd860.png">

**Comment by yubiuser** [comment] 2021-01-06 11:19
This is a duplicate of

https://github.com/pi-hole/pi-hole/issues/3483

Closing this issue. If you want to add something, please use the other issue.

**Closed by yubiuser** 2021-01-06 11:19 UTC
