### ISSUE TITLE
Long-term load (15min avg) larger than number of processors: 2.3 > 2 This may slow down DNS resolution and can cause bottlenecks.

### ISSUE THREAD

**Issue by e-i-k-e** [pi-hole/pi-hole#4487] opened 2021-12-27 10:57 UTC
### Versions
root@PIHole:~# pihole -v
  Pi-hole version is v5.7 (Latest: v5.7)
  AdminLTE version is v5.9 (Latest: v5.9)
  FTL version is v5.12.1 (Latest: v5.12.1)
Ubuntu 20.04.3 LTS (GNU/Linux 5.13.19-2-pve x86_64)

Hi, everyone,
since the last update i got the message.

"Long-term load (15min avg) larger than number of processors: 2.3> 2
This may slow down DNS resolution and can cause bottlenecks. "

I run piHole on an Intel NUC with Proxmox in a container.
After the first information, I managed to allocate more cores to pi Hole, which I did. Unfortunately brought no improvement.

What can I do / test?

![image](https://user-images.githubusercontent.com/83473829/147464972-8b7e8789-d233-4254-be08-63ccd294dd2d.png)
![image](https://user-images.githubusercontent.com/83473829/147465003-acf2f612-c5c9-4b0c-bbb0-beecd1006c6f.png)
![image](https://user-images.githubusercontent.com/83473829/147465122-a56bde41-5c25-4ecf-af3d-0f1a6db27df3.png)
![image](https://user-images.githubusercontent.com/83473829/147465171-b20f0c2d-f834-4b7e-b365-a6d0d50f8ca1.png)
![image](https://user-images.githubusercontent.com/83473829/147465094-c603529c-fc31-449b-bc6c-59f4c1958f17.png)

**Comment by DL6ER** [comment] 2021-12-27 14:21
Naja, es meint was die Warnung sagt: Ein System, dessen Last dauerhaft höher als die Anzahl der zur Verfügung stehenden CPU-Kerne ist, wird allgemein nicht als "gesund" angesehen. Prozesse müssen ständig auf die Zuteilung von Ressourcen warten. Da Pi-hole als kritische Infrastruktur (DNS-Server) hoch priorisiert ist, ist diese Ressourcenverknappung evtl. erst bei anderen Prozessen auf der gleichen Maschine zu bemerkt.

Pi-hole berücksichtigt hierbei das gesamte System, nicht nur den eigenen Container. Wenn Du die Last nicht reduzieren kannst und glaubst, dass das kein Problem darstellt, dann kann die Warnung auch einfach mit der Option `CHECK_LOAD=false` in der Datei `/etc/pihole/pihole-FTL.conf` deaktiviert werden (siehe [hier](https://docs.pi-hole.net/ftldns/configfile/#check_load)).

**Comment by jbeardon** [comment] 2021-12-28 20:02
I've had this warning as well on a Proxmox LXC container install. After monitoring host load, container memory, disc and CPU usage, I am convinced it is mis-reporting. The proxmox server is an 8 core i5 with 32 gb ram. Over the course of an hour, the host load did not exceed 3%. CPU usage on the container did not exceed 2%. RAM usage was constant at 94mb with 512 allocated. Disk usage at 9%. There are a number of posts appearing on the facebook group and reddit regarding this.

**Comment by DL6ER** [comment] 2021-12-28 21:24
@jbeardon When Pi-hole is running inside a virtual environment it all depends on the supervisor what Pi-hole sees. I vaguely recall Proxmox had some issues with reporting the entire system's load to containers but only the number of cores you allocated - resulting in that Pi-hole sees a very busy machine that is running only on, say, two cores and warns accordingly. It may be that this bug is still not fixed.

Could you check the output of the command `uptime`? This is the simplest way to get the system load. What does it look like? How many cores did you assign to the virtualization?

I'm not involved in Facebook or Reddit discussions but you could pass on any information we can find together if you like. Also,

**Comment by jbeardon** [comment] 2021-12-29 02:58
Thank you. 
I'm also not sure if the mentioned bug exists. I do only have a single core assigned to both of the pihole instances on this machine. Uptime of the secondary pihole (which is currently displaying the warning - I dismissed on the primary) shows the following:
![image](https://user-images.githubusercontent.com/14904316/147622718-cbcfda40-15a5-4467-ac9a-6a3d56899244.png)

The Facebook and Reddit discussions aren't going to be a great deal of help - people indicating they have an issue and a bunch of ill-thought-out replies saying 'throw more resources at it'.

I am assuming this warning doesn't auto-reset? 
Thanks, John

**Comment by dschaper** [comment] 2021-12-29 03:27
Can you also show the output for `nproc` so we can see how many cores the VM is seeing?

**Comment by jbeardon** [comment] 2021-12-29 08:11
nproc returns one core

**Comment by DL6ER** [comment] 2021-12-29 09:35
> I am assuming this warning doesn't auto-reset?

It doesn't. Imagine your network is down throughout the night because your server running Pi-hole was extremely busy but things recovered til morning. You surely want to know about this as an excessive load may have influenced other things on the same server, too.

> I'm also not sure if the mentioned bug exists

Simple to try: Just run anything that is generating a lot of load on the main server for one minute, and then check `uptime` both on the server and in your Pi-hole container. If there is no bug, the increase in load should be visible on the host but not in the container. You could, for instance, use an infinite `bash` loop to keep one core busy (increase load by roughly one):
``` bash
while true; do true; done
```
(kill it with <kbd>Ctrl</kbd>+<kbd>C</kbd> once you are done).

I know it may be questioned if this is a bug at all because it allows the container to see if the host system is busy (without being able to do anything against it, though). When setting the core count artificially low, the comparison to `nproc` becomes useless and you should consider disabling the check using `CHECK_LOAD=false` in `/etc/pihole/pihole-FTL.conf` as mentioned in the [docs](https://docs.pi-hole.net/ftldns/configfile/#check_load)). I still consider this useful in the vast majority of bare-metal installations. Keep in mind that many Pi-hole users are beginners and it may not even know if their Raspberry Pis are overwhelmed by the numbers of task they put on them.

**Comment by jbeardon** [comment] 2021-12-29 09:53
Thanks for the detailed reply. I appreciate your time on this. In my instance, I will just disable the check. It may well have been triggered when a linux VM was performing a version update which may have increased overall load.
I do however wonder if the time over which the long term load is calculated should be increased or be user-definable. My reason being that on low powered, bare metal installs, it is quite feasible the warning could be triggered during normal operation (eg when updating pihole or the underlying OS). A Pi zero can easily take 15 minutes to perform a version update and at that time would be flagged as being under high load. I appreciate that a high number of Pi-Hole users are beginners but conversely, a beginner can also be overly worried by the warning and not actually have the skillset to diagnose and rectify an underlying issue if present. Especially if it is triggered during the normal process of updating.

Thanks again!
John

**Comment by DL6ER** [comment] 2021-12-29 10:00
> I do however wonder if the time over which the long term load is calculated should be increased or be user-definable.

This isn't possible. Only the kernel is capable of computing the load as he is the only one seeing everything. The load values offered by the Linux kernel are 1 min, 5 min and 15 min. This is hard-coded and cannot be changed. Link to the Linux source:

``` c
#define EXP_1		1884		/* 1/exp(5sec/1min) as fixed-point */
#define EXP_5		2014		/* 1/exp(5sec/5min) */
#define EXP_15		2037		/* 1/exp(5sec/15min) */
```

https://github.com/torvalds/linux/blob/e7c124bd04631973a3cc0df19ab881b56d8a2d50/include/linux/sched/loadavg.h#L21-L23

**Comment by jbeardon** [comment] 2021-12-29 10:03
Understood.
Thanks again - this has given me more information with which to advise on the Facebook group etc.

**Closed** 2022-01-11 10:06 UTC
Labels: Issue: Not a bug

**Comment by cmileto** [comment] 2023-04-29 13:01
i still have this constantly and it drives me crazy. is there no way to disable this mistaken reporting?

**Comment by yubiuser** [comment] 2023-04-29 13:10
If you read this thread carefully, you would find

> you should consider disabling the check using `CHECK_LOAD=false` in `/etc/pihole/pihole-FTL.conf`

**Comment by iamdoubz** [comment] 2024-04-01 16:48
So, I run my PiHole in docker on Synology, and when I run htop I get two sets of load averages: one for IO and the other for CPU. It appears that it is reading the IO average as opposed to the CPU average. Could this be the missing link for me?

**PiHole Screen**:
![image](https://github.com/pi-hole/pi-hole/assets/4871781/6206140e-4b44-4b47-9d94-a4c356616076)
**htop screen**:
![image](https://github.com/pi-hole/pi-hole/assets/4871781/7e02236a-369b-4640-82df-5b7865fe12b4)

**Comment by rdwebdesign** [comment] 2024-04-01 17:42
> It appears that it is reading the IO average as opposed to the CPU average.

The web interface uses PHP function [`sys_getloadavg()`](https://www.php.net/manual/en/function.sys-getloadavg.php) to retrieve the values from `/proc/loadavg`.

Apparently this issue is caused by a Synology OS changing the contents of the file, using a custom format and changing the PHP returned value.

**Comment by qbabron** [comment] 2025-02-19 08:18
In my case it was backup of the proxmox machines by the time the message was logged. There was no load on the LXC container with Pihole but the whole Proxmox was loaded by the backup.

**Comment by emigrating** [comment] 2025-03-24 09:34
Old thread and issue, but I am running into this on v6.0.5 (and I believe all previous 6.0.x releases). I believe Pi-hole is misreading or misinterpreting data when running in a Proxmox CT/LXC/container.

This happens on all my instances, and they all seem to report things slightly differently. If I allocate one core to the Pi-hole in question, it consistently displays a  **Long term load ... 1.2 > 1**. However, if I take the same container and assign another core, it starts showing something like **2.3 > 2** instead. This seems to scale up with the number of cores available.

Using uptime, it shows the load average as anywhere from **0.82 - 2.41** depending on when you take the reading. This aligns with the **1.2 > 1** for a single core. But those stats are not entirely accurate due to how LXC reports metrics. On the other hand, top provides a more realistic view, showing 94.9% idle, with minimal user-space (us) and system (sy) activity, which matches the lower 2% container usage reported by Proxmox.

Yes, I know I can disable the checks, but there is clearly an issue here that can be resolved in how measurements are collected. For comparison, I also run Beszel on my LXC instances, which reports a CPU usage much closer to "reality"—just a few percent."

**Comment by yubiuser** [comment] 2025-03-24 10:39
This seems to be related to https://github.com/pi-hole/FTL/issues/2324
