### ISSUE TITLE
Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf not found

### ISSUE THREAD

**Issue by BigBobDalton** [pi-hole/pi-hole#3277] opened 2020-04-16 10:07 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

`{A detailed description of what you expect to see}`

**Actual behaviour:**

`{A detailed description and/or screenshots of what you do see}`

**Steps to reproduce:**

`{Detailed steps of how we can reproduce this}`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment] 2020-04-16 17:18
The file does exist:
```plain
dschaper@Mariner-10:~$ curl -L https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

Check your `/etc/resolv.conf` to see if there is an accessible DNS server listed.

**Comment by webdevisme** [comment] 2020-04-18 08:28
Checked:
`# Generated by dhcpcd
# /etc/resolv.conf.head can replace this line
# /etc/resolv.conf.tail can replace this line`

What should this be?

I have the same problem as OP on my pi-zeroW running buster lite.

After running `curl -sSL https://install.pi-hole.net | bash`

**Comment by emostar** [comment] 2020-05-07 22:23
I am getting the same error.

However, when opening the URL on a web-browser, it redirects to an S3 URL, and I get a "SignatureDoesNotMatch" XML error (standard AWS S3 error page).

**Comment by emostar** [comment] 2020-05-07 22:32
For clarification, all the binaries on the page https://github.com/pi-hole/FTL/releases/tag/v4.3.1 result in the above mentioned AWS error message when opening them.

It is reproducible by just clicking the links.

**Comment by emostar** [comment] 2020-05-07 22:52
And it is fixed now. It seems that github releases had a site-wide error in rewriting the URL to S3.

**Comment by helo-head** [comment] 2020-05-10 20:32
Still broken as of 05/10/2020. I get the following when trying to install or update pi-hole

  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf not found
  [✗] FTL Engine not installed

**Comment by lucki1000** [comment] 2020-05-11 13:23
By me too

> 
> 
> Still broken as of 05/10/2020. I get the following when trying to install or update pi-hole
> 
> [✗] Downloading and Installing FTL
> Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf not found
> [✗] FTL Engine not installed

**Comment by thejford** [comment] 2020-05-11 14:07
Me too. 

"sudo apt-get update" works so it's not a DNS issue.

**Comment by vaaarg** [comment] 2020-05-12 09:33
me too

**Comment by thejford** [comment] 2020-05-12 11:32
> Me too. 
> 
> 
> 
> "sudo apt-get update" works so it's not a DNS issue. 

I was DNS for me.

**Comment by charliesz** [comment] 2020-05-12 12:38
So how to fix. Which address should be listed. For me it is my pis address and another one.

**Comment by HugooB** [comment] 2020-05-17 16:54
For some reason, performing an additional `sudo apt-get update` and `sudo apt-get upgrade` after the failed installation fixed the problem for me..

**Comment by dschaper** [comment] 2020-05-17 17:31
What would help the most is if we see the `curl` errors that are displayed. So far every report has been an issue with the OS and not with anything we can control.

```plain
  [i] Downloading and Installing FTL...curl: (60) SSL: no alternative certificate subject name matches target host name 'github.com'
More details here: https://curl.haxx.se/docs/sslcerts.html
```
That indicates a certificate error, either with GitHub or with the Certificate Authority (CA) files on the local device.

We've seen other errors that relate to SSL/TLS and errors that relate to DNS failures, but they almost all have been caused by the OS itself.

**Comment by charliesz** [comment] 2020-05-17 19:09
Maybe that helps?

>  [i] Latest FTL Binary already installed (v5.0). Confirming Checksum...
curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com
  [i] Corruption detected...
  [i] Downloading and Installing FTL...curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf not found
  [✗] FTL Engine not installed <

**Comment by dschaper** [comment] 2020-05-17 19:12
Yes, another example of the failure being from DNS.

`curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com`

Something is preventing `github-production-release-asset-2e65be.s3.amazonaws.com` from being resolved. If this is happening now, then please run `dig github-production-release-asset-2e65be.s3.amazonaws.com` on the Pi-hole command line.

**Comment by charliesz** [comment] 2020-05-17 21:07
> Yes, another example of the failure being from DNS.
> 
> `curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com`
> 
> Something is preventing `github-production-release-asset-2e65be.s3.amazonaws.com` from being resolved. If this is happening now, then please run `dig github-production-release-asset-2e65be.s3.amazonaws.com` on the Pi-hole command line.

```
~ $ dig github-production-release-asset-2e65be.s3.amazonaws.com

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> github-production-release-asset-2e65be.s3.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54040
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;github-production-release-asset-2e65be.s3.amazonaws.com. IN A

;; Query time: 14 msec
;; SERVER: 192.168.178.37#53(192.168.178.37)
;; WHEN: So Mai 17 22:53:50 CEST 2020
;; MSG SIZE  rcvd: 84
```

I'm affraid I don't understand the output. The ip address xxx.37 is the ip address of my pi.

**Comment by dschaper** [comment] 2020-05-17 21:16
You're missing an entire `Answer` section of the response. 

```plain
;; ANSWER SECTION:
github-production-release-asset-2e65be.s3.amazonaws.com. 1229 IN CNAME s3-1-w.amazonaws.com.
s3-1-w.amazonaws.com.   1       IN      A       52.216.89.148
```

I'm confused though, you said the update didn't work, and now you're saying you are running version 5? What versions do you have installed right now?

**Comment by charliesz** [comment] 2020-05-18 04:35
```
pi@raspberrypi:~ $ sudo dig github-production-release-asset-2e65be.
s3.amazonaws.com

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> github-production-release-as
set-2e65be.s3.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44486
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL:
1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;github-production-release-asset-2e65be.s3.amazonaws.com. IN A

;; Query time: 9 msec
;; SERVER: 192.168.178.37#53(192.168.178.37)
;; WHEN: Mo Mai 18 06:18:40 CEST 2020
;; MSG SIZE  rcvd: 84




──────────────────┤ Existing Install Detected! ├───────────────────


 We have detected an existing install.

 Please choose from the following options:
 (You will remain on the same version)

   Repair      This will retain existing settings
   Reconfigure This will reset your Pi-hole and allow you to ent







                 <Ok>                     <Abbrechen>

───────────────────────────────────────────────────────────────────




  [i] Repair option selected
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... 1 updates available
  [i] It is recommended to update your OS after installing the Pi-h
ole!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php7.3-common
  [✓] Checking for php7.3-cgi
  [✓] Checking for php7.3-sqlite3
  [✓] Checking for php7.3-xml
  [✓] Checking for php-intl

  [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [i] Latest FTL Binary already installed (v5.0). Confirming Checks
um...
curl: (6) Could not resolve host: github-production-release-asset-2
e65be.s3.amazonaws.com
  [i] Corruption detected...
  [i] Downloading and Installing FTL...curl: (6) Could not resolve
host: github-production-release-asset-2e65be.s3.amazonaws.com
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/downloa
d/pihole-FTL-arm-linux-gnueabihf not found
  [✗] FTL Engine not installed
```

I'm on v5.0 but it does not work. By trying some dubugging with `pihole -r` I endet up with this error. So I guessed that my problem has something to do with this thread, because I have the same error.

In the meanwhile I'm close to either reinstall pihole with hope that a clean installation wouldn't end up in the mess I have now or simply give up to save my time.

**Comment by dschaper** [comment] 2020-05-18 04:51
Do you have any kind of firewall configured? Something is truncating the DNS response at 512 bytes.

**Comment by dschaper** [comment] 2020-05-18 04:52
Please provide the output from `pihole -v`

**Comment by charliesz** [comment] 2020-05-18 10:11
```
pi@raspberrypi:~ $ pihole -v
  Pi-hole version is v5.0 (Latest: v5.0)
  AdminLTE version is v5.0 (Latest: v5.0)
  FTL version is v5.0 (Latest: v5.0)
```

but I'm struggeling with much bigger problems since I updated:

Log: 2gpg584e2u

**Comment by PromoFaux** [comment] 2020-05-18 10:14
>but I'm struggeling with much bigger problems since I updated:

This is likely the reason why:

```
[53] is in use by dnsmasq (https://discourse.pi-hole.net/t/hardware-software-requirements/273#ports)
```

do `sudo systemctl stop dnsmasq && sudo systemctl disable dnsmasq` and then restart the pi.

What is strange is that `dnsmasq` should have been disabled as part of the installation process. Did you enable/install it since installing Pi-hole?

Basically, `pihole-FTL` contains `dnsmasq` within it's code already, so it cannot run at the same time.

**Comment by charliesz** [comment] 2020-05-18 13:13
I don't want to waste more of your time. Thank you, but I will make a clean install of pihole tonight. I tried so many settings till now to solve my issue that it is not reproducable.
As far as I can tell pihole worked on v4 very good but with the update to v5 it got some problems maybe resulting on my bad settings.

**Comment by sam-wright** [comment] 2020-05-22 19:41
I'd like to second this issue. I have the same issue on a pi3 running plain debain10 (dedicated only to this). I've successfully updated to 5.0: 
```
$ pihole -v
  Pi-hole version is v5.0 (Latest: v5.0)
  AdminLTE version is v5.0 (Latest: v5.0)
  FTL version is v5.0 (Latest: v5.0)
```

and as a part of general system updates and maintenance I go to update with:
```
$ pihole -up
  [i] Checking for updates...
fatal: unable to access 'https://github.com/pi-hole/pi-hole.git/': Failed to connect to github.com port 443: Connection refused
  [i] Pi-hole Core:	up to date
fatal: unable to access 'https://github.com/pi-hole/AdminLTE.git/': Failed to connect to github.com port 443: Connection refused
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Existing PHP installation detected : PHP version 7.3.14-1~deb10u1
  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php7.3-common
  [✓] Checking for php7.3-cgi
  [✓] Checking for php7.3-sqlite3
  [✓] Checking for php7.3-xml
  [✓] Checking for php-intl

  [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (7) Failed to connect to github.com port 443: Connection refused
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf not found
  [✗] FTL Engine not installed

  Unable to complete update, please contact Pi-hole Support

```

**Comment by PromoFaux** [comment] 2020-05-22 19:48
> I've successfully updated to 5.0:

So...

> and as a part of general system updates and maintenance I go to update with:

Do you have something that is checking for updates? you might be hitting rate limits if so...

**Comment by sam-wright** [comment] 2020-05-22 19:50
No this is me manually running  less than once per week, perhaps once a month

**Comment by dschaper** [comment] 2020-05-22 19:52
I suggest not running `pihole -up` on any kind of automation or scheduling. You should have a notification when there is an update.

**Comment by dschaper** [comment] 2020-05-22 19:54
Can you run `curl -I https://github.com/pi-hole/pi-hole.git/` from the Pi-hole device command line and see if there is a response?

**Comment by sam-wright** [comment] 2020-05-22 19:54
```
$ curl -I https://github.com/pi-hole/pi-hole.git/
curl: (7) Failed to connect to github.com port 443: Connection refused
```

**Comment by sam-wright** [comment] 2020-05-22 19:56
hmm, something interesting however, when run through my laptop (on the same network):
```
curl -I https://github.com/pi-hole/pi-hole.git/                     Fri 22 May 2020 01:56:03 PM MDT
HTTP/1.1 301 Moved Permanently
date: Fri, 22 May 2020 19:55:20 GMT
content-type: text/html
content-length: 162
server: GitHub.com
location: https://github.com/pi-hole/pi-hole/
x-frame-options: DENY
vary: Accept-Encoding
Set-Cookie: _gh_sess=Gc0CRH4v5zSSG5eqQRRi3mVdNaGtdwDWz9fnVFnaHRHlt1w%2BU3vRQACd2gIZ5CEIvMRclaNnrqmjn%2FVa4QpPkJJGNoIYwCAwG9kWEmK7MBAgvckj05SaTxmC1IwG7GBTeTBn2p22itxDvkjVszQ65MTJ61ChdHPcC0P7FYl6XnGvqiasUeuLwE6RsasnRcRbB%2B86w0OepEIHV04rUEbOhWRdmrNcC1qdyAfpPNRWP5lKVbpLaGdhB5Q1vy1VNSYKhlLe8mPzyV99XQd2Sk78Cg%3D%3D--h1YZN0BSJJZ79My9--d9D6X6qBneAtoAduwV%2FawQ%3D%3D; Path=/; HttpOnly; Secure
Set-Cookie: _octo=GH1.1.780498204.1590177320; Path=/; Domain=github.com; Expires=Sat, 22 May 2021 19:55:20 GMT; Secure
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Sat, 22 May 2021 19:55:20 GMT; HttpOnly; Secure
X-GitHub-Request-Id: B3FE:4BB7:BE24:10E34:5EC82E28
```

**Comment by dschaper** [comment] 2020-05-22 19:56
Looks like you are indeed being blocked from GitHub. What is the IP address you get for github? `dig github.com @127.0.0.1`?

**Comment by sam-wright** [comment] 2020-05-22 19:58
(from pihole)
```
$ dig github.com @127.0.0.1

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Raspbian <<>> github.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1199
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;github.com.			IN	A

;; ANSWER SECTION:
github.com.		2	IN	A	0.0.0.0

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri May 22 13:57:12 MDT 2020
;; MSG SIZE  rcvd: 44
```

**Comment by dschaper** [comment] 2020-05-22 20:05
You have `github.com` on a blocklist.

**Comment by dschaper** [comment] 2020-05-22 20:06
`pihole -q -exact github.com`

**Comment by sam-wright** [comment] 2020-05-22 20:46
hmmm, interesting. I _think_ you're right:
```
$ pihole -q -exact github.com
 Exact matches for github.com found in:
  - https://easylist.to/easylist/fanboy-annoyance.txt
  - https://easylist.to/easylist/fanboy-annoyance.txt
  - https://easylist.to/easylist/fanboy-social.txt
```
Except that Im taking to you guys on github.com currently...

Also adding `www.github.com` to the whitelist had not effect

**Comment by sam-wright** [comment] 2020-05-22 20:47
hmm, i suspect I don't know how to configure this. I disabled pihole for 30 sec and the update ran just fine... Apparently I don't know how to whitelist items properly...

**Comment by PromoFaux** [comment] 2020-05-22 20:51
If I were you I would remove those lists, they are not in the correct format for pi-hole, they are designed for browser-based blockers.

@WaLLy3K has a version of the easylist formatted correctly:

https://v.firebog.net/hosts/Easylist.txt

**Comment by sam-wright** [comment] 2020-05-22 20:58
Thanks. I removed the old ones and replaced with your recommendation. It all works as intended now.

**Comment by starlord1980** [comment] 2020-09-18 14:42
This isnt solving it for me:
pi@raspberrypi:~ $ pihole -q -exact github.com
  [i] No exact results found for github.com within the block lists
pi@raspberrypi:~ $ pihole -up
  [i] Checking for updates...
fatal: unable to access 'https://github.com/pi-hole/pi-hole.git/': Couldn't connect to server
  [i] Pi-hole Core:	up to date
fatal: unable to access 'https://github.com/pi-hole/AdminLTE.git/': Couldn't connect to server

I realised I couldnt even ping 8.8.8.8

pi@raspberrypi:~ $ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.0.1.0        0.0.0.0         255.255.255.0   U     202    0        0 eth0

Gateway was the problem, it should be the address of the router so I added:
sudo route add default gw [THE_IP_OF_YOUR_ROUTER]

Now it works!
pi@raspberrypi:~ $ pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	update available
  [i] Web Interface:	update available
  [i] FTL:		update available

**Comment by summrum** [comment] 2020-11-29 16:45
I have this exact same issue, trying to update to FTL v5.3.1 from v5.2 today. The rest of my pihole update went without issue, but cannot update FTL with the phiole updater. It appears that [https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf](url) is not a valid address as of this post, as I can not ping/reach it from any of my devices. I am greeted with the github "this is not the page you are looking for" page not found no matter which device I use, and they all have no issues with internet access!

**Comment by dschaper** [comment] 2020-11-29 18:08
The file doesn't exist anymore. The binaries were renamed.

**Closed** 2020-11-29 18:08 UTC

**Comment by colejd** [comment] 2020-12-09 22:47
@dschaper does that mean Pi-hole needs an update, then? The file not being available means people can't repair or upgrade their Pi-hole installations.

**Comment by matchmee** [comment] 2020-12-19 21:03
If the file doesn't exist anymore, how are we supposed to update the FTL?

**Comment by dschaper** [comment] 2020-12-19 21:03
Run`pihole -up` and the new binaries will be chosen.

**Comment by matchmee** [comment] 2020-12-19 21:06
That is the command I am running (normally I add sudo before) and I am still getting the issue:

`pi@PiHole:~ $ pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u10
  [i] Performing unattended setup, no whiptail dialogs will be displayed

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for dnsutils

  [✓] Supported OS detected
  [i] SELinux not detected
  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for libcap2
  [✓] Checking for lighttpd
  [✓] Checking for php7.0-common
  [✓] Checking for php7.0-cgi
  [✓] Checking for php7.0-sqlite3
  [✓] Checking for php7.0-xml
  [✓] Checking for php7.0-json
  [✓] Checking for php7.0-intl

  [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected ARMv7 processor (with hard-float support)
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-armv7-linux-gnueabihf not found
  [✗] FTL Engine not installed

  Unable to complete update, please contact Pi-hole Support`

**Comment by summrum** [comment] 2020-12-19 21:06
Actually, that didn't work for me - hence the reason for me posting the issue after running "pihole -up". Perhaps I wasn't explicitly clear that that was the procedure I carried out. I had to install from source to circumvent the problem.

**Comment by summrum** [comment] 2020-12-19 21:07
@matchmee that is exactly what I saw. You could try compiling from source.

**Comment by dschaper** [comment] 2020-12-19 21:08
[i] Downloading and Installing FTL...curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com

Your issue isn't that the binary isn't there, it's that the domain is not being resolved. You may be blocking it or some other issue. 

What does `dig github-production-release-asset-2e65be.s3.amazonaws.com` show on the Pi-hole?

And you don't need to compile from source.

**Comment by summrum** [comment] 2020-12-19 21:10
Mine was telling me that the address https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf that I posted wasn't available, so that was what was being searched on my installation when running pihole -up.

**Comment by dschaper** [comment] 2020-12-19 21:10
Thanks, then you had a different issue. Please let me work with matchmee.

**Comment by matchmee** [comment] 2020-12-19 21:11
`; <<>> DiG 9.10.3-P4-Raspbian <<>> github-production-release-asset-2e65be.s3.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28418
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;github-production-release-asset-2e65be.s3.amazonaws.com. IN A

;; Query time: 40 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Dec 19 15:10:27 CST 2020
;; MSG SIZE  rcvd: 84`

**Comment by dschaper** [comment] 2020-12-19 21:12
That domain should return as a CNAME, try `dig github-production-release-asset-2e65be.s3.amazonaws.com @8.8.8.8` on the Pi-hole.

**Comment by matchmee** [comment] 2020-12-19 21:13
`; <<>> DiG 9.10.3-P4-Raspbian <<>> github-production-release-asset-2e65be.s3.amazonaws.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44010
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;github-production-release-asset-2e65be.s3.amazonaws.com. IN A

;; ANSWER SECTION:
github-production-release-asset-2e65be.s3.amazonaws.com. 21444 IN CNAME	s3-1-w.amazonaws.com.
s3-1-w.amazonaws.com.	4	IN	A	52.217.99.60

;; Query time: 24 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Dec 19 15:12:58 CST 2020
;; MSG SIZE  rcvd: 121`

**Comment by dschaper** [comment] 2020-12-19 21:16
Okay, something on your local resolver is not returning a valid IP. Try editing your `/etc/resolv.conf` file and changing `127.0.0.1` to a public DNS like `8.8.8.8` or `1.1.1.1` and then do a `pihole -up`.

**Comment by gnat79** [comment] 2021-04-29 01:31
I had basically this same error. After some poking around, I found out that my Raspberry Pi 4 had only set 1M for /tmp, which wasn't enough for the install. I got the error with curl (23) which is:

**23     Write error. Curl couldn't write data to a local filesystem or similar.**

I changed (somewhat aggressively) the amount of disk allocated for /tmp to 1G instead of 1M, rebooted, and restarted. Subsequently the install went just fine. (sudo vim /etc/fstab)

I have questions:
1. How much space should I have for /tmp on a raspberry pi?
2. Is it the standard practice to put all these files in /tmp before install? Updating the os doesn't have issues, so it must cache downloaded files somewhere else on disk.
3. This seems like a preventable error with Pi-Hole; perhaps a more user friendly warning could be emitted? Or use a different method to download the file? I am using "stock" raspbian, I believe, so this is probably a common situation, if I had to guess.

I would appreciate any helpful comments or corrections! Thanks!

**Comment by dschaper** [comment] 2021-04-29 02:23
>     1. How much space should I have for /tmp on a raspberry pi?

Stock Raspbian doesn't have a separate partition for `/tmp`.

**Comment by dschaper** [comment] 2021-04-29 02:30
> I had basically this same error.

Can you share exactly what the error message was that you saw? 'URL not found' isn't something that one would see with the condition you are describing.

**Comment by gnat79** [comment] 2021-04-29 11:54
In retrospect, my issue seems different than this topic. My error was specifically that the curl command failed while fetching this file, which is what brought me to this issue via web search.

I do not have the specific errors from the failed process, but if it's useful enough, I could replicate the error by changing /tmp back to 1M and going through the install process again. Just let me know, I'll be happy to do it, and apologies for gettin' off topic / any confusion :-)

**Comment by Makeshift** [comment] 2021-06-03 20:37
Obviously this is way late, but for anybody still coming across this issue, in my case the `/etc/ssl/certs/ca-certificates.crt` file had somehow become empty, which was causing `curl` to fail to download.

The fix for this was to reinstall the `ca-certificates` package like so:

```
sudo apt install ca-certificates --reinstall
```

**Comment by jfb-pihole** [comment] 2021-06-03 22:13
Thanks for closing the loop on this.

**Comment by SamboMambo** [comment] 2021-09-03 20:13
@Makeshift hi, I have the same issue as all the above, and when I try to reinstall ca-certificates I get 

`E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by jfb-pihole** [comment] 2021-09-04 00:20
`maybe run apt-get update or try with --fix-missing?`

What happened when you ran those commands?

**Comment by DrBillyG** [comment] 2021-10-24 00:26
Had the same issue, apt-get update, upgrade as well as a lot of insturctions i read haven't helped.
I've been running dietpi, didn't think of doing a dietpi update first, after this, rebooting the pi, pihole -up worked, no issues at all.
