### ISSUE TITLE
Getting "curl: (7) Couldn't connect to server" while testing.

### ISSUE THREAD

**Issue by PhantomGhost** [pi-hole/pi-hole#396] opened 2016-03-23 19:30 UTC
I was testing a new install of Pi-Hole, just wanted to make sure all was working well, and I got to this step:
From one of your devices configured to use the Pi-hole, run this command:

curl -I doubleclick.com

this should return the header from the Pi-hole Web server, which contains a line like this:

HTTP/1.1 200 OK
X-Pi-hole: A black hole for Internet advertisements.
Expires: Sat, 10 Oct 2015 22:16:58 GMT
Cache-Control: max-age=86400
Content-Type: text/html
Accept-Ranges: bytes
ETag: "831319033"
Last-Modified: Sat, 03 Oct 2015 16:56:15 GMT
Content-Length: 49
Date: Fri, 09 Oct 2015 22:16:58 GMT
Server: lighttpd/1.4.35

The line above should be returned when you curl any ad-serving domain that is on /etc/pihole/gravity.list.  If you see the X-Pi-hole header, then it is working.  You could use any domain on your list for this test, a-ads.com is just any easy one to remember.  Now, if you look on your Raspberry Pi, you should see an entry that your computer made a request for a-ads.com, which tells you name resolution is working and your Pi is responding to requests.

Well when I do that, all I get is this:
curl -I doubleclick.com
curl: (7) Couldn't connect to server

Other than that, it seems to be working, but I was wondering what was causing that to happen? This was a fresh install of Raspbian on a Pi 2, and then using the automated install for Pi-Hole. There were no issues during the install. I have pfsense as my router, with all of its DNS servers removed except for the Pi. Thanks for any help!

**Comment by nate-ubiquisoft** [comment] 2016-03-23 23:38
@PhantomGhost could you do me a favor and do the following:
`wget https://raw.githubusercontent.com/nate-ubiquisoft/pi-hole/master/advanced/Scripts/piholeDebug.sh` (This will get my *hopefully* soon to be merged debugging script for PiHole)
`chmod +x piholeDebug.sh`
Then run `./piholeDebug.sh` and try to load doubleclick.com in your browser while the script is running. After the page loads/doesnt load, follow the script instructions to quit debugging. `/var/log/pihole_debug.log` will then need to be attached as a response to this thread so I can take a look at what is going on.

**Comment by PhantomGhost** [comment] 2016-03-24 00:51
Here you go. When trying to browse to doubleclick.com, I just get the usual page not found error. Looking in that log, it looks like its catching it, just...not redirecting to the web server? Kinda looks like its just dropping the connection all together. 
[pihole_debug.txt](https://github.com/pi-hole/pi-hole/files/187088/pihole_debug.txt)

**Comment by nate-ubiquisoft** [comment] 2016-03-24 04:20
I see here that you dont have a valid adlist file.
`############### adlists.list ###############
No adlists.list file found!
`
I suspect this might be what the root cause of your issue may be. Run the installer script, `curl -L install.pi-hole.net | bash`, and it will update. Check the installer log file to see if it had any issue connecting to the adlists.list sources.
And as always, make sure to `sudo apt-get update
sudo apt-get upgrade`!

**Comment by Mcat12** [comment] 2016-03-24 04:31
That actually is the default behavior. adlist.default stores the default lists, with adlist.list being the custom lists. That file is not created by default, hence the file missing error.

**Comment by nate-ubiquisoft** [comment] 2016-03-24 04:48
Oh right I confused that with gravity.list, my bad. 
@PhantomGhost, what is the output of `hostname`? Have you changed the default one on your system? Your /etc/hosts file shows it as raspberrypi.

**Comment by PhantomGhost** [comment] 2016-03-24 12:31
I hadn't before, kinda forgot to, I normally use DHCP for everything and just reserve the IP, but Pi-Hole forced me to use static, after I did that, I reserved it anyway and changed the host name on my pfsense DNS for it, but never changed the actual host name. I just changed it to match (in /etc/hostname and /etc/hosts), and also did an update, but still have the same problem.

**Comment by PromoFaux** [comment] 2016-03-24 13:45
Hmm, that's interesting.

@PhantomGhost  Try this:

Add the line `ad blocked by pi-hole!` (or something similar) to the `<body>` element in  `/var/www/html/pihole/index.html`

Then, on your client machine, navigate to `http://doubclick.com` in your browser. If everything is working correctly, you will see `ad blocked by pi-hole!`

**Comment by PhantomGhost** [comment] 2016-03-24 14:36
Nope, I still get a page cannot be displayed message, specifically "ERR_NAME_NOT_RESOLVED" in Chrome. The Pi is catching it, but not redirecting like it should be. I did try navigating straight to the Pi's web server, just to make sure its working, and I get a white page with the message I added to the body of index.html, so it looks like the web server is functioning fine, just something is failing in the redirect.

**Comment by PromoFaux** [comment] 2016-03-24 14:48
OK, could you paste the output of `cat /etc/lighttpd/lighttpd.conf` please.

**Comment by PhantomGhost** [comment] 2016-03-24 14:50
I was just looking through that file...

`pi@Pi-Hole:~ $ cat /etc/lighttpd/lighttpd.conf
# Pi-hole: A black hole for Internet advertisements
# (c) 2015, 2016 by Jacob Salmela
# Network-wide ad blocking via your Raspberry Pi
# http://pi-hole.net
# lighttpd config for Pi-hole
#
# Pi-hole is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

server.modules = (
	"mod_access",
	"mod_accesslog",
	"mod_expire",
	"mod_compress",
 	"mod_redirect",
	"mod_setenv",
	"mod_rewrite"
)

server.document-root        = "/var/www/html"
server.error-handler-404	= "pihole/index.html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename			= "/var/log/lighttpd/access.log"
accesslog.format			= "%{%s}t|%V|%r|%s|%b"


index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"

# If the URL starts with /admin, it is the Web interface
$HTTP["url"] =~ "^/admin/" {
	# Create a response header for debugging using curl -I
	setenv.add-response-header = ( "X-Pi-hole" => "The Pi-hole Web interface is working!" )
}

# If the URL does not start with /admin, then it is a query for an ad domain
$HTTP["url"] =~ "^(?!/admin)/.*" {
	# Create a response header for debugging using curl -I
	setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
}`

**Comment by PromoFaux** [comment] 2016-03-24 14:55
OK, that looks OK. I'll get back to scratching my head...

**Comment by PhantomGhost** [comment] 2016-03-24 15:34
Should I just try wiping the Pi and starting fresh? I mean I don't know what could have caused it to fail, but if it normally works fine for everyone else, maybe something got screwed up in the install and I never noticed an error message...

**Comment by PromoFaux** [comment] 2016-03-24 15:38
If it's not too much trouble, it's always worth a shot! If it still happens, then we can rule out the pi-hole and maybe troubleshoot other aspects of your network.

**Comment by nate-ubiquisoft** [comment] 2016-03-24 15:58
Are you running the full Raspbian install or the lite? I am using the lite
simply because it is easy to flash repeatedly if necessary. Apt-get for the
win.

**Comment by PhantomGhost** [comment] 2016-03-24 16:04
Actually I am on the lite, are there any other packages I need to install before I install Pi-Hole on the lite image? I didn't even think about that.

**Comment by Mcat12** [comment] 2016-03-24 16:06
Nope, just remember to expand root.

**Comment by PromoFaux** [comment] 2016-03-24 16:11
@PhantomGhost The install script takes care of any dependant packages it needs, so once you've flashed the SD card, make sure the first thing you do is run `raspi-config` to expand the filesystem/change the password etc.

**Comment by nate-ubiquisoft** [comment] 2016-03-24 16:30
Also make sure to run sudo apt-get update and sudo apt-get upgrade after
expanding the fs and before installing pihole to ensure you are up to date.
Also, if you change your hostname, make sure to do it with hostname-ctl
set-hostname <newhostname> then also vim /etc/hosts and
:%s/raspberrypi/<newhostname/g to replace the old hostname with your new
one and reboot.

**Comment by PromoFaux** [comment] 2016-03-24 16:33
>make sure to run sudo apt-get update

Taken care of by the install script! Which also advises on whether or not to run `apt-get upgrade` (though in the case of a fresh install, it certainly will need to run!) But yeah, that was implemented in case people forgot to run `apt-get update`

**Comment by nate-ubiquisoft** [comment] 2016-03-24 16:41
Yea I saw that when I was going though the install script however it simply
checks for updates but doesnt apply them, rather it prompts the user to run
it after installation but making sure all core packages are up-to-date
before install can rule out any system package issues causing an
installation problem with PiHole.
On another note, if you are reinstalling PiHole on a device that already
had it installed and you remove it with the uninstall.sh script, it will
cause a resintall to act like an update rather than a full reinstall
because /etc/pihole/ isn't removed correctly with the uninstall.sh.

**Comment by PromoFaux** [comment] 2016-03-24 16:42
You know, thinking about that. I'm not sure why the script doesn't exit there and advise user to run upgrade. There were issues with just running upgrade at that point in the script, which is why it's an advise for the user to run it manually.

**Comment by PhantomGhost** [comment] 2016-03-24 16:52
Alright, freshly imaged the Pi with raspbian lite, after first boot I expanded the file system, changed password and hostname (all using raspi-config), rebooted, ran apt-get update and upgrade (only found 2 packages to upgrade). Now I'm trying the Pi-Hole install again. So lets see what happens. (Note: Remember to change DNS server back to a public one before taking down the Pi-Hole...)

**Comment by nate-ubiquisoft** [comment] 2016-03-24 17:08
Are you using ipv4 and ipv6 blocking? Can you hit the admin page? @PhantomGhost

**Comment by PhantomGhost** [comment] 2016-03-24 17:37
Just ipv4, I don't use ipv6 on my network at all, its disabled. And yes, admin page works just fine. I can see it updating and showing ads being blocked.

**Comment by nate-ubiquisoft** [comment] 2016-03-24 17:45
@PhantomGhost can you paste the pihole_debug.log file?

**Comment by PhantomGhost** [comment] 2016-03-24 18:11
[pihole_debug.txt](https://github.com/pi-hole/pi-hole/files/188377/pihole_debug.txt)

There you go.

**Comment by nate-ubiquisoft** [comment] 2016-03-24 18:17
@PhantomGhost Thanks! What is the output of `hostname` on your system?

**Comment by PhantomGhost** [comment] 2016-03-24 18:17
pi@Pi-Hole:/var/log $ hostname
Pi-Hole

**Comment by dschaper** [comment] 2016-03-24 18:18
Does the debug log grab the configuration of `/etc/dnsmasq.d/01-pihole.conf`?

**Comment by nate-ubiquisoft** [comment] 2016-03-24 18:19
@PhantomGhost How are you setting 172.21.1.29 as the IP of Pi-Hole? Is it a static IP setup on Pi-Hole or a DHCP allocation from your router? If DHCP, is it a permanent allocation (i.e. is the DHCP locked for this Pi-Hole)?

**Comment by dschaper** [comment] 2016-03-24 18:19
Sorry, didn't see that it was below the pull of the log. Should probably adjust that...

**Comment by PhantomGhost** [comment] 2016-03-24 18:21
@nate-ubiquisoft It is both, actually. Reserved on the router (outside the DHCP pool) and also set statically on the Pi. Its reserved by Mac, so the new install pulled the same IP as last time, and I told the Pi-Hole installer to use that as the static IP.

**Comment by nate-ubiquisoft** [comment] 2016-03-24 18:29
@dschaper I will rearrange the logging to put that up with the dnsmasq.conf file. I also have added additional logging for system settings but have not commited them yet as I want to test them when I get home tonight.

**Comment by nate-ubiquisoft** [comment] 2016-03-24 18:30
@PhantomGhost Okay hmm... I was thinking that another device on your network might have the same IP which would could consume the forwarding request rather than the pihole lighttpd.

**Comment by nate-ubiquisoft** [comment] 2016-03-24 18:31
@dschaper I also have the logging removing all comments from the config files to make it a little smaller debug.log file as well as making it easier to read through quickly.

**Comment by PhantomGhost** [comment] 2016-03-24 18:32
@nate-ubiquisoft Nope, there's nothing else with that IP, and the logs show the Pi is receiving the request, it just isn't redirecting it...

**Comment by PhantomGhost** [comment] 2016-03-24 18:51
Alright, do any of your guys use pfsense? I'm just looking around trying to figure this out, and on pfsense is a dnslookup lookup diagnostic page...and that works. If I look up doubleclick.com from that page, it returns with the Pi's address. So...if the router can get the redirected IP, why wouldn't the clients get that?

**Comment by dschaper** [comment] 2016-03-24 18:54
Actually in the middle of installing a PFSense box at a client location right now. (Though we probably are going to pull and go RouterOS and dedicate Microtik hardware in a bit...) Can you dig/drill from the CLI on the PFSense box and get back the Pi address?

**Comment by nate-ubiquisoft** [comment] 2016-03-24 18:55
@PhantomGhost Run the following and paste the output here.
`nslookup doubleclick.com`
`nslookup doubleclick.com 8.8.8.8`
This will do the nslookup from your local machine against your local DNS (Pi-Hole) and against Google's nameservers.

**Comment by PhantomGhost** [comment] 2016-03-24 19:00
Alright, well, that got an interesting result. Below is what Windows returns. Linux and OS X both return "Can't find doubleclick.com: No answer"

H:\>nslookup doubleclick.com
Server:  ghostnet.main.ghost.local
Address:  172.21.1.1

Name:    doubleclick.com
Address:  2607:f8b0:4002:802::200e


H:\>nslookup doubleclick.com 8.8.8.8
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Non-authoritative answer:
Name:    doubleclick.com
Addresses:  2607:f8b0:4002:c03::8b
          74.205.129.34
          74.205.129.38
          74.205.129.30
          74.205.129.49
          74.205.129.15
          74.205.129.44
          74.205.129.57
          74.205.129.45
          74.205.129.27
          74.205.129.29
          74.205.129.53
          74.205.129.19
          74.205.129.23
          74.205.129.59
          74.205.129.42

**Comment by nate-ubiquisoft** [comment] 2016-03-24 19:11
@PhantomGhost Ahhhh that helps A LOT! (That is going to be added to my debug script in a future release #394) I see that your `nslookup doubleclick.com` against your DNS returns only the ipv6 address, not the ipv4. As well, it seems to be using 172.21.1.1 as your DNS, not 172.21.1.29 as your Pi-Hole is configured to use. That would make sense if you are setting it on your router which I am assuming to be 172.21.1.1 however your router may also be trying to handle DNS requests separately. Can you do one more `nslookup doubleclick.com 172.21.1.29`? This will tell me what the Pi-Hole is directly resolving.

**Comment by PhantomGhost** [comment] 2016-03-24 19:12
Alright, well, believe I figured it out...turns out it was pfsense the whole time. Sorry guys, and thanks for all the help! In the future though, if someone else has this problem, have them look for a setting similar to:
Disable DNS Rebinding Checks
And turn that on (which disables it). That setting has this description:
"When this is unchecked, your system is protected against DNS Rebinding attacks. This blocks private IP responses from your configured DNS servers. Check this box to disable this protection if it interferes with webConfigurator access or name resolution in your environment."

Now both curl and nslookup return the Pi's address, and browsing to an ad domain site redirects like it should...gah...of course it has to be something stupid.

**Comment by dschaper** [comment] 2016-03-24 19:14
Yeah, Rebind will bite you in the backside everytime... Thanks for pointing out that PFSense does a reverse on the toggle for rebinds... May need to add that to the FAQs...

**Comment by PhantomGhost** [comment] 2016-03-24 19:16
Yeah, and its defaults to on (well, unchecked), so anyone that sets this up with pfsense will have issues! 

I really appreciate everyones help by the way, thanks a lot!

**Comment by nate-ubiquisoft** [comment] 2016-03-24 19:16
Good catch @PhantomGhost! I am going to add a check for pfsense installation to the installer script and set that flag to ON if it is installed.

**Comment by nate-ubiquisoft** [comment] 2016-03-24 19:20
@PhantomGhost Good catch!

**Comment by PhantomGhost** [comment] 2016-03-24 19:26
@nate-ubiquisoft One quick question if you don't mind though, and this should be an easy one...how can I get the admin console to display local times instead of UTC?

**Comment by PromoFaux** [comment] 2016-03-24 19:28
Of course it was remind protection!!  Can't believe none of us thought if that,  it's come up before!

**Comment by nate-ubiquisoft** [comment] 2016-03-24 19:39
@PhantomGhost Do you have your Pi-Hole set to your timezone? `sudo raspi-config` under Localization has an option to set your timezone. Reboot your Pi after just to ensure the change is applied.

**Comment by PhantomGhost** [comment] 2016-03-24 19:46
@nate-ubiquisoft Tried that first...its set correctly, but the graph on the admin console is still UTC...

**Comment by PromoFaux** [comment] 2016-03-24 20:35
Err,  that should have been fixed a while back...  Do the dates and times look OK in pihole.log?

**Comment by PhantomGhost** [comment] 2016-03-24 21:04
It gets corrected half way through the log, when I changed the timezone.

**Comment by PromoFaux** [comment] 2016-03-24 21:23
Ah! OK, that might be the source of this issue. Flush the logs (`piholeLogFlush.sh`) and wait for it to build up again

**Comment by PromoFaux** [comment] 2016-03-24 21:47
Closing this for now, feel free to continue discussion.

**Closed by PromoFaux** 2016-03-24 21:47 UTC
Labels: External issue

**Comment by ggrats** [comment] 2016-07-04 01:32
I wanted to add Tomato & Tomato USB & Shibby's Tomato USB also do the same.
it's url for you router: /advanced-dhcpdns.asp
-> advanced -> DHCP/DNS

"Prevent DNS-rebind attacks" is on by default, disable it

thanks to this thread I found out the issue, after about 10 hours of messing around (though I reconfigured nginx and put pihole as a virtual server during this time too)

**Comment by dschaper** [comment] 2016-07-04 02:10
Glad you found a solution, and if you'd like to share the Nginx config files I'm sure there are other users who would like to see them.

**Comment by ggrats** [comment] 2016-07-04 04:02
@dschaper sure man 

I just have a variant of something like this:
https://github.com/pi-hole/pi-hole/wiki/Nginx-configuration-instead-of-the-default-lighttpd-and-php-cgi-option
here is my first vserver that handles all the DNS: I explain my rewrites for you guys down there, it was just an example but I don't think it should be done. however even with them nginx still responds in almost half the time lighttpd does.

```
    server {
        listen 80 default_server;
        server_name _;
        index index.html index.php;
        root /var/www/html;
        autoindex off;
        expires max;
        rewrite .+?(png|gif|jpe?g)$ /imgreqs last;
        rewrite ^(.*)$ / last;
        
        location / {
            return 204;
        }
        
        location /imgreqs {
            empty_gif;
        }

        error_page 404 /404.html;
    }

```
the main difference is I have many more things running on it, majority of my house is automated (all of my lights, garage, hot tub, pool etc) 

I just did the:
nano /etc/dnsmasq.d/01-pihole.conf 

and added

```
address=/pihole.grats/192.168.1.165
address=/movies.grats/192.168.1.189
address=/lights.grats/192.168.1.165
```

here's 3 examples the key here is we treat the admin page and pi dns dump separately.. I threw in some rewrites on the first server chunk so people can see how to treat images and pages separately when it comes to ads
even with the rewrites nginx processes and returns data before lighttpd even processes it.. no offense, lighttpd has **always** been garbage. 

my first chunk is the catch all for the dns
I throw in 404 catches for all of them just cuz. take note all 3 of mine in the first server chunk are just empty_gif instead of return 204 && /404.html

second chunk is the pihole admin page supplied, though it seems to be parsing all of the data instead of processing what's needed and concatenating the new data which I'll change later.
then the admin page has it's own dns as "pihole.grats" maybe for everybody it should be pihole.admin? or whatever.

and the last chunk is my light system which are all my home lights, they're all 3 way (wall switch + relay) so you can turn them on/off with a switch or your phone or computer etc.. it's self explanatory
I kept the pihole in it's directories I assume it'll be updated in the same space so I just left it there

as far as web serving goes I found this to be the best for speed, of course we're only talking fractions of milliseconds but I like it the slight speed boost and organization. there's no reason to load php or anything really for the return of the DNS
I'd just send a "empty_gif" 
http://nginx.org/en/docs/http/ngx_http_empty_gif_module.html

for everything that has to do with the default server. because as somewhere on the pi hole site it says the javascript that loads the ads blocks you a lot of the time you don't even see you index.html for the pi hole "ad blocked by pi hole" or whatever you have..
and in the future we'll probably see wayyyyyyy less of it, I hit a couple hundred sites with the default curl install of pihole with an altered index.html and saw no-where it popped up so I don't even care to see it if it ever does
originally I would have hijacked the DNS of all the ads and replaced it with dank memes

```

#user  nobody;
worker_processes  1;
error_log  /home/web/logs/error.log;

events {
    worker_connections  1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    add_header "X-UA-Compatible" "IE=Edge,chrome=1";
    access_log off;
    sendfile on;
    client_header_timeout 15s;
    keepalive_timeout 45s;
    gzip on;
    gzip_comp_level 6;
    gzip_proxied any;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/javascript application/x-javascript;
    gzip_buffers 16 8k;
    server_tokens off;

    server {
        listen 80 default_server;
        server_name _;
        index index.html index.php;
        root /var/www/html;
        autoindex off;
        expires max;
        rewrite .+?(png|gif|jpe?g)$ /imgreqs last;
        rewrite ^(.*)$ / last;
        
        location / {
            return 204;
        }
        
        location /imgreqs {
            empty_gif;
        }

        error_page 404 /404.html;
    }

    server {
        listen  80;
        server_name pihole.grats;
        error_log /home/web/logs/pihole_error.log;
        root /var/www/html/admin;
        location / {
            index index.php index.html;
            auth_basic "Restricted";
            auth_basic_user_file /opt/nginx/.htpasswd;
        }

        location ~ \.php$ {
            fastcgi_index index.php;
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_pass unix:/tmp/phpfpm.sock;
        }
        error_page 404 /404.html;
    }

    server {
        listen   80;
        server_name lights.grats;
        error_log /home/web/logs/lights_error.log;
        root   /home/web/public/lights/;
        
        location / {
            index i.php;
        }

        location ~ \.php$ {
            fastcgi_index index.php;
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_pass unix:/tmp/phpfpm.sock;
        }
        error_page 404 /404.html;
    }
}
`
```
