### ISSUE TITLE
[i18n] Multi-language interface

### ISSUE THREAD

**Issue by Quenty31** [pi-hole/pi-hole#2802] opened 2019-06-16 12:46 UTC
Hello,
I have done some searches but it seems like it's not currently possible to have a different language set.
That's why I open this issue, to add the possibility to translate the interface in other languages.

**Comment by DL6ER** [comment] 2019-06-16 12:52
Duplicate of #2228

The current web interface is coming to an end. Its successor has already been translated into a number of languages, see here: https://crowdin.com/project/pi-hole

**Closed by DL6ER** 2019-06-16 12:52 UTC

**Comment by Quenty31** [comment] 2019-06-21 12:19
Hello @DL6ER ! How to add Occitan to the language list on Crowdin?
Best regards

**Comment by DL6ER** [comment] 2019-06-21 15:24
@Quenty31 We have to approve that we want it. I did that now.
Happy translating :-)

**Comment by Quenty31** [comment] 2019-06-23 10:51
Occitan translation done! Many thanks @DL6ER !

**Comment by Fruity-0** [comment] 2021-03-23 03:26
Do the languages ​​on the Crowdin website support the Wep interface? There are many languages ​​on the website because the website (PHP) of Pi-Hole Administration is only in English.
