### ISSUE TITLE
binary files in gravity.list

### ISSUE THREAD

**Issue by tuplink** [pi-hole/pi-hole#816] opened 2016-10-20 00:38 UTC
some times gravity.list will end up being truncated. with a binary file matches error.    i belive this to be due to https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt.    taking the output file from that list  tells me its gzipped      i belive the solution to this is adding --compressed to curl   not sure if it hurts to do this on all of the lists but adding    
            "ransomwaretracker.abuse.ch")
                cmd_ext="--compressed"
            ;;
in gravity_spinup semes to have cured this but only time will tell as this is a random error

**Comment by dschaper** [comment] 2016-10-20 02:17
I've been running that on a loop to curl the file once every 30 seconds and I've always received txt. How did you determine that it was a gz file? `type`?

**Comment by tuplink** [comment] 2016-10-20 02:23
file list.8*

**Comment by dschaper** [comment] 2016-10-20 02:25
I'm just not able to reproduce the situation. Possibly one of the other team members can. You're just `curl`ing that file, correct?

**Comment by tuplink** [comment] 2016-10-20 02:29
using gravity

**Comment by tuplink** [comment] 2016-10-20 02:30
trying to get the file off my vm at the moment to atach

**Comment by tuplink** [comment] 2016-10-20 02:35
fe80::a00:27ff:fecb:896e engine.letsstat.nl
192.168.0.107 Binary file /etc/pihole/list.preEventHorizon matches
fe80::a00:27ff:fecb:896e Binary file /etc/pihole/list.preEventHorizon matches

ubuntu@ubuntu:/etc/pihole$ file list.8.ransomwaretracker.abuse.ch.domains
list.8.ransomwaretracker.abuse.ch.domains: gzip compressed data, from Unix


had to zip it
[list.8.ransomwaretracker.abuse.ch.zip](https://github.com/pi-hole/pi-hole/files/540679/list.8.ransomwaretracker.abuse.ch.zip)

**Comment by dschaper** [comment] 2016-10-20 02:36
Okay, lets bring in the rest of the team.

**Comment by tuplink** [comment] 2016-10-20 02:38
as i said in my op adding 
"ransomwaretracker.abuse.ch")
cmd_ext="--compressed"
;;
in the case statment in gravity_spinup semes to stop it

rm /etc/pihole/list.8.ransomwaretracker.abuse.ch.domains ; sudo pihole -g ; tail /etc/pihole/gravity.list
is how i was testing it

**Comment by dschaper** [comment] 2016-10-20 02:40
I've seen that `Binary file` bug before, a week or so ago. What version of Pi-hole CORE are you running?

**Comment by tuplink** [comment] 2016-10-20 02:40
from the curl manpage
            --compressed
              (HTTP)  Request  a compressed response using one of the algorithms curl supports, and save the uncompressed
              document.  If this option is used and the server sends an unsupported encoding, curl will report an error.

so i wouldnt add it as a default option

**Comment by dschaper** [comment] 2016-10-20 02:41
Agreed, that would toss an error.

**Comment by tuplink** [comment] 2016-10-20 02:45
i tried calling 
if [[ $(file ${patternBuffer} | cut -f2 -d":") != " ASCII text"* ]] ; then
  something to redownload
fi
but ${patternBuffer} isnt always set

**Comment by tuplink** [comment] 2016-10-20 02:50
list.5.s3.amazonaws.com.domains returns    ASCII text, with CRLF line terminators all the rest return ASCII text except for ransomwaretracker.abuse.ch and sometimes is right

**Comment by dschaper** [comment] 2016-10-20 02:51
If you take a text file and gzip it, then run `head file.gz` you should see the gzip text header with some internal information. Try it with any text file and see what a gzip structure looks like, that may give you something to trigger on. As to line endings, we're not that concerned, we can handle that in a parser if needed.

**Comment by tuplink** [comment] 2016-10-20 02:59
gunzip /etc/pihole/list.8.ransomwaretracker.abuse.ch.domains
gzip: /etc/pihole/list.8.ransomwaretracker.abuse.ch.domains: unknown suffix -- ignored

so guess it get corupted somehow

**Comment by dschaper** [comment] 2016-10-20 03:05
```
dan.schaper@tyson:~$ touch sample.txt
dan.schaper@tyson:~$ nano sample.txt
dan.schaper@tyson:~$ cat samplet.txt
dan.schaper@tyson:~$ cat sample.txt
This is some sample text
dan.schaper@tyson:~$ gzip sample.txt
dan.schaper@tyson:~$ ls -lac
total 84
drwxr-xr-x  13 dan.schaper dan.schaper  4096 Oct 20 03:00 .
drwxr-xr-x   4 root        root         4096 Oct 18 04:47 ..
-rw-rw-r--   1 dan.schaper dan.schaper    54 Oct 20 03:00 sample.txt.gz
dan.schaper@tyson:~$ cat sample.txt.gz                                                                                                                                                 2Xsample.txt
           ▒▒,V▒▒▒▒T▒▒▒܂▒T▒▒Ԋ.▒sH
dan.schaper@tyson:~$ gunzip sample.txt.gz
dan.schaper@tyson:~$ ls
sample.txt
dan.schaper@tyson:~$ cat sample.txt
This is some sample text
```

**Comment by dschaper** [comment] 2016-10-20 03:07
What you don't see it that the head of the file is
```
dan.schaper@tyson:~$ cat sample.txt.gz                                                                                                                                                 2Xsample.txt
```

**Comment by dschaper** [comment] 2016-10-20 03:08
So the file name is stored in plain text as the first line of the file (along with the magic number of 2X which is a signal to the zipper what kind of compression was used.)

**Comment by tuplink** [comment] 2016-10-20 03:10
head on the file returns 襾▒▒▒y&▒▒X▒▒▒@▒N9j▒▒▒▒▒▒▒▒y?▒r)▒y▒▒▒▒;▒!▒Ի▒:▒@▒▒݈▒y▒R▒▒▒o▒=A▒o▒▒▒▒қ▒▒▒▒▒▒

**Comment by dschaper** [comment] 2016-10-20 03:11
That's unicode, there's some kind of corruption going on or they are sending the file with high bit Unicode characters, may be time to pull that from the supplied lists...

**Comment by dschaper** [comment] 2016-10-20 03:14
Okay, that list isn't an ad block, it's a ransomware block, which I personally feel is out of scope for the Pi-hole. Needs to be pulled from default. Will open PR.

**Comment by tuplink** [comment] 2016-10-20 03:15
ive don i=0 ;while true ; echo $i; do rm /etc/pihole/list.8.ransomwaretracker.abuse.ch.domains ; sudo pihole -g > /dev/null; file /etc/pihole/list.* ; let i+=1; done     with my modified spinup and its been good 50 times      i uncomment it and it takes about 6 times to break

**Comment by tuplink** [comment] 2016-10-20 03:16
eather way a simple fix

**Closed** 2016-10-20 09:41 UTC
Labels: Discussion, In progress, Possible Bug
