### ISSUE TITLE
Pi-Hole does not route DNS queries after restart

### ISSUE THREAD

**Issue by OfficialMuffin** [pi-hole/pi-hole#3108] opened 2020-01-29 21:27 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Pi-Hole to route all DNS requests through the raspberry pi via ethernet. Everything works until a restart.`

**Actual behaviour:**

`When the pi has been restarted, DNS queries no longer get passed through. Errors when visiting sites in firefox. "Problem loading page"`
`The admin page does not load`

**Steps to reproduce:**

`Install Pi-Hole with the recommended settings. Nothing is user specified`

**Temporary Fix Issue:**

`Reinstall PiHole with the same settings as previous installation`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/2r1ukcipkf`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `Reinstalled PiHole'
> * `Flush DNS cache on PC and restart`
> * `Used another browser`

**Comment by dschaper** [comment] 2020-01-29 21:32
The debug looks fine. What URL are you using for the admin page? Are you able to `ping` the Pi-hole device when the issue is happening?

**Comment by OfficialMuffin** [comment] 2020-01-29 21:41
I am using `http://<IP ADDRESS>/admin`
Pings are successful and SSH login is still working fine.

**Comment by dschaper** [comment] 2020-01-29 21:51
Check both of those when DNS queries are failing.

**Comment by OfficialMuffin** [comment] 2020-02-01 22:00
Yes, I checked these. Pings are working fine.
Just the admin page does not work at all.

**Comment by dschaper** [comment] 2020-02-02 01:41
We'll need a debug log when there is a problem. The log provided has expired and did not show any issues.

**Comment by phenomeus** [comment] 2020-02-19 08:11
oh nice, I have exactly the same problem! see here https://github.com/pi-hole/pi-hole/issues/2898#issuecomment-586634585

todays post over there: 
i still have the same problem, and I noticed that when I do pihole -r and the 2nd option "reconfigure" its not working UNTIL I confirm the question about "firewall rules installation" appears and its continuing to install.

I compared the installed ufw rules before and after the reconfiguration and there where no difference.

also I noticed that only localhost AND wireguard clients were able to be recognized and filtered after a reboot and before the reconfiguration. anything else on the local net is blocked and therefore "offline"

(Tenda mesh cube tells me that its offline with a red LED and I also know that Tenda is calling home a lot, this is filtered with pihole so I know that its not working and I have the problem to reconfigure after reboot)

**Comment by dschaper** [comment] 2020-02-19 08:12
>We'll need a debug log when there is a problem.

**Comment by phenomeus** [comment] 2020-02-19 08:41
@dschaper of course, here you go

fresh after reboot:
https://tricorder.pi-hole.net/m3nv5o78lz 

after pihole -r, 2nd option reconfigure:
https://tricorder.pi-hole.net/x0cqlyay6z

`  [✓] Installing new IPTables firewall rulesets`
> between this two lines the queries are working again 
`  [✓] man pages installed and database updated`

**Comment by dschaper** [comment] 2020-02-19 16:03
Fresh after reboot, everything is working:

```text
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] www.linkfame.com is 0.0.0.0 via localhost (127.0.0.1)
[✓] www.linkfame.com is 0.0.0.0 via Pi-hole (192.168.1.10)
[✓] doubleclick.com is 172.217.23.14 via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
[✓] banerator.net is :: via localhost (::1)
[✓] banerator.net is :: via Pi-hole (2a01:c22:7250:bd01:350c:c3ad:12b1:94b9)
[✓] doubleclick.com is 2a00:1450:4016:800::200e via a remote, public DNS server (2001:4860:4860::8888)
```

After `pihole -r`, everything is still working:

```text
*** [ DIAGNOSING ]: Name resolution (IPv4) using a random blocked domain and a known ad-serving domain
[✓] stats.thoughtcatalog.com is 0.0.0.0 via localhost (127.0.0.1)
[✓] stats.thoughtcatalog.com is 0.0.0.0 via Pi-hole (192.168.1.10)
[✓] doubleclick.com is 172.217.23.14 via a remote, public DNS server (8.8.8.8)

*** [ DIAGNOSING ]: Name resolution (IPv6) using a random blocked domain and a known ad-serving domain
[✓] wsqrylku0ztgwhkg.trade is :: via localhost (::1)
[✓] wsqrylku0ztgwhkg.trade is :: via Pi-hole (2a01:c22:7250:bd01:350c:c3ad:12b1:94b9)
[✓] doubleclick.com is 2a00:1450:4016:800::200e via a remote, public DNS server (2001:4860:4860::8888)
```

What settings do you have for the interface? Are you listening on all interfaces?

**Comment by phenomeus** [comment] 2020-02-19 16:10
yes I listen on all interfaces because of wireguard setup

**Comment by phenomeus** [comment] 2020-02-19 16:12
is it the `ufw` firewall?

**Comment by dschaper** [comment] 2020-02-19 16:14
I don't know. The Pi-hole seems to be working just fine so the situation is caused by something outside of Pi-hole.

**Comment by dschaper** [comment] 2020-02-19 16:15
You're not using the unbound upstream.

```text
    PIHOLE_DNS_1=84.200.69.80
    PIHOLE_DNS_2=84.200.70.40
```

**Comment by dschaper** [comment] 2020-02-19 16:18
And just for information, you have issue with your regex filters:

```text
[2020-02-19 09:37:12.371 1004] ERROR compiling regex on line 1: Invalid preceding regular expression (13)
```

**Comment by phenomeus** [comment] 2020-02-20 05:04
maybe I debuged this time before I edited to my unbound again. something I have to adjust every time after reboot because of pihole -r

so no luck :( is it because its starting to "fast" before a network connection is established and its not listening on eth0 properly? some thoughts from my other thread, that's maybe the reason because wireguard and localhost have no issues

**Comment by Roki100** [comment] 2020-03-18 17:08
i have similar issue, and my pihole starts working after i change dns servers to ones that i never used then i just change it back and it works

**Comment by scyto** [comment] 2020-03-24 20:35
Interesting thread, for months i have had issue where suddenly one day my pihole stops resolving certain domains.  Usually bing is the first one to go (which is my default search engine).  I have been running with blocking off since it last happened.  Today i had it again.  Restarting the resolver always fixes (i note this flushes the cache) (so does changing custom DNS servers.  I had this om multiple versions too.

Either it was because in the custom I had loop back of 127.0.0.1 in addition to the custom internal forwarder or there is some other underlying issue with the cache.  I note while having the name resolution issue in all my browser the pio logs indicated it was serving out of the cache to me.

Next time it happens i will do packet sniff to see what I am actually getting back from the pihole (if anything) and then report back.

**Comment by Rancheroo** [comment] 2020-04-10 12:37
I have the same issue with DNS resolution failing after restart.
Restarting DNS makes it all come to life. Cant see anything in the logs. Happy to provide and/or test

  Pi-hole version is v4.4 (Latest: v4.4)
  AdminLTE version is v4.3.3 (Latest: v4.3.3)
  FTL version is v4.3.1 (Latest: v4.3.1)

I have has this issue since fresh install on Raspberry Pi 3

**Comment by Rancheroo** [comment] 2020-04-15 10:27
Thinking proper systemd startup would help this issue.
https://github.com/pi-hole/pi-hole/issues/2924

**Comment by Rancheroo** [comment] 2020-04-15 10:37
Hackjob workaround is to put a sleep in the start service section, this fixes the issue for me, however it is not really checking for a result, merely allowing more time for dependent services to come up.

```
# Start the service
start() {
  if is_running; then
    echo "pihole-FTL is already running"
  else
    # Touch files to ensure they exist (create if non-existing, preserve if existing)
    sleep 60
    touch /var/log/pihole-FTL.log /var/log/pihole.log
    touch /run/pihole-FTL.pid /run/pihole-FTL.port
    touch /etc/pihole/dhcp.leases
    mkdir -p /var/run/pihole
```

**Comment by yubiuser** [comment] 2020-04-15 10:42
With v5.0 there is a option to delay startup of FTL:
https://discourse.pi-hole.net/t/add-option-to-delay-pihole-startup-to-set-up-wireguard-interfaces-before-correctly/29715

**Comment by clh360** [comment] 2020-06-25 23:27
Hello, I was having similar issues, after a reboot network devices couldn't load webpages. as soon as I opened pihole admin page on the pi everything started working again.
This seemed to fix what I was experiencing.
sudo raspi-config
go to boot options,
enable "wait for network at boot"
Maybe this will help.

**Comment by amphore728** [comment] 2020-08-16 04:54
hello guys.
I have the same issue and I need to manually run the command `pihole restartdns` after each reboot to make it work. I found some post on reddit about dnsmask issue but the fix seem not to work on raspbian (people who fixed it this way was running ubuntu) it should be the same tho or maybe im wrong.

I suspect this happening after installing PiVPN but im not sure yet.

**Comment by yubiuser** [comment] 2020-08-16 06:36
> since I suspect pivpn.
https://github.com/pivpn/pivpn/issues/946

**Comment by SpawnTerror** [comment] 2020-12-24 10:16
It's still not fixed. What a useless piece of software.

**Comment by PromoFaux** [comment] 2020-12-24 10:30
What specifically are you saying is still not fixed?

**Comment by SpawnTerror** [comment] 2020-12-24 12:21
The issue this topic is about.

**Comment by PromoFaux** [comment] 2020-12-24 12:25
Did you try the linked topic with the `DELAY_STARTUP` option in FTL? https://github.com/pi-hole/FTL/pull/716

**Comment by dschaper** [comment] 2020-12-24 17:50
> It's still not fixed. What a useless piece of software.

Funny, I was going to say the same about your comment.

**Comment by immae1** [comment] 2021-03-06 15:29
same issue here - after reboot dns resolving doesn't work on a fresh pihole installation raspberry pi 3 
The hack with sleep added mentioned earlier in this post worked. But useing sleep is not really the smartest way ...  Anyone have a better solution?

**Comment by yubiuser** [comment] 2021-08-12 19:50
I'm closing this issue since the OP did not interact since one year. If the issue persists, please open a new ticket or look for help on https://discourse.pi-hole.net/

**Closed by yubiuser** 2021-08-12 19:50 UTC
Labels: triage: Issue

**Comment by sfthink** [comment] 2022-01-09 13:55
> Hello, I was having similar issues, after a reboot network devices couldn't load webpages. as soon as I opened pihole admin page on the pi everything started working again. This seemed to fix what I was experiencing. sudo raspi-config go to boot options, enable "wait for network at boot" Maybe this will help.

This problem is still present on
`$ pihole -v
  Pi-hole version is v5.8.1 (Latest: v5.8.1)
  AdminLTE version is v5.10.1 (Latest: v5.10.1)
  FTL version is v5.13 (Latest: v5.13)`
and can be circumvented on newer raspberries by
`sudo raspi-config nonint do_boot_wait 0`

**Comment by kevin-king** [comment] 2022-02-11 14:33
Running into the same issue on:
```
pihole -v
  Current Pi-hole version is v5.8.1
  Current AdminLTE version is v5.10.1
  Current FTL version is v5.13
```

Raspberry Pi 4B

I've tried the following each individually as well as all at the same time:
1. Added `@reboot pihole restartdns` to `crontab -e`
2. Added `DELAY_STARTUP=30` to `/etc/pihole/pihole-FTL.conf`
3. Set `Network at Boot` to `Yes` in `sudo raspi-config`

Manually running `pihole restartdns` or "Restart DNS resolver" from the admin panel works as mentioned above. I also use a local upstream unbound recursive dns server on 127.0.0.1#5335. Configuration is verbatim as is described [here](https://docs.pi-hole.net/guides/dns/unbound/). pihole is set as the DHCP server and everything works perfectly once DNS is manually restarted after boot.

**Comment by kevin-king** [comment] 2022-03-05 12:47
I think I found a solution to my own issue at least. I had DNSSEC enabled both on the pihole and on the upstream Unbound DNS server. After disabling pihole-level DNSSEC all of my weird restart issues went away. Note that this makes validating your upstream DNS server's DNSSEC all the more important:

```
dig sigfail.verteiltesysteme.net @127.0.0.1 -p 5335     Should give SERVFAIL
dig sigok.verteiltesysteme.net @127.0.0.1 -p 5335      Should give NOERROR
```

Hope that helps others.
