### ISSUE TITLE
Inclusivity in strings

### ISSUE THREAD

**Issue by sidprax** [pi-hole/pi-hole#5022] opened 2022-11-16 18:44 UTC
Change "Whitelist" and "Blacklist" to Allow and Deny lists instead.

PS. I know this riles up some people, but please keep the comments civil 👍

**Comment by yubiuser** [comment] 2022-11-16 18:47
Duplicate of https://github.com/pi-hole/AdminLTE/issues/2137

**Closed by yubiuser** 2022-11-16 18:47 UTC

**Comment by dschaper** [comment] 2022-11-16 19:28
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
