### ISSUE TITLE
Problems with adblock

### ISSUE THREAD

**Issue by Potterli20** [pi-hole/pi-hole#5282] opened 2023-05-21 14:23 UTC
### Screenshots

![mmexport1684678777483.png](https://github.com/pi-hole/pi-hole/assets/28734349/e3231588-1bc9-4d2a-bda9-10bf7ff103a9)

### Additional context

Can this adblock problem be solved?
At the same time this adblock link can be solved?
https://github.com/Potterli20/file/blob/main/ad-hosts/adblock

**Comment by rdwebdesign** [comment] 2023-05-21 16:54
Can you please explain?

You posted part of the output of `gravity.sh`, but there are no error messages.
What is exactly the problem you see here?

**Comment by jfb-pihole** [comment] 2023-05-21 17:04
We don't understand the problem you are trying to solve. Are you trying to import and adlist and it isn't importing?

Please post the full (and complete, unredacted, etc) output of the following command :

`pihole -g -f`

**Comment by yubiuser** [comment] 2023-05-22 04:17
It's still not clear what the problem is ...

**Comment by yubiuser** [comment] 2023-05-22 04:59
https://github.com/pi-hole/pi-hole/blob/d885e92674e8d8d9a673b35ae706b2c49ea05840/gravity.sh#L554

**Comment by TheNec** [comment] 2023-05-22 12:32
> ### Screenshots
> 
> removed
> ### Additional context

First adlist 2 possibilities:
1. Ask the creator to remove at least the asterisks and/or dots from the entries: *.domain.tld -> domain.tld or .domain.tld 
2. Feature request for pi-hole autocleaning when importing

Second adlist
> https://github.com/pi-hole/pi-hole/blob/d885e92674e8d8d9a673b35ae706b2c49ea05840/gravity.sh#L554
DNS specifications say that every character is supported - except for separation . (dots) of course so I don't see why it shouldn't be supported in pi-hole. I think the problem is the uncommon - (dash) . (dot) combination. Maybe a dnsmasq limitation. =)

> Can this adblock problem be solved? At the same time this adblock link can be solved? https://github.com/Potterli20/file/blob/main/ad-hosts/adblock

For this list you need a browser addon or maybe a proxy server :)

**Comment by TheNec** [comment] 2023-05-22 13:53
> Alas, pihole is to support adblock, but to change manually, if it can be changed to online update, it is also perfect, of course I know there is adgh this thing, but he can't use the 200m rule

Please try to use https://www.deepl.com/translator if possible or try a better translator. I'm out =)

> This problem is just to solve the random domain name above the second-level domain name, because I don't know what the domain name is, I caught it but it changed after a while, this is irritating work. So use the number as a substitute for the domain name that adapts.

Again two possibilities:
1. Manually add regex filters
2. FReq pi-hole: Use regex parser in list and auto add to manual list
3. FReq pi-hole: Add importing regex adblock block and go lists. I second this =)

**Comment by TheNec** [comment] 2023-05-24 11:27
> After internal discussion we agreed to loose the requirements for "valid domains" a bit. We will allow underscores and hyphens in all positions of the (sub)domain (not TLD). While such domains might be not 100% compatible with RFCs, they are used in the wild to serve (ad)content and we decided to allow blocking of such domains. This is implemented with [pi-hole/FTL#1563](https://github.com/pi-hole/FTL/pull/1563) and will likely be part of the next Pi-hole release.

Are you sure? In the last years I have read many many theoratical stuff about DNS including RFCs. As far as I know - as I wrote before - DNS can and should handly any character and always when I read about underscores and hyphens limitations of hostnames come to my mind and that many people mix up rules for domains and hostnames.

Here a snippet from another guy thinking in the same direction:

> Ausgeschnitten aus: https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it
>
>Most answers given here are false. It is perfectly legal to have an underscore in a domain name. Let me quote the standard, [RFC >2181, section 11, "Name syntax"](https://tools.ietf.org/html/rfc2181#section-11):
	The DNS itself places only one restriction on the particular labels that can be used to identify resource records. That one restriction relates to the length of the label and the full name. [...] Implementations of the DNS protocols must not place any restrictions on the labels that can be used. In particular, DNS servers must not refuse to serve a zone because it contains labels that might not be acceptable to some DNS client programs.

>See also the original DNS specification, [RFC 1034](http://www.ietf.org/rfc/rfc1034.txt), section 3.5 "Preferred name syntax" but read it carefully.
Domains with underscores are very common in the wild. Check _jabber._tcp.gmail.com or _sip._udp.apnic.net.
Other RFC mentioned here deal with different things. The original question was for domain names. If the question is for host names (or for URLs, which include a host name), then this is different, the relevant standard is [RFC 1123](http://www.ietf.org/rfc/rfc1123.txt), section 2.1 "Host Names and Numbers" which limits host names to letters-digits-hyphen.

A good solution or suggestion for this would be to take this for differentiating between real (internal) hostnames = hostnames and some kind of external hostname = part of a domain.

_jabber._tcp.gmail.com looks like a hostname.domain composition but it's not the hostname of the server itself it's a name for a service and router thing that forwards to the real host(name). Sorry I hope you understand what I try to express =)

**Comment by yubiuser** [comment] 2023-05-24 11:55
I know this thread and the distinction between hostnames and domains and DNS lables. However, the RFCs I found regarding the naming schema contradict each other. While 2181 states

> The DNS itself places only one restriction on the particular labels
   that can be used to identify resource records.  That one restriction
   relates to the length of the label and the full name.
   
1035 limites he lables to what is allowed for hostnames

> The labels must follow the rules for ARPANET host names.  They must
start with a letter, end with a letter or digit, and have as interior
characters only letters, digits, and hyphen.  There are also some
restrictions on the length.  Labels must be 63 characters or less.

__

Even putting the limitations of 1035 aside: is Pi-hole dealing with domain as identifier of a resource in a DNS database or with hostnames (as in special type of domain name which identifies Internet hosts) (see https://stackoverflow.com/a/14622263). I think this is the place where it gets complicated: domains (no limitation on lables) are used as hosts for content (label restrictions). 
___

> A good solution or suggestion for this would be to take this for differentiating between real (internal) hostnames = hostnames and some kind of external hostname = part of a domain.

> _jabber._tcp.gmail.com looks like a hostname.domain composition but it's not the hostname of the server itself it's a name for a service and router thing that forwards to the real host(name)s. Sorry I hope you understand what I try to express =)

I'm not sure what you exactly propose Pi-hole should do. How should we differentiate this? The only other solution we thought of was to allow everything to be added to the gravity database and only apply the lenght restriction filter.

**Comment by TheNec** [comment] 2023-05-24 13:17
> I know this thread ... While 2181 states
> 
> > [stuff]
> 
> 1035 limites the lables to what is allowed for hostnames
> 
> > [more stuff]

You are right!

The problem is that 2181 is absolute (and newer!) and 1035 is relative (and updated through the first) except for the arpanet part. Second says preferred (bevorzugt), "avoid problems with old software" and "syntax for fewer problems" (at or before november 1987!). The rules are followed by the last sentence that gives an example for identifying **_hosts_** on the internet. That's what I was trying to say: Nowadays there are mostly no hosts directly connected to the internet. It's all about domain labels without the host part. And even if there are still some - pi-hole doesn't need to deal with that from a content blocker perspective!

> 
> __
> 
> [even more stuff answered by above paragraph I think]

---

> 
> I'm not sure what you exactly propose Pi-hole should do. How should we differentiate this? The only other solution we thought of was to allow everything to be added to the gravity database and only apply the lenght restriction filter.

Yep :)

So much words from me for a very easy thing:

pi-hole Domains/Adlists: max63octets.max63octets.max63octets... with no rules except max255octets including dots and root dot
pi-hole Local DNS/CNAME: HOSTNAME.domain.domain.... with hostname rules for the hostname part and above domain rules

While this would be the best solution to cover any future DNS case this wouldn't solve the OPs asterisk problem from the first adlist examples and maybe this needs a warning message that this would not work... (Only for asterisks should be enough maybe)

As I wrote before those need to be cleaned by someone before importing or added to a new "regex" list that pi-hole can't handle (at the moment). Don't say it too loud but this may be a discussable feature request =)

**Comment by yubiuser** [comment] 2023-05-28 19:59
Fixed with https://github.com/pi-hole/FTL/releases/tag/v5.23

**Closed by yubiuser** 2023-05-28 19:59 UTC
Labels: Fixed in next release
