### ISSUE TITLE
Installer OS check broken if ns1.pi-hole.net is unreachable

### ISSUE THREAD

**Issue by niklasea** [pi-hole/pi-hole#3694] opened 2020-08-16 22:46 UTC
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  N/A
- FTL:  N/A

### Platform

- OS and version:  Debian 10

- Platform:  x86_64 VM

### Expected behavior

I expect the installer to successfully detect my system as supported.

### Actual behavior / bug

The installer attempts to make a DNS query to an external server which is blocked by my network firewall. Since that query fails, the installer incorrectly reports that the system is unsupported.

```
  [✗] Unsupported OS detected: Ubuntu 20.04 LTS
```

### Steps to reproduce

1. Block outbound DNS on port 53
2. Run installer
3. See error

### Workaround

Run with `PIHOLE_SKIP_OS_CHECK=true`.

Though I see why `ns1.pi-hole.net` is used, the installer does in fact work if I edit it to query the system DNS server instead.

### Additional context

The issue was introduced in commit https://github.com/pi-hole/pi-hole/commit/0ff32c3629220f386a45c14d8982aaaf128aa47f.

I understand that this is not a standard configuration and that `PIHOLE_SKIP_OS_CHECK=true` is a viable workaround, but I think the OS check could be improved upon. Personally, I would prefer it failed open since the installation will fail on unsupported systems regardless, but you could also use a fallback list if failing open is a problem.
This issue also means that all installations will fail if `ns1.pi-hole.net` is down despite said server not serving any meaningful purpose in the installation process.

```
  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Update local cache of available packages
  [i] Update option selected
  [✓] Disk space check

  [✗] Checking apt-get for upgraded packages
      Kernel update detected. If the install fails, please reboot and try again
  [i] Installer Dependency checks...
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail
  [✓] Checking for dnsutils

DEBUG: detected_os_pretty = Ubuntu 20.04 LTS
DEBUG: detected_os = Ubuntu
DEBUG: detected_version = 20.04

DEBUG: os_part = ;;
DEBUG: versions_part = ;;
DEBUG: os_part = connection
DEBUG: versions_part = connection
DEBUG: os_part = timed
DEBUG: versions_part = timed
DEBUG: os_part = out;
DEBUG: versions_part = out;
DEBUG: os_part = no
DEBUG: versions_part = no
DEBUG: os_part = servers
DEBUG: versions_part = servers
DEBUG: os_part = could
DEBUG: versions_part = could
DEBUG: os_part = be
DEBUG: versions_part = be
DEBUG: os_part = reached
DEBUG: versions_part = reached
DEBUG: valid_os = false, valid_version = false

  [✗] Unsupported OS detected: Ubuntu 20.04 LTS
      https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems

      e.g: If you are seeing this message on a fresh install, you can run:
             'curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash'

           If you are seeing this message after having run pihole -up:
             'PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r'
           (In this case, your previous run of pihole -up will have already updated the local repository)

      If that is the case, you can feel free to ask the community on Discourse with the Community Help category:
      https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/
```

**Comment by dschaper** [comment] 2020-08-16 22:51
No one way will ever be the best. We added the `@ns1` because local servers on networks with AD DNS would fail.

If you know enough to block DNS 53 then you know enough on how to get around the issue.

**Comment by niklasea** [comment] 2020-08-16 22:52
Why should it fail closed?

**Comment by dschaper** [comment] 2020-08-16 22:53
Why shouldn't it?

**Comment by dschaper** [comment] 2020-08-16 22:53
Big warnings are just ignored. We provide you with the exact directions to install anyways so use them.

**Comment by niklasea** [comment] 2020-08-16 22:55
The error message is wrong as well. Why not check for a successful `dig` response and give a more meaningful error?

**Comment by dschaper** [comment] 2020-08-16 22:56
How is the error message wrong?

**Comment by niklasea** [comment] 2020-08-16 22:58
The system is supported

Distribution | Release | Architecture
-- | -- | --
Ubuntu | 16.x / 18.x / 20.x | ARM / x86_64

yet the error message is `  [✗] Unsupported OS detected: Ubuntu 20.04 LTS`

**Comment by dschaper** [comment] 2020-08-16 22:59
Your configuration is unsupported. You have been provided with the exact instructions on how to proceed and install Pi-hole on your customized OS. Use them.

**Comment by niklasea** [comment] 2020-08-16 23:00
Would you accept a pull request?

**Comment by dschaper** [comment] 2020-08-16 23:00
Of course.

**Comment by dschaper** [comment] 2020-08-16 23:02
Just be sure you use `development` branch as your base and also base any PRs against `development`. We do not accept PRs against `master`.

There is also a PR open that addresses some changes in `os_check()` function.

**Comment by niklasea** [comment] 2020-08-20 01:37
Beyond changing the error message, you could remove your dependency on `ns1.pi-hole.net` by using the list of supported OSs [on GitHub](https://github.com/pi-hole/pi-hole/blob/master/supportedos.txt), GitHub being a hard dependency for the installer anyway.

**Comment by dschaper** [comment] 2020-08-20 01:48
There's a reason we don't.

**Comment by Shnoobins** [comment] 2020-08-25 19:56
As another user who just ran into this EXACT thing, I have to agree with niklasea. Having a hard dependency on reaching a certain name server is not great, but beyond that the error message is completely wrong. 

If there is nothing changed on a fresh install of <supported OS> but it still fails the version check because of a network firewall blocking access to that name server or outbound access on port 53 for some reason, it would be far more helpful to return an error that says "Can't reach name server ns1.pi-hole.net to verify OS compatibility" or similar. 

To that end, several comments on other issues suggest running "dig +short -t txt versions.pi-hole.net" as a test. In my environment, that passes just fine, because it follows my typical DNS configuration, which is NOT accessing ns1.pi-hole.net directly on port 53 from the VM that is being setup. In reality the command should be "dig +short -t txt versions.pi-hole.net @ns1.pi-hole.net" which would return a failure in the scenario listed in the original report. 

None the less I look forward to the day that the branch is merged with the changes niklasea is working on.

**Comment by yippieskippie24** [comment] 2020-08-25 20:12
I actually also ran into this issue. I have port 53 blocked outbound on my firewall because of DNS-over-HTTPS.  But because of the error displayed in the script I just assumed it was incorrectly identifying the OS that I was trying to install it on (Ubuntu 20.04). Nothing about the error indicated a DNS issue and I didn't think to check that initially.  I only stumbled upon this because a friend of mine found it when he encountered the same issue. 

I do agree that big warnings are typically ignored... but misleading or incomplete error messages definitely don't help.

**Comment by dschaper** [comment] 2020-08-25 20:19
There's a fix already merged in to development, but thank you for your comments.

**Comment by PromoFaux** [comment] 2020-08-26 08:43
Example outputs in `development`: 

Blank response
![image](https://user-images.githubusercontent.com/1998970/90975670-4e1cfb80-e52e-11ea-9337-d71181d54d35.png)

`dig` returns non-zero
![image](https://user-images.githubusercontent.com/1998970/90975675-583efa00-e52e-11ea-8fd8-125da5b394ed.png)

Debug info:
![image](https://user-images.githubusercontent.com/1998970/90975686-73116e80-e52e-11ea-813c-cc10982a3e5c.png)

Full error output:
![image](https://user-images.githubusercontent.com/1998970/90975705-94725a80-e52e-11ea-80be-bef677d99102.png)

**Comment by yubiuser** [comment] 2021-08-10 19:13
Closing the issue.

If `ns1@pi-hole.net` is not reachable the installation fails by design. A PR with more detailed explanation why it is failinf was already published.

**Closed by yubiuser** 2021-08-10 19:13 UTC
