### ISSUE TITLE
When deleting a local DNS record, a longer record might also be deleted

### ISSUE THREAD

**Issue by fdahlgren** [pi-hole/pi-hole#4193] opened 2021-06-06 22:22 UTC
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.5
- FTL:  5.8.1

### Platform

- OS and version:  Ubuntu 18.04

- Platform:  VM

### Expected behavior

Under local DNS, when deleting a domain that is a partial match with a longer domain and shares the same IP, it should only delete the intended domain.

### Actual behavior / bug

Both the domain you chose to delete and the longer domain is deleted.

### Steps to reproduce

1. Go to Local DNS / DNS Records
2. Add two domains (test.co, test.com) with the same IP address (1.2.3.4, 1.2.3.4)
3. Delete test.co
4. Both test.co and test.com are deleted

**Comment by yubiuser** [comment] 2021-06-07 04:26
Duplicate of https://github.com/pi-hole/AdminLTE/issues/1811

**Closed by yubiuser** 2021-06-07 04:26 UTC
