### ISSUE TITLE
Dashboard Query Type to Recent Queries displaying incorrect filter on logs.

### ISSUE THREAD

**Issue by HalfBit-hacks** [pi-hole/pi-hole#3642] opened 2020-08-02 17:19 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behavior:**

Dashboard Query Types pie graph should go to Recent Queries logs based on the record type clicked in the list

**Actual behavior:**

The Recent Queries log filter is off. If I click TXT, the filter shows whatever is above the clicked item in the list.

**Steps to reproduce:**

Dashboard > Query Types > Click on Query type in list which then goes to Recent Queries log search.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Let me know if this is necessary, but I don't think it is.

**Troubleshooting undertaken, and/or other relevant information:**

Not sure how to fix. When you click on a record type, it displays the record type above the one clicked.

> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by yubiuser** [comment] 2020-08-02 18:29
Thanks for reporting. Duplicate of https://github.com/pi-hole/AdminLTE/issues/1508

**Closed by yubiuser** 2020-08-02 18:29 UTC
Labels: Duplicate
