### ISSUE TITLE
Command `pihole -w` fails inside a v6 container.

### ISSUE THREAD

**Issue by rdwebdesign** [pi-hole/pi-hole#5528] opened 2023-12-29 18:14 UTC
As title says, using the command line to run `pihole -w example.com` inside a v6 container will result in an error message:

```console
# pihole -w example.com
grep: unrecognized option: P
BusyBox v1.36.1 (2023-11-07 18:53:09 UTC) multi-call binary.
(...)
```

We have 2 options:
1. change the code in Core to use a different `grep` option (or use some other program to execute the regex) or;
2. add `grep` to the [install command](https://github.com/pi-hole/docker-pi-hole/blob/174a39facd054eb4c33a96458136c251a6b5c67d/src/Dockerfile#L15-L35) in the docker image .

**Comment by yubiuser** [comment] 2023-12-29 18:17
Duplicate of https://github.com/pi-hole/pi-hole/issues/5458

Best solution is probably the use of FTL's new API and no direct database interaction.

**Closed by yubiuser** 2023-12-29 18:17 UTC
Labels: Pi-hole v6.0
