### ISSUE TITLE
/etc/pihole/setupVars.conf is missing.

### ISSUE THREAD

**Issue by Illustratum** [pi-hole/pi-hole#1111] opened 2017-01-07 18:06 UTC
/etc/pihole/setupVars.conf is missing no matter what i try!

All scripts download curled and what not!

Still its broken.

You broke something. something got broken. and something won't be fixed with pihole -rsjhbjslfk not one single thing works.

You broke something.

**Comment by Illustratum** [comment] 2017-01-07 18:11
pi@raspberrypi:/etc/.pihole/automated install $ sudo ./basic-install.sh 
:::
::: You are root.
::: Verifying free disk space...
:::
::: Updating local cache of available packages... done!
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 230 updates available for your system!
::: We recommend you update your OS after installing Pi-Hole! 
:::
:::    Checking for apt-utils... installed!
:::    Checking for debconf... installed!
:::    Checking for dhcpcd5... installed!
:::    Checking for git... installed!
:::    Checking for whiptail... installed!
:::
::: Checking for existing repository...
:::    Updating repo in /etc/.pihole... done!
:::
::: Checking for existing repository...
:::    Updating repo in /var/www/html/admin... done!
:::
::: Stopping dnsmasq service... done.
:::
::: Stopping lighttpd service... done.
::: Using OpenDNS servers.
::: Your static IPv4 address:    192.168.3.1
::: Your static IPv4 gateway:    192.168.1.1
::: Static IP already configured
::: IPv4 address: 192.168.3.1
::: IPv6 address: 
::: Logging On.
:::    Checking for bc... installed!
:::    Checking for cron... installed!
:::    Checking for curl... installed!
:::    Checking for dnsmasq... installed!
:::    Checking for dnsutils... installed!
:::    Checking for iproute2... installed!
:::    Checking for iputils-ping... installed!
:::    Checking for lighttpd... installed!
:::    Checking for lsof... installed!
:::    Checking for netcat... installed!
:::    Checking for php5-common... installed!
:::    Checking for php5-cgi... installed!
:::    Checking for sudo... installed!
:::    Checking for unzip... installed!
:::    Checking for wget... installed!
::: Checking if user 'pihole' exists...
::: User 'pihole' already exists
:::
::: Installing scripts from /etc/.pihole... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
sed: -e expression #1, char 12: unterminated `s' command
grep: /etc/pihole/setupVars.conf: No such file or directory
::: Restarting services...
:::
::: Starting dnsmasq service...pi@raspberrypi:/etc/.pihole/automated install $ 

And my dnsmasq.d/01 config is destroyed. and internet drops out....GOOD WORK! :)

**Comment by Illustratum** [comment] 2017-01-07 18:12
sed: -e expression #1, char 12: unterminated `s' command
grep: /etc/pihole/setupVars.conf: No such file or directory

Is your problem.

**Comment by PromoFaux** [comment] 2017-01-07 19:00
Please ensure you follow the [issue template](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md) when submitting a new issue. It's there to help us to help you!

Seriously, be constructive and we might stand a better chance of resolving your issue.

**Comment by Mcat12** [comment] 2017-01-07 19:00
Please settle down. We can't help you unless you help us. Please get a debug token via `pihole -d` so that we can help you fix this.

**Comment by dschaper** [comment] 2017-01-08 01:03
My collegues are way nicer than I am, changed topic and steering conversation to the direction grown adults use when discussing issues.

**Comment by trick77** [comment] 2017-01-08 07:29
Actually, I saw the same problem on an Ubuntu 16.04 server yesterday. The variable that should habe been replaced with sed was empty, leading to the error posted above.

**Comment by trick77** [comment] 2017-01-08 09:21
https://github.com/pi-hole/pi-hole/pull/1113

**Comment by Illustratum** [comment] 2017-01-08 12:19
pihole -d same output like everything else.
Fresh install 5 times.

Still same error. :)

Seriously, be better than this and we might stand a better chance of using this kiddie script again.

Are you triggered by words?

I get triggered by bad coding.

**Comment by Illustratum** [comment] 2017-01-08 12:31
Yes the same thing with no explanation happens over and over again.

Telling me to to do a pihole -d and everything else is doing the exact same thing. it crashes over and over again.

Hard to understand?

**Comment by Illustratum** [comment] 2017-01-08 13:40
Ran the command curl -L https://install.pi-hole.net | bash as sudo -s without sudo with sudo ... and updated & upgraded the Pi

Still same error about missing setupVars.conf.

it never creates the setupVars.conf .. been looking for the file just to replace it so the setup could continue but nope.

It crashes over and over .. the pihole -rdpha does the same thing. it just stops. tried this on Ubuntu server. CRASHED. tried on other pi like the very first one from 2012 CRASHED. and of course on a virtual machine linux! guess what...it crashed.

Yey! are we gonna talk about words that triggers you? or the script that got broken?

Decisions decisions...

**Comment by DL6ER** [comment] 2017-01-08 13:51
There seems to be something with how you use computers that triggers these failure.

We have hundreds of users which successfully use Pi-hole with its installer script on various flavors of Raspberry-specific distros, various flavors or Debian (including Ubuntu) and it works nicely for all of them.

Also you misunderstand the purpose of `pihole -d`. It is not there to magically solve all your issues, but it collects data about your operating system (like used kernel, installed versions of critical software packages, if cloning the git repositories was successful and what not). If you don't want to upload and/or share the debug token, then that is your decision. There is nothing secret in it- you can check its contents before uploading it.

**Comment by trick77** [comment] 2017-01-08 14:08
@DL6ER I whish I'd have your patience handling situations like this 👍

**Comment by Illustratum** [comment] 2017-01-08 14:32
It is not there to magically solve your issues ?

What kinda conclusion is this?

Did i say pihole -d would fix my problems? its a debug.

I can't even.

trick77 go and do something productive ;)

**Comment by Illustratum** [comment] 2017-01-08 14:35
I have installed pi hole more than most people. over and over again. since its was just simple adblock.

with the same ducks in a row.

And it works every time.

Now this happens.

For two days.

And i haven't changed one thing. the "hardware changes" you are mentioning is on a Pi with recover with the same OS over and over again used for this.

No changes other than failure in the script.

And the debug -d does the same. crashes it with same output.

No setupVars.conf... so nothing is really happening.

**Comment by darkrain-nl** [comment] 2017-01-08 14:41
With an attitude like this, people are not likely willing to help you.
So start treating people the way you like to be treated...

Thumbs up @DL6ER and @trick77 !

**Comment by Illustratum** [comment] 2017-01-08 14:42
darkrain-nl who are you talking about?

The issue here or the triggering happening inside your head?

**Comment by dschaper** [comment] 2017-01-08 23:00
Differences in opinions may and will occur. Personal insults will not. I will lock and close this thread if any further personal attacks or insults occur. Only one warning.

**Comment by bakman2** [comment] 2017-01-09 09:23
@Illustratum did you fork and fix the scriptkiddie script already ? 
@dschaper could it be caused by the single/double quotes ? I see that is inconstently (?) used.

``` sed -i "s/@INT@/$PIHOLE_INTERFACE/" ${dnsmasq_pihole_01_location}
  if [[ "${PIHOLE_DNS_1}" != "" ]]; then
    sed -i "s/@DNS1@/$PIHOLE_DNS_1/" ${dnsmasq_pihole_01_location}
  else
    sed -i '/^server=@DNS1@/d' ${dnsmasq_pihole_01_location}
  fi
  if [[ "${PIHOLE_DNS_2}" != "" ]]; then
    sed -i "s/@DNS2@/$PIHOLE_DNS_2/" ${dnsmasq_pihole_01_location}
  else
    sed -i '/^server=@DNS2@/d' ${dnsmasq_pihole_01_location}
  fi

  sed -i 's/^#conf-dir=\/etc\/dnsmasq.d$/conf-dir=\/etc\/dnsmasq.d/' ${dnsmasq_conf}
```

**Comment by DL6ER** [comment] 2017-01-09 10:15
> I see that it is inconstently (?) used.

No, it is not. If you’re simply enclosing a few words of text, it really doesn’t matter which one you use, as they will both work exactly the same. The difference between single and double quotes becomes more important when you’re dealing with variables on the command line (double quote -> expand variable, single quote -> don't do it).

Hence, we include those strings with variables like `"s/@DNS1@/$PIHOLE_DNS_1/"` in double quotes and those without like `'s/^#conf-dir=\/etc\/dnsmasq.d$/conf-dir=\/etc\/dnsmasq.d/'` in single quotes (note that we also can safely use the dollar sign without escaping it here).

**Comment by PromoFaux** [comment] 2017-01-09 10:17
@bakman2 actually this should be fixed in the latest hotfix earlier today/yesterday (depending on your timezone!).

**Comment by wioxjk** [comment] 2017-01-10 10:05
holy shit, this thread was really toxic

**Comment by PromoFaux** [comment] 2017-01-10 10:07
Ah, yes. 

Can probably close this now. The issue is fixed, and I doubt we'll see so much as a thanks from @Illustratum

**Closed by PromoFaux** 2017-01-10 10:07 UTC
