### ISSUE TITLE
dnsmasq: failed to bind DHCP server socket: Address already in use

### ISSUE THREAD

**Issue by fasfas9993** [pi-hole/pi-hole#2606] opened 2019-01-29 01:46 UTC
Hi, I installed pihole few days ago and I'm encountering a problem. It doesn't block ads!
After researching and doing everything I can, I realized that dnsmasq is not running and I cannot get it to run! 
Also, If I set IPv4 and IPv6's DNS network properties to point the the Raspberry pi IP address, then IT WORKS AND BLOCKS ADS!

Output of `systemctl status dnsmasq.service` is
`dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; disabled; vendor preset; enabled)
   Active: failed (Result: exit-code) since Tue 2019-01-29 01:31:40 GMT; 9min ago
  Process: 5237 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
  Process: 5234 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)

Jan 29 01;31;39 raspberrypi systemd[1] Starting dnsmasq - A lightweight DHCP and caching DNS server...
Jan 29 01;31;39 raspberrypi dnsmasq[5234]; dnsmasq: syntax check OK.
Jan 29 01;31;40 raspberrypi dnsmasq[5237]; dnsmasq: failed to bind DHCP server socket: Address already in use
Jan 29 01;31;40 raspberrypi systemd[1]; dnsmasq.service: Control process exited, code=exited status=2
Jan 29 01;31;40 raspberrypi systemd[1]; Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Jan 29 01;31;40 raspberrypi systemd[1]; dnsmasq.service; Unit entered failed state.
Jan 29 01;31;40 raspberrypi systemd[1]; dnsmasq.service; Failed with result 'exit-code'.`

P.S. there is very similar issue already closed but without a solution
link to the issue: https://github.com/pi-hole/pi-hole/issues/487

Please help

**Comment by dschaper** [comment] 2019-01-29 02:01
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Closed by dschaper** 2019-01-29 02:01 UTC
Labels: triage: Issue Template Ignored

**Comment by fasfas9993** [comment] 2019-01-29 02:03
My apologies, I have been checking many issues with similar problems and I found that many does not follow so I thought it's not mandatory. My apologies again.

**Comment by amitdhiman000** [comment] 2023-03-19 19:29
This might be old. 

The main problem is that, `systemd-resolved` is already running on port 53. you can verify that using below command.
```
sudo ss -lp "sport = :domain"
```
If we found the root cause, then there are 2 solutions.
1.) Disable the `systemd-resolved`
```
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
sudo systemctl mask systemd-resolved

# in case you want to revert back

sudo systemctl unmask systemd-resolved
sudo systemctl enable systemd-resolved
sudo systemctl start systemd-resolved
```

2.) Run dnsmasq on a differen port.
```
sudo nano /etc/dnsmasq.conf

# add below line to config.
port=5353
```
Hope it helped :)

**Comment by jfb-pihole** [comment] 2023-03-19 21:31
> This might be old.

4 years.
