### ISSUE TITLE
Dashboard doesn't show queries

### ISSUE THREAD

**Issue by robkuehl** [pi-hole/pi-hole#3789] opened 2020-10-09 15:24 UTC
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  RaspberryPi OS

- Platform:  Raspberry Pi,

### Expected behavior
While browsing queries should be displayed on the dashboard

_A clear and concise description of what you expected to happen._

### Actual behavior / bug
Looking at some websites it seems pihole is blocking ads, but the dashboard doesn't show anything.
Despite that, queries are logged when i run "pihole -d" in the console

_A clear and concise description of what the bug is._

### Steps to reproduce

1. Fresh install of RaspberryPi OS with Pi Imager
2. Install pihole (everything as recommended)
3. Open Dashboard and visit websites

## Debug Token

- URL:  https://tricorder.pi-hole.net/vxvx4amnso

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment] 2021-08-10 18:48
Duplicate of 
https://github.com/pi-hole/pi-hole/issues/3790

**Closed by yubiuser** 2021-08-10 18:48 UTC
