### ISSUE TITLE
updating via curl doesn't affect all components

### ISSUE THREAD

**Issue by deepgray** [pi-hole/pi-hole#2036] opened 2018-03-10 20:13 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1
---
**Expected behaviour:**

using the cli command "curl -sSL https://install.pi-hole.net | bash" and selecting "update" processes normally without error.

after reboot, the web admin panel should show all components are up to date

**Actual behaviour:**

Pi-hole Version v3.2.1 (Update available!) Web Interface Version v3.3 FTL Version v3.0

**Steps to reproduce:**

see above

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

> * `{Please delete this quoted section when opening your issue}`
> * You must follow the template instructions. Failure to do so will result in your issue being closed.
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by deepgray** [comment] 2018-03-10 20:15
additionally, using pihole -up shows everything updated:

root@pi-hole:~# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] FTL:		up to date
  [i] Web Interface:	up to date

  [✓] Everything is up to date!
root@pi-hole:~#

**Comment by dschaper** [comment] 2018-03-10 20:30
Duplicate of #1975
Duplicate of #1964

**Closed** 2018-03-10 20:30 UTC
Labels: Duplicate
