### ISSUE TITLE
Change Blacklist/Whitelist to Blocklist/Allowlist

### ISSUE THREAD

**Issue by HanSooloo** [pi-hole/pi-hole#4149] opened 2021-04-28 12:30 UTC
Suggest changing the terminology used in the app to use Blocklist and Allowlist in line with industry practices of moving to race neutral terminology.

https://thenextweb.com/news/github-plans-to-replace-racially-insensitive-terms-like-master-and-whitelist

**Comment by yubiuser** [comment] 2021-04-28 13:41
Duplicate of

https://github.com/pi-hole/AdminLTE/issues/1448

**Closed by yubiuser** 2021-04-28 13:41 UTC
