### ISSUE TITLE
Windows store Locked

### ISSUE THREAD

**Issue by flamme-demon** [pi-hole/pi-hole#832] opened 2016-10-22 23:06 UTC
There is a problem of access and download to the "Windows Store", I think it is block by the anti-ad

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [x] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10 (very familiar)

---
**[OTHER]:**

Use Synology DS1515+ (debian chroot), IPV6, IPV4

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

- Adding a domain name and or sub domain white list
- It is not possible to access the site from the white list

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

**Comment by dschaper** [comment] 2016-10-22 23:22
https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

The XBox/Windows 10 domains should get you back on track.

**Comment by flamme-demon** [comment] 2016-10-23 07:52
I add domains to the whitelist. But I'm still block, I'm a "ipconfig /flushdns" but nothing changes. " As if the whitelist was not active.

I also try to unlock "support.microsoft.com" and I'm always send the IP of the server DNS here "192.168.0.200"

**Comment by dschaper** [comment] 2016-10-23 07:59
This may be duplicity, but did you whitelist the domain via the instructions at https://discourse.pi-hole.net/t/how-do-i-whitelist-or-blacklist-a-domain/244 ? And can you provide is with the address for a `pihole -d`? (This would typically be covered by the template we use for Issue submissions, and we may need to have that template filled out if we're unable to resolve the issue without the missing information.)

**Comment by flamme-demon** [comment] 2016-10-23 08:16
I have put in the white list the address of the slot area to not only unlock this site "support.microsoft.com "
screen : [http://imgur.com/CIDuuCy](url)

But I'm always redirect my dns server.
screen : [http://imgur.com/36gRHoV](url)

**Comment by dschaper** [comment] 2016-10-23 10:32
Do you have both IPv4 and IPv6 enabled on the Pi-hole, and are you running dual-stack or just one protocol on your clients?

I'm going to add back in the Issues Template to your original post, please fill that out in its entirety to help us with your issue.

**Comment by flamme-demon** [comment] 2016-10-23 13:14
It's better like this?

**Comment by dschaper** [comment] 2016-10-23 22:02
Yes, much better, we now know that you are on a Synology system, and we don't directly support Synology. I see that you have found the Discourse thread on Synology and I would suggest that as your support venue as they have the ability to help you there. None of the development team have Syn's or the ability to debug and reproduce on Syn's like other users can.

**Comment by jacobsalmela** [comment] 2016-10-24 00:11
Closing since it's not a platform we are currently supporting.  

Leaving this here for others who may land here:

https://discourse.pi-hole.net/t/how-do-i-install-pi-hole-on-a-synology-nas/289/13

**Closed by jacobsalmela** 2016-10-24 00:11 UTC

**Comment by solidus1983** [comment] 2020-07-08 16:31
For people having issues with Windows Store Updates and Downloads

,,,
* ctldl.windowsupdate.com
* displaycatalog.mp.microsoft.com
* dl.delivery.mp.microsoft.com
* sls.update.microsoft.com
* geo-prod.do.dsp.mp.microsoft.com
,,,

Had to add them to whitelist in order to stop getting Windows 10 Store 0x8024402C  Error codes
