### ISSUE TITLE
Pihole -up with no network showing update available for FTL

### ISSUE THREAD

**Issue by DL6ER** [pi-hole/pi-hole#1877] opened 2017-12-27 11:07 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).
---
See https://discourse.pi-hole.net/t/pihole-up-with-no-network-gives-ftl-update-available/6155

> When running pihole -up on ubuntu server 64bit 16.04.3 in virtualbox and network disable, update says Pi-hole core is up to date and FTL needs updating, Web interface check is missing

**Comment by terminator9999** [comment] 2017-12-31 16:21
What do you guys think about doing a simple internet connection test before checking updates?
1. Ping 8.8.8.8 if it fails go to step 2, if not go to step 4
2. Ping some ipv6 address if it fails go to step 3, if not go to step 4
3. Show error message, stop the script
4. Run the script normally

**Comment by dschaper** [comment] 2017-12-31 16:55
I would be okay with a ping to one of the upstream resolvers. I wouldn't want to hardcode in Google, just because even pinging them gives them the IP of the installation.

**Comment by terminator9999** [comment] 2017-12-31 17:29
Okay, pinging the upstream resolver (the one that user choosed in installation process) should be perfect. I will think about the effective way of grabing the ip of choosen upstream resolver (maybe just exporting it from the network configuration file) and will do my PR when I will have time :)

**Comment by PromoFaux** [comment] 2019-06-15 17:14
I note that the PR #1889 that was aiming to resolve this issue was closed as apparently the issue was fixed in #1943 , though I cannot see where in the code it was fixed! Am I being blind, or is this issue now resolved?

**Comment by Mcat12** [comment] 2019-06-29 03:53
@PromoFaux I checked this out today and saw that we were not handing a possible error caused by the `curl` command failing when retrieving the latest FTL version. See #2820.

**Closed** 2019-09-15 15:52 UTC
Labels: triage: Issue
