### ISSUE TITLE
Adding some website into whitelist.txt but it not working

### ISSUE THREAD

**Issue by ookangzheng** [pi-hole/pi-hole#696] opened 2016-09-18 07:10 UTC
I use on Centos6
I add pihole -w -f tieba.baidu.com , but it not working
Error message: tieba.baidu.com refused to connect. (chrome)

**Comment by nomoreads** [comment] 2016-09-18 07:28
There are multiple threads regarding issues with whitelisting so the devs should really dig into this.
Meanwhile you might have to wait a few minutes before it actually works (don't ask me why) https://github.com/pi-hole/pi-hole/issues/675#issuecomment-247829732

**Comment by PromoFaux** [comment] 2016-09-18 15:41
Closing as duplicate of #675 . @ookangzheng please don't open multiple issues on the same subject!

**Closed by PromoFaux** 2016-09-18 15:41 UTC
