### ISSUE TITLE
`unattended` requires a tty when it shouldn't

### ISSUE THREAD

**Issue by TronPaul** [pi-hole/pi-hole#2319] opened 2018-08-05 13:52 UTC
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
7

---
**Expected behaviour:**

When passing `--unattended` the `basic_installer` should complete even when there is no tty present.

**Actual behaviour:**

debconf-apt-progres fails with no tty `open /dev/tty: No such device or address`

**Steps to reproduce:**

Via EC2 (how I originally discovered this)
Create an ubuntu ec2 instance with the following user-data:
```
#!/bin/bash
wget -O /tmp/basic-install.sh https://install.pi-hole.net
chmod +x /tmp/basic-install.sh
mkdir /etc/pihole/
cat > /etc/pihole/setupVars.conf <<EOF
INSTALL_WEB=false 
PIHOLE_DNS_1=10.0.0.2
PIHOLE_INTERFACE=eth0
IPV4_ADDRESS=10.0.1.5
QUERY_LOGGING=false
EOF
/tmp/basic-install.sh --unattended
```

What happens:
pi hole is not installed and `/var/log/cloud-init-output.log` contains the error `open /dev/tty: No such device or address`.

Via at:
Create a script with the following in /tmp/at_install.sh:
```
#!/bin/bash
wget -O /tmp/basic-install.sh https://install.pi-hole.net
chmod +x /tmp/basic-install.sh
mkdir /etc/pihole/
cat > /etc/pihole/setupVars.conf <<EOF
INSTALL_WEB=false 
PIHOLE_DNS_1=10.0.0.2
PIHOLE_INTERFACE=eth0
IPV4_ADDRESS=10.0.1.5
QUERY_LOGGING=false
EOF
/tmp/basic-install.sh --unattended 2>&1 | tee /tmp/install.log
```
Run:

    chmod +x /tmp/at_install.sh
    echo /tmp/at_install.sh | sudo at now

What happens:
The script stalls at package installation and does not continue (see `/tmp/install.log`).

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

vxjf7vk6il (this token was gotten after running the install with an interactive shell)

**Troubleshooting undertaken, and/or other relevant information:**

I removed the `debconf-apt-progress --` by sed'ing the script during the curl and that seemed to work.

**Comment by dschaper** [comment] 2018-08-05 13:53
This appears to be a duplicate of #2178, can you check and confirm?

**Comment by TronPaul** [comment] 2018-08-05 13:55
I don't think so since removing `debconf-apt-progress --` in my case fixes the issue. I have not modified `dnsmasq.conf`

**Comment by TronPaul** [comment] 2018-08-05 13:56
I'm willing to submit a PR to remove `debconf-apt-progress` in the `unattended` case if this behavior is considered a bug.

**Comment by dschaper** [comment] 2018-08-05 13:59
Looking at https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L1243 if that is removed then none of the dependent packages are installed. Might need another solution to fix it.

**Comment by dschaper** [comment] 2018-08-05 14:08
But I do see the issue, and with unattended installations we should be just calling `apt-get` straight without the curses wrapper around it.

**Comment by TronPaul** [comment] 2018-08-05 14:10
To be clear, current workaround is to `curl -sL https://install.pi-hole.net | sed 's/debconf-apt-progress -- //' > /tmp/basic-install.sh`. It is not to remove the line at https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L1243.

**Comment by dschaper** [comment] 2018-08-05 14:12
I think there's a better option that we can pass in that will handle the environment, `export DEBIAN_FRONTEND=noninteractive` will handle the lack of `tty`, it's just a matter of checking to see if apt still passes the proper status to the file descriptors, or if there's a need to not use `debconf` completely, and still pass in the `noninteractive` environment variable.

**Comment by dschaper** [comment] 2018-08-05 14:25
Great, if you would like to PR that change we can set it up for 4.1 as the release target.

**Comment by TronPaul** [comment] 2018-08-05 14:48
Ok. I've also run into another issue where `USER` is not defined during cloud-init scripts. Do you consider failing on an empty `USER` environment variable to be a bug? If so, would you prefer a PR to make `USER` default to `whoami` or just switch `USER` out for `whoami`? Also would it be better to include both fixes in 1 PR or separate PRs?

**Comment by dschaper** [comment] 2018-08-05 14:51
Two separate would be better. And `${USER}` is going to be modified a bit with a change to how the script is called for `sudo` or `root` prefixing on individual calls instead of the whole scripts. But something along the lines of prefering `id -u` and then if that is not valid a `whoami` call. Since the majority of the installs are going to be ones that do not use `cloud-init` I'd prefer to keep as much of the native code as is and then patch in some failover as needed.

**Comment by dschaper** [comment] 2018-08-05 14:57
Is `id -un` valid under a cloud-init session?

**Comment by TronPaul** [comment] 2018-08-05 14:58
By preferring `id -u` do you mean the PR should switch `USER` to `id -u` or default `USER` to `id -u` and fallback on `whoami` if `id -u` is not available?

**Comment by dschaper** [comment] 2018-08-05 15:01
Something along the lines of: If `${USER}` is empty then fill it with `id -un`. So `USER=${USER:-$(id -un)}`, which should work, `whoami` is deprecated, but if `id -un` is not valid and `whoami` works, then substitute that. And that shell code is just a off the top of my head call, it may not work as I wrote it.

**Comment by bcambl** [comment] 2019-01-04 18:43
This fix is now in the `master` branch. Closing

**Closed by bcambl** 2019-01-04 18:43 UTC
Labels: Investigating, triage: Issue
