### ISSUE TITLE
'Queries answered by' can have duplicate hostnames for ipv4 and ipv6

### ISSUE THREAD

**Issue by StefanSchoof** [pi-hole/pi-hole#2362] opened 2018-08-15 10:27 UTC
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

I have set up my router ipv4 and ipv6 as upstream DNS Server. I like to know if Pi-hole uses the ipv4 or ipv6 connection to my router. In the 'Queries answered by' on the Dashboard should it possible to identify proportion of the ipv4 and the ipv6 requests,

**Actual behaviour:**

Pi-hole resolves both ips to the same hostname and show only the hostname. So I can not see which is the ipv4 and which is the ipv6. The hostname of my router is ´fritz.box´.
![grafik](https://user-images.githubusercontent.com/4662023/44143870-a7ef48d8-a085-11e8-8966-433cbc835a70.png)

**Steps to reproduce:**

1. Set up the local router with ipv4 and ipv6 address as upstream DNS Server
2. make some requests an wait until some data on the dashboard
3 Open the Dashboard and take a look at the 'Queries answered by' chart.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

N/A

**Troubleshooting undertaken, and/or other relevant information:**

No known workaround.

**Comment by dschaper** [comment] 2018-08-15 10:39
Thanks for the post, this appears to be a Feature Request and not a bug, so we'll close this out and add the instructions on how to open Feature Requests for Pi-hole.

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Closed by dschaper** 2018-08-15 10:39 UTC

**Comment by pe0mot** [comment] 2018-08-15 10:40
Same here :-)
AVM answers on both IP's with the same name, so the Console shows what it's told.
Cloudfare and OpenDNS can show the same.

**Comment by StefanSchoof** [comment] 2018-08-15 21:27
I understand.

To answer my question, which protocol is used I copied the pihole-FTL.db an run the command:

`sqlite3 pihole-FTL.db "SELECT forward, count(forward) from queries group by forward"`

In my case the ipv4 address is much more used.

Since this answers my question, I will not pursue a feature request further.

**Comment by bluikko** [comment] 2019-09-04 12:28
I too noticed this problem and in my opinion it is a bug (design error).
It is not clear which server gave the result when the "queries answered by" does not distinguish between IPv4 and IPv6 addresses and only displays the same reverse DNS result.

**Comment by dschaper** [comment] 2019-09-04 13:01
Edit your `/etc/hosts` and give the IPv4 and IPv6 addresses of the server different names.
