### ISSUE TITLE
/etc/lighttpd/lighttpd.conf is overwritten on upgrade

### ISSUE THREAD

**Issue by g3ck000** [pi-hole/pi-hole#4033] opened 2021-02-02 09:52 UTC
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.3.2
- FTL:  5.6

### Platform

- OS and version:   Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-1026-raspi aarch64)

- Platform:  Raspberry Pi 3B

### Expected behavior

_A clear and concise description of what you expected to happen._
When pihole is updated, /etc/lighttpd/lighttpd.conf is overwritten. Changes for SSL/TLS and redirection to HTTPS are gone.

### Actual behavior / bug

_A clear and concise description of what the bug is._
I don't know if this is a bug or a configuration mistake on my part. 

### Steps to reproduce

customize /etc/lighttpd/lighttpd.conf and then upgrade pihole (if update available)

1. edit /etc/lighttpd/lighttpd.conf
2. upgrade pihole (if update available)
3. review /etc/lighttpd/lighttpd.conf
4. See edits are gone

## Debug Token

- URL:  https://tricorder.pi-hole.net/5m1qr639di

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment] 2021-02-02 11:31
Duplicate of
https://github.com/pi-hole/pi-hole/issues/4022

**Closed by yubiuser** 2021-02-02 11:31 UTC

**Comment by g3ck000** [comment] 2021-02-02 15:05
> 
> 
> Duplicate of
> #4022

Thanks
