### ISSUE TITLE
BUG: pihole -r must follow rules

### ISSUE THREAD

**Issue by LinoBarreca** [pi-hole/pi-hole#4442] opened 2021-11-29 18:58 UTC
on the PI, as root:

pihole -r
```
...
  [✗] Retrieval of supported OS list failed. dig failed with return code 9.
      Unable to determine if the detected OS (Debian 11) is supported
      Possible causes for this include:
        - Firewall blocking certain DNS lookups from Pi-hole device
        - ns1.pi-hole.net being blocked (required to obtain TXT record from versions.pi-hole.net containing supported operating systems)
        - Other internet connectivity issues
```

but everything resolves through pihole, even the rpi itself
```
cat /etc/resolv.conf
# Generated by resolvconf
nameserver 127.0.0.1
```
and
```
PIHOLE_DNS_1=192.168.1.1
PIHOLE_DNS_2=fd10:cacc:a000:1::1
```

on the router however:
`Mon Nov 29 19:42:04 2021 kern.warn kernel: [85849.682281] REJECT wan out: IN=br-lan OUT=eth0.34 MAC=... SRC=192.168.1.2 DST=185.136.96.96 LEN=89 TOS=0x00 PREC=0x00 TTL=63 ID=36197 PROTO=UDP SPT=52226 DPT=53 LEN=69
`

**Comment by jfb-pihole** [comment] 2021-11-29 19:30
> everything resolves through pihole, even the rpi itself

From the Pi terminal, what is the output of the following command:

`dig -t txt versions.pi-hole.net @ns1.pi-hole.net`

**Comment by LinoBarreca** [comment] 2021-11-29 19:35
> 

of course it's
```
root@Pi:/etc/pihole# dig -t txt versions.pi-hole.net @ns1.pi-hole.net

; <<>> DiG 9.16.15-Debian <<>> -t txt versions.pi-hole.net @ns1.pi-hole.net
;; global options: +cmd
;; connection timed out; no servers could be reached
```
as it should be

**Comment by PromoFaux** [comment] 2021-11-29 22:44
You've left out the rest of the output that is given when `versions.pi-hole.net` cannot be resolved via `ns1.pi-hole.net`

`If you wish to attempt to continue anyway, you can try one of the following commands to skip this check:`

etc etc etc and then:

`PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r`

> pihole -r doesn't have to ask to ns1.pi-hole.net

It does. The only time Pi-hole ever needs to resolve via that DNS server is at that point in the installer. IMHO, this is not a bug - because the behaviour is intended. Please read the following thread for the reasons as to why:

- https://github.com/pi-hole/pi-hole/issues/3595

**Comment by LinoBarreca** [comment] 2021-11-29 23:04
@PromoFaux whoever thought that it could work made a mistake assuming that the RPI has free access to internet.
It doesn't.
The only machine which can do DNS queries is the router (encrypting them and, if needed, routing them through a VPN)
Every other query (DNS, DNS-over-TLS and DNS-over-HTTP) from any other device in the network is blocked at router level.
Basically pi.hole wants to act like all the other programs do: just ignore the settings and query whatever he likes and this is not allowed.
This can not succeed.
Pi-hole receives all the queries, filters them and forwards the allowed ones to the upstream server: the router.
The router accepts only the queries from pi-hole, checks several ipsets and routes them properly.

**Comment by PromoFaux** [comment] 2021-11-29 23:15
This is a configuration issue. Pi-hole is working exactly as designed. Of course, not every network is the same... And there are, like yours, edge cases that will come up against issues. Nothing is 100% perfect for 100% of users/use cases

The linked thread in my previous comments explains how we came to the decision to use `ns1.pi-hole.net` to lookup the TXT record at this single domain.

Also mentioned in my previous comment (as well as the original error output) is an instruction on how to skip the check all together.

(Or configure your firewall to intercept and transparently redirect all DNS lookups, rather than blocking them)

**Closed** 2021-11-29 23:15 UTC

**Comment by LinoBarreca** [comment] 2021-11-29 23:17
But the "workaround" still doesn't work....

**Comment by LinoBarreca** [comment] 2021-11-29 23:23
and anyway "configure your firewall to intercept and transparently redirect all DNS lookups" **can not** work.
To what should I redirect the DNS queries?
To the pihole? so we have a loop?
Or to the internet? so everything runs on the rpi has free access?
Any other brilliant solution besides the "workaround" which doesn't work and gives the same error or the "redirect" which can't work?

**Comment by PromoFaux** [comment] 2021-11-30 10:42
> But the "workaround" still doesn't work....

"Doesn't work" is not helpful for troubleshooting. What have you tried? What outputs were on screen? Have you dug into the code to see what's supposed to happen? Have you disabled your custom configuration to ensure that it is not interfering with things? 

What is the output of `PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r`

Though, I see you are running commands as root. So perhaps try `PIHOLE_SKIP_OS_CHECK=true pihole -r`

Either way, here is the line of code for the skip. You just need an environment variable named `PIHOLE_SKIP_OS_CHECK` set to `true` https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L169

Follow the logic in the code. If the environment variable is present, then the DNS lookup via `ns1.pi-hole.net` is never hit.


> To what should I redirect the DNS queries?

I don't know - I'm just tossing out ideas. If you think it is a bad idea, that's OK. It didn't cost me anything to come up with.

---

nb. There is an issue template for issues - it is there to help us help you. The more information you provide at the very beginning, and the less we have to slowly tease out of you - the more helpful we can be. 

There is no issue with attempting to secure your network - but when something isn't working, and you want help with it, perhaps be up front about changes you have made to your system, or details about how your system is configured before to help us help you troubleshoot.

I've provided links and explanations as to why things are the way they are - they work for the 99% - of course there will be 1% of users that have incompatibilities - it would be unrealistic to expect things to work in 100% of configurations - I'd appreciate a little less hostility, if you can manage it. Thanks!

**Comment by LinoBarreca** [comment] 2021-11-30 17:47
@PromoFaux I become hostile when, without any respect for someone which takes time to report a bug, you come out with "this is by design" and close the bug wasting my time and the time from all the other people which are reporting this problem.
This is might be by design but, as a developer, it's a crappy design for several reasons.
1) You are handling a program which is supposed to handle DNS queries in a DNS-restricted environment.
2) It's not MY network which has special (or weird) setup. Any network in which the pihole is supposed to run should block DNS queries by default except from one authorized program.
3) When "you" (whoever decided to handle it this way) took that decision you assumed the pi-hole has free, unlimited access to any dns server. The rpi, being a complete linux system with gigabytes of ram, is just wasted to run only the pi-hole. Most likely the users run the pihole as a service and the rest of the rpi in other ways. This means that the rpi **_might_** have the same restrictions as all the other devices on the network.
4) using dns servers different than what the network administrator tells you to use puts you in the list of the "bad guys", in the same way apps which want to show ads try to workaround the limitation imposed.
5) "you" make the pihole, you aren't a developer from a third party program. You know how to read the settings to use the dns server which the pihole already uses. try the standard way and if nothing works try "escaping" by accessing directly the custom nameserver.

so... yeah... I am hostile because instead of slamming the bugreport on my face like a door (and with me you did the same with the other users which obviously are running in a "secure way" and not "as a joke") you might have said "well...we did it for this reason, but I understand that accessing a DNS not expected by the user, in a restricted environment like ours, 99% of the time will fail...probably we need to look again at this decision"

**Comment by LinoBarreca** [comment] 2021-11-30 17:53
But the thing that pisses me off more is that you blame me and my secure configuration because your program can't do something it shouldn't do...and instead of saying "well...yeah..you are right, but changing it is not possible or too complicate, so maybe you need to find another workaround" you talk to me like I'm an idiot which misconfigured the network....did you expect less hostility?

**Comment by PromoFaux** [comment] 2021-11-30 18:18
I haven't blamed you for anything.

Your configuration is the reason that you have hit this error message. That is a fact. I guess another way of looking at it is that you have hit this message because, out of the box, Pi-hole is incompatible with your configuration.

> You are handling a program which is supposed to handle DNS queries in a DNS-restricted environment.

>  It's not MY network which has special (or weird) setup. Any network in which the pihole is supposed to run should block DNS queries by default except from one authorized program.

While this is a perfectly valid way to run ones network, it is by no means "normal". I expect you will find that the majority of users have Pi-hole installed on a raspberry pi, plugged into their ISP provided router. Blocking all DNS queries except ones you allow is certainly not an out of the box experience for the majority. But that is not me saying you are wrong to do so.

> using dns servers different than what the network administrator tells you to use puts you in the list of the "bad guys", in the same way apps which want to show ads try to workaround the limitation imposed.

In normal operation, Pi-hole does not require access to any DNS server other than those that have been configured. In this _one_ (OK, two if you count the debug log tool) case it is there to resolve an issue that multiple users immediately reported on when we first added the OS Check into the installer. This is all explained in the thread(s) I linked you to in previous comments.

> You assumed the pi-hole has free, unlimited access to any dns server.

Clearly we did not, hence the check for the environment variable to skip this section of the code if it is problematic... On that note, you have still not answered my question there regarding what errors you are seeing when you attempt to use the environment variable to work around this problem. "It doesn't work" is not good enough.

How much more of my time would you like to waste?

**Comment by PromoFaux** [comment] 2021-11-30 18:19
>you talk to me like I'm an idiot which misconfigured the network

I never said you misconfigured your network.

**Comment by jfb-pihole** [comment] 2021-11-30 19:17
> without any respect for someone which takes time to report a bug

As Promo has noted, it's not a bug.  It is the intended method of operation, by design, as explained in the referenced PR.

You are free to configure your network however you like.  If your configuration interferes with the normal operation of Pi-hole, you have several options, some as previously noted.

1.  Skip the update check - this is a provided option in Pi-hole for the reasons previously noted.
2. Change your firewall rules to allow the query to the ns1.pi-hole.net nameserver from the Pi-hole host device.
