### ISSUE TITLE
wrong size of Type and Content columns in Domain tabs

### ISSUE THREAD

**Issue by stefanostatuti** [pi-hole/pi-hole#3712] opened 2020-08-28 07:46 UTC
### Versions
pi@raspberrypi4:~ $ pihole -v
  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)

### Platform
- OS and version:  Debian Buster
- Platform:  Raspberry PI

### Expected behavior

display the entire content of the column

### Actual behavior / bug

the content inside the column is unreadable

### Steps to reproduce

1. Go to 'Group Management'
2. Click on 'domains'
3. if you ahave any blacklisted domain or REGEX is inpossible to read the content of columns Type and Comment

## Debug Token

- URL:  
https://tricorder.pi-hole.net/fx4ys1szdt

### Screenshots

https://ibb.co/b5gLW7T

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment] 2020-08-28 07:59
Thanks for the report.
Duplicate of https://github.com/pi-hole/AdminLTE/issues/1458

**Closed by yubiuser** 2020-08-28 07:59 UTC
