### ISSUE TITLE
Disk shortage bug

### ISSUE THREAD

**Issue by French-Cat** [pi-hole/pi-hole#4634] opened 2022-03-01 07:32 UTC
### Versions

- Pi-hole:  [v5.9](https://github.com/pi-hole/pi-hole/releases/v5.9)
- AdminLTE:  [v5.14](https://github.com/pi-hole/FTL/releases/v5.14)
- FTL:  [v5.11](https://github.com/pi-hole/AdminLTE/releases/v5.11)

### Platform

- OS and version:  macOS Monterey 12.3

- Platform:  Docker

### Expected behavior

_No errors/logs._

### Actual behavior / bug

Disk shortage (/etc/pihole/pihole-FTL.db) ahead: 37293363% used

/etc/pihole: 18.4EB used, 494.4GB total

is  appearing under diagnosis 

### Steps to reproduce

Not exactly sure what happened-?

## Debug Token

- URL:  https://tricorder.pi-hole.net/ztP08Y9T/

### Screenshots

<img src="https://cdn.discordapp.com/attachments/932796532913213440/948117839968079902/unknown.png">

### Additional context

Again, I have no damn clue what happened. Fresh install of PiHole and I see that.

**Comment by yubiuser** [comment] 2022-03-01 07:57
Thanks for the report. It's a duplicate of https://github.com/pi-hole/docker-pi-hole/issues/951

**Closed by yubiuser** 2022-03-01 07:57 UTC
