### ISSUE TITLE
Pi-hole not updating from 3.2.1 to 3.3

### ISSUE THREAD

**Issue by behemoth88** [pi-hole/pi-hole#2038] opened 2018-03-12 21:50 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:2

`{Replace this with a number from 1 to 10. 1 being not familiar, and 10 being very familiar}`

---
**Expected behaviour:**

I would expect the pi-hole be updated to version 3.3.

**Actual behaviour:**

Pi-hole is not updating to newest version (3.3), although update (and repair) was successful.
The version remain untouched:
root@osmc:/var/www/html# pihole -v
  Pi-hole version is v3.2.1-73-g1e87850 (Latest: v3.3)
  AdminLTE version is v3.3 (Latest: v3.3)
  FTL version is v3.0 (Latest: v3.0)

**Steps to reproduce:**

1. Login as root
2. Initiate pi-hole update:
root@osmc:/var/www/html# pihole -up
3. Result of the update:
root@osmc:/var/www/html# pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] FTL:              up to date
  [i] Web Interface:    up to date

  [✓] Everything is up to date!

4. The only red X sign is here:
[✗] Backing up index.lighttpd.html
      No default index.lighttpd.html file found... not backing up
5. Version remains the same:
root@osmc:/var/www/html# pihole -v
  Pi-hole version is v3.2.1-73-g1e87850 (Latest: v3.3)
  AdminLTE version is v3.3 (Latest: v3.3)
  FTL version is v3.0 (Latest: v3.0)

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

d3sll4sv3i

**Troubleshooting undertaken, and/or other relevant information:**

System is up to date.
Kernel:
root@osmc:/var/www/html# uname -a
Linux osmc 4.14.15-6-osmc #1 SMP PREEMPT Sat Mar 10 21:02:39 UTC 2018 armv7l GNU/Linux

OS version:
root@osmc:/var/www/html# cat /etc/debian_version
9.4

**Comment by Mcat12** [comment] 2018-03-12 23:17
Duplicate of #2036 
Duplicate of #1975
Duplicate of #1964

**Closed by Mcat12** 2018-03-12 23:17 UTC
