### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by xnetworker** [pi-hole/pi-hole#4529] opened 2022-01-07 07:55 UTC
### Versions
  Pi-hole version is v5.8.1 (Latest: v5.8.1)
  AdminLTE version is v5.10.1 (Latest: v5.10.1)
  FTL version is v5.13 (Latest: v5.13)

### Platform

- OS and version:  Raspberry OS

- Platform:  Raspberry Pi 4 4GB

I flashed the OS image to an SSD with Belena-Etcher and then started the installation with "curl -sSL https://install.pi-hole.net | bash". In doing so, I get the following errors.

  [✗] Check for existing repository in /etc/.pihole
 
  [✗] Check for existing repository in /var/www/html/admin

  [✗] Pulling blocklist source list into range
  [i] No source list found, or it is empty

  [i] Building tree...
  [✗] Unable to build gravity tree in /etc/pihole/gravity.db_temp
  Error: no such table: main.gravity
   [✗] Unable to create database. Please contact support

## Debug Token

- URL:  https://tricorder.pi-hole.net/wim5hft4rq](https://tricorder.pi-hole.net/cypsICQU/

**Comment by yubiuser** [comment] 2022-01-07 08:19
I guess you did not select any adlist during installation.

Duplicate of: https://github.com/pi-hole/pi-hole/issues/4506

**Closed by yubiuser** 2022-01-07 08:19 UTC
