### ISSUE TITLE
Pihole image shows on webpage

### ISSUE THREAD

**Issue by akmlhkmi** [pi-hole/pi-hole#1875] opened 2017-12-25 02:49 UTC
anyone have solutions for this issue?

![image](https://user-images.githubusercontent.com/34821824/34331376-287ed43c-e961-11e7-8bdf-167e92d7edde.png)

**Comment by Mcat12** [comment] 2017-12-25 02:52
[You asked this on Discourse 12 days ago](https://discourse.pi-hole.net/t/school-management/5955) and I asked for some more information. Do you want to work on this issue here or on Discourse? Either way, please give more information on what your problem is and what you are trying to do.

**Comment by akmlhkmi** [comment] 2017-12-25 03:12
192.168.0.103 is my raspberry pi's IP address
before I'm install the pihole, it will show Apache2 Debian Default Page

![image](https://user-images.githubusercontent.com/34821824/34331693-0a5a2fc6-e964-11e7-9f25-d7ac25e15f71.png)

when I've install it, there show me that pihole's image
I think there were some configuration to do

**Comment by dschaper** [comment] 2017-12-25 06:12
We use `lighttpd` for the web server. If you would like you use `apache` instead then you need to edit the `apache` configuration to load the Pi-hole pages properly. That is something we do not support, but you may find other users that have done the same configuration on Discourse.

**Comment by akmlhkmi** [comment] 2017-12-25 06:49
I need to use apache for my final year project and must to find the solution of this issue asap.

**Comment by dschaper** [comment] 2017-12-25 07:11
What exactly is the issue, are you being blocked from viewing web pages on the internet? Please explain in detail as the template requested of you.

**Comment by akmlhkmi** [comment] 2017-12-25 07:36
It is not a website's problem actually, all the websites are running well. I want to access the file from my local server but it was blocked by pi-hole

**Comment by DL6ER** [comment] 2017-12-25 11:31
- Has `lighttpd` been installed and is it now replacing `apache2` on port 80?
- With `lighttpd` show the blocking page for everything (as 404 page) so you might get the wrong impression of what is blocked as it will show you the status blocked also for pages that do not even exist.

**Comment by davekr8** [comment] 2017-12-25 11:52
Oh a second post for the same issue (not too good)...

If you can go with pihole controling it from the shell, just give

> `sudo systemctl stop lighttpd.service `

a try.

**Comment by PromoFaux** [comment] 2017-12-25 11:54
Closing this comment thread here in favour of the one already going on discourse. No need for two threads, and as this is not a bug with the code, discourse is better suited for this discussion.

**Closed** 2017-12-25 11:54 UTC

**Comment by dschaper** [comment] 2017-12-25 23:03
Just in case someone else happens to find this thread the discussion is https://discourse.pi-hole.net/t/school-management/5955/
