### ISSUE TITLE
/admin/settings.php blank Site

### ISSUE THREAD

**Issue by Vepox** [pi-hole/pi-hole#1824] opened 2017-12-09 13:05 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Load the Settings Page`

**Actual behaviour:**

`A wild Blank Site appears`

**Steps to reproduce:**

`Click on Settings in the Webinterface`

**Comment by PromoFaux** [comment] 2017-12-09 13:06
Duplicate of https://github.com/pi-hole/AdminLTE/issues/628

**Closed by PromoFaux** 2017-12-09 13:06 UTC
