### ISSUE TITLE
Restore of Backup not complete using teleporter

### ISSUE THREAD

**Issue by plani-de** [pi-hole/pi-hole#3858] opened 2020-11-22 16:41 UTC
### Versions
- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform
- OS and version:  Armbian 20.08.17 Buster
- Platform:  Friendlyarm ZeroPi

### Expected behavior

Importing PiHole settings to new PiHole-System by using Teleporter to import settings via the restore function, after exporting the settings from old PiHole-System through the teleporter backup function.

### Actual behavior / bug

Only partial import of the settings. 

### Steps to reproduce

0. On old PiHole, login to webfrontend
1. Go to Settings --> Teleporter 
2. Click on 'Backup'
3. Save downloaded Backupfile (pi-hole-PiHole-teleporter_2020-11-21_20-17-06.tar.gz)
4. Go to new PiHole and login to webfrontend
5. Go to Settings --> Teleporter
6. Click on 'Restore' after selecting upload file. (All checkboxes are checked.)
7. Look at new Window stating:
     Processed adlist (36 entries)
     Processed adlist group assignments (36 entries)
     Processed blacklist (exact) (0 entries)
     Processed blacklist (regex) (1 entries)
     Processed client (0 entries)
     Processed client group assignments (0 entries)

8. Check settings and lists:
     - Local DNS records only imports 1 record and duplicates this record with each restore

## Debug Token

- URL:  https://tricorder.pi-hole.net/knqrskn0vz

### Screenshots

Screenshot of the content of the Backup-File:
![screenshot backup tar gz](https://user-images.githubusercontent.com/74870189/99909512-46195700-2ce9-11eb-86ff-92236c43a63d.png)

### Additional context
When looking into the lighttpd error-log I find this statement:
2020-11-22 17:31:47: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  SQLite3::exec(): no such table: blacklist in /var/www/html/admin/scripts/pi-hole/php/teleporter.php on line 90
2020-11-22 17:31:47: (mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  SQLite3::exec(): no such table: regex_blacklist in /var/www/html/admin/scripts/pi-hole/php/teleporter.php on line 90
2020-11-22 17:31:47: (mod_fastcgi.c.421) FastCGI-stderr: PHP Fatal error:  Cannot redeclare error() (previously declared in /var/www/html/admin/scripts/pi-hole/php/func.php:126) in /var/www/html/admin/scripts/pi-hole/php/func.php on line 126

I also tried to create the blacklis and regex_blacklist table in the sqlite3-db but didn't change anything. 

Possible solution for me would probably be to just clone the /etc/pihole directory, but that is just a workaround. Would be nice to understand where the issue is, as I didn't find anything.

Thanks for your great work.

**Comment by dschaper** [comment] 2020-11-22 19:03
Is this a duplicate of the issue opened right before this one? https://github.com/pi-hole/pi-hole/issues/3857

**Comment by plani-de** [comment] 2020-11-23 06:47
Not sure if this is a duplicate. A duplicate would mean an issue report that is based on the same source of issue as another report. I can't see where the source of the issue #3857 is, neither for this issue. I only can point out that all error in the log point out to:
a) missing table in the db
b) failure in the php-script
The later varies in the message that the error is in line 90 of pi-hole/php/teleporter.php and line 126 of pi-hole/php/func.php

If there is any further information required, please let me know. I'll be happy to provide.

**Comment by plani-de** [comment] 2020-11-23 09:35
After further testing I can add the following: Even restoring the Backup from the original Raspi to the original Raspi shows the same behaviour. I restored a previous backup to my working PiHole and checked the box "Clear existing data". The response is the same as mentioned above:
- Entries on the White- and Blacklist created after the backup are not removed
- Local DNS-Entries show also that one entry has been duplicated and nothing else, other entries are untouched
- lighttpd-error-log refers to missing table regex_blacklist in /pi-hole/php/teleporter.php on line 90

So this should at least rule out that the issue is related to armbian as OS or any access-rights issues for scripts and so on.

**Comment by plani-de** [comment] 2020-11-25 10:19
Update: Issue seems to be solved, but not sure why. 

While trying other options of syncing I got annoyed by the Message `bash: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF-8)` showing up always somewhere in between. Running the 'locale' command showed:
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=de_DE.UTF-8
LANGUAGE=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=de_DE.UTF-8
```

Neither  a `dpkg-reconfigure` nor  `locale-gen` would solve this. After editing the /etc/defaults/locale file adding the lines:
```
LC_CTYPE="de_DE.UTF-8"
LC_ALL="de_DE.UTF-8"
LANG="de_DE.UTF-8"
```
I could import the teleporter backups without any problems.

**Comment by dschaper** [comment] 2020-11-25 16:44
Locale is very important for the proper use of data. Saving a backup as one language and trying to restore as another language will fail, as you have seen. Also note in the top copy/paste that some of the UTF callouts are quoted and some are not.

**Closed by dschaper** 2020-11-25 16:44 UTC
