### ISSUE TITLE
iproute2 required for pi-hole install script to run correctly using OSMC base img

### ISSUE THREAD

**Issue by graemefox** [pi-hole/pi-hole#1242] opened 2017-02-12 20:14 UTC
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

0{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---
** OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Running the install script using "curl -sSL https://install.pi-hole.net | bash" should successfully complete the installation process.

**[BUG | ISSUE] Actual Behaviour:**
I am using the latest OSMC disc image for Raspberry Pi 2/3 (Release: 2017.02-2 , md5:	eb684bc872b81924aaa021062079826c) and was getting the following error(s) during the pi-hole install script:

bash: line 192: ip: command not found
::: Using OpenDNS servers.
bash: line 182: ip: command not found

I installed iproute2 using "apt-get install iproute2" and the install script now runs successfully. It is probably worth doing a check that iproute2 is installed on the system?
Thanks,

**[BUG | ISSUE] Steps to reproduce:**
Re-downloaded OSMC image and re-flashed onto SD card.
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment] 2017-02-12 20:23
Already fixed by #1231

**Comment by dschaper** [comment] 2017-02-13 20:39
Duplicate of many other issues.

**Closed by dschaper** 2017-02-13 20:39 UTC
