### ISSUE TITLE
Add an Response for "pihole blacklist --nuke"

### ISSUE THREAD

**Issue by DjCrays** [pi-hole/pi-hole#3845] opened 2020-11-15 21:44 UTC
### Versions
  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version:  Raspbian 10 buster
- Platform:  Rasberry Pi

### Expected behavior

_A clear and concise description of what you expected to happen._

When using pihole blacklist --nuke i should get something like "done - Black list is now empty" or something like this

### Actual behavior / bug

Just shows just the help screen for pihole blacklist -h.

### Steps to reproduce

1. Put something in the blacklist.
2. In an shell just type :" pihole blacklist --nuke"
3. See the response

## Debug Token

- URL:   https://tricorder.pi-hole.net/s1rulqs8gp

**Comment by dschaper** [comment] 2020-11-16 00:35
Are you sure you're not overlooking a warning about readonly databases?

What is the exact output including your input?

**Comment by DjCrays** [comment] 2020-11-16 19:23
Yes i am sure. :) But here is the exact output:

```
pi@raspberrypi:~ $ pihole blacklist --nuke
Usage: pihole -b [options] <domain> <domain2 ...>
Example: 'pihole -b site.com', or 'pihole -b site1.com site2.com'
Blacklist one or more domains

Options:
  -d, --delmode       Remove domain(s) from the blacklist
  -nr, --noreload     Update blacklist without reloading the DNS server
  -q, --quiet         Make output less verbose
  -h, --help          Show this help dialog
  -l, --list          Display all your blacklistlisted domains
  --nuke              Removes all entries in a list
pi@raspberrypi:~ $ 

```

**Comment by dschaper** [comment] 2020-11-16 19:27
Okay, try `sudo bash -x /opt/pihole/list.sh blacklist --nuke`

**Comment by DjCrays** [comment] 2020-11-16 19:32
okay, done: 
```
pi@raspberrypi:~ $ sudo bash -x /opt/pihole/list.sh blacklist --nuke
+ basename=pihole
+ piholeDir=/etc/pihole
+ gravityDBfile=/etc/pihole/gravity.db
+ reload=false
+ addmode=true
+ verbose=true
+ wildcard=false
+ web=false
+ domList=()
+ typeId=
+ comment=
+ declare -i domaincount
+ domaincount=0
+ colfile=/opt/pihole/COL_TABLE
+ source /opt/pihole/COL_TABLE
++ [[ -t 1 ]]
+++ tput colors
++ [[ 256 -ge 8 ]]
++ COL_BOLD=''
++ COL_ULINE=''
++ COL_NC=''
++ COL_GRAY=''
++ COL_RED=''
++ COL_GREEN=''
++ COL_YELLOW=''
++ COL_BLUE=''
++ COL_PURPLE=''
++ COL_CYAN=''
++ COL_WHITE=''
++ COL_BLACK=''
++ COL_LIGHT_BLUE=''
++ COL_LIGHT_GREEN=''
++ COL_LIGHT_CYAN=''
++ COL_LIGHT_RED=''
++ COL_URG_RED=''
++ COL_LIGHT_PURPLE=''
++ COL_BROWN=''
++ COL_LIGHT_GRAY=''
++ COL_DARK_GRAY=''
++ TICK='[✓]'
++ CROSS='[✗]'
++ INFO='[i]'
++ QST='[?]'
++ DONE=' done!'
++ OVER='\r'
+ readonly whitelist=0
+ whitelist=0
+ readonly blacklist=1
+ blacklist=1
+ readonly regex_whitelist=2
+ regex_whitelist=2
+ readonly regex_blacklist=3
+ regex_blacklist=3
+ ((  2  ))
+ case "${1}" in
+ typeId=1
+ shift
+ ((  1  ))
+ case "${1}" in
+ NukeList
+ sqlite3 /etc/pihole/gravity.db 'DELETE FROM domainlist WHERE type = 1;'
+ shift
+ ((  0  ))
+ shift
+ [[ 0 == 0 ]]
+ helpFunc
+ local listname param
++ GetListnameFromTypeId 1
++ [[ 1 == \0 ]]
++ [[ 1 == \1 ]]
++ echo blacklist
+ listname=blacklist
++ GetListParamFromTypeId
++ [[ 1 == \0 ]]
++ [[ 1 == \1 ]]
++ echo b
+ param=b
+ echo 'Usage: pihole -b [options] <domain> <domain2 ...>
Example: '\''pihole -b site.com'\'', or '\''pihole -b site1.com site2.com'\''
Blacklist one or more domains

Options:
  -d, --delmode       Remove domain(s) from the blacklist
  -nr, --noreload     Update blacklist without reloading the DNS server
  -q, --quiet         Make output less verbose
  -h, --help          Show this help dialog
  -l, --list          Display all your blacklistlisted domains
  --nuke              Removes all entries in a list'
Usage: pihole -b [options] <domain> <domain2 ...>
Example: 'pihole -b site.com', or 'pihole -b site1.com site2.com'
Blacklist one or more domains

Options:
  -d, --delmode       Remove domain(s) from the blacklist
  -nr, --noreload     Update blacklist without reloading the DNS server
  -q, --quiet         Make output less verbose
  -h, --help          Show this help dialog
  -l, --list          Display all your blacklistlisted domains
  --nuke              Removes all entries in a list
+ exit 0

```

**Comment by yubiuser** [comment] 2020-11-16 19:43
The syntax is 

`pihole -b --nuke`

**Comment by dschaper** [comment] 2020-11-16 19:43
`+ sqlite3 /etc/pihole/gravity.db 'DELETE FROM domainlist WHERE type = 1;'`

@PromoFaux Looks like the sqlite3 command worked fine, may not have actually removed any records though.

**Comment by dschaper** [comment] 2020-11-16 19:44
> The syntax is
> 
> `pihole -b --nuke`

`pihole blacklist --nuke` should work as well.

**Comment by DjCrays** [comment] 2020-11-16 19:46
> The syntax is
> 
> `pihole -b --nuke`

Also it does not work either.. 🤷🏽  😄 

> > The syntax is
> > `pihole -b --nuke`
> 
> `pihole blacklist --nuke` should work as well.
> 
> ```
> + readonly blacklist=1
> + blacklist=1
> + case "${1}" in
> + typeId=1
> + shift
> + case "${1}" in
> + NukeList
> + sqlite3 /etc/pihole/gravity.db 'DELETE FROM domainlist WHERE type = 1;'
> ```

Not a big deal, since its deleating any EXACT URL but not the RegEx.

**Comment by yubiuser** [comment] 2020-11-16 19:47
You're right.
I just tried it... worked well with my exact blacklist enties

**Comment by dschaper** [comment] 2020-11-16 19:48
> Not a big deal, since its deleating any EXACT URL but not the RegEx.

I don't believe that command is meant to remove regex.

**Comment by DjCrays** [comment] 2020-11-16 19:48
Here some more code:

```
pi@raspberrypi:~ $ pihole -b -l
Not showing empty list
pi@raspberrypi:~ $ pihole -b site1.com site2.com
  [i] Adding site1.com to the blacklist...
  [i] Adding site2.com to the blacklist...
  [✓] Reloading DNS lists
pi@raspberrypi:~ $ pihole -b -l
Displaying blacklist:
  1: site1.com (enabled, last modified Mon, 16 Nov 2020 20:47:48 +0100)
  2: site2.com (enabled, last modified Mon, 16 Nov 2020 20:47:48 +0100)
pi@raspberrypi:~ $ pihole -b --nuke
Usage: pihole -b [options] <domain> <domain2 ...>
Example: 'pihole -b site.com', or 'pihole -b site1.com site2.com'
Blacklist one or more domains

Options:
  -d, --delmode       Remove domain(s) from the blacklist
  -nr, --noreload     Update blacklist without reloading the DNS server
  -q, --quiet         Make output less verbose
  -h, --help          Show this help dialog
  -l, --list          Display all your blacklistlisted domains
  --nuke              Removes all entries in a list
pi@raspberrypi:~ $ pihole -b -l
Not showing empty list
pi@raspberrypi:~ $ 

```

**Comment by yubiuser** [comment] 2020-11-16 19:48
For regex

`pihole blacklist --regex --nuke`

**Comment by DjCrays** [comment] 2020-11-16 19:50
> For regex
> 
> `pihole blacklist --regex --nuke`

Well, it would be nice if there would something in the "pihole blacklist -h" witch states that --regex deals with that... :D Also: Not that big of a deal, since there is not that many people useing that i think, but its a nice to have :)

**Comment by yubiuser** [comment] 2020-11-16 19:52
Still strange that its not working for you but for me.

Try to run the SQL manually and see if it deletes the entries

`sqlite3 /etc/pihole/gravity.db 'DELETE FROM domainlist WHERE type = 1;'`

**Comment by dschaper** [comment] 2020-11-16 19:53
It worked, it just didn't remove the regex lists. The output from the `bash -x` shows that the `sqlite3` call completed without any errors.

**Comment by DjCrays** [comment] 2020-11-16 19:53
> Still strange that its not working for you but for me.
> 
> Try to run the SQL manually and see if it deletes the entries
> 
> `sqlite3 /etc/pihole/gravity.db 'DELETE FROM domainlist WHERE type = 1;'`

Now there is an warning about readonly database..

**Comment by dschaper** [comment] 2020-11-16 20:00
Run `pihole blacklist -l` and you'll see the lists are gone.

**Comment by DjCrays** [comment] 2020-11-16 20:02
> Run `pihole blacklist -l` and you'll see the lists are gone.

Jep, did that allready. But also it would be cool if the Scripts would give some response to the user if it worked or not.

**Comment by dschaper** [comment] 2020-11-16 20:03
I agree, but that may have been the intention and it just didn't work out the way we had hoped. I pinged the person that would know that section the best.

**Comment by dschaper** [comment] 2020-11-16 20:05
Hang on a sec, we don't know if the issue is resolved yet.

**Comment by PromoFaux** [comment] 2020-11-16 22:02
I'm sure this is the second time I've seen this mentioned. I'll have a look in a sec ..

**Comment by PromoFaux** [comment] 2020-11-16 22:16
Yeah, thought so. The errant help output is fixed in this pull:

https://github.com/pi-hole/pi-hole/pull/3349

I've coded a PR to make the output more meaningful https://github.com/pi-hole/pi-hole/pull/3847

**Comment by yubiuser** [comment] 2020-11-29 20:43
Closing as both PRs are merged in master 
https://discourse.pi-hole.net/t/pi-hole-core-web-v5-2-and-ftl-v5-3-released/40909/1

**Closed by yubiuser** 2020-11-29 20:43 UTC
Labels: Investigating, triage: Issue
