### ISSUE TITLE
Web interface: Different output between Firefox/Chromium

### ISSUE THREAD

**Issue by TylonHH** [pi-hole/pi-hole#693] opened 2016-09-15 19:43 UTC
##### Expected Behaviour:
Same web Interface on every Browser

##### Actual Behaviour:
Different Interface

##### Steps to reproduce this issue:
open http://pi.hole/admin/ in FireFox
open http://pi.hole/admin/ in Chrome/ium

When I open the web ui at http://pi.hole/admin in Chromium, the upper left corner shows me the pi-hole logo, the status with color and the temperature of the Pi.
In Firefox, the same page does not show any of these three.

Am I missing anything obvious, or is this a bug?
![ff](https://cloud.githubusercontent.com/assets/18073299/18564784/6d55bd66-7b8d-11e6-97ae-23115e807774.png)
![chromium](https://cloud.githubusercontent.com/assets/18073299/18564791/721cd4f6-7b8d-11e6-8bcb-1afd91511b65.png)

[Source](https://pi-hole.net/forums/topic/web-interface-different-output-between-firefoxchromium/)

**Comment by TylonHH** [comment] 2016-09-15 21:25
and the favicon is not displayed in FF

**Comment by PromoFaux** [comment] 2016-09-18 16:31
Duplicate of pi-hole/AdminLTE/issues/140

Closing this one as it's an issue with the web repo

**Closed by PromoFaux** 2016-09-18 16:31 UTC
