### ISSUE TITLE
PiHole does not install on Buster (Stretch works)

### ISSUE THREAD

**Issue by stevenwalton** [pi-hole/pi-hole#2946] opened 2019-09-27 23:09 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [?] The issue I am reporting can be *replicated*. 
Someone else on Reddit reported they had a similar issue and that's how I found the solution.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

Install does no work on Raspbian Buster

**Actual behaviour:**
I'm using a RPi-3b+. I've checked multiple guides which all make it look trivial, so I don't think I'm doing anything weird.

I first tried with raspbian lite since this is going to be headless (I am at all times connected via ssh). Tried the two line because I don't like piping bash. Didn't work after full updates. I notice that I can't even ping outside the local network. The failure I get is at FTL (it always fails here and after install I can't access wide area networks, only local). I tried the git approach. Even the one line installer. All the same. So I decided to try the full raspbian. Updated then tried all the methods again (after flashing each time). The full output is below.

I take all the defaults except for using Cloudflare. The install fails on FTL. I've checked pings and pulls to the FTL lines in the bash script. I get the correct version numbers and stuff through my local machine.

After the install I have /etc/.pihole and /etc/pihole (which only contains adlists.list). `ps aux | grep -i pihole` shows nothing (nor pi-hole. And nothing relevant for pi). `find / -name pihole` only returns me the two /etc directories and the clone of the repo that I have. The pihole command does not get added to `PATH` but I can run it from `/etc/.pihole`. As probably guessed, I don't get much from running this. Uninstall, disable, and restartdns fails because there's nothing in `/opt`.

This problem was **solved** by downgrading to Raspbian Stretch.  So it appears Buster is the issue. These were fresh installs as of yesterday's image. 

```bash
pi@raspberrypi:~/Downloads/Pi-hole/automated install $ sudo ./basic-install.sh
[✓] Root user check
[✓] Disk space check
[✓] Update local cache of available packages
[✓] Checking apt-get for upgraded packages... up to date!
[i] Installer Dependency checks...
[✓] Checking for apt-utils
[i] Checking for dialog (will be installed)
[✓] Checking for debconf
[✓] Checking for dhcpcd5
[✓] Checking for git
[✓] Checking for iproute2
[✓] Checking for whiptail
[i] Using Cloudflare
[✓] Set IP address to 192.168.x.xxx
You may need to restart after the install is complete
[i] Unable to find IPv6 ULA/GUA address, IPv6 adblocking will not be enabled
[i] IPv4 address: 192.168.``x``.``xxx``/24
[i] IPv6 address:
[i] Web Interface On
[i] Web Server On
[i] Logging On.
[✗] Check for existing repository in /etc/.pihole
[✓] Clone https://github.com/pi-hole/pi-hole.git into /etc/.pihole
[✗] Check for existing repository in /var/www/html/admin
[✓] Clone https://github.com/pi-hole/AdminLTE.git into /var/www/html/admin
[i] Main Dependency checks...
[✓] Checking for cron
[✓] Checking for curl
[i] Checking for dnsutils (will be installed)
[✓] Checking for iputils-ping
[✓] Checking for lsof
[i] Checking for netcat (will be installed)
[✓] Checking for psmisc
[✓] Checking for sudo
[✓] Checking for unzip
[✓] Checking for wget
[i] Checking for idn2 (will be installed)
[i] Checking for sqlite3 (will be installed)
[✓] Checking for libcap2-bin
[i] Checking for dns-root-data (will be installed)
[i] Checking for resolvconf (will be installed)
[✓] Checking for libcap2
[i] Checking for lighttpd (will be installed)
[i] Checking for php-common (will be installed)
[i] Checking for php-cgi (will be installed)
[i] Checking for php-sqlite3 (will be installed)
[✓] Enabling lighttpd service to start on reboot...
[i] FTL Checks...
[✓] Detected ARM-hf architecture (armv6 or lower) Using ARM binary
[i] Checking for existing FTL binary...
[✗] Downloading and Installing FTL
Error: Unable to get latest release location from GitHub
[✗] FTL Engine not installed
```

**Comment by Mcat12** [comment] 2019-09-28 00:46
Try changing `/etc/resolv.conf` to use an external DNS server, then try again.

**Comment by stevenwalton** [comment] 2019-09-28 04:07
I'm not going to flash again today since I do have a working install, might try again later.

This issue is more about that the instructions need to be updated. If the solution is to fix the external DNS then this needs to be documented. If Buster just doesn't work, then this also needs to be updated. But clearly there's an issue of a product that is aimed at raspberry pi and aims for a one command install doesn't do those things.

**Comment by dschaper** [comment] 2019-09-28 17:50
Currently it doesn't do it for you. It does it for a great number of other people and it does it for all of our tests. Buster is officially supported and working so we need to find out from a non-working system exactly what the problem is. If you do choose to flash again then we can go through the steps of troubleshooting to see where problems may be. Part of that troubleshooting is running the debug command that we have created to make the process faster and easier for all parties involved.

**Comment by Mister-Chief117** [comment] 2019-09-28 18:13
I am also experiencing this issue on Raspbian Buster.

**Comment by dschaper** [comment] 2019-09-28 18:57
Can you provide us a debug token then?

**Comment by stevenwalton** [comment] 2019-09-28 19:56
Can you give us more information with what exactly you want? We're dealing with one line installs here. I don't remember seeing a debug file being produced when I did my install (I was looking for one). Or do you need a different install method?

**Comment by dschaper** [comment] 2019-09-28 20:00
Does the `pihole` command exist on your system? If it does then run `pihole -d` for the token and debug information. If it does not please run `curl -sSL https://install.pi-hole.net | sudo bash -x` for a verbose install that will output the exact commands and responses during the installation attempt.

**Comment by stevenwalton** [comment] 2019-09-28 20:03
When I had gotten the failed install, the  `pihole` command did not exist (I was also shut out of WAN). @Mister-Chief117 was this the same for you? Can you provide the `-x` info?

**Comment by TheEliteGeek** [comment] 2019-09-28 22:27
It was the same for me. Ultimately I jumped the gun on saying "it was broken" as I was able to resolve it by updating the DNS entry in resolv.conf (I updated it to 8.8.8.8) and then re-attempted the install and it worked. I had to reboot the Pi after the install.

I wasn't able to get "Conditional Forwarding" to work, however. After a few attempts, I gave up and just told Pi-Hole to manage DHCP and now everything works as expected.

**Comment by fluxsauce** [comment] 2019-10-06 04:28
FWIW, worked without issue for me on a fresh install of `2019-09-26-raspbian-buster-lite.img` on a Raspberry Pi 3 Model B Rev 1.2.

**Comment by dschaper** [comment] 2019-10-12 15:47
Any more information or can we close this?

**Closed** 2019-10-17 09:44 UTC
Labels: Submitter Attention Required, triage: Issue

**Comment by axelfoley67** [comment] 2020-01-01 04:48
I ran into problems with the install too (hence found this page :-)). 
Clean updated Buster Lite (i.e. No GUI) on RPi 3 Model B+. No admin page and no pihole command, install log file or web server installed.

I had run this: ~ $ curl -sSL https://install.pi-hole.net | bash. 

Even though it will walk through the setup screens and allow you to configure them, this install ultimately fails.

I then tried ~ $ sudo curl -sSL https://install.pi-hole.net | bash - this will also fail.

I had to elevate my session as per below:

~ $ sudo bash
root@<servername>:/home/pi# cd /
root@<servername>:/# whoami
root
root@<servername>:/# curl -sSL https://install.pi-hole.net | bash

Then it installed and configured with no issues.

To check if you have the same issue, scroll back up on the failed installation screen (once you exit the blue installation screens) and you will see the following text:

[✗] Root user check **<--- this will have a red x**
  [i] Script called with non-root privileges **<--- this text will be in red** 
      The Pi-hole requires elevated privileges to install and run
     
 Hope this helps.
