### ISSUE TITLE
Pi-hole requires non configured DNS server

### ISSUE THREAD

**Issue by evlewt** [pi-hole/pi-hole#4708] opened 2022-04-21 16:19 UTC
### Versions

- Pi-hole:  5.10
- AdminLTE:  5.12
- FTL:  5.15

### Platform
- OS and version:  Debian 11

### Expected behavior

Pi-hole updates using `pihole -up`

### Actual behavior / bug

When running `pihole -up` the update process fails:
```
[✗] Retrieval of supported OS list failed. dig failed with return code 9. 
      Unable to determine if the detected OS (Debian 11) is supported
```

### Steps to reproduce

1. block all DNS requests from Pi-hole except to the configured DNS server
2. run `pihole -up` => error
3. echo "127.0.0.1 ns1.pi-hole.net" >> /etc/hosts
4. run `pihole -up` => success

### Additional context

The issue is that the update process is trying to use the DNS server `ns1.pi-hole.net` (IP: 205.251.193.151). If requests to all DNS server except the configured DNS server is blocked, the update process will fail with the error message provided (see: Actual behavior / bug).

**Comment by PromoFaux** [comment] 2022-04-21 16:27
This is by design, instructions to skip this check are even included in the output (should be, at least - example output [here](https://docs.pi-hole.net/main/prerequisites/)

Here is a previous conversation on the subject:

https://github.com/pi-hole/pi-hole/issues/3694

Note the closing remark, however, it is by design.

**Closed by PromoFaux** 2022-04-21 16:27 UTC

**Comment by evlewt** [comment] 2022-04-21 16:34
Thanks for the quick answer! And sorry for not finding #3694.
