### ISSUE TITLE
CHIP computer PiHole install script not detecting / FS

### ISSUE THREAD

**Issue by CDeeRON** [pi-hole/pi-hole#602] opened 2016-07-30 23:25 UTC
##### Expected Behaviour:
`existingFreeBytes=$(df -k / 2>&1 | awk '{print $4}' | head -2 | tail -1)`
`3206688`
##### Actual Behaviour:
`existingFreeBytes=$(df -lk / 2>&1 | awk '{print $4}' | head -2 | tail -1)`
`systems`
##### Steps to reproduce this issue:
Install Pi-hole on CHIP computer

**Comment by Mcat12** [comment] 2016-07-31 18:32
Can you specify what the issue is?

**Comment by CDeeRON** [comment] 2016-07-31 21:34
The install script isn't picking up / fs on CHIP computer.

**Comment by dschaper** [comment] 2016-07-31 21:41
Okay, so root free space is coming back as a string and not an actual value. I'll add that to the list.

**Comment by Fourdee** [comment] 2016-08-10 16:50
@dschaper @Mcat12 
Try this. It will find the entry in ```df``` that has a ```/``` at the end of the line. RootFS being the only entry to have this.
```
df -Pk | grep -m1 '\/$' | awk '{print $4}'
```

Example result:
```
root@DietPi:~# df -Pk | grep -m1 '\/$'
/dev/mmcblk0p2   120091852 984744 119090724       1% /
root@DietPi:~# df -Pk | grep -m1 '\/$' | awk '{print $4}'
119090724
```

**Comment by CDeeRON** [comment] 2016-08-11 21:23
@Fourdee 

```
chip@chip:~$ df -k
Filesystem     1K-blocks   Used Available Use% Mounted on
udev               10240      0     10240   0% /dev
tmpfs             101584  14984     86600  15% /run
ubi0:rootfs      3777124 650964   3126160  18% /
tmpfs             253956      0    253956   0% /dev/shm
tmpfs               5120      4      5116   1% /run/lock
tmpfs             253956      0    253956   0% /sys/fs/cgroup
tmpfs              50792      0     50792   0% /run/user/1000
chip@chip:~$ df -Pk | grep -m1 '\/$' | awk '{print $4}'
3126160
```

**Comment by CDeeRON** [comment] 2016-08-11 21:25
not sure `-P` is needed though...thoughts?

**Comment by Fourdee** [comment] 2016-08-12 10:09
@CDeeRON 

> not sure -P is needed though...thoughts?

Nope, its not needed. Its an attempt to "standardize" the output:
```
root@DietPi-XU4:~# df --help | grep '\-P'
  -P, --portability     use the POSIX output format
```

> `-P'
`--portability'
Use the POSIX output format. This is like the default format except for the following:
- The information about each filesystem is always printed on exactly one line; a mount device is never put on a line by itself. This means that if the mount device name is more than 20 characters long (e.g., for some network mounts), the columns are misaligned.
- Non-integer values are rounded up, instead of being rounded down or rounded to the nearest integer.
- The labels in the header output line are changed to conform to POSIX.

> http://askubuntu.com/questions/55702/df-h-command-puts-line-breaks-in-output-how-do-i-fix

**Comment by CDeeRON** [comment] 2016-08-12 10:19
@Fourdee would you mind creating a PR with your change? I prefer yours over the one I came up with...haha I already closed my PR.

**Comment by Fourdee** [comment] 2016-08-12 10:26
@CDeeRON 
Yep, development branch?

**Comment by CDeeRON** [comment] 2016-08-12 10:31
yeah

**Comment by Fourdee** [comment] 2016-08-12 11:49
if ```existingFreeBytes``` is invalid int, added option to override:
![image](https://cloud.githubusercontent.com/assets/7077026/17621433/300c406e-608b-11e6-9e95-7d91782084e4.png)

**Comment by CDeeRON** [comment] 2016-08-12 11:51
Nice

**Comment by dschaper** [comment] 2016-10-14 03:33
Bug should be resolved in released code. Please notify if this is not working.

**Closed by dschaper** 2016-10-14 03:33 UTC
