### ISSUE TITLE
Error flushing logs -> logrotate

### ISSUE THREAD

**Issue by woftor** [pi-hole/pi-hole#1193] opened 2017-01-29 16:21 UTC
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
1

---
**[OTHER]:**

**[BUG | ISSUE] Expected Behaviour:**
`'pihole -f'` or flushing the logs in the web-interface should actually flush the logs

**[BUG | ISSUE] Actual Behaviour:**
It does not flush, but throws an error:

> ::: Flushing /var/log/pihole.log ...error: skipping "/var/log/pihole.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.

**[BUG | ISSUE] Steps to reproduce:**

-`pihole -f`

I found out that there is an error in the file /etc/pihole/logrotate and that this is the reason it does not work (at least on Ubuntu 16.04).  The file looks like this:

> /var/log/pihole.log {
>         daily
>         copytruncate
>         rotate 5
>         compress
>         delaycompress
>         notifempty
>         nomail
> }
> su root syslog

But the last statement is on the wrong line. The working one (again, on my Ubuntu 16.04 machine) is:

> /var/log/pihole.log {
>         daily
>         copytruncate
>         rotate 5
>         compress
>         delaycompress
>         notifempty
>         nomail
>         su root syslog
> }

**Comment by DL6ER** [comment] 2017-01-29 16:26
I cannot reproduce this. `logrotate` is working for me with both variants of the file. The latter one specifies that `su root syslog` belongs only to `/var/log/pihole.log`, while the first one makes it a global property - which has essentially the same effect.

**Comment by DL6ER** [comment] 2017-01-29 16:49
Can you specify which Ubuntu version you used exactly (like Ubuntu 16.04.1 x64)? I will do a fresh installation of this version then and try to reproduce your issue with this machine.

**Comment by woftor** [comment] 2017-01-29 16:53
I reproduced several times swichting between the files.
My exact version is:

> Description:    Ubuntu 16.04.1 LTS
> (GNU/Linux 4.4.0-59-generic x86_64)

**Comment by Mcat12** [comment] 2017-01-29 18:02
I can't reproduce this on my Pi, although it is sometimes used for dev work so it's not exactly a fully production Pi.

**Comment by DL6ER** [comment] 2017-01-29 19:02
Thanks!

I was able to confirm your issue on specifically this version (Ubuntu 16.04.1 x64). We tested Ubuntu 16.10, two versions of Debian and Raspbian and all of them are fine. I have a fix for this, currently reinstalling Ubuntu 16.04 from scratch on my test machine to confirm that it is working now.

**Comment by woftor** [comment] 2017-01-29 19:41
Thanks bro.

**Comment by xxcriticxx** [comment] 2017-01-31 11:51
how do i fix this manual way before next release?

**Comment by woftor** [comment] 2017-01-31 11:58
> how do i fix this manual way before next release?

Read the first post.

**Comment by xxcriticxx** [comment] 2017-01-31 18:43
@woftor thx

**Closed** 2017-01-31 20:33 UTC
Labels: Confirmed Bug, Fixed in next release
