### ISSUE TITLE
Pi-Hole Fails to Auto Start on Debian Buster

### ISSUE THREAD

**Issue by jedimasterjonny** [pi-hole/pi-hole#2813] opened 2019-06-24 20:27 UTC
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

4
---
**Expected behaviour:**

Pi-hole starts serving DNS requests immediately upon system boot, and during Pi-hole install.

**Actual behaviour:**

Pi-hole fails to serve DNS requests until an Pihole restartdns is issued.

Furthermore, the install script crashed halfway after the system wide DNS server had been changed to 127.0.0.1, as github could not be resolved during the second repository checkout

**Steps to reproduce:**

* Install Raspbian Buster Lite
* Run the standard pi-hole installer script - observe crash halfway through due to name resolution failiure
* Manually change the static dhcpcd DNS entry to something other than localhost
* Re run the standard pi-hole installer script - installation completes
* Reboot - find DNS resolution fails
* pihole restartdns - DNS starts working
* Reboot again - behaviour is repeatable

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

mnc57pqv3g

**Troubleshooting undertaken, and/or other relevant information:**

* Run pi-hole repair twice
* Status of pihole-FTL service:

```● pihole-FTL.service - LSB: pihole-FTL daemon
   Loaded: loaded (/etc/init.d/pihole-FTL; generated)
   Active: active (exited) since Mon 2019-06-24 21:11:01 BST; 8min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 6867 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)

Jun 24 21:11:01 ithilien systemd[1]: Starting LSB: pihole-FTL daemon...
Jun 24 21:11:01 ithilien pihole-FTL[6867]: Not running
Jun 24 21:11:01 ithilien su[6909]: (to pihole) root on none
Jun 24 21:11:01 ithilien su[6909]: pam_unix(su:session): session opened for user pihole by (uid=0)
Jun 24 21:11:01 ithilien pihole-FTL[6867]: FTL started!
Jun 24 21:11:01 ithilien su[6909]: pam_unix(su:session): session closed for user pihole
Jun 24 21:11:01 ithilien systemd[1]: Started LSB: pihole-FTL daemon.
```

* Log of pihole-FTL, showing SIGHUP at 20:36:38, 30 seconds after boot which was required to make DNS resolution work:

```[2019-06-24 20:35:22.264 1018] ########## FTL terminated after 372582.8 ms! ##########
[2019-06-24 20:36:10.029 739] Using log file /var/log/pihole-FTL.log
[2019-06-24 20:36:10.030 739] ########## FTL started! ##########
[2019-06-24 20:36:10.030 739] FTL branch: master
[2019-06-24 20:36:10.030 739] FTL version: v4.3.1
[2019-06-24 20:36:10.030 739] FTL commit: b60d63f
[2019-06-24 20:36:10.030 739] FTL date: 2019-05-25 21:37:26 +0200
[2019-06-24 20:36:10.030 739] FTL user: pihole
[2019-06-24 20:36:10.030 739] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
[2019-06-24 20:36:10.030 739]    SOCKET_LISTENING: only local
[2019-06-24 20:36:10.030 739]    AAAA_QUERY_ANALYSIS: Show AAAA queries
[2019-06-24 20:36:10.030 739]    MAXDBDAYS: max age for stored queries is 365 days
[2019-06-24 20:36:10.030 739]    RESOLVE_IPV6: Resolve IPv6 addresses
[2019-06-24 20:36:10.030 739]    RESOLVE_IPV4: Resolve IPv4 addresses
[2019-06-24 20:36:10.030 739]    DBINTERVAL: saving to DB file every 3600 seconds
[2019-06-24 20:36:10.031 739]    DBFILE: Using /etc/pihole/pihole-FTL.db
[2019-06-24 20:36:10.031 739]    MAXLOGAGE: Importing up to 24.0 hours of log data
[2019-06-24 20:36:10.031 739]    PRIVACYLEVEL: Set to 0
[2019-06-24 20:36:10.031 739]    IGNORE_LOCALHOST: Show queries from localhost
[2019-06-24 20:36:10.031 739]    BLOCKINGMODE: Null IPs for blocked domains
[2019-06-24 20:36:10.031 739]    ANALYZE_ONLY_A_AND_AAAA: Disabled. Analyzing all queries
[2019-06-24 20:36:10.031 739]    DBIMPORT: Importing history from database
[2019-06-24 20:36:10.031 739]    PIDFILE: Using /var/run/pihole-FTL.pid
[2019-06-24 20:36:10.031 739]    PORTFILE: Using /var/run/pihole-FTL.port
[2019-06-24 20:36:10.031 739]    SOCKETFILE: Using /var/run/pihole/FTL.sock
[2019-06-24 20:36:10.031 739]    WHITELISTFILE: Using /etc/pihole/whitelist.txt
[2019-06-24 20:36:10.031 739]    BLACKLISTFILE: Using /etc/pihole/black.list
[2019-06-24 20:36:10.031 739]    GRAVITYFILE: Using /etc/pihole/gravity.list
[2019-06-24 20:36:10.031 739]    REGEXLISTFILE: Using /etc/pihole/regex.list
[2019-06-24 20:36:10.031 739]    SETUPVARSFILE: Using /etc/pihole/setupVars.conf
[2019-06-24 20:36:10.031 739]    AUDITLISTFILE: Using /etc/pihole/auditlog.list
[2019-06-24 20:36:10.031 739]    MACVENDORDB: Using /etc/pihole/macvendor.db
[2019-06-24 20:36:10.031 739]    PARSE_ARP_CACHE: Active
[2019-06-24 20:36:10.031 739] Finished config file parsing
[2019-06-24 20:36:10.060 739] Database version is 3
[2019-06-24 20:36:10.061 739] Database successfully initialized
[2019-06-24 20:36:10.065 739] New forward server: 1.0.0.1 (0/512)
[2019-06-24 20:36:10.065 739] New forward server: 1.1.1.1 (1/512)
[2019-06-24 20:36:10.069 739] Resizing "/FTL-strings" from 4096 to 8192
[2019-06-24 20:36:10.069 739] New forward server: 127.0.0.1 (2/512)
[2019-06-24 20:36:10.071 739] Imported 863 queries from the long-term database
[2019-06-24 20:36:10.071 739]  -> Total DNS queries: 863
[2019-06-24 20:36:10.071 739]  -> Cached DNS queries: 196
[2019-06-24 20:36:10.071 739]  -> Forwarded DNS queries: 667
[2019-06-24 20:36:10.071 739]  -> Exactly blocked DNS queries: 0
[2019-06-24 20:36:10.071 739]  -> Unknown DNS queries: 0
[2019-06-24 20:36:10.071 739]  -> Unique domains: 216
[2019-06-24 20:36:10.071 739]  -> Unique clients: 6
[2019-06-24 20:36:10.071 739]  -> Known forward destinations: 3
[2019-06-24 20:36:10.071 739] Successfully accessed setupVars.conf
[2019-06-24 20:36:10.083 741] PID of FTL process: 741
[2019-06-24 20:36:10.083 741] Listening on port 4711 for incoming IPv4 telnet connections
[2019-06-24 20:36:10.084 741] Listening on port 4711 for incoming IPv6 telnet connections
[2019-06-24 20:36:10.084 741] Listening on Unix socket
[2019-06-24 20:36:10.086 741] Received SIGHUP, reloading cache
[2019-06-24 20:36:10.087 741] Blocking status is enabled
[2019-06-24 20:36:10.088 741] Compiled 0 Regex filters and 10 whitelisted domains in 0.9 msec (0 errors)
[2019-06-24 20:36:10.089 741] /etc/pihole/black.list: parsed 0 domains (took 0.1 ms)
[2019-06-24 20:36:11.494 741] /etc/pihole/gravity.list: parsed 114864 domains (took 1402.9 ms)
[2019-06-24 20:36:38.429 741] Received SIGHUP, reloading cache
[2019-06-24 20:36:38.430 741] Blocking status is enabled
[2019-06-24 20:36:38.430 741] Compiled 0 Regex filters and 10 whitelisted domains in 0.1 msec (0 errors)
[2019-06-24 20:36:38.678 741] /etc/pihole/black.list: parsed 0 domains (took 0.1 ms)
[2019-06-24 20:36:39.524 741] /etc/pihole/gravity.list: parsed 114864 domains (took 845.2 ms)
[2019-06-24 21:04:54.812 741] Resizing "/FTL-strings" from 8192 to 12288
[2019-06-24 21:11:01.147 741] Shutting down...
[2019-06-24 21:11:01.349 741] Finished final database update
[2019-06-24 21:11:01.349 741] delete_shm(): shm_unlink(/FTL-lock) failed: No such file or directory
[2019-06-24 21:11:01.349 741] delete_shm(): shm_unlink(/FTL-strings) failed: No such file or directory
[2019-06-24 21:11:01.350 741] delete_shm(): shm_unlink(/FTL-counters) failed: No such file or directory
[2019-06-24 21:11:01.350 741] delete_shm(): shm_unlink(/FTL-domains) failed: No such file or directory
[2019-06-24 21:11:01.350 741] delete_shm(): shm_unlink(/FTL-clients) failed: No such file or directory
[2019-06-24 21:11:01.350 741] delete_shm(): shm_unlink(/FTL-queries) failed: No such file or directory
[2019-06-24 21:11:01.350 741] delete_shm(): shm_unlink(/FTL-forwarded) failed: No such file or directory
[2019-06-24 21:11:01.350 741] delete_shm(): shm_unlink(/FTL-overTime) failed: No such file or directory
[2019-06-24 21:11:01.350 741] delete_shm(): shm_unlink(/FTL-settings) failed: No such file or directory
```

**Comment by dschaper** [comment] 2019-06-24 20:28
Buster is not currently supported. Please install on a supported distribution: https://docs.pi-hole.net/main/prerequesites/#supported-operating-systems

**Comment by jedimasterjonny** [comment] 2019-06-24 20:31
My apologies - hopefully this will be useful to you anyway when Buster devolopment begins.

P.S Thanks for all you do!

**Comment by dschaper** [comment] 2019-06-24 20:32
Thank you for the output. I'll keep this open so that others may see and not create duplicate issues.

**Comment by filips123** [comment] 2019-06-26 10:15
Buster is now the default version of Raspbian available on [Raspberry Pi Downloads](https://www.raspberrypi.org/downloads/raspbian/).

Pi-Hole should really be compatible with it, as it will probably be used on all new Raspbian installations.

**Comment by tlk** [comment] 2019-06-27 03:13
I installed Raspbian Buster and opted in for so-called "predictable network interface names" thinking that sounded like a good thing, but ... eventually I went with the traditional "eth0" ;-)

This seems to work:
```
sudo raspi-config   # Network options, Network interface names, select "No" to predictable network interface names

sudo pihole -r      # Select "Reconfigure" in the menu

sudo sed 's/create-mime\.assign/create-mime.conf/' -i /etc/lighttpd/lighttpd.conf
sudo systemctl restart lighttpd.service
sudo systemctl enable pihole-FTL.service
pihole updateGravity
```

Set web admin password:
```
pihole -a -p
```

Then access the web admin interface via http://raspberrypi.local/admin/

**Comment by Kentsson** [comment] 2019-06-27 13:48
Anyone looking for Raspbian Stretch Lite can find it on their offical page:
https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/

Had a hard time finding the ISO myself.

**Comment by jshamg** [comment] 2019-06-27 17:18
+1 for Buster support

**Comment by dschaper** [comment] 2019-06-27 18:01
We support a number of distributions, Raspbian Buster released before the upstream Debian has released. We will support it when we can, there's already a pull request with the fix in it if you would like to change the files yourself.

**Comment by jshamg** [comment] 2019-06-27 18:39
don't worry, development takes time. I know this. just leave it open until issue is solved, i use strech for now... @Kentsson thx btw for the link!

**Comment by lenny76** [comment] 2019-06-28 12:50
> sudo systemctl enable pihole-FTL.service

t

> I installed Raspbian Buster and opted in for so-called "predictable network interface names" thinking that sounded like a good thing, but ... eventually I went with the traditional "eth0" ;-)
> 
> This seems to work:
> 
> ```
> sudo raspi-config   # Network options, Network interface names, select "No" to predictable network interface names
> 
> sudo pihole -r      # Select "Reconfigure" in the menu
> 
> sudo sed 's/create-mime\.assign/create-mime.conf/' -i /etc/lighttpd/lighttpd.conf
> sudo systemctl restart lighttpd.service
> sudo systemctl enable pihole-FTL.service
> pihole updateGravity
> ```
> 
> Set web admin password:
> 
> ```
> pihole -a -p
> ```
> 
> Then access the web admin interface via http://raspberrypi.local/admin/

this works
thanks

**Comment by Mcat12** [comment] 2019-06-29 20:03
Fixed in v4.3.1

**Closed by Mcat12** 2019-06-29 20:03 UTC
Labels: triage: Issue

**Comment by filips123** [comment] 2019-06-29 20:10
@Mcat12 You also need to add Buster to list of supported systems.

**Comment by Mcat12** [comment] 2019-06-29 20:11
That is on the list of things to do.

**Comment by jedimasterjonny** [comment] 2019-06-29 21:48
FWIW - My problem was never related to lighttpd, I was applying the fix maunally (although I never said this in my first post, my bad!).

Pi-Hole works absolutely fine, but not at startup, a `pihole restartdns` is required after the system first boots to make DNS resolution work.

I think some of the commentors just assumed this was my problem and/or used this thread as 'general Buster bugs', so my original issue got lost, from my first post:

>* Reboot - find DNS resolution fails
>* pihole restartdns - DNS resolution starts working
>* Reboot again - behaviour is repeatable

Sorry if this is also fixed, I'm not sure what commit(s) constitue 4.3.1, but from above it looks like you've closed this because of the lighttpd fix.

If no one else is seeing this it could be related to the fact I installed Buster Lite?

**Comment by Mcat12** [comment] 2019-06-29 21:55
To start with a clean history, please make a new issue if you can reproduce this on a fresh install of Buster on v4.3.1.

**Comment by richerve** [comment] 2020-03-18 11:07
I'm also seeing the same behaviour in Ubuntu server arm64 version on the raspberrypi. I presume is something related to the init.d script but haven't debug it.

**Comment by bcutter** [comment] 2021-02-05 23:43
Pi-Hole 5.2.4 (Web 5.3.2, FTL 5.6) on a Raspberry Pi OS (Buster). After reboot Pi-Hole is not working (DNS service not running), a "pihole restartdns" works around it.

System ran for few weeks where some Pi-Hole updates have been applied meanwhile. No idea what broke it but that´s a new and ugly behaviour... :-( Any ideas?

**Comment by bcotton** [comment] 2022-02-12 16:21
Pi-hole [v5.8.1](https://github.com/pi-hole/pi-hole/releases/v5.8.1) FTL [v5.13](https://github.com/pi-hole/FTL/releases/v5.13) Web Interface [v5.10.1](https://github.com/pi-hole/AdminLTE/releases/v5.10.1)
Fresh install of 64 bit Raspberry PI OS (ubuntu)

Same problems, works after install. After reboot, a "pihole restartdns" fixes the probem

**Comment by bcutter** [comment] 2022-02-12 16:48
3 years. Wow.

Still very annoyed because of this.

**Comment by yubiuser** [comment] 2022-02-12 17:07
> 3 years. Wow.
Still very annoyed because of this.

What makes you believe this is still the same issue?

Please open a new issue.
