### ISSUE TITLE
CentOS 7 installer crashes out if nmcli is not available

### ISSUE THREAD

**Issue by slacker87** [pi-hole/pi-hole#1653] opened 2017-08-10 14:36 UTC
The CentOS/Fedora portion of the installer should do a basic sanity check to verify the NetworkManager service is running, if not it should start the service for the user via:` systemctl start NetworkManager`

Currently if the service is installed but not running the installer will just crash back to bash with a `Error: NetworkManager is not running.` Error message which leaves the user to search the web for an answer.

**Comment by jacobsalmela** [comment] 2017-11-25 21:05
@bcambl I tested on a fresh droplet and was not able to reproduce this.  Is `NetworkMangler` supposed to be installed by default on CentOS?

**Comment by bcambl** [comment] 2017-11-25 21:09
Yes. `NetworkManager` should be enabled by default.

**Comment by jacobsalmela** [comment] 2017-12-08 01:17
@bcambl did we fix this one for 3.2?

**Comment by bcambl** [comment] 2017-12-08 02:44
No this was not addressed in 3.2 but I will address this shortly.

**Comment by jacobsalmela** [comment] 2017-12-08 03:44
Great thanks!

**Comment by bcambl** [comment] 2017-12-08 04:12
@slacker87 Thanks for submitting an issue. Cheers!

**Closed** 2017-12-22 20:53 UTC
Labels: Fixed in next release
