### ISSUE TITLE
Pihole API /status always shows disabled

### ISSUE THREAD

**Issue by nate8199** [pi-hole/pi-hole#4556] opened 2022-01-11 23:24 UTC
### Versions
  Pi-hole version is v5.8.1 (Latest: v5.8.1)
  AdminLTE version is v5.10.1 (Latest: v5.10.1)
  FTL version is v5.13 (Latest: v5.13)

### Platform
Debian 11 VM
- OS and version:  
Debian 11 KVM Host
- Platform:  

### Expected behavior

http://pi.hole/admin/api.php?status&auth=xxxxxxxxxxxxxxxxx
when disabled says disabled, when enabled says enabled

### Actual behavior / bug

json returned always shows {"status":"disabled"}

### Steps to reproduce

Update to latest version
update OS
restart
disable pihole and check status with API
enable pihole and check status with API

## Debug Token

- URL:  

### Additional context

I just updated from an unknown version to the latest yesterday, I noticed today that my trending shows that Pihole has been disabled since then.  I have two instances going, and both have the same behavior.
I did verify that pihole is actually enabled, by trying to get to a blocked site.

**Comment by rdwebdesign** [comment] 2022-01-12 00:22
Duplicate of pi-hole/AdminLTE#2051, pi-hole/AdminLTE#2053, pi-hole/AdminLTE#2056, pi-hole/AdminLTE#2064

Fixed by pi-hole/AdminLTE#2052

**Comment by nate8199** [comment] 2022-01-12 00:27
Thank you, I will try the development version.
I was just coming back to say my previous update was on 2021-11-01

**Closed** 2022-01-12 00:26 UTC
