### ISSUE TITLE
[$50] Blocking Hulu [$50]

### ISSUE THREAD

**Issue by jrtoman** [pi-hole/pi-hole#371] opened 2016-03-08 16:39 UTC
##

**Comment by Mcat12** [comment] 2016-03-08 17:05
I believe we tried messing around with blocking video ads, but haven't really gotten it to work. If you tail the DNS log while reproducing the issue, you should see what domains are being blocked. Some of them might be needed to watch the video correctly, so it's a trial and error kind of solution.

**Comment by PromoFaux** [comment] 2016-03-08 17:15
running the following command shows the domains in the blocklists that contain the string 'hulu'

`for list in /etc/pihole/list.*;do echo $list;grep 'hulu' $list;done`

from which I get the following output:

```
/etc/pihole/list.0.raw.githubusercontent.com.domains
0.0.0.0 ads.hulu.com
0.0.0.0 ads-a-darwin.hulu.com
0.0.0.0 ads-v-darwin.hulu.com
0.0.0.0 a.huluad.com
0.0.0.0 hulu.112.2o7.net
0.0.0.0 huludev.112.2o7.net
#0.0.0.0 ll.a.hulu.com  # Uncomment to block Hulu.
#0.0.0.0 t2.hulu.com            # Uncomment to block Hulu.
#0.0.0.0 track.hulu.com # Uncomment to block Hulu.
#0.0.0.0 ad.hulu.com            # Uncomment to block Hulu.
0.0.0.0 ads.hulu.com.edgesuite.net
#0.0.0.0 ads.hulu.com           # Uncomment to block Hulu.
/etc/pihole/list.1.adblock.gjtech.net.domains
/etc/pihole/list.2.mirror1.malwaredomains.com.domains
blackhulu.com
/etc/pihole/list.3.sysctl.org.domains
127.0.0.1        a.huluad.com
127.0.0.1        ads-a-darwin.hulu.com
127.0.0.1        ads-v-darwin.hulu.com
127.0.0.1        ads.hulu.com
127.0.0.1        hulu.112.2o7.net
127.0.0.1        huludev.112.2o7.net
127.0.0.1        ll.a.hulu.com
/etc/pihole/list.4.zeustracker.abuse.ch.domains
/etc/pihole/list.5.s3.amazonaws.com.domains
/etc/pihole/list.6.s3.amazonaws.com.domains
/etc/pihole/list.7.hosts-file.net.domains
127.0.0.1       hulu.112.2o7.net
127.0.0.1       t-ak.hulu.com
127.0.0.1       t2.hulu.com
127.0.0.1       t2.huluim.com
127.0.0.1       tw.i.hulu.com
127.0.0.1       urlcheck.hulu.com
/etc/pihole/list.8.raw.githubusercontent.com.domains
```

I'm in the UK, and don't have hulu over here, but if you use [this chrome extension](https://chrome.google.com/webstore/detail/whitelist-assistant-by-dn/fdmpekabnlekabjlimjkfmdjajnddgpc) you should be able to see what domains are being requested when you try to watch a hulu stream, and then cross reference those with the blocklists by running the above command (replace 'hulu' with the domain you wish to query).

If you get any hits, then it's likely those are the domains causing issues. You can whitelist the offending domains by referring to [this wiki page](https://github.com/pi-hole/pi-hole/wiki/Whitelisting-and-Blacklisting) (the gist of which is `whitelist.sh <domain>`)

**Comment by jacobsalmela** [comment] 2016-03-08 17:30
This is actually one of the [longest-standing issues](https://github.com/pi-hole/pi-hole/pull/12) of Pi-hole.  I have also [written about my efforts to block Hulu ads](http://jacobsalmela.com/attempting-block-hulu-plus-video-ads-raspberry-pi/).

**Comment by travisdietrich** [comment] 2016-05-28 14:46
Hey all,

I looked into this years ago while trying to get [Hulu on Android to work with AdAway](http://forum.xda-developers.com/showpost.php?p=48524249&postcount=54).

Along with all the *hulu* domains, you need to whitelist *akamai* domains as well.  There are other domains that Hulu uses for advertising, but my in my experience only the two I just mentioned caused the streaming to break.

Here's the whole list, hope it helps:

```
Hulu Domain:
*hulu.com
*huluad.com
*huluim.com

CDN Providers:
*akamai*
*darwin*
*edgecast*
*level3*
*limelight*

Ad Providers:
*adtology.com
*adtology?.com
*lightningcast.com
*lightningcast.net
```

**Comment by dschaper** [comment] 2016-05-28 23:31
Thanks @travisdietrich. We'll take a look at it!

**Comment by roshkins** [comment] 2016-08-31 04:09
@jacobsalmela has there been any attempt to try to fetch the next block of video without the ad requirement?

Or perhaps Hulu is corroborating the ad request with a unique id that is being looked for by the server? Ilike the PRNG for many 2FA's?

**Comment by jacobsalmela** [comment] 2017-05-14 05:11
Closing for now as it's out of scope for now and hasn't had progress for quite some time.  I spent **considerable** time on it but always ended up just breaking Hulu completely.  We can re-open if need be or if the community deems it important, but blocking specific ads is out of scope for us and better left up to the blocklist maintainers.  

However, I opened this as [a feature request on discourse.pi-hole.net](https://discourse.pi-hole.net/t/block-hulu-ads/3146) to make it votable.

**Comment by PromoFaux** [comment] 2017-07-25 18:36
Reopening this as I've just noticed there is an [active bounty of $50](https://www.bountysource.com/issues/31683840-blocking-hulu) on this issue. Seems only fair to the backer, and those looking to bountyhunt to keep the issue open :)

**Comment by miguelroboso** [comment] 2017-12-03 22:02
yeah, same issue here: trying to watch Brooklyn Nine Nine, stops at the first ad and never starts

**Comment by JS1982** [comment] 2018-02-13 07:27
Any possibility you can implement some streaming ad blocking?

I have seen promising results from this project:

http://vasanthkalingeri.github.io/CommercialDetection/

**Comment by Mcat12** [comment] 2018-02-13 15:04
We can't use that project. Even if we tried, they put ads in the normal video stream so we can't block them.

**Comment by dNetGuru** [comment] 2018-03-09 00:37
I've been doing this for a long time (when they didn't offer the commercial free option) successfully on various devices including iPads and Xbox One.

Essentially the way you can do it is to set DNS entries for the CDNs that are serving their ads (like ads-a-darwin.hulu.com or ads-v-darwin.hulu.com etc.) so that you'd resolve them to a web server you control (it can be the PiHole in this case).

Then you set a wildcard rule on that web server to respond to all requests for ads with a very short (sub 1 second) MPEG file in lieu of the advertisement! And you're done! All you'd see for an ad is a momentary blank screen.

There are some caveats with some platforms for example on the IOS apps for Hulu the app shows you the show you're trying to watch as the advertisement when you do this, now this is fine unless you try to rewind or forward the video (pausing is okay) since rewinding is not allowed during an ad playback.

**Comment by worldofpeace** [comment] 2018-03-15 07:32
@dNetGuru 
This sounds like black magic but it's awesome. Please take my money. :) :1st_place_medal:

**Comment by jacobsalmela** [comment] 2018-04-10 00:48
We're moving this feature request to Discourse so it's votable: https://discourse.pi-hole.net/t/find-a-way-to-block-hulu-ads/8758

We'll also be shutting down BountySource.  We're less driven by money and more by what the community wants.  The plugin has also not been very successful or all that useful.

**Closed by jacobsalmela** 2018-04-10 00:48 UTC
Labels: Bounty, Feature Request, Hacktoberfest

**Comment by lnorton89** [comment] 2018-05-28 21:04
@dNetGuru I've tried to replicate your setup and am not having any success. I've added the following line to my lighttpd.conf file and can confirm visiting any of the domains in my browser gets served the blank video file. 

`$HTTP["host"] =~ "a.huluad.com|ads-a-darwin.hulu.com|ads-v-darwin.hulu.com|ads-e-darwin.hulu.com|ads.hulu.com|ads.hulu.com.edgesuite.net|hulu.112.2o7.net|huludev.112.2o7.net|ll.a.hulu.com|mtsnu-miftahululum.sch.id|t-ak.hulu.com|t2.hulu.com|t2.huluim.com|tw.i.hulu.com|urlcheck.hulu.com" {
	url.redirect = ( ".*" => "http://pi.hole/admin/blank.m4v")
}`

Maybe I'm missing something here?

**Comment by amlamarra** [comment] 2018-06-14 17:53
@lnorton89 And this works?

**Comment by lnorton89** [comment] 2018-06-14 18:00
@amlamarra Somewhat. My older smart TV (Vizio) will skip the ads with NGINX responding to every request with the short blank mp4 file. 

Where I had issues / inconsisently ad skipping was on desktop computers on the network due to what I believe is an issue with SSL certificates. Since most (if not all) the ads are being served via HTTPS and I don't have the SSL cert for the domain browsers won't retrieve the blank video file due to the content being served by a domain with an invalid SSL certificate. 

Sometimes if I manually visited my the ad domain via HTTPS on my local network first in the browser and manually accepted the invalid certificate Hulu would skip ads in browser. Sometimes it wouldn't. 

I believe the Hulu app for my TV was poorly implemented and doesn't enforce SSL certificates for the ad CDN's that's why my TV will skip ads. I haven't confirmed this but I do know the TV is pulling the blank video file as I replaced it with a test video and it displayed it as an ad. Maybe if I poke around access logs I can figure out if its pulling it via HTTPS with the invalid certificate or just falling back to HTTP. 

Hope this sheds some light on your question. If anyone has a work around for the SSL aspect of this I'm all ears. I wasn't sure if creating my own certificate authority on the LAN and issuing an SSL certificate that way would work, I don't really know too much about SSL certificates. If anyone has any insight on this I'm all ears.

**Comment by dNetGuru** [comment] 2018-06-14 18:16
@lnorton89 Try adding the SSL certificate that you are using on Nginx to serve the blank ads to your OS's trust store.

**Comment by lnorton89** [comment] 2018-06-14 20:00
@dNetGuru I've added my own self-signed certificate to NGINX's config already. Never messed with trust store; I'm assuming its a place to store SSL certificates OS-wide. I will look into it and research implementing it and report back when I can.

**Comment by jakky567** [comment] 2018-10-17 19:53
@dNetGuru I have been trying to implement this, and have had success with ads over http only (UWP, Hulu v < 3 on android). Https redirects are not working for me on android. I put my self signed certificate in the os trust store (needed to have root to do so, as I am running oreo). Chrome for android even shows the certificate is valid. Any advice would be appreciated!

**Comment by pralor** [comment] 2020-07-17 19:52
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/find-a-way-to-block-hulu-ads/8758/1

**Comment by pralor** [comment] 2020-07-17 19:53
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/block-hulu-ads/3146/1

**Comment by BFB2q** [comment] 2023-06-19 03:24
any light still left in this? I tried blocking the hulu AD dns's via my admin panel it worked for 80% of the ads.

**Comment by roshkins** [comment] 2023-06-19 04:34
I've found that the Chrome extension called Hulu Skipper in combination
with Hulu ad simpler works, with id lenacnekoepfjoldmbhgobbifkalnfdf
and pgpdfnkeeppfohmophlpcfmciioeenig

**Comment by BFB2q** [comment] 2023-06-19 19:54
thank you!
